### ISSUE TITLE
Doesn't work on my router with hidden ssid with special character passwords

### ISSUE THREAD

**Issue by Stevemoretz** [OpenIntelWireless/itlwm#100]
Hi there is a bug, my Hotspot phone password is with digits 64373737

My router ssid is hidden and also has a hard password containing @$&#/%
There is no internet when I connect to my router but when I connect to my Hotspot it works just fine.

**Comment by Stevemoretz** [comment]
Hi I forgot to say I tested it via
https://github.com/zxystd/itlwm/issues/96
This tool it gives an ability to edit plist and put ssid and password in there and then it works with regular names but for hidden + special characters it fails. Any idea? Is this considered to be solved?

**Comment by zxystd** [comment]
You should not call it as "issue", it is a new feature, not a bug. Hidden ssid auth is different from common scan, it should broadcast ssid when scanning. just wait for the new feature. thanks.

**Comment by Stevemoretz** [comment]
Oh I didn't know that I thought it was a small problem with the code.Thanks waiting for it.

**Comment by zxystd** [comment]
now itlwm can connect to hidden ssid network(use heliport and join to network). itlwmx also can work, but crash after association, need to be fixed.

**Comment by Stevemoretz** [comment]
Thank you zxystd you've done some neat job.Well done honestly you're the best. How far from a release kext you'd think we are? Seems pretty close to me.

**Comment by Stevemoretz** [comment]
Any updates on this?

**Comment by Stevemoretz** [comment]
Just checked with airport version still not working

**Comment by Stevemoretz** [comment]
I do confirm that heliport works but only for a few seconds then crashes again and again :/

**Comment by williambj1** [comment]
Feel free to request a reopen and continue the discussion with the debug logs provided.

**Comment by Stevemoretz** [comment]
Is it implemented now?
In which version?

**Comment by williambj1** [comment]
> Is it implemented now?
> In which version?

Have you tried the latest alpha?

**Comment by Stevemoretz** [comment]
Not yet, so it finally happened, very well done!

The work is done in this repo is really admiring!
Keep up the great work.
Thanks for this nice feature.

**Comment by MohammedBadr20s** [comment]
@Stevemoretz  I'm using version Number v2.0.0 stable and can't connect to hidden ssid isn't it implemented in the latest version yet ?
