### ISSUE TITLE
Airportitwlm 2.3.0 Stable Sonoma 14.4: iServices not working in Sonoma with intel AX210 - Is this normal?

### ISSUE THREAD

**Issue by bhuether** [OpenIntelWireless/itlwm#1002]
**Have You Read Our Docs**
Yes

**Are You Reporting A Bug**
Not sure if this is bug or expected behavior.

**Environment**
- Kext Version: Airportitwlm 2.3.0 Stable Sonoma 14.4

- WiFi Card Model: Intel AX210 built in to Asus Z790 ProArt

- PCI Product ID: Not sure what "PCI Product ID" is, but here is some data from IOReg, Hackintool
<"pci8086,24", "pci8086,2725", "pciclass,028000", "PXSX">
IOService:/AppleACPIPlatformExpert/PC00@0/AppleACPIPCI/RP03@1C,2/IOPP/PXSX@0
PciRoot(0x0)/Pci(0x1C,0x2)/Pci(0x0,0x0)

- macOS Version: Sonoma 14.5 (installed new, not update)

- Hardware: Asus Z790 ProArt BIOS 2202, 14700K, G.Skill 2x32 GB DDR5 6400, SN850X NVMe

**Description**
iMessage and FaceTime not working with Airportitwlm. They work via ethernet (en0 Aquantia AQC113CS, en1 Intel i226-V). Also work using Itwlm and heliport.

Documentation says we might expect iServices not working, but doesn't say definitively. Some users are reporting iServices working with Airportitwlm Sonoma.  Not clear under what circumstances we can expect it to work or if I should abandon Airportitwlm and use Itwlm.  Hoping my provided data can help figure out how to get iServices working.

There was brief period when I had iMessage working with Airportitwlm.  I was using VPN at that moment. But I haven't been able to reproduce that success.  iMessage will show blue status bar, then status bar stops, then minutes later message about failed send.

My board has two NICs.  Not sure if that throws a curve ball.  WiFi is always en2.  In System Settings->network I have tried ordering the network services with WiFi first, WiFi last. No change in result.

I am using 1,1 SMBIOS.  Data generated with GenSMBIOS. I deleted my other devices (installs that I then abandoned) attached to my Apple ID.

Apple ID is also attached to my real MacBook Air 2023 M2.

I have also followed troubleshooting instructions https://openintelwireless.github.io/itlwm/Troubleshooting.html and deleted files as suggested.  Also deleted the network devices, installed DebugEnhancer, enabled logging, rebooted. 

**Bug Report Archive**
Here is kextstat output:

Executing: /usr/bin/kmutil showloaded
No variant specified, falling back to release
  101    0 0xffffff8004aca000 0xfa8000   0xfa8000   com.zxystd.AirportItlwm (2.3.0) BEB9788E-D601-3C37-B6BA-1C8E5DAFA3BE <100 99 55 53 18 7 6 3 1>

<img width="1831" alt="en2 IoReg" src="https://github.com/user-attachments/assets/988bbfb2-4b7b-484a-9983-50aa215d2474">
<img width="1832" alt="en2 PCI path" src="https://github.com/user-attachments/assets/d3be05f7-f139-44a4-81a2-042eb825fc1e">

I issued this command right after getting the iMessage failed to send message:

sudo dmesg | grep -E "itlwm|Airport|IO80211|EAPOL" > ~/Desktop/Log_"$(date '+%Y-%m-%d_%H-%M-%S')".log

Not sure what to look for, some entries that catch my attention:

[   11.077699]: itlwm: SKU ID didn't match!

Some bluetooth related fails:

[   35.304614]: 308 duplicate reports for Sandbox: secd(439) deny(1) mach-lookup com.apple.lsd.modifydbSandbox: bluetoothd(153) deny(1) iokit-open-user-client IO80211APIUserClientIOUC IO80211APIUserClient failed MACF in process pid 153, bluetoothd
[   35.304618]: com.apple.p2p.stats: IOUC-WIFI: [bluetoothd] virtual IOReturn IO80211APIUserClient::clientClose()
[   35.304891]: IO80211APIUserClient init failed in checkEntitlement
[   35.304893]: IO80211APIUserClient::free
[   35.305608]: IOUC IO80211APIUserClient failed MACF in process pid 153, bluetoothd
[   35.305610]: com.apple.p2p.stats: IOUC-WIFI: [bluetoothd] virtual IOReturn IO80211APIUserClient::clientClose()
[   35.306115]: itlwm: getDRIVER_VERSION
[   35.306539]: IO80211APIUserClient::stop(377) _onWLANQueue(1)
[   35.306638]: 1 duplicate report for Sandbox: bluetoothd(153) deny(1) iokit-open-user-client IO80211APIUserClientSandbox: airportd(232) deny(1) file-read-xattr /usr/sbin/systemstatscom.apple.p2p.stats: [airportd] succeeded in calling newUserClient, type[0x00000000], role[1], ret[0x00000000]

Some more dies and fails:

[   35.309084]: Sandbox: airportd(232) deny(1) file-read-xattr /usr/sbin/WirelessRadioManagerdSandbox: airportd(232) deny(1) file-read-xattr /usr/sbin/bluetoothdSandbox: airportd(232) deny(1) file-read-xattr /usr/libexec/configdSandbox: airportd(232) deny(1) file-read-xattr /usr/libexec/PerfPowerServicesIO80211APIUserClient init failed in checkEntitlement
[   35.313776]: IO80211APIUserClient::free
[   35.317066]: IO80211APIUserClient init failed in checkEntitlement
[   35.317068]: IO80211APIUserClient::free
[   35.322874]: itlwm: getDRIVER_VERSION
[   35.329364]: 1 duplicate report for Sandbox: airportd(232) deny(1) file-read-xattr /usr/sbin/bluetoothdSandbox: airportd(232) deny(1) file-read-xattr /usr/libexec/PerfPowerServicesIO80211APIUserClient init failed in checkEntitlement

Some more fails

[   35.578903]: IO80211ScanManager::startScan: Scan request failed (22, stringFromReturn unexpected call)!ClientMemoryForType[0x1]
[   35.579027]: IO80211APIUserClient::destroyEventPipe(1410) _onWLANQueue(0)
[   35.579030]: IO80211IOUCEventPipe::free
[   35.590465]: IO80211ScanManager::startScan: Scan request failed (22, stringFromReturn unexpected call)!ClientMemoryForType[0x1]
[   35.590525]: IO80211APIUserClient::destroyEventPipe(1410) _onWLANQueue(0)
[   35.590528]: IO80211IOUCEventPipe::free
[   35.625921]: IO80211ScanManager::startScan: Scan request failed (22, stringFromReturn unexpected call)!ClientMemoryForType[0x1]
[   35.626030]: IO80211APIUserClient::destroyEventPipe(1410) _onWLANQueue(0)
[   35.626040]: IO80211IOUCEventPipe::free
[   35.644424]: itlwm: iwx_enable_fwload_interrupt
[   35.647341]: IO80211APIUserClient init failed in checkEntitlement
[   35.647344]: IO80211APIUserClient::free
[   35.656085]: IO80211ScanManager::startScan: Scan request failed (22, stringFromReturn unexpected call)!ClientMemoryForType[0x1]
[   35.656244]: IO80211APIUserClient::destroyEventPipe(1410) _onWLANQueue(0)
[   35.656247]: IO80211IOUCEventPipe::free
[   35.678970]: IO80211ScanManager::startScan: Scan request failed (22, stringFromReturn unexpected call)!ClientMemoryForType[0x1]
[   35.679072]: IO80211APIUserClient::destroyEventPipe(1410) _onWLANQueue(0)
[   35.679074]: IO80211IOUCEventPipe::free
[   35.780891]: Sandbox apply: ScreenTimeAgent[525] <bytes>Sandbox: CommCenter(482) deny(1) file-read-data /private/var/db/mds/messages/501/se_SecurityMessagesSandbox: fileproviderd(508) deny(1) mach-lookup com.apple.tccd.system1 duplicate report for Sandbox: fileproviderd(508) deny(1) mach-lookup com.apple.tccd.systemSandbox: syncdefaultsd(518) deny(1) mach-lookup com.apple.tccd.systemitlwm: iwx_rx_pkt: firmware alive, size=144

Anyway, various other fails, denies, errors, no idea what is critical here.  Log attached.

**Kext Download Source**
From GitHub https://github.com/OpenIntelWireless/itlwm/releases/download/v2.3.0/AirportItlwm_v2.3.0_stable_Sonoma14.4.kext.zip

[Log_2024-07-18_12-42-37.log](https://github.com/user-attachments/files/16281419/Log_2024-07-18_12-42-37.log)

**Comment by KevinamdKim** [comment]
The itlwm.kext+ Heliport will work.
