### ISSUE TITLE
5Ghz not working, Need to TurnOff Bluetooth, Re-enter Password

### ISSUE THREAD

**Issue by Rexadev** [OpenIntelWireless/itlwm#1003]
1. Using itlwm 
2. 5ghz not working
3. Bluetooth needs to be turned-off for using Wi-Fi
4. and to disable Bluetooth I need [IntelBluetoothFirmware](https://github.com/OpenIntelWireless/IntelBluetoothFirmware)
5. need to forget Network and Re-Save the password every time I reboot

**Have You Read Our Docs**
Yes

**Are You Reporting A Bug**
Yes

**Environment**

- Kext Version: 2.3.0
- WiFi Card Model: Intel Dual Band Wireless-AC 9260 on MSI B450 Gaming Pro Carbon AC
- PCI Product ID: 
- macOS Version: Catalina

**Description**

**Bug Report Archive**

**Kext Download Source**
GitHub Release Page

**Comment by zxystd** [comment]
Forget password in the setting.
