### ISSUE TITLE
Airportitwlm 2.3.0 Stable Sonoma 14.4 not working on Sonoma 14.6.1

### ISSUE THREAD

**Issue by hartmut181059** [OpenIntelWireless/itlwm#1005]
**Have You Read Our Docs**

Yes
**Are You Reporting A Bug**

YEs
**Environment**

- Kext Version:        2.3.0 Stable for Sonoma 14.4
- WiFi Card Model: Elitebook 840 G3  Intel Wireless 8260
- PCI Product ID:   0x8086, 0x24F3 , sub: 0x10 , Intel Wireless 8260
- macOS Version:  Sonoma 14.6.1

**Description**

Wifi under 14.6.1 not working, (but 14.4.1 is working)

**Bug Report Archive**

**Kext Download Source**

https://github.com/OpenIntelWireless/itlwm

**Comment by Mauri13** [comment]
Kext Version: 2.3.0 Stable for Sonoma 14.4 work well on Sonoma 14.6.1 Intel CNVi interface 802,11a (z390)

**Comment by hartmut181059** [comment]
Sorry I have done a new plain Installation and now it works with itlwm,kext and heliport Thx and excuse

**Comment by arg0WAK** [comment]
It does not work properly in 14.6.1. DHCP is not assigned automatically. If entered manually, it connects to the WiFi network.
