### ISSUE TITLE
AX200无可用网络列表

### ISSUE THREAD

**Issue by cuijianzhuang** [OpenIntelWireless/itlwm#1014]
<img width="1966" alt="Snipaste_2024-09-27_13-07-48" src="https://github.com/user-attachments/assets/d11d1323-d9d5-49c1-a75b-d1f34113f950">
<img width="844" alt="Snipaste_2024-09-27_13-07-32" src="https://github.com/user-attachments/assets/f73e5332-acf5-4670-bc59-10817c0f36db">

**Comment by WangLiangsen** [comment]
一样的问题，请问您是怎么解决的？
