### ISSUE TITLE
Wake on Wireless not working (anyone else?)

### ISSUE THREAD

**Issue by DrHurt** [OpenIntelWireless/itlwm#1024]
**Have You Read Our Docs**
Yes

**Are You Reporting A Bug**
Yes

**Environment**

- Kext Version: 2.3.0
- WiFi Card Model: AX200
- PCI Product ID: 
- macOS Version: Monterey 12.7.4

**Description**

Computer does not wake from sleep to magic packet. It does on windows on the same machine (dual booting).
I need this to be able to use Plex Server, so that my TV would be able to wake up the machine like it did with Windows.

**Bug Report Archive**

**Kext Download Source**

GitHub here

**Comment by jozews321** [comment]
I don't think that functionality is implemented yet. See [Issue 872](https://github.com/OpenIntelWireless/itlwm/issues/872)

**Comment by zxystd** [comment]
scan offload and WOWL should be implemented, hackintosh hibernate should be normal too, so there is no plan to implement that.
