### ISSUE TITLE
AX201 Support

### ISSUE THREAD

**Issue by svandive** [OpenIntelWireless/itlwm#127]
Trying to load this kext to get an Intel AX 201 (Intel NUC 10) up and running.  However, after doing a kextload the driver doesn't seem to be loading.  Are there logs that would be helpful in understanding the support of this kext for AX 201?

**Comment by svandive** [comment]
Fantastic, thank you!

**Comment by simon-marcus** [comment]
@zxystd thank you for your development! I would also be glad to test and share feedback on the AX201 which is presently the included card in my [Gigabyte Z-490 Vision D](https://www.gigabyte.com/Motherboard/Z490-VISION-D-rev-1x/sp#sp).

**Comment by svandive** [comment]
I just wanted to add a log from attempting to load the itlwmx kext.

[itlwmx_load_log.txt](https://github.com/zxystd/itlwm/files/4805434/itlwmx_load_log.txt)

**Comment by purecmd** [comment]
I got a same problem. ASUS ROG STRIX Z490-I GAMING

**Comment by chyinan** [comment]
小米笔记本2020增强版的AX201（AC9560）网卡也不行，什么时候能支持呢

**Comment by zncs520** [comment]
cnvio2接口的目前是都不行的
我是ICE LAKE G7 哎 显卡也是没有驱动

**Comment by zxystd** [comment]
ax201 is same chip with 9462, please turn to #88
