### ISSUE TITLE
MTU setting

### ISSUE THREAD

**Issue by zxystd** [OpenIntelWireless/itlwm#130]
Now MTU is hardcode to 1500, maybe this will leave some connection issue, should make it configurable.

**Comment by mackonsti** [comment]
Hello @zxystd not sure if you are the same person that was kind to compile the latest version for running in Mojave 10.14 (in a known Forum) please see the MTU value of the driver today: It shows MTU as "Custom" with value 1482.
![MTU 1482](https://user-images.githubusercontent.com/1313613/86519614-a2fc9980-be3c-11ea-9e20-f1f4cf4e5a86.png)
Also, is Duplex supposed to be empty? Just curious. Thank you again.
P.S. Please do make your code officially support Mojave (_LSMinimumSystemVersion_) it works well, actually I am writing from my NUC :-D
