### ISSUE TITLE
Warm reboot issue

### ISSUE THREAD

**Issue by zxystd** [OpenIntelWireless/itlwm#131]
when reboot from Windows, the card(seems only 9560AC) didn't work.

**Comment by DellG3** [comment]
I have 9462AC with the same issue when rebooting from Windows.

**Comment by yusifsalam** [comment]
Same issue when rebooting from linux (9560AC and arch linux)

**Comment by weidongbcn** [comment]
苹果下热启动也会出现这样的情况。
