### ISSUE TITLE
上传速度问题

### ISSUE THREAD

**Issue by lifsux** [OpenIntelWireless/itlwm#141]
0607kext驱动上传速度最大1MB左右，同样的在win10系统上传在5.7MB左右。8代网卡。
[itlwm_log.txt](https://github.com/zxystd/itlwm/files/4790381/itlwm_log.txt)

**Comment by zxystd** [comment]
目前网卡峰值速度可以到7m~8m/s，可能你的路由器或者设置有些问题。另外后面也会提速。
