### ISSUE TITLE
从Windows热重启到macOS后，无法连接网络

### ISSUE THREAD

**Issue by 70599** [OpenIntelWireless/itlwm#145]
供应商ID: `0x8086`
设备ID: `0x9DF0`

从Windows热重启到macOS后，系统偏好设置中对应的网络接口显示**电缆已拔出**

`[6.18]`、`[6.7]`版本都有这个问题

**Comment by paranoiagu** [comment]
大概就是6月份后的版本，我这边网卡一直连接。
7系的网卡。

**Comment by chenyuyou** [comment]
9056 也存在这个问题

**Comment by daniuwo** [comment]
这个问题9462在linux和win切换都存在

**Comment by williambj1** [comment]
duplicate of #139
