### ISSUE TITLE
Basic tutorial for itlwm

### ISSUE THREAD

**Issue by M69W** [OpenIntelWireless/itlwm#146]
### 驱动 kext
自行编译 [itlwm源码](https://github.com/OpenIntelWireless/itlwm)

上面远景链接下 `itlwmx_ax200_0618.kext.zip` ( 例如 itlwmx 带`x`的才适用 [Intel AX200](https://ark.intel.com/content/www/cn/zh/ark/products/189347/intel-wi-fi-6-ax200-gig.html))
### 客户端 HeliPort
自行编译 [HeliPort源码](https://github.com/OpenIntelWireless/HeliPort)

#### 下面提供编译好的驱动和客户端(来源: `黑苹果Intel WiFi交流群` 群号:`1036194654`)
[HeliPort.zip](https://github.com/OpenIntelWireless/itlwm/files/4808904/HeliPort.zip)（编译日期0618，非最新编译）
[itlwmx.kext.zip](https://github.com/OpenIntelWireless/itlwm/files/4808905/itlwmx.kext.zip)（编译日期0618，非最新编译）

## 使用
如果不使用 `HeliPort` 客户端，
记得要预先在驱动 `itlwmx.kext`里面的 `Info.plist` 中改为你的路由器(热点)的 `SSID`和 `password`，
操作：【`itlwmx.kext`->右键->显示包内容】:`Contents/Info.plist`
<img width="770" alt="1" src="https://user-images.githubusercontent.com/15809201/85216897-e4ad2f00-b3bc-11ea-875d-2a5913116904.png">
_这里顺便提一下，可能会有人执行命令后再修改`info.plist`会提示权限问题，下面有说到_

根据作者@zxystd在上面的远景链接帖子提供的使用方法，这里暂时使用命令输入启动驱动，如下
```
如果在使用过程中需要添加 `Wi-Fi`但是又不想重启,可以用以下命令卸载,然后编译好之后再次加载
卸载: sudo kextunload -b com.zxystd.itlwm
加载:
sudo chown -R root:wheel itlwm.kext
sudo kextutil -v 6 itlwm.kext
```

这里有必要说下驱动的操作和加载的路径，
以 `AX200` 用 `itlwmx.kext` 为例
例如驱动 `itlwmx.kext` ->`放桌面`，
找到并打开终端输入 `sudo chown -R root:wheel `
再把 `itlwmx.kext`在拖入终端，对，拖入终端里面
最后显示就是 `sudo chown -R root:wheel /Users/abc/Desktop/itlwmx.kext` 
而不是 `sudo chown -R root:wheel itlwm.kext`

一般来说，
如果不放入OC 或 Clover 开机加载驱动，
而是使用命令加载驱动，
只需要执行两行命令
```
sudo chown -R root:wheel itlwmx.kext
sudo kextutil -v 6 itlwmx.kext
```

执行上面👆命令后，
打开 【 启动台->系统偏好设置->网络->左下角->【+ 】-> 选【以太网】->应用
![image](https://user-images.githubusercontent.com/15809201/85216979-dad7fb80-b3bd-11ea-9023-e84c12aec19a.png)

然后打开客户端 `HeliPort`，
第一次没有显示`Wi-Fi`列表，可尝试多次点击`Wi-Fi`图标
目前(`当前时间为0618-2020`)客户端HeliPort 支持Wi-Fi 支持输入Wi-Fi密码，其他功能没测试！
后期客户端功能有所不同，请继续关注。

## 注意

1. 怎么看是否已连接Wi-Fi？
打开 `HeliPort`,【打开网络偏好设置->网络->显示已连接(`绿色标志`)】

2. 如果没有【以太网】选项:
以[小新pro13 EFI OC](https://github.com/daliansky/XiaoXinPro-13-hackintosh) 为例 
注释或删除两项：(猜测跟 `ASPM` 有关，详情看这里 [PCI设备ASPM](https://github.com/daliansky/OC-little/tree/master/01-%E5%85%B3%E4%BA%8EAOAC/01-5-%E8%AE%BE%E7%BD%AEASPM%E5%B7%A5%E4%BD%9C%E6%A8%A1%E5%BC%8F)，需要验证）
```
DeviceProperties\Add\PciRoot(0x0)/Pci(0x1C,0x0)
DeviceProperties\Add\PciRoot(0x0)/PciRoot(0x0)/Pci(0x1C,0x0)/Pci(0x0,0x0)
```
<img width="902" alt="2" src="https://user-images.githubusercontent.com/15809201/85217250-2d66e700-b3c1-11ea-98f9-abb521f59386.png">

**08-24-2020更： 在Big Sur中不禁用ASPM 注入也能正常使用AX200/AX201**  

3. 关闭 `HeliPort`客户端 ：
感谢@williambj1 提供的方法：
```
HeliPort 按住 ALT 有退出选项
终端执行 sudo killall HeliPort 也行
```
或 使用最繁琐的方法(`估计没有谁会这样操作`)
打开 【 启动台->其他->活动监视器->找到【 HeliPort】双击 【退出】

4.睡眠后Wi-Fi 连接：
睡眠后理论上它自己会自动连接，
但如果断网的话：
使用`HeliPort`客户端 ：1.先关闭Wi-Fi；2.再打开Wi-Fi；如果预先写好Wi-Fi和password，会自动连接。

### 优化使用
把 `itlwmx.kext`放入 `OC` 或 `Clover` 下，开机加载驱动，不需要命令启动；
如果在 `Info.plist` 编辑好使用的`Wi-Fi` 的`SSID`和 `password`，不需要客户端 `HeliPort`也能使用 `Wi-Fi`。

### 最后感谢 对 Intel 网卡 能够在 macOS 使用作出贡献的所有大佬们，再次特别感谢 @zxystd

**Comment by zncs520** [comment]
AX201 现在还不行吗?

**Comment by williambj1** [comment]
HeliPort 按住 ALT 有退出选项
终端执行 ```sudo killall HeliPort``` 也行

**Comment by M69W** [comment]
> HeliPort 按住 ALT 有退出选项
> 终端执行 `sudo killall HeliPort` 也行

多谢提醒

**Comment by lacostey86** [comment]
thanks its working fine with ax200 10.15.5 os , but there is one tiny issue if you are already connected to a ssid there is not way to find which ssid i'm using

**Comment by williambj1** [comment]
> thanks its working fine with ax200 10.15.5 os , but there is one tiny issue if you are already connected to a ssid there is no way to find which ssid i'm using

This is not an issue, but a feature that hasn't been implemented

**Comment by arvinws** [comment]
AX201可以使用么

**Comment by evertjr** [comment]
Can you upload the itlwm.kext too?

**Comment by lawman21c** [comment]
有个问题，在mac使用了ax200之后，windows10里用不了wifi了。

**Comment by lacostey86** [comment]
> > thanks its working fine with ax200 10.15.5 os , but there is one tiny issue if you are already connected to a ssid there is no way to find which ssid i'm using
> 
> This is not an issue, but a feature that hasn't been implemented

ok thanks for the clarification , good job , hope this is the first step for handoff and airdrop

**Comment by naveenkrdy** [comment]
great work ! 
AX200 works fine on macos 10.15.5 
@lawman21c  works fine for me on windows even with this kext.

**Comment by allanwhledu** [comment]
请问一下，在macOS 10.14上AC9560可以用了吗？我试了下还是不行呢，在网络中一直没有以太网的选项可以添加，是否不支持10.14系统了？

启动日志也只有：
2020-06-24 05:14:56.361506+0800 0x484 Default 0x0 0 0 kernel: (kernel) itlwm: free
2020-06-24 05:14:56.362479+0800 0x482 Default 0x0 0 0 kernel: (kernel) itlwm: free
2020-06-24 05:14:56.366004+0800 0x47e Default 0x0 0 0 kernel: (kernel) itlwm: free

**Comment by zxystd** [comment]
支持10.14，你先尝试彻底断电，然后再开启电脑

**Comment by allanwhledu** [comment]
> 支持10.14，你先尝试彻底断电，然后再开启电脑

嗯嗯，可以了。其实是因为AC9560有2代的有1代的是吧，我以为都是2代的呢……从itlwmx换回itlwm就没问题了，感谢大佬！！

**Comment by andiest13** [comment]
谢谢，可以使用ax200上网了，但是那个网速好像限制了30Mbps左右（转win是可以跑满wifi6的）。

**Comment by M69W** [comment]
> 谢谢，可以使用ax200上网了，但是那个网速好像限制了30Mbps左右（转win是可以跑满wifi6的）。

先解决能不能用的问题，
再解决好不好的问题。

继续关注吧

**Comment by jxp98** [comment]
貌似还是不行额...是不是只能支持部分ID的AX200

**Comment by jxp98** [comment]
同AX200，失败了...一直不显示wifi 直接在kext里该wifi密码也找不到wifi 连不上。大佬，还有得救吗

**Comment by lawman21c** [comment]
> 有个问题，在mac使用了ax200之后，windows10里用不了wifi了。

这个问题应该是windows10的，而不是这个驱动的问题。尝试重装系统看看。

**Comment by leoli-dev** [comment]
大佬们，AX201 有希望吗？我板载那块是 AX201NGW，这个方法不行吧？

**Comment by M69W** [comment]
> 大佬们，AX201 有希望吗？我板载那块是 AX201NGW，这个方法不行吧？

[ax201不能加载 #129](https://github.com/OpenIntelWireless/itlwm/issues/129)

**Comment by 8x13b** [comment]
Roses are red,
Violets are blue,
The title is in english,
So why is the issue in chinese?

**Comment by williambj1** [comment]
I’m working on docs right now, but unfortunately this guide with google translate is currently the best you can get.

**Comment by scutxd** [comment]
> 9560

你好，9560还分1代和2代码？如何区分的？

**Comment by scutxd** [comment]
> > 支持10.14，你先尝试彻底断电，然后再开启电脑
> 
> 嗯嗯，可以了。其实是因为AC9560有2代的有1代的是吧，我以为都是2代的呢……从itlwmx换回itlwm就没问题了，感谢大佬！！

你好，9560还分1代和2代吗？如何区分呢？

**Comment by mbirth** [comment]
Short form:

1. Get Xcode
1. Clone itlwm (from inside Xcode or manually, then open in Xcode)
1. Modify the `itlwm/Info.plist` to match your SSID(s) and password
1. Build/Compile
1. Find the itlwm.kext in `~/Library/Developer/Xcode/DerivedData/itlwm-...../Build/Products/Debug/`
1. Use the Terminal to cd to that dir and try to load the extension to see if it works: `sudo kextload itlwm.kext`
   * probably need to [disable SIP](https://www.howtogeek.com/230424/how-to-disable-system-integrity-protection-on-a-mac-and-why-you-shouldnt/) if you haven't already
1. If it loads fine and your system doesn't crash, you could move it to `/System/Library/Extensions/` to have it autoloaded on boot
   * Catalina+ users will have to remount the system partition for writing first: `sudo mount -uw /`
   * Or move it onto your EFI partition and have OC load it

(If you have Intel cc or Qu/QuZ card, use `itlwmx` instead.)

For HeliPort:

1. Clone repo
1. Have CocoaPods installed (`sudo gem install cocoapods` followed by `pod setup`)
1. cd into cloned dir and install additional cocoa stuff: `pod install`
1. Build/Compile
1. Find HeliPort in `~/Library/Developer/Xcode/DerivedData/HeliPort-...../Build/Products/Debug/`
1. Move it to Applications
1. Set it as a Login Item

For new versions: Do a `git pull` (or from Xcode menu), then clean build dir(!) before atttempting a new build. You may also want to run `pod install` once in a while so updated pods can be pulled in.

Also there's https://github.com/1hbb/OpenIntelWireless-Factory/releases now.

But: **PLEASE DON'T MAKE NEW ISSUES HERE IF YOU DON'T KNOW HOW TO DEBUG PROPERLY!** This is still in development and not yet ready for the general public. If something doesn't work out for you, see if there already is an issue about that (also search the closed issues) and maybe add a comment there, or ask on reddit. Or wait for the next build and see if that fixes your problem.

**Comment by williambj1** [comment]
@mbirth Huge thanks for your guide, I would like to slightly modify your comment and correct some errors, is that ok?

**Comment by mbirth** [comment]
@williambj1 Sure, go ahead.

**Comment by williambj1** [comment]
Here's a more detailed guide for How to build HeliPort

https://openintelwireless.gitbook.io/openintelwireless/heliport/advanced

**Comment by yoqu** [comment]
> Roses are red,
> Violets are blue,
> The title is in english,
> So why is the issue in chinese?

Haha...

**Comment by rexding97** [comment]
ax200 and use common to run itlwm.kext but fail to load...

dingdongcheng@Dings-iMac-Pro ~ % sudo kextutil -v 6 /Users/dingdongcheng/Desktop/itlwm.kext
Password:
Kext user-space log filter changed from 0xff2 to 0xfff.
Kext kernel-space log filter changed from 0xff2 to 0xfff.
Kext library architecture set to x86_64.
Can't stat /AppleInternal - No such file or directory.
Defaulting to kernel file '/System/Library/Kernels/kernel'
Kext library recording diagnostics for: validation authentication dependencies warnings.
Reading loaded kext info from kernel.
(kernel) User-space log flags changed from 0x0 to 0xfff.
(kernel) Received 'Get Loaded Kext Info' request from user space.
(kernel) Returning loaded kext info.
Loaded kext info:
{
}

Reading loaded kext info from kernel.
(kernel) User-space log flags changed from 0x0 to 0xfff.
(kernel) Received 'Get Loaded Kext Info' request from user space.
(kernel) Returning loaded kext info.
Loaded kext info:
{
}

Kext with invalid signature (-67062) allowed: <OSKext 0x7fc8074129b0 [0x7fff8c66ccc0]> { URL = "file:///Users/dingdongcheng/Desktop/itlwm.kext/", ID = "com.zxystd.itlwm" }
Code Signing Failure: not code signed
/Users/dingdongcheng/Desktop/itlwm.kext appears to be loadable (not including linkage for on-disk libraries).
Reading loaded kext info from kernel.
(kernel) User-space log flags changed from 0x0 to 0xfff.
(kernel) Received 'Get Loaded Kext Info' request from user space.
(kernel) Returning loaded kext info.
Loaded kext info:
{
}

Loading /Users/dingdongcheng/Desktop/itlwm.kext.
Reading load info for 9 kexts.
Reading loaded kext info from kernel.
(kernel) User-space log flags changed from 0x0 to 0xfff.
(kernel) Received 'Get Loaded Kext Info' request from user space.
(kernel) Returning loaded kext info.
Loaded kext info:
{
"com.apple.kpi.bsd" = {
    "OSBundleWiredSize" = 50016
    "CFBundleIdentifier" = "com.apple.kpi.bsd"
    "OSBundleUUID" = <91a52191 d68e41a5 91162683 c2bbd6e8>
    "OSBundleCompatibleVersion" = "8.0.0b1"
    "CFBundleVersion" = "19.6.0"
    "OSBundleStarted" = true
    "OSKernelResource" = true
    "OSBundleLoadTag" = 1
    "OSBundleLoadAddress" = -551890460672
    "OSBundlePath" = 
        "/System/Library/Extensions/System.kext/PlugIns/BSDKernel.kext"
    "OSBundleRetainCount" = 112
    "OSBundlePrelinked" = true
    "OSBundleIsInterface" = true
    "OSBundleLoadSize" = 50016
}
"com.apple.kpi.libkern" = {
    "OSBundleWiredSize" = 65712
    "CFBundleIdentifier" = "com.apple.kpi.libkern"
    "OSBundleUUID" = <2ac6caf5 0e694e40 bcac6f1b 6fe7254d>
    "OSBundleCompatibleVersion" = "8.0.0d0"
    "CFBundleVersion" = "19.6.0"
    "OSBundleStarted" = true
    "OSKernelResource" = true
    "OSBundleLoadTag" = 5
    "OSBundleLoadAddress" = -551890530304
    "OSBundlePath" = 
        "/System/Library/Extensions/System.kext/PlugIns/Libkern.kext"
    "OSBundleRetainCount" = 138
    "OSBundlePrelinked" = true
    "OSBundleIsInterface" = true
    "OSBundleLoadSize" = 65712
}
"com.apple.kpi.mach" = {
    "OSBundleWiredSize" = 25312
    "CFBundleIdentifier" = "com.apple.kpi.mach"
    "OSBundleUUID" = <ebd8877c 63d14872 b14d9a38 e407fa18>
    "OSBundleCompatibleVersion" = "8.0.0d0"
    "CFBundleVersion" = "19.6.0"
    "OSBundleStarted" = true
    "OSKernelResource" = true
    "OSBundleLoadTag" = 6
    "OSBundleLoadAddress" = -551890714624
    "OSBundlePath" = "/System/Library/Extensions/System.kext/PlugIns/Mach.kext"
    "OSBundleRetainCount" = 119
    "OSBundlePrelinked" = true
    "OSBundleIsInterface" = true
    "OSBundleLoadSize" = 25312
}
"com.apple.iokit.IOPCIFamily" = {
    "OSBundleWiredSize" = 233472
    "CFBundleIdentifier" = "com.apple.iokit.IOPCIFamily"
    "OSBundleUUID" = <df219cc1 366a31fc b8ed17c5 84ba2549>
    "OSBundleCPUType" = 16777223
    "CFBundleVersion" = "2.9"
    "OSBundleCompatibleVersion" = "1.0.0b1"
    "OSKernelResource" = false
    "OSBundleStarted" = true
    "OSBundleLoadTag" = 13
    "OSBundleLoadAddress" = -551889465344
    "OSBundleDependencies" = (
        6
        5
        3
        8
        7
    )
    "OSBundlePath" = "/System/Library/Extensions/IOPCIFamily.kext"
    "OSBundleRetainCount" = 37
    "OSBundleCPUSubtype" = 3
    "OSBundlePrelinked" = true
    "OSBundleIsInterface" = false
    "OSBundleLoadSize" = 233472
}
"com.apple.kpi.iokit" = {
    "OSBundleWiredSize" = 153600
    "CFBundleIdentifier" = "com.apple.kpi.iokit"
    "OSBundleUUID" = <77d6c85f d5b64d60 92f06961 a169004f>
    "OSBundleCompatibleVersion" = "7.0"
    "CFBundleVersion" = "19.6.0"
    "OSBundleStarted" = true
    "OSKernelResource" = true
    "OSBundleLoadTag" = 3
    "OSBundleLoadAddress" = -551890685952
    "OSBundlePath" = 
        "/System/Library/Extensions/System.kext/PlugIns/IOKit.kext"
    "OSBundleRetainCount" = 133
    "OSBundlePrelinked" = true
    "OSBundleIsInterface" = true
    "OSBundleLoadSize" = 153600
}
"com.apple.kpi.unsupported" = {
    "OSBundleWiredSize" = 33280
    "CFBundleIdentifier" = "com.apple.kpi.unsupported"
    "OSBundleUUID" = <c00fca33 35324d9b 996888a2 39cde07f>
    "OSBundleCompatibleVersion" = "8.0.0b1"
    "CFBundleVersion" = "19.6.0"
    "OSBundleStarted" = true
    "OSKernelResource" = true
    "OSBundleLoadTag" = 8
    "OSBundleLoadAddress" = -551890407424
    "OSBundlePath" = 
        "/System/Library/Extensions/System.kext/PlugIns/Unsupported.kext"
    "OSBundleRetainCount" = 87
    "OSBundlePrelinked" = true
    "OSBundleIsInterface" = true
    "OSBundleLoadSize" = 33280
}
"com.apple.kpi.private" = {
    "OSBundleWiredSize" = 66928
    "CFBundleIdentifier" = "com.apple.kpi.private"
    "OSBundleUUID" = <44482c31 5d754bfa bcf8610b efbd60e3>
    "OSBundleCompatibleVersion" = "8.0.0b1"
    "CFBundleVersion" = "19.6.0"
    "OSBundleStarted" = true
    "OSKernelResource" = true
    "OSBundleLoadTag" = 7
    "OSBundleLoadAddress" = -551890370560
    "OSBundlePath" = 
        "/System/Library/Extensions/System.kext/PlugIns/Private.kext"
    "OSBundleRetainCount" = 79
    "OSBundlePrelinked" = true
    "OSBundleIsInterface" = true
    "OSBundleLoadSize" = 66928
}
"com.apple.iokit.IONetworkingFamily" = {
    "OSBundleWiredSize" = 196608
    "CFBundleIdentifier" = "com.apple.iokit.IONetworkingFamily"
    "OSBundleUUID" = <2fa065d5 72f73be5 855ce45b 01aefbd4>
    "OSBundleCPUType" = 16777223
    "CFBundleVersion" = "3.4"
    "OSBundleCompatibleVersion" = "1.0.0b1"
    "OSKernelResource" = false
    "OSBundleStarted" = true
    "OSBundleLoadTag" = 18
    "OSBundleLoadAddress" = -551890300928
    "OSBundleDependencies" = (
        1
        5
        3
        8
        7
        6
    )
    "OSBundlePath" = "/System/Library/Extensions/IONetworkingFamily.kext"
    "OSBundleRetainCount" = 13
    "OSBundleCPUSubtype" = 3
    "OSBundlePrelinked" = true
    "OSBundleIsInterface" = false
    "OSBundleLoadSize" = 196608
}
}

/System/Library/Extensions/System.kext/PlugIns/BSDKernel.kext (version 19.6, UUID 91A52191-D68E-41A5-9116-2683C2BBD6E8) is loaded.
/System/Library/Extensions/System.kext/PlugIns/BSDKernel.kext (version 19.6): is started.
setting load address of /System/Library/Extensions/System.kext/PlugIns/BSDKernel.kext to 0xffffff7f80c3e000
/System/Library/Extensions/System.kext/PlugIns/Mach.kext (version 19.6, UUID EBD8877C-63D1-4872-B14D-9A38E407FA18) is loaded.
/System/Library/Extensions/System.kext/PlugIns/Mach.kext (version 19.6): is started.
setting load address of /System/Library/Extensions/System.kext/PlugIns/Mach.kext to 0xffffff7f80c00000
/System/Library/Extensions/IONetworkingFamily.kext (version 3.4, UUID 2FA065D5-72F7-3BE5-855C-E45B01AEFBD4) is loaded.
/System/Library/Extensions/IONetworkingFamily.kext (version 3.4): is started.
setting load address of /System/Library/Extensions/IONetworkingFamily.kext to 0xffffff7f80c65000
/System/Library/Extensions/System.kext/PlugIns/IOKit.kext (version 19.6, UUID 77D6C85F-D5B6-4D60-92F0-6961A169004F) is loaded.
/System/Library/Extensions/System.kext/PlugIns/IOKit.kext (version 19.6): is started.
setting load address of /System/Library/Extensions/System.kext/PlugIns/IOKit.kext to 0xffffff7f80c07000
/System/Library/Extensions/System.kext/PlugIns/Libkern.kext (version 19.6, UUID 2AC6CAF5-0E69-4E40-BCAC-6F1B6FE7254D) is loaded.
/System/Library/Extensions/System.kext/PlugIns/Libkern.kext (version 19.6): is started.
setting load address of /System/Library/Extensions/System.kext/PlugIns/Libkern.kext to 0xffffff7f80c2d000
/System/Library/Extensions/IOPCIFamily.kext (version 2.9, UUID DF219CC1-366A-31FC-B8ED-17C584BA2549) is loaded.
/System/Library/Extensions/IOPCIFamily.kext (version 2.9): is started.
setting load address of /System/Library/Extensions/IOPCIFamily.kext to 0xffffff7f80d31000
/System/Library/Extensions/System.kext/PlugIns/Private.kext (version 19.6, UUID 44482C31-5D75-4BFA-BCF8-610BEFBD60E3) is loaded.
/System/Library/Extensions/System.kext/PlugIns/Private.kext (version 19.6): is started.
setting load address of /System/Library/Extensions/System.kext/PlugIns/Private.kext to 0xffffff7f80c54000
/System/Library/Extensions/System.kext/PlugIns/Unsupported.kext (version 19.6, UUID C00FCA33-3532-4D9B-9968-88A239CDE07F) is loaded.
/System/Library/Extensions/System.kext/PlugIns/Unsupported.kext (version 19.6): is started.
setting load address of /System/Library/Extensions/System.kext/PlugIns/Unsupported.kext to 0xffffff7f80c4b000
Omitting loaded kext /System/Library/Extensions/System.kext/PlugIns/BSDKernel.kext from mkext for kernel load.
Omitting loaded kext /System/Library/Extensions/System.kext/PlugIns/Mach.kext from mkext for kernel load.
Omitting loaded kext /System/Library/Extensions/System.kext/PlugIns/Private.kext from mkext for kernel load.
Omitting loaded kext /System/Library/Extensions/System.kext/PlugIns/Unsupported.kext from mkext for kernel load.
Omitting loaded kext /System/Library/Extensions/System.kext/PlugIns/IOKit.kext from mkext for kernel load.
Omitting loaded kext /System/Library/Extensions/System.kext/PlugIns/Libkern.kext from mkext for kernel load.
Omitting loaded kext /System/Library/Extensions/IONetworkingFamily.kext from mkext for kernel load.
Omitting loaded kext /System/Library/Extensions/IOPCIFamily.kext from mkext for kernel load.
Disabling KextAudit: SIP is off
KextAudit initialized: audit=F
Adding /Users/dingdongcheng/Desktop/itlwm.kext to mkext.
/Users/dingdongcheng/Desktop/itlwm.kext added 16323400-byte noncompressed executable to mkext.
Created mkext for architecture x86_64 containing 1 kexts.
Loading /Users/dingdongcheng/Desktop/itlwm.kext.
(kernel) User-space log flags changed from 0x0 to 0xfff.
(kernel) Received kext load request from user space.
(kernel) Received request from user space to load kext com.zxystd.itlwm.
(kernel) Recorded kext com.zxystd.itlwm as a candidate for inclusion in prelinked kernel.
(kernel) Loading kext com.zxystd.itlwm.
(kernel) Kext com.apple.kpi.bsd is already loaded.
(kernel) Kext com.apple.kpi.mach is already loaded.
(kernel) Kext com.apple.iokit.IONetworkingFamily is already loaded.
(kernel) Kext com.apple.iokit.IONetworkingFamily sending 2 personalities to the IOCatalogue and starting matching.
(kernel) Kext com.apple.kpi.iokit is already loaded.
(kernel) Kext com.apple.kpi.libkern is already loaded.
(kernel) Kext com.apple.iokit.IOPCIFamily is already loaded.
(kernel) Kext com.apple.iokit.IOPCIFamily sending 3 personalities to the IOCatalogue and starting matching.
(kernel) Allocated link buffer for kext com.zxystd.itlwm at 0xffffff7fa12f2000 (16261120 bytes).
(kernel) Kext com.zxystd.itlwm executable loaded; 3970 pages at 0xffffff7f866f2000 (load tag 149).
(kernel) Kext com.zxystd.itlwm calling module start function.
(kernel) OSMetaClass: Kext com.zxystd.itlwm class pci_intr_handle is a duplicate;kext com.zhong.AppleIntelWiFi already has a class by that name.
(kernel) Kext com.zxystd.itlwm did not start (return code 0xdc00400a).
(kernel) Kext com.zxystd.itlwm start failed (result 0xdc00400a).
(kernel) Kext com.zxystd.itlwm failed to load (0xdc008017).
(kernel) Failed to load kext com.zxystd.itlwm (error 0xdc008017).
(kernel) Kext com.zxystd.itlwm unloading.
(kernel) Kext com.zxystd.itlwm unwiring and unmapping linked executable.
(kernel) Kext com.zxystd.itlwm unloaded.
(kernel) Kext com.zxystd.itlwm removing all personalities naming it from the IOCatalogue.
Kernel error handling kext request - (libkern/kext) kext (kmod) start/stop routine failed.
Failed to load /Users/dingdongcheng/Desktop/itlwm.kext - (libkern/kext) kext (kmod) start/stop routine failed.
Failed to load /Users/dingdongcheng/Desktop/itlwm.kext - (libkern/kext) kext (kmod) start/stop routine failed.

**Comment by LeoLittleZhun** [comment]
HeliPort好像有点问题啊。对于不需要密码的wifi也要强制你输入密码。所以没有密码的WiFi就连不上

**Comment by williambj1** [comment]
@LeoLittleZhun 请按照 issue 模板打开一个新的 issue

**Comment by M69W** [comment]
**08-24-2020更**  ： 
[小新pro13](https://github.com/daliansky/XiaoXinPro-13-hackintosh) 在Big Sur中不禁用 ASPM 注入也能正常使用AX200/AX201
如果为了省电，`AX201`也可以改为以下`CNVW路径`，并设置对应的[ASPM工作模式](https://github.com/daliansky/OC-little/tree/master/01-%E5%85%B3%E4%BA%8EAOAC/01-5-%E8%AE%BE%E7%BD%AEASPM%E5%B7%A5%E4%BD%9C%E6%A8%A1%E5%BC%8F)
```
DeviceProperties\Add\PciRoot(0x0)/Pci(0x14,0x3)
DeviceProperties\Add\PciRoot(0x0)/PciRoot(0x0)/Pci(0x14,0x3)/Pci(0x0,0x0)
```

**Comment by LingyeHan** [comment]
这试了wif可以正常使用，就是bluetooth不显示，不知道怎么解决？
