### ISSUE TITLE
Purpose of itl80211.kext?

### ISSUE THREAD

**Issue by hacker1024** [OpenIntelWireless/itlwm#155]
Hi,
Thanks for these drivers - my 9560 card works superbly.
I've used only `itlwm.kext`, and everything works.
I can't find any clear documentation on what `itl80211.kext` is for, though. Is it possible to perhaps mention it in the README?

**Comment by zxystd** [comment]
it is a 80211 stack library, not a single functional kext.
these infos will be added in readme. thanks for your focus.
