### ISSUE TITLE
Compiling error on Xcode Catalina with itlwm

### ISSUE THREAD

**Issue by mr-vito** [OpenIntelWireless/itlwm#156]
I am trying to compile the latest version of itlwm with Xcode 11.5 on Catalina 10.5.5.

All I do is change the config.plist and compile but I get a semantic error, which fails to compile the itlwm.kext.

"Assigning to 'bus_addr_t' (aka 'unsigned long long') from incompatible type 'nullptr_t')"
File in question is io.cpp > itlwm:: iwm_dma_config_free(dma).

Thanks for your help!

![Schermata 2020-06-30 alle 23 34 09](https://user-images.githubusercontent.com/56235915/86181089-aa1a6380-bb2d-11ea-88c5-5ee07594961a.png)

**Comment by ErrorErrorError** [comment]
Make sure you're using the latest SDK when building.

**Comment by mr-vito** [comment]
> Make sure you're using the latest SDK when building.

Thanks for your reply! I am using macOS 10.15 when building, so latest non-beta SDK. Problem persists...

**Comment by ailuoku6** [comment]
![截屏2020-07-01 上午8 13 41](https://user-images.githubusercontent.com/23209876/86188981-dc9a7f80-bb72-11ea-898b-c9a9e2014623.png)

**Comment by Longcoming** [comment]
I am getting four errors when compiling:
//  itlwm

//  Copyright © 2020 钟先耀. All rights reserved.
#include "FwData.h"

const unsigned char itlwm_master[] = {
};

const long int itlwm_master_size = sizeof(itlwm_master);

const unsigned char *[] = {
};

const long int *_size = sizeof(*);

const struct FwDesc fwList[] = {
{IWL_FW("itlwm-master", itlwm_master, itlwm_master_size)},
{IWL_FW("*", *, *_size)},
};
const int fwNumber = 2;

**Comment by mr-vito** [comment]
> I am getting four errors when compiling:
> // itlwm
> 
> // Copyright © 2020 钟先耀. All rights reserved.
> #include "FwData.h"
> 
> const unsigned char itlwm_master[] = {
> };
> 
> const long int itlwm_master_size = sizeof(itlwm_master);
> 
> const unsigned char *[] = {
> };
> 
> const long int __size = sizeof(_);
> 
> const struct FwDesc fwList[] = {
> {IWL_FW("itlwm-master", itlwm_master, itlwm_master_size)},
> {IWL_FW("*", *, *_size)},
> };
> const int fwNumber = 2;

I can also confirm I have now 4 errors as well. Thanks!

**Comment by Longcoming** [comment]
ı solved my compiling problem by doing this.
1.open terminal
2.git clone https://github.com/zxystd/itlwm.git
3.locate the itlwm folder(users/your user name)
4.open itlwm
5.first run fwgen then target itlwm

ı hope it helps

**Comment by mehmetyukcell** [comment]
> ı solved my compiling problem by doing this.
> 
> 1.open terminal
> 
> 2.git clone https://github.com/zxystd/itlwm.git
> 
> 3.locate the itlwm folder(users/your user name)
> 
> 4.open itlwm
> 
> 5.first run fwgen then target itlwm
> 
> 
> 
> ı hope it helps

Thanks but How do you compiled Heliport?

**Comment by Longcoming** [comment]
ı only compiled itlwm.kext which is now not connecting.
I don't know Heliport,ıf you could enlighten me ı would be pleased.

**Comment by mr-vito** [comment]
> ı solved my compiling problem by doing this.
> 1.open terminal
> 2.git clone https://github.com/zxystd/itlwm.git
> 3.locate the itlwm folder(users/your user name)
> 4.open itlwm
> 5.first run fwgen then target itlwm
> 
> ı hope it helps

Thanks, this worked. No errors left now.

Although, when I changed the variable to 0 (https://github.com/zxystd/itlwm/issues/156#issuecomment-652113894), cleaned build folder, ran fwgen then itlwm target, it would not compile successfully.

**Comment by Longcoming** [comment]
NULL means empty,0 is not empty

**Comment by Longcoming** [comment]
can you connect now,because ı can't

**Comment by vitalpig** [comment]
> > ı solved my compiling problem by doing this.
> > 1.open terminal
> > 2.git clone https://github.com/zxystd/itlwm.git
> > 3.locate the itlwm folder(users/your user name)
> > 4.open itlwm
> > 5.first run fwgen then target itlwm
> > ı hope it helps
> 
> Thanks but How do you compiled Heliport?

I complied HeliPort by doing this. I don't know whether it is the right way.
1.git clone https://github.com/zxystd/HeliPort.git
2. cd HeliPort
3. pod install
4. open the HeliPort.xcworkspace

**Comment by Longcoming** [comment]
how did you install podfile?can you specify?

**Comment by vitalpig** [comment]
> how did you install podfile?can you specify?

open the terminal, locate the HeliPort folder , enter the command "pod install"

**Comment by Longcoming** [comment]
command not found:pod

**Comment by Longcoming** [comment]
after installing cocoapods,ıt worked.thanks.
By the way,heliport works
