### ISSUE TITLE
Release and Big Sur Support

### ISSUE THREAD

**Issue by hierimpaug** [OpenIntelWireless/itlwm#159]
Hi! Thanks for all the hard work you've been putting in this project. If I may ask what percentage are you in now in the development progress and how far will it take more to push for a Release of a 1.0? Do you also have plans for macOS Big Sur? Thanks again!

**Comment by williambj1** [comment]
No plans for Big Sur, since it's already perfectly supported.

![image](https://user-images.githubusercontent.com/45396585/86365815-95b0a500-bcac-11ea-92f0-92fc345f887a.png)

**Comment by ErrorErrorError** [comment]
Man that checkmark looks so misplaced on Big Sur lol. I will update WiFiMenuItemView with some improvements and fixed with wrapping text.

**Comment by williambj1** [comment]
It seems that Big Sur's macOS SDK has a broken icon set implementation.

Icons appear correctly when I build HeliPort with Xcode 12 Beta and Catalina's SDK.

![image](https://user-images.githubusercontent.com/45396585/86419574-25cf0880-bd06-11ea-9887-12bca2ed0b1c.png)

**Comment by ErrorErrorError** [comment]
> It seems that Big Sur's macOS SDK has a broken icon set implementation.
> 
> Icons appear correctly when I build HeliPort with Xcode 12 Beta and Catalina's SDK.
> 
> ![image](https://user-images.githubusercontent.com/45396585/86419574-25cf0880-bd06-11ea-9887-12bca2ed0b1c.png)

I was actually talking about the position of the check in relation to the "Turn Wi-Fi Off" text but now that you mentioned I can see the different check icon appearance lol
