### ISSUE TITLE
Connects to Wifi but does not get IP address after switching networks a few times with HeliPort

### ISSUE THREAD

**Issue by igorkulman** [OpenIntelWireless/itlwm#160]
On Intel 7260 AC when I just load the kext with my networks in Info.plist it always works fine.

With HelkiPort when I connected to a different network only most only works on second try, never on first try. Sometime I get to a state when I cannot connect back to my original network.

In my example, logs attached, I connected to K-guest and then was trying to connect back to K.

Although the status was connected I either got not IP address

![Screenshot 2020-07-03 at 20 48 06](https://user-images.githubusercontent.com/4746070/86492951-f5bc4f80-bd6f-11ea-9080-b80ff85a11e3.png)

Or a self assigned IP address

![image](https://user-images.githubusercontent.com/4746070/86493005-27351b00-bd70-11ea-99e2-8c8dd31a7081.png)

I tried renewing DHCP lease in System Preferences but it did not help.

I had to unload the kext and load it again to make it work again with K.

Logs: 
[itlwm.log](https://github.com/zxystd/itlwm/files/4871141/itlwm.log)

**Comment by ErrorErrorError** [comment]
More information: I noticed after reading the state of the WiFi card while trying to authenticate the SSID, reguardless if the password is right or wrong, the status when it's trying to connect actually returns `ITL80211_S_SCAN` rather than `ITL80211_S_ASSOC` or `ITL80211_S_AUTH`.

**Comment by zxystd** [comment]
can you check the latest code? thank you.
