### ISSUE TITLE
Requesting versioning and optimised 'Release' version in Git

### ISSUE THREAD

**Issue by mackonsti** [OpenIntelWireless/itlwm#163]
Hello @zxystd thank you for your continuous work on this driver!

Please, can I suggest that you include some form of versioning in your driver? Perhaps date-based inside the **Info.plist** ?

Both **CFBundleShortVersionString** and **CFBundleVersion** have not changed, kindly consider a release based on date e.g. **2020.07.04** that can always appear incremental per your commits...

Also, can I ask you why both _Release_ and _Debug_ compiled versions have the same size (about 16MB)? Is it the inclusion of the /firmware/ folder contents? Is is technically necessary to package them in such a big file? I guess judging from **BrcmFirmwareData.kext** technique, this must be the case... Was hoping for a solution like **BrcmFirmwareRepo.kext** but I guess Clover or OpenCore can't make it work like that, correct? (i.e. having firmware files in folder, instead)

Thank you.

**P.S.** Please do make your project settings to officially support Mojave (LSMinimumSystemVersion and BaseSDK) it works well, actually I am writing from my NUC!

**Comment by williambj1** [comment]
Mojave is supported.

You can delete other firmware and leave the one your card uses then compile the kext, this will significantly reduce the kext’s size. No macros are used to reduce kext size on release builds so they’re the same.

Using date as version is not a proper way of versioning, GitHub releases will come soon once HeliPort’s bugs are fixed and itlwm’s  CI and CD gets implemented.

**Comment by mackonsti** [comment]
Thank you for the tip and versioning news, appreciate it.

On a side note, please, how can we find out the detect / loaded firmware for the specific card? Is the exact firmware file name or model found in debug output of kernel? Today, I have no idea which file is used, to be honest. Thank you.

**Comment by williambj1** [comment]
The firmware file’s name simply the same as your card model, located inside the firmware folder.

You don't have to dig into those fancy logs.

**Comment by mackonsti** [comment]
Thank you @williambj1 however my Intel NUC is using 802.11ac wireless 9560 chipset [8086:9df0] hence the question :-) There is no such firmware file, so it must be something compatible with the existing files. Could it be **iwm-9260-34** ? Possibly, I am not sure. I would certainly like the debug output a little more verbose... The only readable thing I get is:
```
(itlwm) itlwm: iwm_match devId=0x9DF0
(itlwm) itlwm: itlwm: hw rev 0x310, fw ver 34.3125811985.0, address XYZ
```
Thanks!

**Comment by williambj1** [comment]
9000
