### ISSUE TITLE
your readme doesn't call out support for intel 

### ISSUE THREAD

**Issue by myusrn** [OpenIntelWireless/itlwm#165]
Your english readme document [ https://github.com/OpenIntelWireless/itlwm/blob/master/.github/README_en.md ] doesn't list the "8 Series:8260, 8265" in supported devices section like the main chinese language readme document [ https://github.com/OpenIntelWireless/itlwm/blob/master/README.md ] does.  

I suggest updating it to match as otherwise folks might be mislead into thinking 8 series adapters are not supported.

**Comment by zxystd** [comment]
thanks, the readme will be rewrite soon, add supported device ids instead of device product name.

**Comment by myusrn** [comment]
Thanks for details. I'll let you close this issue when you see fit. Looking forward to testing this kext with intel ax200 / wifi6 m2 adapter.

**Comment by mjsorribas** [comment]
It will be interesting if you share details of the install process after the compile process with xcode.

**Comment by myusrn** [comment]
@mjsorribas are you raising a new english readme.md related issue or is this feedback for the main readme.md provided in the itlwm repo?
