### ISSUE TITLE
AX200使用两分钟左右无法访问网络

### ISSUE THREAD

**Issue by CLAY-BIOS** [OpenIntelWireless/itlwm#167]
无论我使用2.4Ghz或5Ghz的Wi-Fi 网络都会在两分钟左右中断(使用目前最新的kext)
在HeilPort中显示已连接 但无法访问网络
解决方法是关闭Wi-Fi重新打开或者连接其他Wi-Fi
我注意到在日志中出现了mDNSResponder: [com.apple.mDNSResponder:SPS] CheckInterfaceSupport: No mDNS_Keepalive for interface en1/itlwmx_interface kr 0xE00002C0
[itlwm.log](https://github.com/OpenIntelWireless/itlwm/files/4886004/itlwm.log)

**Comment by zxystd** [comment]
日志里没有看到掉线，不过看到有大流量上传的情况，竟然避免吧
另外你说的那条日志是正常获取dns的日志，没有关系的。

**Comment by CLAY-BIOS** [comment]
我找到原因了 是路由器设置的问题
我把路由器设置为AP模式解决了这个问题
