### ISSUE TITLE
AC 9260 appears as ethernet

### ISSUE THREAD

**Issue by marcelloinfoweb** [OpenIntelWireless/itlwm#169]
I downloaded it today and compiled it, but it doesn't show the networks to access.

![Captura de Tela 2020-07-08 às 16 00 01](https://user-images.githubusercontent.com/2093128/86959496-4d720680-c134-11ea-9d09-6b9e1c53fb21.png)

**Comment by rafhagunz** [comment]
Download Heliport to manage networks. 👍

**Comment by zxystd** [comment]
Use Heliport. Also I hope you can take some time to read the README. thanks.
