### ISSUE TITLE
网速监控下载速度一直是0

### ISSUE THREAD

**Issue by bininc** [OpenIntelWireless/itlwm#172]
![image](https://user-images.githubusercontent.com/3025159/87110556-e5d5cb80-c299-11ea-8787-886f52c79b7a.png)
如图上所示，使用软件是腾讯的Lemon

**Comment by yuqZY** [comment]
是的，另外的外置的USB无线网卡也有这个问题，应该不是驱动的问题，可能跟系统有关系

**Comment by zxystd** [comment]
确实有这个问题，但是在10.14以下的系统是正常的。这种问题优先级比较低，以后发现问题了再修复吧。

**Comment by lang-ji** [comment]
10.15以后的很多系统都有这种问题，我的做法是照图中步骤把wifi硬件套一层桥接器，这样就能监听了
![image](https://user-images.githubusercontent.com/23096078/87389690-cb715a00-c5d9-11ea-84e4-a89169c0d26e.png)
![iShot2020-07-14下午01 57 02](https://user-images.githubusercontent.com/23096078/87390160-dbd60480-c5da-11ea-910b-ebb9f6b4fc2f.jpg)

**Comment by shomerchang** [comment]
嗯 是有这个问题

**Comment by bininc** [comment]
> 10.15以后的很多系统都有这种问题，我的做法是照图中步骤把wifi硬件套一层桥接器，这样就能监听了
> ![image](https://user-images.githubusercontent.com/23096078/87389690-cb715a00-c5d9-11ea-84e4-a89169c0d26e.png)
> ![iShot2020-07-14下午01 57 02](https://user-images.githubusercontent.com/23096078/87390160-dbd60480-c5da-11ea-910b-ebb9f6b4fc2f.jpg)

你这个方法看起来不错啊，试试看

**Comment by sgzman** [comment]
使用PeakHour4这个软件试试

**Comment by Misaka13514** [comment]
> 10.15以后的很多系统都有这种问题，我的做法是照图中步骤把wifi硬件套一层桥接器，这样就能监听了
> ![image](https://user-images.githubusercontent.com/23096078/87389690-cb715a00-c5d9-11ea-84e4-a89169c0d26e.png)
> ![iShot2020-07-14下午01 57 02](https://user-images.githubusercontent.com/23096078/87390160-dbd60480-c5da-11ea-910b-ebb9f6b4fc2f.jpg)

成功解决
第一步是齿轮里管理虚拟接口
[创建方法](https://support.apple.com/zh-cn/guide/mac-help/mh43557/mac)

**Comment by uifor** [comment]
macOS big sur 11.0.1下面在新建桥接器找不到Wi-Fi选项
![截屏2020-11-07 11 30 43](https://user-images.githubusercontent.com/13254011/98430989-ad7db700-20ec-11eb-80ca-9e0da4e326b6.png)

**Comment by llkhs** [comment]
<img width="580" alt="截屏2020-11-07 下午4 26 24" src="https://user-images.githubusercontent.com/51050409/98436495-a7043500-2116-11eb-8a09-b76b82ccb79c.png">
我把wifi硬件套一层桥接器，似乎还是不能监听

**Comment by llkhs** [comment]
> <img alt="截屏2020-11-07 下午4 26 24" width="580" src="https://user-images.githubusercontent.com/51050409/98436495-a7043500-2116-11eb-8a09-b76b82ccb79c.png">
> 
> 我把wifi硬件套一层桥接器，似乎还是不能监听

请问是不是9560普遍都读不了下行网速？

**Comment by lvjin250** [comment]
我也是这问题，AC9462，我还以为是我系统问题，重装了还是没解决，用网线就是正常的，WiFi就不行，虽然问题小，但逼死强迫症。上面说桥接WiFi的，我试了，苹果官网也说了，不能桥接无线网络，裂开了

**Comment by Misaaya** [comment]
> 我也是这问题，AC9462，我还以为是我系统问题，重装了还是没解决，用网线就是正常的，WiFi就不行，虽然问题小，但逼死强迫症。上面说桥接WiFi的，我试了，苹果官网也说了，不能桥接无线网络，裂开了

最新的开发版本已经解决了这个问题，可以下载来试试
