### ISSUE TITLE
怎么用heliport啊

### ISSUE THREAD

**Issue by Evan-tc** [OpenIntelWireless/itlwm#174]
设置heliport开机自启动:
设置--用户与群组--登陆项--把heliport添加进去

我按这个设置了 然后重启后没有看到任何界面 点击右上角无线网上也没有wifi选择

**Comment by williambj1** [comment]
手动双击打开

**Comment by Evan-tc** [comment]
> 手动双击打开，自动启动会在未来添加。手动添加时确保本体在 Applications 文件夹，不然会因权限被阻止

![image](https://user-images.githubusercontent.com/40584291/87171697-9fb65180-c305-11ea-8b93-f1c117b3b442.png)
放到应用程序里后打开就是这样【应用程序“heliport"无法打开】

**Comment by williambj1** [comment]
程序不存在此问题，请检查你文件的完整性，编译环境等等。GitHub issue 不是个人问题求助的地方，请移步论坛，gitter，以及各大交流群
