### ISSUE TITLE
10.15.6 beta3版本

### ISSUE THREAD

**Issue by ghsssss** [OpenIntelWireless/itlwm#175]
10.15.6 beta3版本只能登录qq，无法打开网页，ax200 0618固件

**Comment by williambj1** [comment]
听上去不像是驱动的问题

**Comment by zxystd** [comment]
qq能用说明网络通了,应用层的东西内核层这边管不了.先给你关了,有更详细的信息的话可以附在这里大家一起讨论,谢谢.
