### ISSUE TITLE
关于itlwmx

### ISSUE THREAD

**Issue by XHL669** [OpenIntelWireless/itlwm#176]
您在远景论坛说，AX200等二代设备需要itlwmx来驱动，还说某些九系如我在用的9560也属于二代设备。
但是根据实测，itlwmx搭配HeliPort并不能上网，相反itlwm可以
而且编译出的itlwm.ketx有16MB，而itlwmx.kext只有4M多，
所以是怎么回事。。。

**Comment by williambj1** [comment]
9560马甲不少，有的是一代有的是二代，itlwm支持的设备多，内置固件多所以文件大，用能用的就好啦
