### ISSUE TITLE
Intel AC 9560 not detected

### ISSUE THREAD

**Issue by ccxex29** [OpenIntelWireless/itlwm#179]
The ProductID is 0xA370. (Device: 0xA370; Sub Device: 0x0034)
OpenCore macOS Catalina  

Upon booting, itlwm would show errors like :  
```
could not load firmware chunk 0 (error 1)
failed to load init firmware
```  
The kext is shown using `kextstat` but not in Hackintool's Extensions. The wifi card is not shown in Hackintool System Peripherals.  
Heliport just shows the WiFi Off and can't be turned on.

**Comment by zxystd** [comment]
full shutdown your computer, unplug the power cable, then boot macOS. Don't direct reboot from Windows or Linux, it will leave the card (0xA370) a bad state and won't work.
