### ISSUE TITLE
7260AC Not connecting.

### ISSUE THREAD

**Issue by hierimpaug** [OpenIntelWireless/itlwm#183]
Hi! I have been trying to make the itlwm.kext work but it unfortunately it won't work and it still show as Not Connected. As of now the kext is in C/K/O and I have tried to kextload but to no avail. 

Edit: **en3** is a USB Wifi Adapter and it is connected.

![Screen Shot 2020-07-14 at 5 57 13 PM](https://user-images.githubusercontent.com/67745665/87413156-801c7300-c5fc-11ea-9858-d5798512ce95.png)

**Comment by Xpl0itU** [comment]
You have to specify the network details in the info.plist file and reboot

**Comment by hierimpaug** [comment]
Yes I did specify the network details in the info.plist.

**Comment by Xpl0itU** [comment]
unplug the USB WiFi adapter and reboot

**Comment by hierimpaug** [comment]
@Xpl0itU I tried uninstalling the usb wifi adapter and rebuild the kext then load it/put in C/K/O still nothing. Tried to download Heliport and it shows the connected to the wifi icon on the menu bar but it is still not connected on the internet(Network Preferences)

**Comment by zxystd** [comment]
check your EFI, this card actually can work.
