### ISSUE TITLE
Awesome Work![Feature Request]

### ISSUE THREAD

**Issue by abaza7** [OpenIntelWireless/itlwm#188]
First of all, Thanks so much for your great efforts it works flawlessly for me (although a bit slower at 40mbps but I am not complaining lol). Do you have a paypal or a patreon if someone wants to support this awesome project?

Secondly, The feature request:
Would it be possible to inject it as an actual wifi instead of the ethernet spoofing? I have no idea how easy or hard it would be so I'm just proposing the idea. The thing is, if that is implemented that would suddenly mean that we can use handoff and continuity features without spending 80$+ on Wi-Fi cards.

Again thanks man!

**Comment by ErrorErrorError** [comment]
> First of all, Thanks so much for your great efforts it works flawlessly for me (although a bit slower at 40mbps but I am not complaining lol). Do you have a paypal or a patreon if someone wants to support this awesome project?
> 
> 
> 
> Secondly, The feature request:
> 
> Would it be possible to inject it as an actual wifi instead of the ethernet spoofing? I have no idea how easy or hard it would be so I'm just proposing the idea. The thing is, if that is implemented that would suddenly mean that we can use handoff and continuity features without spending 80$+ on Wi-Fi cards.
> 
> 
> 
> Again thanks man!

From what I've read implementing the Apple802.11 stack is fairly complicated/time consuming and worst part is that is closed source. There was actually another repo that attempted to add native support but we'll I haven't heard anything from them in months. Maybe in the future it will be considered by the team once the intel cards are more stable, however don't quote me on that.

**Comment by zxystd** [comment]
Just like above said, Apple80211 is closed source, no document, no sdks, system version dependent. We need too much time on reversing it and investigating how to use, and it will cause too much compatibility and stability problems. It is nonsense until we full implemented Intel card hardware features/net80211 stack(we SHOULD self implemented 80211 stack whether the Apple80211 is used).
BTW, airdrop/handoff/continuity  are entire large sub systems, different with you think there is a switch can enable it.
Thanks.

**Comment by igorkulman** [comment]
@zxystd you should probably rename this issue to something like `[Feature request] Airdrop / Handoff / Continuity support` to make it stand out as a pinned issue.

**Comment by zxystd** [comment]
> @zxystd you should probably rename this issue to something like `[Feature request] Airdrop / Handoff / Continuity support` to make it stand out as a pinned issue.

Yes, you are right.

**Comment by Stevemoretz** [comment]
What about Hotspot?Is that impossible too?

**Comment by ErrorErrorError** [comment]
> What about Hotspot?Is that impossible too?

Hotspot is unsupported as of now.

**Comment by cleihen** [comment]
能给个内测群吗？

**Comment by williambj1** [comment]
https://github.com/OpenIntelWireless/itlwm/tree/airport_impl
