### ISSUE TITLE
[Bug]Cannot turn on WIFI after a shutdown from windows

### ISSUE THREAD

**Issue by XHL669** [OpenIntelWireless/itlwm#189]
**Describe the bug**
Cannot turn on WIFI after a shutdown from windows. I don't know if it is because of itlwm or the HeliPort GUI. It needs a forced shutdown to work properly.

**To Reproduce**
1. Shut dowm from Windows
2. Boot and Login in  macOS
3. The WIFI icon will turn into blank one and HeliPort cannot turn on WIFI. ![截屏2020-07-15 下午12 14 31](https://user-images.githubusercontent.com/63577165/87502747-02587600-c695-11ea-8c70-284432cad607.png)

**Expected behavior**
Be able to turn on WIFI after a normal shutdown from Windows OS rather than a forced shutdown.

**Screenshots**
This is a screenshot after a normal shutdown from windows.
![截屏2020-07-15 下午12 26 29](https://user-images.githubusercontent.com/63577165/87503535-156c4580-c697-11ea-88db-acb4d3f2ad78.png)
HeliPort cannot find the driver. Click "Turn on WIFI" but there is no response.

This is a screenshot after a forced shutdown from windows.
![IMG_20200715_121139](https://user-images.githubusercontent.com/63577165/87503742-8e6b9d00-c697-11ea-9a5a-8bc296dda81a.png)

**Environment (please complete the following information):**
 - OS Version: macOS 10.15.5

**Comment by williambj1** [comment]
Duplication of #139

**Comment by XHL669** [comment]
> Duplicate of #139

I see, but how to cold boot except a forced shutdown?
I have already disabled "Quick boot" in Windows OS and "Secure Boot" in BIOS. What's more?

**Comment by ErrorErrorError** [comment]
> > Duplicate of #139
> 
> I see, but how to cold boot except a forced shutdown?
> I have already disabled "Quick boot" in Windows OS and "Secure Boot" in BIOS. What's more?

Still a WIP. As of now the only way to fix is to cold boot, i.e. forced shutdown.

**Comment by williambj1** [comment]
Really not that convenient, but for now that's the only solution, unfortunately.

**Comment by XHL669** [comment]
> > > Duplicate of #139
> > 
> > 
> > I see, but how to cold boot except a forced shutdown?
> > I have already disabled "Quick boot" in Windows OS and "Secure Boot" in BIOS. What's more?
> 
> Still a WIP. As of now the only way to fix is to cold boot, i.e. forced shutdown.

I am worried that long pressing power key to shut down could damage the computer such as the SSD, but now it is the only way.
Anyway, thank you both.

**Comment by zxystd** [comment]
> > > > Duplicate of #139
> > > 
> > > 
> > > I see, but how to cold boot except a forced shutdown?
> > > I have already disabled "Quick boot" in Windows OS and "Secure Boot" in BIOS. What's more?
> > 
> > 
> > Still a WIP. As of now the only way to fix is to cold boot, i.e. forced shutdown.
> 
> I am worried that long pressing power key to shut down could damage the computer such as the SSD, but now it is the only way.
> Anyway, thank you both.

You don't need to force shutdown, shutdown only as well. don't direct reboot to Mac, that will not have problem.

**Comment by XHL669** [comment]
> > > > > Duplicate of #139
> > > > 
> > > > 
> > > > I see, but how to cold boot except a forced shutdown?
> > > > I have already disabled "Quick boot" in Windows OS and "Secure Boot" in BIOS. What's more?
> > > 
> > > 
> > > Still a WIP. As of now the only way to fix is to cold boot, i.e. forced shutdown.
> > 
> > 
> > I am worried that long pressing power key to shut down could damage the computer such as the SSD, but now it is the only way.
> > Anyway, thank you both.
> 
> You don't need to force shutdown, shutdown normally as well. don't direct reboot to Mac, that will not have problem.

OK, thank you. Right now @williambj1 told me that I need shutdown without charging.
