### ISSUE TITLE
Intel AC3165无线网卡Bug提交

### ISSUE THREAD

**Issue by Code-God1024** [OpenIntelWireless/itlwm#192]
连接不上Windows系统下开的WI-FI热点，我用了三台Windows电脑开热点测试，都不可以，不知道算不算BUG，提交一下。别的Wi-Fi类型可以正常连接。

**Comment by Code-God1024** [comment]
这三台WI-FI的名称和密码中都不含有特殊字符

**Comment by zxystd** [comment]
重新复现一下，取一下log,
log show --last boot | grep itlwm >~/Desktop/itlwm.log
另外Wi-Fi名称是什么？加密类型是什么？

**Comment by Code-God1024** [comment]
今天我们这里断电了，要到晚上11点恢复，log晚点发给你。
WiFi1名称biubiubiu，密码fuck2see;
WiFi2名称jiu，密码erziyaoguai;
WiFi3名称ccc，密码880196XY;
加密都是wpa2personal;

---原始邮件---
发件人: "zxystd"<notifications@github.com&gt;
发送时间: 2020年7月17日(周五) 上午9:43
收件人: "OpenIntelWireless/itlwm"<itlwm@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"Code"<407654933@qq.com&gt;;
主题: Re: [OpenIntelWireless/itlwm] Intel AC3165无线网卡Bug提交 (#192)




 
重新复现一下，取一下log,
 log show --last boot | grep itlwm &gt;~/Desktop/itlwm.log
 另外Wi-Fi名称是什么？加密类型是什么？
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
 
---原始邮件---
发件人: "zxystd"<notifications@github.com&gt;
发送时间: 2020年7月17日(周五) 上午9:43
收件人: "OpenIntelWireless/itlwm"<itlwm@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"Code"<407654933@qq.com&gt;;
主题: Re: [OpenIntelWireless/itlwm] Intel AC3165无线网卡Bug提交 (#192)




 
重新复现一下，取一下log,
 log show --last boot | grep itlwm &gt;~/Desktop/itlwm.log
 另外Wi-Fi名称是什么？加密类型是什么？

**Comment by Code-God1024** [comment]
_

[itlwm.log](https://github.com/OpenIntelWireless/itlwm/files/4940857/itlwm.log)
_

**Comment by Code-God1024** [comment]
日志可以吗，不行的话我重新上传

**Comment by Code-God1024** [comment]
> 重新复现一下，取一下log,
> log show --last boot | grep itlwm >~/Desktop/itlwm.log
> 另外Wi-Fi名称是什么？加密类型是什么？
日志可以吗，不行的话我重新上传

**Comment by Code-God1024** [comment]
> 重新复现一下，取一下log,
> log show --last boot | grep itlwm >~/Desktop/itlwm.log
> 另外Wi-Fi名称是什么？加密类型是什么？

日志可以吗，不行的话我重新上传

**Comment by zxystd** [comment]
> > 重新复现一下，取一下log,
> > log show --last boot | grep itlwm >~/Desktop/itlwm.log
> > 另外Wi-Fi名称是什么？加密类型是什么？
> 
> 日志可以吗，不行的话我重新上传

下载半天下载不下来，发我邮箱吧1051244836@qq.com

**Comment by zxystd** [comment]
![image](https://user-images.githubusercontent.com/16227538/87871735-9e5fe580-c9e5-11ea-984e-e3ddd5be6b13.png)
跟网卡硬件没关系，是你的热点有问题，给的IE不符号标准。
![image](https://user-images.githubusercontent.com/16227538/87871740-a9b31100-c9e5-11ea-8eac-9262ad523b61.png)
