### ISSUE TITLE
[Bug] Wifi state does not persist after reboot/wake from sleep

### ISSUE THREAD

**Issue by nemphys** [OpenIntelWireless/itlwm#193]
**Describe the bug**
The wifi on/off state is not persisted after a reboot or wake from sleep.

**To Reproduce**
1. Reboot with wifi turned off

**Expected behavior**
Wifi state is off when the computer boots

**Environment (please complete the following information):**
 - OS Version: macOS Mojave
 - Software Version: latest git revision

**Comment by zxystd** [comment]
No need to fix in recent releases. thanks for you focus.

**Comment by alessiomatricardi** [comment]
Now wifi state is remembered from one session to another

**Comment by williambj1** [comment]
Documented
