### ISSUE TITLE
"Ethernet" not showing in Network Preferences

### ISSUE THREAD

**Issue by DellG3** [OpenIntelWireless/itlwm#197]
itlwm used to work fine. However, I deleted the "**Ethernet**" in network preferences. No internet works! Nothing shows. What to do?

**Comment by williambj1** [comment]
https://openintelwireless.gitbook.io/openintelwireless/general/troubleshooting#resetting-system-preferences-network

**Comment by DellG3** [comment]
Thanks! Resetting as mentioned in the guide worked.
