### ISSUE TITLE
[Feature Request] Map Function Keys to Toggle WiFi

### ISSUE THREAD

**Issue by 2eno** [OpenIntelWireless/itlwm#201]
Hello There,
I hope this is not the wrong place for this kind of request!
I just wonder whether it's possible to implement a feature so you can map a custom key to toggle wifi on and off.
Many laptops have a special "function key" to do this and, as far as I know, till now it's not possible to use it on Hackintosh.
With this driver, and the control through an external App: "HeliPort", I thought it should be technically possible to implement a feature to support it?
Thanks for reading!

**Comment by williambj1** [comment]
Theoretically, this would be possible, but it requires code changes in both VoodooPS2 and itlwm. Maybe @Goshin knows more about it.

**Comment by 1Revenger1** [comment]
Atleast for a lot of Thinkpads, they are EC queries. Though, normally what we do for backlight brightness is have them send PS2 key codes that correspond to brightness up and down, since those are keycodes that macOS and VoodooPS2 recognize.

**Comment by 1Revenger1** [comment]
Another approach is something similar to what [Thinkpad Assistance](https://github.com/MSzturc/ThinkpadAssistant) does, and use ACPI patches to send PS2 commands for Function keys above 12. We could capture those Function keys in HeliPort and show an icon when Wifi is enabled/disabled which may be a better option.

**Comment by junaedahmed** [comment]
https://github.com/MSzturc/ThinkpadAssistant/issues/23#issue-627413413

**Comment by Stevemoretz** [comment]
How about a few command that we could run in the command line to turn on, turn off, and get the status of wifi?Then we can use Automator service and put the commands there and then assign hotkey.Even tough the hotkey obviously wouldn't be fn + something but anyways, it's still great a lot of people included me don't even have a wifi button to press with fn.So why over complicate things for the start?

**Comment by Goshin** [comment]
I just added a service in HeliPort to toggle WiFi.

After updating the app (remember to install it in `Applications`) and rebooting, you will find a service named `HeliPort: Toggle WiFi` in `System Preferences > Keyboard > Shortcuts > Services > General`, then you can assign a keyboard shortcut for it.

![](https://user-images.githubusercontent.com/10056397/90335666-cc314d80-dfd6-11ea-9b19-44f6624ee8d7.png)


For Fn hotkeys based on EC queries, they are not able to be directly captured by the OS so it is out of the scope of itlwm and HeliPort. Luckily many laptop models send Fn hotkeys via WMI events. I have implemented a WMI driver months ago, with which you don't have to patch your DSDT to convert them to PS/2 key code. Check out the repo [here](https://github.com/Goshin/VoodooWMI).

**Comment by shervintravel** [comment]
# Developer 
**DanPattaya**
**[Official Site](https://dandeveloper.carrd.co)**
