### ISSUE TITLE
Internet speed is very slow in Intel 9560 Wi-Fi card. 

### ISSUE THREAD

**Issue by md-siam** [OpenIntelWireless/itlwm#202]
Hi,

First of all, thank you for your hard works. 
Internet speed is very slow in Intel 9560 Wi-Fi card in 5GHz. I checked the "Link Speed" and it is showing only 100Mbps whereas it should be around 860Mbps. The "Link Speed" in 2.4GHz is also only 100Mbps.

**Comment by williambj1** [comment]
duplicate of #198
