### ISSUE TITLE
Do you write drivers for..?

### ISSUE THREAD

**Issue by oybekrustamov** [OpenIntelWireless/itlwm#206]
Hello everyone, those who are interested.
Can you write a driver for Qualcomm Atheros devices?
More than 2-3 million users have QCA9377 card. I would like to see a driver for Mac OS from you. Many would be grateful for your work! Here I posted the necessary files (I think so), I think they will be useful to you .. Thank you!

[link: source in my repo](https://github.com/oybekrustamov/qca9377_fully_source)

**Comment by wklxd** [comment]
no, I think

**Comment by zxystd** [comment]
I am sorry to say no. I paid so much my spare time on this Intel driver, no plan for other drivers now. thanks.
