### ISSUE TITLE
I'm facing a weird issue with my wifi on hackintosh

### ISSUE THREAD

**Issue by swaroop2208** [OpenIntelWireless/itlwm#216]
My wifi in fluctuating continuesly even though I updated to new version can any give me suggestions how to fix it.
It would be really helpful for me.

**Comment by zxystd** [comment]
check the log by the command.
`log show --last boot | grep itlwm >~/Desktop/itlwm.log`
and send it to me.

**Comment by swaroop2208** [comment]
> check the log by the command.
> `log show --last boot | grep itlwm >~/Desktop/itlwm.log`
> and send it to me.
![Uploading Screenshot 2020-07-28 at 7.51.26 PM.png…]()

**Comment by swaroop2208** [comment]
> check the log by the command.
> `log show --last boot | grep itlwm >~/Desktop/itlwm.log`
> and send it to me.

![Screenshot 2020-07-28 at 7 51 26 PM](https://user-images.githubusercontent.com/68352363/88679970-a3bbdf00-d10d-11ea-9aa3-35fe11abc070.png)

**Comment by zxystd** [comment]
get the log file from your desktop, and upload here.

**Comment by swaroop2208** [comment]
itlwm.log

**Comment by zxystd** [comment]
log file, not file name, drag the file here and wait for upload done, then commit your comment.

**Comment by swaroop2208** [comment]
[system.log](https://github.com/OpenIntelWireless/itlwm/files/4989346/system.log)
[itlwm.log](https://github.com/OpenIntelWireless/itlwm/files/4989347/itlwm.log)

**Comment by zxystd** [comment]
the driver is worked, but your wifi password is wrong, check it, BTW, the driver version you are using is too old, download the latest. thanks.

**Comment by swaroop2208** [comment]
for your info wifi worked for 2 hours once i restarted it stopped working.
can u give me latest link for drivers.

**Comment by Syedayy** [comment]
https://github.com/OpenIntelWireless/itlwm/releases

itlwm under assets.

**Comment by Syedayy** [comment]
https://github.com/OpenIntelWireless/itlwm/releases

itlwm under assets.

**Comment by swaroop2208** [comment]
thank you will try...

**Comment by swaroop2208** [comment]
My issue have been solved as I updated my intel wi-fi and Bluetooth kexts and updates oc snapshot thanks for helping.
