### ISSUE TITLE
Frequently reboot with "OUTPUT_ERROR status=131"

### ISSUE THREAD

**Issue by daiyifei** [OpenIntelWireless/itlwm#218]
AC9560 with itlwm v1.0.0-alpha.Reboot every 10min or so.
Here's the log with many lines of "OUTPUT_ERROR status=131",hope it helps.
Thanks for the great job.
[itlwm.log](https://github.com/OpenIntelWireless/itlwm/files/5001655/itlwm.log)

**Comment by zxystd** [comment]
try to adjust your MTU to lower value.

**Comment by daiyifei** [comment]
> try to adjust your MTU to lower value.

Thanks a lot,setting to 1482 seems better now.
