### ISSUE TITLE
This is not a issue, but a query

### ISSUE THREAD

**Issue by Parthvsquare** [OpenIntelWireless/itlwm#221]
![image](https://user-images.githubusercontent.com/26404957/89073063-5fdc0a80-d397-11ea-8e54-5b0776d14d78.png)
this is how it should turn out right?
i came from reddit call for contributor. 
using LG Gram 14 (8265dw2)
i was using the hard wired version. i made a automator app and was not able to use sip for a long time. thanks guys for making this possible.
i have no issue with sleep, it takes a sec or few to restart. it's just and hour well keep updating

**Comment by Parthvsquare** [comment]
i haven't used the (firmware) itlmx.kext. just popped itlm to C/O, removed the files as requested from library->Preferences->systemConfiguration

**Comment by ErrorErrorError** [comment]
> this is how it should turn out right?

Yes that is supposed to turn out. itlwm/x creates an ethernet interface since Apple80211, macOS's Wi-Fi, is closed source.

 

> i haven't used the (firmware) itlmx.kext. just popped itlm to C/O, removed the files as requested from library->Preferences->systemConfiguration and reboot that's it

You should only use itlwmx if you have a gen 2 intel device. If you don't then you should be using itlwm.

**Comment by williambj1** [comment]
https://openintelwireless.github.io/

Please read our docs
