### ISSUE TITLE
[FEATURE REQUEST] Support for Location Services?

### ISSUE THREAD

**Issue by NotARobot6969** [OpenIntelWireless/itlwm#222]
I get it's emulating ethernet currently for the internet support, but, y'know, it'd be cool for Siri to know where I live.

**Comment by ErrorErrorError** [comment]
As far as I've read, it needs Apple80211, which is a closed source. I don't think it's possible at this state, but maybe in the future once, however don't quote me on that.

**Comment by williambj1** [comment]
Duplicate of #182

**Comment by williambj1** [comment]
Duplicate of #194

**Comment by williambj1** [comment]
Duplicate of #40
