### ISSUE TITLE
Bangla(বাংলা) Translation

### ISSUE THREAD

**Issue by md-siam** [OpenIntelWireless/itlwm#224]
If you want to include "Bangla Translation" then I want to contribute to this project.

**Comment by ErrorErrorError** [comment]
> If you want to include "Bangla Translation" then I want to contribute to this project.

You can create a pull request once you have the Bangla translation ready.

**Comment by zxystd** [comment]
Good boy, thank you very much, but I think English and Chinese the two languages are enough in `itlwm`, and easy to maintain.
