### ISSUE TITLE
NUC8 Intel 9560 Wifi Problems

### ISSUE THREAD

**Issue by Ibrahim778** [OpenIntelWireless/itlwm#225]
For some reason my wifi only works when I run it on the SECOND Reboot. For example after a cold start it doesnt work reboot and its fine. Same for windows I have to go into macOS once and reboot again to make it work otherwise Heliport doesn't show any wifi networks. I'm on Catalina btw.

**Comment by williambj1** [comment]
1. Please specify your kext and heliport version
2. Provide logs for failures and successes
3. Test again with a Linux live USB

Based on your info, it's impossible to identify whether it's your issue or ours.

**Comment by zxystd** [comment]
Try remove All the Intel kexts, and try again if it is still happened in Windows.
And, fill all necessary info like @williambj1  said, so we can locate where is the problem. thanks.

**Comment by Ibrahim778** [comment]
Right. Sorry It's getting late now and I'm Busy tomorrow so I'll do what you said the day after. I never had these problems in windows or Linux. Thanks you very much for your quick response!  :)

**Comment by zxystd** [comment]
OK, waiting for your further response, if problem exists, maybe we need your help to locate the problem and test, thanks.

**Comment by Ibrahim778** [comment]
OK back now so how do I provide log files? I don't actually know the version because I found this kext and heliport on a subreddit a while ago but I think It's fairly recent.

**Comment by ErrorErrorError** [comment]
> OK back now so how do I provide log files? I don't actually know the version because I found this kext and heliport on a subreddit a while ago but I think It's fairly recent.

Please use the latest version, I.e. the latest compiled. You can get it here https://github.com/OpenIntelWireless/itlwm/releases/

**Comment by Ibrahim778** [comment]
Ok. Ill report back with the new version soon

**Comment by williambj1** [comment]
Please reopen if necessary.
