### ISSUE TITLE
HeliPort not working

### ISSUE THREAD

**Issue by Babyvox550** [OpenIntelWireless/itlwm#227]
![截屏2020-08-02 下午12 24 26](https://user-images.githubusercontent.com/13328183/89115471-2997ab80-d4bb-11ea-8c24-646590cfd35a.png)
![截屏2020-08-02 下午12 23 40](https://user-images.githubusercontent.com/13328183/89115472-2ac8d880-d4bb-11ea-89b3-82681c1ed9a7.png)
![截屏2020-08-02 下午12 05 49](https://user-images.githubusercontent.com/13328183/89115474-2d2b3280-d4bb-11ea-8bba-fd7cee9ec388.png)
Heliport still not working!!!!

OC as follows:

![截屏2020-08-02 下午12 25 39](https://user-images.githubusercontent.com/13328183/89115494-5cda3a80-d4bb-11ea-939e-68183570efbf.png)
![截屏2020-08-02 下午12 25 55](https://user-images.githubusercontent.com/13328183/89115495-5e0b6780-d4bb-11ea-87bc-b877c1ce24d4.png)

What should I do next?

**Comment by Babyvox550** [comment]
![截屏2020-08-02 下午12 30 16](https://user-images.githubusercontent.com/13328183/89115539-f570ba80-d4bb-11ea-9253-113b5017bd3f.png)
Hackintool showed wifi is drived.

**Comment by 1Revenger1** [comment]
Get logs and see if itlwm attached right. The PCIe section of Hackintool doesn't show if the driver attached, Hackintool has it's own way to recognize PCIe devices.

https://openintelwireless.github.io/General/Troubleshooting.html

**Comment by zxystd** [comment]
Use the latest pre-release kext will help you fix this. Ac9462 certainly can work now.
