### ISSUE TITLE
will it be supported EDUROAM for University Campus

### ISSUE THREAD

**Issue by mehmetyukcell** [OpenIntelWireless/itlwm#230]
I am an PhD student in the university. will it be supported for eduroam internet connection?

**Comment by ErrorErrorError** [comment]
As of now there are still things that need to be implemented before you will be able to connect to networks that require Username and password

**Comment by mehmetyukcell** [comment]
> As of now there are still things that need to be implemented before you will be able to connect to networks that require Username and password 

what are these things? I have username and password. i will try to connect next week with Eduroam in the campus.

**Comment by ErrorErrorError** [comment]
https://github.com/OpenIntelWireless/HeliPort/issues/4

**Comment by mehmetyukcell** [comment]
> https://github.com/OpenIntelWireless/HeliPort/issues/4
> 

Thanks for your interest, Sincerely

**Comment by williambj1** [comment]
Duplicate of #101
