### ISSUE TITLE
关于昨天更新的wifi驱动

### ISSUE THREAD

**Issue by Tazlorkkenm** [OpenIntelWireless/itlwm#231]
丢进kext之后进入黑苹果没有进度条，就一直卡在苹果logo，用之前版本的驱动则不会

**Comment by williambj1** [comment]
没有 -v 图，没有日志，没有设备信息，我们无法排错。提供完这些信息后我会重新 open，具体排错和日志获取方式可以阅读文档，用其他渠道求助他人

**Comment by Tazlorkkenm** [comment]
抱歉大哥，我下错驱动了，刚刚下了9代驱动的完美运行，现在可以直接更好WiFi了，非常完美 谢谢大佬，期待稳定版！
