### ISSUE TITLE
itlwm works after a few restarts

### ISSUE THREAD

**Issue by FaneCH** [OpenIntelWireless/itlwm#232]
When i try to load the driver, it shows in terminal that it loaded successful but nothing happens (heliport shows itlwm not running). After a few restarts, it connects.
I'm running macOS Catalina 10.15.6 and my WiFi card is Intel AC 3165.
L.E: Tried with the latest prebuild version of itlwm.

![Screenshot 2020-08-03 at 18 46 04](https://user-images.githubusercontent.com/33597024/89202690-043e9680-d5bc-11ea-8274-0b8d1a558733.png)

**Comment by ErrorErrorError** [comment]
Please upload logs https://openintelwireless.github.io/General/Troubleshooting.html#kernel-extensions

**Comment by FaneCH** [comment]
Got it to work after a few reboot and deleting the stuff from network.

![Screenshot 2020-08-03 at 19 47 51](https://user-images.githubusercontent.com/33597024/89206990-aeb9b800-d5c2-11ea-8206-420b07ca2c86.png) 

There are the logs:
[Log_2020-08-03_19-49-54.log](https://github.com/OpenIntelWireless/itlwm/files/5017201/Log_2020-08-03_19-49-54.log)

**Comment by Silfalion** [comment]
> Got it to work after a few reboot and deleting the stuff from network.
> 
> ![Screenshot 2020-08-03 at 19 47 51](https://user-images.githubusercontent.com/33597024/89206990-aeb9b800-d5c2-11ea-8206-420b07ca2c86.png)
> 
> There are the logs:
> [Log_2020-08-03_19-49-54.log](https://github.com/OpenIntelWireless/itlwm/files/5017201/Log_2020-08-03_19-49-54.log)

Could you specify the things you deleted please?

**Comment by FaneCH** [comment]
In the network pane (sys pref) i had two connections: one for bluetooth, one for ethernet (from a usb wifi dongle).
I deleted those 2 things and after a couple of tries, it worked. This is my problem, itlwm is not loading everytime after a reboot even if the output of kextload/ kexutil says so.

**Comment by Silfalion** [comment]
Thank for the details. Encountered that problem as well. I restarted twice and it works now but only tested for 2 restarts.

**Comment by zxystd** [comment]
@FaneCH @Silfalion I think that's yours EFI issue, the driver loaded, but can't find the network device, driver is passive load and match by system, if the system didn't pass the PCI device, how can the driver work?

**Comment by Silfalion** [comment]
I’ll retest now with a few restarts and btw, thank you so much. I’m over the top to have wifi working at mostly full speed right now.

**Comment by Silfalion** [comment]
just tried now, on cold boot it doesn't work, the driver loads, heliports launches and detects the wifi, connects to it but always have an exclamation mark on it. After a restart it works(writing these lines from the Hackintosh). Any ideas?

**Comment by zxystd** [comment]
@Silfalion if the Heliport can show the network, that means the driver is working, if the network didn't get a IP address then Heliport will show an exclamation mark on it. for more detail, you should give me to log. 
`log show --last boot | grep itlwm >~/Desktop/itlwm.log`
also, tell me the time the problem happened.

**Comment by Silfalion** [comment]
Here is the log file, on cold start, same problem:

[itlwm.log](https://github.com/OpenIntelWireless/itlwm/files/5040851/itlwm.log)

**Comment by zxystd** [comment]
@Silfalion everything works fine, the network is connected, just wait for the ip address. or you can change the router channel 1 to others.

**Comment by Silfalion** [comment]
Thing is, it connects immediately after restarting, whether I wait 10 mn on a cold start or 1. On cold start it never connects despite how long I wait.

**Comment by FaneCH** [comment]
@zxystd i putted itlwm.kext into kexts folder (OC) and after log in, it doesn't connect to internet. Only timewhen it connects to internet is when i load it manually from terminal.
[Log_2020-08-08_15-48-04.log](https://github.com/OpenIntelWireless/itlwm/files/5045266/Log_2020-08-08_15-48-04.log)

**Comment by zxystd** [comment]
@FaneCH edit your OC config.plist, configure the itlwm.kext injection info.

**Comment by zxystd** [comment]
close. this is a EFI issue.
