### ISSUE TITLE
Unable to boot mac os without usb

### ISSUE THREAD

**Issue by swaroop2208** [OpenIntelWireless/itlwm#234]
Hi today i dual booted in my lap with windows.
everything was fine i just added some resources and tried to boot but the boot failed.
so i made recovery dmg file for booting and booted the mac os removed those files and replaced with proper one.
the problem is that im unable to boot to open core without usb.if i removed usb open core option is not available at all.
any solution for this.it would be really helpful for me..

**Comment by zxystd** [comment]
EFI issue, check by your self please. thanks you.

**Comment by swaroop2208** [comment]
> EFI issue, check by yourself please. thanks you.

Ya I found the solution thank you..
