### ISSUE TITLE
No conection to Magic Mousse

### ISSUE THREAD

**Issue by chris1111** [OpenIntelWireless/itlwm#245]
I'm using ➤ [PCE-AC55BT-B1](https://www.asus.com/ca-en/Networking/PCE-AC55BT-B1/)
No device detect ?
![Capture d’écran, le 2020-08-10 à 21 11 51](https://user-images.githubusercontent.com/6248794/89846058-2dc46880-db4e-11ea-8026-103b6cae06a8.png)

If I disconnect the BT cable of the motherboard and I reboot then use my ORICO - Dongle USB Bluetooth 4.0 (BTA-403-BK)

its work 
![Capture d’écran, le 2020-08-10 à 21 25 48](https://user-images.githubusercontent.com/6248794/89846812-45045580-db50-11ea-89d6-469ea05f2540.png)

**Comment by ErrorErrorError** [comment]
This is the wrong repository for this issue. It should be in IntelBluetoothFirmware. Also, run `kextstat | grep IntelBluetoothFirmware` in terminal to check if it's loaded.

**Comment by chris1111** [comment]
> This is the wrong repository for this issue. It should be in IntelBluetoothFirmware. Also, run `kextstat | grep IntelBluetoothFirmware` in terminal to check if it's loaded.
I closed the issue I disconnect the BT cable and put in the Box
Thanks
