### ISSUE TITLE
网速慢是否是因为无线只跑在20Mhz呢～

### ISSUE THREAD

**Issue by hesongtao96** [OpenIntelWireless/itlwm#253]
大佬您好，非常感谢您辛苦制作的驱动，在我的matebook13 2019网卡上确实存在网速过慢的问题，我看了下路由器 我的笔电使用的是20Mhz频率，其他设备都是使用80Mhz频率，纯粹是小白多嘴一句，请问下这是否是造成网速慢的原因呢，小白再次谢谢大佬的辛苦工作，谢谢您！

**Comment by williambj1** [comment]
802.11n 20MHz 的实际使用速度峰值就只能这样了，40/80/160 AC/AX 以后会慢慢支持
