### ISSUE TITLE
9560 AC 0x8086:0x9DB1  support

### ISSUE THREAD

**Issue by teewhydope** [OpenIntelWireless/itlwm#255]
please can you add support for 9560 AC with IDs 0x8086:0x9DB1 and 0x8086:0x9DB0

i'm unable to connect to any hotspot with heliport

**Comment by williambj1** [comment]
9DB1 is a PCI controller's ID, not a Wi-Fi card, reconfirm your ID

**Comment by williambj1** [comment]
https://pci-ids.ucw.cz/read/PC/8086/9db1
