### ISSUE TITLE
WiFi disconnects after a few seconds

### ISSUE THREAD

**Issue by redouglas39** [OpenIntelWireless/itlwm#256]
I have the ac7265 WiFi card and the WiFi disconnects itself from a few seconds to a minute after i turn on WiFi on the heliport. The WiFi fluctuates and I don’t have the same problem when using windows. Here’s the log. Thanks!
[log.txt](https://github.com/OpenIntelWireless/itlwm/files/5075162/log.txt)

**Comment by alessiomatricardi** [comment]
I've also this card (pci 0x095a) but i haven't this problem. It seems works well

**Comment by williambj1** [comment]
Try adjusting the MTU value in sys prefs

**Comment by redouglas39** [comment]
> Try adjusting the MTU value in sys prefs

I have adjusted to the minimum (1200) and maximum (1500) and same behavior is still occurred

**Comment by zxystd** [comment]
seems driver is trying to reconnect to ap after background scan, you are too far away from router? i will take a look tomorrow for the detail.

**Comment by redouglas39** [comment]
> seems driver is trying to reconnect to ap after background scan, you are too far away from router? i will take a look tomorrow for the detail.

Oh yes the connection seems better when I moved it near the router. Yet the signal I got is still weaker than in windows 10. Thanks!
