### ISSUE TITLE
System hang for kernel panic

### ISSUE THREAD

**Issue by xunkutech** [OpenIntelWireless/itlwm#259]
Machine info:
Dell Optiplex 9020m, 4690t, intel ac7260 wifi+bt combo.

Error message:
panic(cpu 0 caller 0xffffff7f9846708a): itlwm: mac clock not ready
Backtrace (CPU 0), Frame : Return Address
0xffffff820a3739a0 : 0xffffff801371a65d mach_kernel : _handle_debugger_trap + 0x49d
0xffffff820a3739f0 : 0xffffff8013854a75 mach_kernel : _kdp_i386_trap + 0x155
0xffffff820a373a30 : 0xffffff80138465fe mach_kernel : _kernel_trap + 0x4ee
0xffffff820a373a80 : 0xffffff80136c0a40 mach_kernel : _return_from_trap + 0xe0
0xffffff820a373aa0 : 0xffffff8013719d27 mach_kernel : _DebuggerTrapWithState + 0x17
0xffffff820a373ba0 : 0xffffff801371a117 mach_kernel : _panic_trap_to_debugger + 0x227
0xffffff820a373bf0 : 0xffffff8013ec1abc mach_kernel : _panic + 0x54
0xffffff820a373c60 : 0xffffff7f9846708a com.zxystd.itlwm : __ZN5itlwm21iwm_nic_assert_lockedEP9iwm_softc.cold.2
0xffffff820a373c70 : 0xffffff7f98460d1a com.zxystd.itlwm : __ZN5itlwm21iwm_nic_assert_lockedEP9iwm_softc + 0x62
0xffffff820a373c90 : 0xffffff7f98460efe com.zxystd.itlwm : __ZN5itlwm12iwm_nic_lockEP9iwm_softc + 0x2c
0xffffff820a373cc0 : 0xffffff7f98460e4f com.zxystd.itlwm : __ZN5itlwm12iwm_read_memEP9iwm_softcjPvi + 0x2d
0xffffff820a373d00 : 0xffffff7f9845acf4 com.zxystd.itlwm : __ZN5itlwm13iwm_nic_errorEP9iwm_softc + 0x84
0xffffff820a373dd0 : 0xffffff7f9845ac02 com.zxystd.itlwm : __ZN5itlwm12iwm_watchdogEP5ifnet + 0x96
0xffffff820a373e00 : 0xffffff7f9843f3a7 com.zxystd.itlwm : __ZN5itlwm14watchdogActionEP18IOTimerEventSource + 0x23
0xffffff820a373e20 : 0xffffff8013e32329 mach_kernel : __ZN18IOTimerEventSource15timeoutSignaledEPvS0_ + 0x89
0xffffff820a373e90 : 0xffffff8013e32249 mach_kernel : __ZN18IOTimerEventSource17timeoutAndReleaseEPvS0_ + 0x99
0xffffff820a373ec0 : 0xffffff801375c605 mach_kernel : _thread_call_delayed_timer + 0xec5
0xffffff820a373f40 : 0xffffff801375c131 mach_kernel : _thread_call_delayed_timer + 0x9f1
0xffffff820a373fa0 : 0xffffff80136c013e mach_kernel : _call_continuation + 0x2e
      Kernel Extensions in backtrace:
         com.zxystd.itlwm(1.0)[92FD4ADD-2DDB-3D57-9466-C65CEA45F960]@0xffffff7f9841f000->0xffffff7f99375fff
            dependency: com.apple.iokit.IONetworkingFamily(3.4)[2FA065D5-72F7-3BE5-855C-E45B01AEFBD4]@0xffffff7f944b0000
            dependency: com.apple.iokit.IOPCIFamily(2.9)[DF219CC1-366A-31FC-B8ED-17C584BA2549]@0xffffff7f94112000

BSD process name corresponding to current thread: kernel_task
Boot args: -v keepsyms=1 debug=0x100 chunklist-security-epoch=0 -chunklist-no-rev2-dev

Mac OS version:
19G2021

Kernel version:
Darwin Kernel Version 19.6.0: Thu Jun 18 20:49:00 PDT 2020; root:xnu-6153.141.1~1/RELEASE_X86_64
Kernel UUID: 1D3A0F3D-D908-397B-BD16-8F48C0823A2E
Kernel slide:     0x0000000013400000
Kernel text base: 0xffffff8013600000
__HIB  text base: 0xffffff8013500000
System model name: iMac15,1 (Mac-42FD25EABCxxxxxx)
System shutdown begun: NO
Panic diags file available: YES (0x0)

System uptime in nanoseconds: 4321101173949

**Comment by williambj1** [comment]
According to the panic logs, your device stopped responding and this panic is designed to catch such an issue. It’s not related to itlwm and likely caused by your incorrect efi configuration or a hardware issue.
