### ISSUE TITLE
删掉Itlwm.kext之后有线无法联网了，有线驱动正常加载着的

### ISSUE THREAD

**Issue by Cxp1220** [OpenIntelWireless/itlwm#263]

**Comment by williambj1** [comment]
这个问题和本驱动无关，驱动都卸载了。尝试重置系统网口设置 / 重装系统。

**Comment by Cxp1220** [comment]
> 这个问题和本驱动无关，驱动都卸载了。尝试重置系统网口设置/重装系统。

系统刚重装了15.6，有线还是一样的无法联网，使用这个驱动之前是可以联网的
