### ISSUE TITLE
Can't connect because of wifi password is too long

### ISSUE THREAD

**Issue by Silfalion** [OpenIntelWireless/itlwm#266]
**Have You Read Our Docs**
Yes

**Are You Reporting A Bug**
Yes

**Environment**

- Kext Version: 1.0.0
- WiFi Card Model: Intel 7260
- Product ID: 
- macOS Version: 10.15.5

**Description**
Wifi connects but maintains the exclamation mark when connected to a network that has a long password(26 characters). It turns out it was the reason for when mentioned it wasn't connecting in previous posts.

**Bug Report Archive** 
[bugreport_6040.zip](https://github.com/OpenIntelWireless/itlwm/files/5114204/bugreport_6040.zip)

**Upload your Kext**
[itlwm_v1.0.0_stable.kext.zip](https://github.com/OpenIntelWireless/itlwm/files/5114195/itlwm_v1.0.0_stable.kext.zip)

**Comment by zxystd** [comment]
seems that it is a router compatibility problem, not related to the password length, also, you can try to reduce password's length and try again, I don't think it can work. BTW, can you provide your router model?

**Comment by Silfalion** [comment]
Actually I tries that on another router, a windows hotspot as well as my iphone's. Iphone and windows work perfectly well, and the 2 routers as well when I shorten the password. The model of the routers is the same, tl-wpa281.

**Comment by zxystd** [comment]
@Silfalion Can you provide the ssid and password and encryption, I will have a try.

**Comment by Silfalion** [comment]
Can I message you the info? There is almost zero chance someone would get the info around here but just in case.

**Comment by zxystd** [comment]
of course you can send it through gitter, I will try it tomorrow.

**Comment by Silfalion** [comment]
Thank you. Will do that right away.

**Comment by williambj1** [comment]
Closed due to no further response.
Feel free to reopen.

**Comment by Silfalion** [comment]
After trying multiple times, I think the problem is the wifi not being able to obtain an ip address from the AP, event the airport new version. Any ideas?

![Screen Shot 2020-09-23 at 2 03 23 PM](https://user-images.githubusercontent.com/23188369/94016136-ac473380-fda5-11ea-8492-68b91b3422b0.png)
