### ISSUE TITLE
doesn't connect iPhone hotspot

### ISSUE THREAD

**Issue by manmassimo** [OpenIntelWireless/itlwm#267]
**Have You Read Our Docs**
yes

**Are You Reporting A Bug**
yes

**Environment**

- Kext Version:1.0.0
- WiFi Card Model: ac7265
- Product ID: 
- macOS Version: 10.15.6

**Description**
<can't connect to iPhone personal hotspot>

**Bug Report Archive**

**Upload your Kext**

**Comment by ErrorErrorError** [comment]
As mentioned on the bug reporter, upload your kext and upload logs to see why it's not connecting.

**Comment by williambj1** [comment]
Please reopen once you provide the files.
