### ISSUE TITLE
can't connect with iPhone personal hotspot

### ISSUE THREAD

**Issue by manmassimo** [OpenIntelWireless/itlwm#269]
**Have You Read Our Docs**
yes

**Are You Reporting A Bug**
yes

**Environment**

- Kext Version:itlwm1.0.0 
- WiFi Card Model:ac7235 
- Product ID: itlwm
- macOS Version: 10.15.6

**Description**
doesn't work with iPhone hotspot
**Bug Report Archive**

[itlw.pdf](https://github.com/OpenIntelWireless/itlwm/files/5119612/itlw.pdf)

**Upload your Kext**
[itlwm_v1.0.0_stable.kext.zip](https://github.com/OpenIntelWireless/itlwm/files/5119558/itlwm_v1.0.0_stable.kext.zip)

**Comment by hesongtao96** [comment]
Same issue.

**Comment by zxystd** [comment]
what's the ssid, wifi encryptions? there is only contains scanning logs.

**Comment by manmassimo** [comment]
Only that I have. The ssid is isevenup . No more information about it.

**Comment by williambj1** [comment]
Closed due to no further response.
