### ISSUE TITLE
itlwm will render IntelBluetoothWireless useless if loaded from OpenCore

### ISSUE THREAD

**Issue by tommyvct** [OpenIntelWireless/itlwm#272]
**Have You Read Our Docs**
Yes, your documentation sucks
**Are You Reporting A Bug**
Yes

**Environment**

- Kext Version: 1.0 stable
- WiFi Card Model: AC3168
- Product ID: 
- macOS Version: 10.15.6

**Description**

If `itlwm` is loaded along with `IntelBluetoothFirmware` kexts from OpenCore bootloader, `IntelBluetoothFirmware` will be failed to upload the firmware to the bluetooth part of the wireless card, cause the bluetooth not available for use. It will also make the whole system lag so bad that the mouse will turn into a beachball every other a minute or so, especially when opening  network settings under system preferences; no adapter are shown and the system will went beachball for a long time.

However, if `itlwm` is loaded with `kextutil` the bluetooth will work just fine. This paticular behaviour happens regardless of `IntelBluetoothFirmware` is loaded from the bootloader or not.

**Bug Report Archive**

[kextutil loaded](https://github.com/OpenIntelWireless/itlwm/files/5126855/bugreport_49151.zip)
[opencore loaded](https://github.com/OpenIntelWireless/itlwm/files/5126904/bugreport_65159.zip)

**Upload your Kext**

[itlwm_v1.0.0_stable.kext.zip](https://github.com/OpenIntelWireless/itlwm/files/5126854/itlwm_v1.0.0_stable.kext.zip)

I'm really impressed this actually works. Appreciated for your hard work, keep it up!

**Comment by Drun555** [comment]
I'm using IntelBluetoothFirmware, itlwm and OpenCore, and it is all working together just fine. Btw, I'm experienced same lags before, but with new versions it's becoming a lot better. Didn't have any problems with last releases yet. Did you tried alpha-releases?

**Comment by zxystd** [comment]
Tested on Intel 3165ac, no problems you described can be reproduced. I think it is an EFI related issue, maybe you can try to turn to check the EFI or the network card? Thanks.

**Comment by tommyvct** [comment]
https://github.com/OpenIntelWireless/IntelBluetoothFirmware/issues/177

I also filed another issue on IntelBluetoothWireless side, my later thought is this kext is not the culprit, IntelBluetoothWireless is. 

I assume there are some racing conditions that happens by chance.

Also, I found that cleaning the kext caches is particularly important during the process of swapping kexts, but this methodology is not in the troubleshoot section of the document.

**Comment by williambj1** [comment]
> Also, I found that cleaning the kext caches is particularly important during the process of swapping kexts, but this methodology is not in the troubleshoot section of the document.

Unless you are installing the kexts in L/E or S/L/E, rebuilding(If it's not the same as “cleaning” plz correct me) kext cache makes no difference at all. Bootloader injection will not be affected unless system dependencies are broken and require some sort of rebuilding to repair; but that has nothing to do with our kexts themselves.

I don't think it's a design flaw that caused a race condition since most of the people didn't experience it. Maybe you can try other's EFI and see if there's any difference.

**Comment by tommyvct** [comment]
You are right, I did try load these things up from /L/E. Kext caches rebuilding is required after any change is posted to kexts in /L/E, failure to do so will result in no changes at all. I still highly recommend put this note in the documentation.

**Comment by alex00x6** [comment]
For some reason my bluetooth works on Catalina without IntelBluetoothFirmware, via itlwmx only (intel ax200). However, sometimes after booting in Catalina I have issues when macOS and Windows won't see my bluetooth adapter at all, which can be resolved only via some strange shutdown-resetnvram-bootwindows sequence. Not sure how it works yet, thought it might be helpful for the discussion.

**Comment by tommyvct** [comment]
I recently updated opencore to 0.6.1.

I injected these kexts with opencore with this order:
![Screen Shot 2020-09-14 at 1 51 02 AM](https://user-images.githubusercontent.com/7903172/93052990-c0b06100-f62c-11ea-8210-6d64cd3f7854.png)
Both the bluetooth and `itlwm` worked without any problem.

**Comment by originalpaingod** [comment]
is there a way to install the itwlm.kext without reinstalling catalina? sorry for the n00b question but it's my first hackintosh (T450s)

**Comment by matheustavaresdev** [comment]
@tommyvct did you need to do any other steps or just load the kext files?
