### ISSUE TITLE
Can it remember last WIFI status(ON/OFF)?

### ISSUE THREAD

**Issue by liyafe1997** [OpenIntelWireless/itlwm#274]
If I turned off WIFI and then reboot, it automatically goes to ON after reboot.

**Comment by williambj1** [comment]
https://openintelwireless.github.io/itlwm/FAQ.html#why-does-my-adaptor-turn-back-on-after-a-sleep-wake-cycle

**Comment by zxystd** [comment]
duplicated with #193
