### ISSUE TITLE
[Question] (possible bug?) TimeOuts and high ping randomly in Network 2.4ghz and 5ghz

### ISSUE THREAD

**Issue by Microvivi** [OpenIntelWireless/itlwm#275]
**Have You Read Our Docs**
YES

**Are You Reporting A Bug**
YES

**Environment**

- Kext Version: 1.0.0
- WiFi Card Model: Intel 9260 and 8260
- Product ID: 
- macOS Version: MacOS 10.14.6

**Description**
I have itlwm 1.0 version, with open core and heliport (Mojave) My card wifi is intel 9260 (I have too 8260 and the problem is the same) I have timeouts and high ping/latency randomly in 2.4ghz and 5ghz.

**Bug Report Archive**
[itlwm log.txt](https://github.com/OpenIntelWireless/itlwm/files/5150357/itlwm.log.txt)

**Upload your Kext**
[itlwm_v1.0.0_stable.kext.zip](https://github.com/OpenIntelWireless/itlwm/files/5150469/itlwm_v1.0.0_stable.kext.zip)

<img width="1333" alt="Captura de pantalla 2020-08-31 a las 15 00 06" src="https://user-images.githubusercontent.com/70517966/91722547-b1e09d80-eb9a-11ea-9dc9-437b16d109ff.png">
<img width="566" alt="Captura de pantalla 2020-08-31 a las 13 19 29" src="https://user-images.githubusercontent.com/70517966/91714851-dcc3f500-eb8c-11ea-9fdf-5716bf536cbc.png">
<img width="566" alt="Captura de pantalla 2020-08-31 a las 13 21 08" src="https://user-images.githubusercontent.com/70517966/91714855-ddf52200-eb8c-11ea-8ad7-4ea6704d0481.png">

**Comment by williambj1** [comment]
Could you provide itlwm logs when this happens? It's not reproducible on our cards. Also please follow the issue template so we could easily identify the problem.

**Comment by Microvivi** [comment]
> Could you provide itlwm logs when this happens? It's not reproducible on our cards. Also please follow the issue template so we could easily identify the problem.

Yeah. I attach logs itlwm. Heliport is fine, I can't see errors in logs Heliport.

[itlwm log.txt](https://github.com/OpenIntelWireless/itlwm/files/5150269/itlwm.log.txt)

**Comment by shanyanhai** [comment]
heliport1.0.1,itlwmx1.0,macos10.15.6,Router:HONORx2
5Ghz
<img width="697" alt="截屏2020-09-05 下午8 42 59" src="https://user-images.githubusercontent.com/17609666/92305286-71c55480-efb8-11ea-9573-449a4dd64257.png">
2.4GHZ
<img width="697" alt="截屏2020-09-05 下午8 45 51" src="https://user-images.githubusercontent.com/17609666/92305339-d54f8200-efb8-11ea-9c9e-d80d38657eba.png">

log：
[bugreport_29816.zip](https://github.com/OpenIntelWireless/itlwm/files/5178082/bugreport_29816.zip)

**Comment by williambj1** [comment]
![image](https://user-images.githubusercontent.com/45396585/94336257-3bf21980-0014-11eb-82d7-98b429dcf649.png)

Tested 500 pings, no time outs. There are random fluctuations due to background network activity which is expected.

---

@shanyanhai There is nothing wrong in your logs, your issue is more likely related to interferene and local network quality.

---

@Microvivi You are using network extensively according to your logs, pings are expected to fluctuate when tx queues are full. You are also expriencing a ton of output errors caused by a compatibility issue with your router, try adjusting mtu values / channels etc.

**Comment by dvrkoo** [comment]
hello I'm having this issue too has anyone found a fix?
