### ISSUE TITLE
[WOW] AirPlay

### ISSUE THREAD

**Issue by longyklee** [OpenIntelWireless/itlwm#279]
### WOW
**Have You Read Our Docs**
Yes

**Are You Reporting A Bug**
Not really

**Environment**

- Kext Version: 1.0
- WiFi Card Model: Intel Wireless 8260
- macOS Version: Catalina 10.15.6

**Description**
Airplay, surprisingly, works! It works flawlessly with my school's AppleTV! I can't believe this. Because itlwm doesn't really have support for AirPlay, I categorize this as a "bug." I know it shouldn't have worked because itlwm emulates an ethernet device, but I swear it does.

### WOW

**Comment by JunkuiZhang** [comment]
interesting

**Comment by yw0822** [comment]
unbelievable

**Comment by zxystd** [comment]
hmmm, it is an expected behavior, AirPlay can work whether you use WiFi or not, Ethernet interface is OK. Thanks for your feedback.

**Comment by marras93** [comment]
Yep I can confirm, it even works on my fake cheap chromecast clone with airplay enabled.

**Comment by zxystd** [comment]
:)

**Comment by ben001109** [comment]
@aaronleetw 你是怎麼做到的
re:arronleetw How'd you make it, could you tell me how to configure it? or how can i watch my wifi adapter support or not?
