### ISSUE TITLE
出现屏幕错乱、闪屏抖动现象

### ISSUE THREAD

**Issue by lzk442195054** [OpenIntelWireless/itlwm#281]
**Have You Read Our Docs**
<YES->

**Are You Reporting A Bug**
<YES>

**Environment**

- Kext Version: itlwn_v1.0.0
- WiFi Card Model: intel wifi ac9560
- Product ID: 0xA370
- macOS Version: macOS Catalina 10.15.6

**Description**
<连接wifi成功，可以上网，但屏幕会出现抖动闪屏现象，而且流量越大闪屏速度越快>

**Bug Report Archive**

**Upload your Kext**

**Comment by williambj1** [comment]
😮

**Comment by daliansky** [comment]
卧槽，这锅不能让网卡背吧

**Comment by lzk442195054** [comment]
大佬，那可能会是啥原因导致的，因为我一旦关闭heliport屏幕就恢复正常，一旦开启并且有流量产生就会闪屏，一旦流量增大闪的就飞快都看不清屏幕了0.0

**Comment by ErrorErrorError** [comment]
您可以上传闪烁区域的视频/ gif吗？

**Comment by lzk442195054** [comment]
[a.zip](https://github.com/OpenIntelWireless/itlwm/files/5175470/a.zip)
录了一段视频

**Comment by lzk442195054** [comment]
> 您可以上传闪烁区域的视频/ gif吗？

已上传 在上面

**Comment by zxystd** [comment]
感谢你的反馈，但是我们不解决非网卡问题，请自行找原因，谢谢。
