### ISSUE TITLE
请问Info.plist中的WiFiConfig最多可以填入多少个WiFi信息

### ISSUE THREAD

**Issue by nukemiko** [OpenIntelWireless/itlwm#282]
WiFiConfig里面有4个预置的WiFi项，想知道是否可以添加更多的WiFi
<img width="800" alt="截屏2020-09-05 17 03 22" src="https://user-images.githubusercontent.com/53572814/92301893-ffde1280-ef99-11ea-9177-9146d2191f7a.png">

**Comment by williambj1** [comment]
∞
