### ISSUE TITLE
Random kernel panic triggered by itlwmx

### ISSUE THREAD

**Issue by juniorzhou** [OpenIntelWireless/itlwm#283]
**Have You Read Our Docs**
Yes

**Are You Reporting A Bug**
Yes

**Environment**

- Kext Version:  v1.0.0_stable
- WiFi Card Model: ax200
- Product ID: 
- macOS Version: 10.15.6

**Description**
From the panic log, it looks like the panic was triggered by the kext. The panic will freeze the system. Hard to tell what triggers this panic. I'm also using the Heliport. 
Here are two the panic logs.

[Panic_log1.txt](https://github.com/OpenIntelWireless/itlwm/files/5178435/Panic_log1.txt)

[Panic_log2.txt](https://github.com/OpenIntelWireless/itlwm/files/5178436/Panic_log2.txt)

**Bug Report Archive**

[bugreport_53005.zip](https://github.com/OpenIntelWireless/itlwm/files/5178429/bugreport_53005.zip)

**Upload your Kext**
It the release version of the itlwmx v1.0.0

**Comment by zxystd** [comment]
How to reproduce it?

**Comment by juniorzhou** [comment]
It's unclear to me how to reproduce. I had those two same panic in the past week. Is there anything you can tell from the panic log or bug report?  I will update this issue when I figure out what cause it.

**Comment by zxystd** [comment]
<img width="397" alt="image" src="https://user-images.githubusercontent.com/16227538/92563168-bb0fef80-f2a9-11ea-8469-0fc05c16a2bb.png">
it is a panic trigger by driver self, because STA can not be remove for twice times, but it is impossible to get here twice times because here have the flag check.
