### ISSUE TITLE
有的wiff连接成功,但是没有网

### ISSUE THREAD

**Issue by SSFsystem** [OpenIntelWireless/itlwm#284]
路由器是可以上网的,显示连接成功,但wiff是感叹号,按common 加wiff名称会显示ip地址未获取到,路由器也只显示127.不太清楚是哪里出了问题,请问可以指点我一下么.有的路由器是这样,有的路由器可以正常上网,很奇怪

**Comment by williambj1** [comment]
Invalid issue format

**Comment by SSFsystem** [comment]
无效的格式是什么问题
