### ISSUE TITLE
"Hackintool" can no longer retrieve the latest itlwm version

### ISSUE THREAD

**Issue by mackonsti** [OpenIntelWireless/itlwm#285]
**Have You Read Our Docs**
Yes

**Are You Reporting A Bug**
Possibly, I don't know if this is a bug, yet.

**Environment**
- Kext Version: 1.0.0 Stable
- WiFi Card Model: Intel Wireless-AC 9560 Controller
- Product ID: 0x9df0
- macOS Version: Mojave 10.14.6

**Description**
Hackintool by @headkaze was detecting at some point the latest available build for **itlwm** but it seems now we only get a $MARK-something instead. This could be either due to a missing tag in the **Info.plist** of **itlwm** or some change in the repository metadata or even a bug in Hackintool -- only @zxystd and @headkaze may know.

**Bug Report Archive**
N/A

**Upload your Kext**
N/A

**Screenshot**

![Hackintool Detecting itlwm](https://user-images.githubusercontent.com/1313613/92444071-aac91900-f1b2-11ea-9631-d08ca2e89e24.png)

Polling @headkaze as it could only be a Hackintool issue, I cannot know. We worked last time on Bug [142](https://github.com/OpenIntelWireless/IntelBluetoothFirmware/issues/142) for BTLE driver. Thank you all !

**Comment by mackonsti** [comment]
Hi @zxystd can I ask you, when you have some time to reply, if the version tags in GitHub metadata, may need something more to add? The middle column (if you never used Hackintool) is obtaining the latest available versions by checkin on-line each kext on its own Git repo. As I cannot expand the columns, this **$(MARK...)** text is not known to me. Perhaps @headkaze can tell the missing tag?
Thank you!

**Comment by alessiomatricardi** [comment]
Now with AirportItlwm, no information is retrieved
![Schermata 2020-09-25 alle 11 02 23](https://user-images.githubusercontent.com/26736913/94248363-a9bc1980-ff1e-11ea-9072-026a2e859830.png)

**Comment by mackonsti** [comment]
Hi @alessiomatricardi that is because Hackintool was not updated to look for "AirportItlwm" kext, you need to report this and request to be added in https://www.insanelymac.com/forum/topic/335018-hackintool-v3xx/ instead ;-)
I had requested the same for "itlwm" too.
