### ISSUE TITLE
[Bug] Wi-Fi Status unavailable, but kext is loaded

### ISSUE THREAD

**Issue by StoneyMalone** [OpenIntelWireless/itlwm#287]
**Describe the bug**
Using heliport v1.0.0 does not let wifi be turned on and says wifi status unavailable

**To Reproduce**
1. Install itlwm.kext into efi and added to config.plist with opencore v6.0.0
2. rebooted the computer
3. disabled sip
4. Rebooted
5. Tried to load heliport and connect

**Expected behavior**
Open heliport and connect to wifi

**Screenshots**

**Environment (please complete the following information):**
 - OS Version: 10.15.6
 - Software Version:V1.0.0

**Additional context**
Lenovo C930
With intel 9260
[Log_2020-08-15.log](https://github.com/OpenIntelWireless/HeliPort/files/5080111/Log_2020-08-15.log)

**Comment by zxystd** [comment]
Network device didn't match the driver, it should be a EFI issue, will not help to fix here, thanks.
