### ISSUE TITLE
买了只DWA-192，发现也是模拟Ethernet

### ISSUE THREAD

**Issue by dan444** [OpenIntelWireless/itlwm#293]
**Have You Read Our Docs**
Yes

**Are You Reporting A Bug**
No

**Environment**

- Kext Version: 1.0.0
- WiFi Card Model: AX200
- Product ID: 
- macOS Version: 10.15.6

**Description**
用驱动速度还是太慢，我这里用AX200+K2P日常使用只有10-20mb/s左右。
DWA-192真的很厉害，不知道大神可否作为参考。AC1900，在MacOS上也是满速，算是普通WIFI5的极致了。。

**Bug Report Archive**

**Upload your Kext**

**Comment by zxystd** [comment]
怎么参考。。你有源代码？

**Comment by M69W** [comment]
我们不如直接参考官方的吧
