### ISSUE TITLE
Airportltlwm doesn't load with the latest Opencore release 0.6.1

### ISSUE THREAD

**Issue by enPause96** [OpenIntelWireless/itlwm#295]
Airportlwm doesn't load with opencore 0.6.1 i tried it many times still same issue. with my previous version it worked without problem. i'm on Catalina 10.15.4

**Comment by s0ullight** [comment]
What value do you have for SecureBootModel in OpenCore?

**Comment by enPause96** [comment]
> What value do you have for SecureBootModel in OpenCore?

Disabled. with Default set my system didn't boot i got OCBS error. i follow the Dortania doc but still secureboot didn't load

**Comment by williambj1** [comment]
IO80211 will not load if SecureBootModel is disabled since immutablekernel is not used. I’m closing this issue because it’s not an issue with our kext.
