### ISSUE TITLE
Handoff and Shared Clipboards dont work

### ISSUE THREAD

**Issue by enPause96** [OpenIntelWireless/itlwm#296]
**Have You Read Our Docs**

yes
**Are You Reporting A Bug**

yes
**Environment**
macOS Catalina
- Kext Version: AirportItlwm 1.1.0
- WiFi Card Model: Intel wireless N 7260
- Product ID: 0x08B1
- macOS Version: 10.15.4

**Description**

Since the kext didn't load for me with the latest release of OpenCore i extract the IO80211Family kext and put my airport into the plugins then inject it through opencore. It works, Locations, Native WiFi, connect Bluetooth to iPhone and Airdrop item on Finder work. but i cannot get Handoff, Airdrop or Shared clipboard to work. i have an Intel Wireless N 7260 card
**Bug Report Archive**

as i dont use Heliport i dont know how to generate a log
**Upload your Kext**

[AirportItlwm.kext.zip](https://github.com/OpenIntelWireless/itlwm/files/5242423/AirportItlwm.kext.zip)
![Capture d’écran 2020-09-17 à 23 39 19](https://user-images.githubusercontent.com/65020150/93537945-c5368b80-f944-11ea-8a52-eb43eb42ef1d.png)
![photo_2020-09-17 23 54 01](https://user-images.githubusercontent.com/65020150/93537953-c8ca1280-f944-11ea-83cf-23243e6c02b3.jpeg)
![Capture d’écran 2020-09-17 à 23 44 00](https://user-images.githubusercontent.com/65020150/93537956-c962a900-f944-11ea-8ddb-45927929178b.png)
![Capture d’écran 2020-09-17 à 23 37 51](https://user-images.githubusercontent.com/65020150/93537958-c9fb3f80-f944-11ea-8e3b-7920b11eb121.png)

**Comment by williambj1** [comment]
#292
