### ISSUE TITLE
Install AirPortItlwm into OpenCore Kext and get kernel

### ISSUE THREAD

**Issue by ducltv** [OpenIntelWireless/itlwm#299]
**Have You Read Our Docs**

**Environment**

- Kext Version: 1.1.0
- WiFi Card Model: Intel AC7265
- Product ID: 
- macOS Version: 10.15.6

**Description**

After i add kext into OC kext and reboot so i get a Panic with the circle of error ;-; Can someone help me pls ?

[itlwm.kext.zip](https://github.com/OpenIntelWireless/itlwm/files/5245789/itlwm.kext.zip)

**Upload your Kext**

**Comment by williambj1** [comment]
Panic log please

**Comment by ManuGithubSteam** [comment]
> > Panic log please
> 
> i not see any log panic in my mac

you have to set -v in bootargs to see it
