### ISSUE TITLE
Intel AC 7265 - kext doesn't load after itlwm 1.0.0

### ISSUE THREAD

**Issue by maxhartung** [OpenIntelWireless/itlwm#301]
**Have You Read Our Docs**
YES

**Are You Reporting A Bug**
YES

**Environment**

- Kext Version: 1.1.0
- WiFi Card Model: Intel AC 7265 (0x095A)
- Product ID: 0x095A
- macOS Version: 10.15.6

**Description**

I tried using itlwm 1.1.0 both stable and beta but the kext doesn't load at all on my wi-fi card. OpenCore is setup properly. The only kext loading is the first release of itlwm 1.0.0

**Upload your Kext**

[itlwm.kext.zip](https://github.com/OpenIntelWireless/itlwm/files/5249349/itlwm.kext.zip) - 1.1.0

**Comment by williambj1** [comment]
Logs please

**Comment by alessiomatricardi** [comment]
I've the same card (same Device id 0x095A) and everything work properly with AirportItlwm.
- Check your EFI (from this version you must change name and path of the kext in config.plist -> Kernel -> Add -> Item X
- Check that AirportItlwm is loaded before Bluetooth and Injector
- Check that you haven't other Wifi kexts

Hope you will solve!! 💪🏼

**Comment by maxhartung** [comment]
> Logs please

What kind of logs you need ? OpenCore debug build logs are okay or you need anything else ?

Thanks,
Max

**Comment by maxhartung** [comment]
> I've the same card (same Device id 0x095A) and everything work properly with AirportItlwm.
> 
> * Check your EFI (from this version you must change name and path of the kext in config.plist -> Kernel -> Add -> Item X
> * Check that AirportItlwm is loaded before Bluetooth and Injector
> * Check that you haven't other Wifi kexts
> 
> Hope you will solve!! 💪🏼

I checked and everything looks fine to me

**Comment by zxystd** [comment]
i don't think it is a driver issue, personal hackintosh related help would not be supportef here. you should fix it by yourself.

**Comment by maxhartung** [comment]
> i don't think it is a driver issue, personal hackintosh related help would not be supported here. you should fix it by yourself.

85:166 00:013 OCAK: Dependency com.apple.iokit.IO80211Family was not found for kext com.zxystd.AirportItlwm
85:214 00:048 OCAK: Vtable patching failed for kext com.zxystd.AirportItlwm
85:219 00:005 OC: Prelinked injection AirportItlwm.kext () - Invalid Parameter

I think it's something

**Comment by williambj1** [comment]
Enable Apple Secure Boot
