### ISSUE TITLE
希望能支持连接企业级并需要账号和密码登录的WIFI

### ISSUE THREAD

**Issue by YGQ8988** [OpenIntelWireless/itlwm#307]
非常感谢楼主的驱动，让我们intel网卡在mac下重生。

现在我有一个诉求，因为我在公司笔记本上安装了黑苹果，本来想在10.14.6上养老，日常逛论坛发现了这个月楼主又重大更新了，第一次时间很激动，终于看到希望了，然后也第一时间升级了10.15.6，还因升级导致无法引导，然后调了半天的EFI，最终还是成功的进入了系统，最后使用套娃的方式成功的驱动了intel3165WIFI，但是到公司连接WIFI时，发现无法正常连接公司的企业级并需要账号密码登录的WIFI。

最终的问题就是希望后续能够支持连接企业级并需要账号密码的WIFI。

网卡型号：intel 3165
Mac版本：10.15.6

**Comment by williambj1** [comment]
Duplicate of #101
