### ISSUE TITLE
[Airportitwlm] Scanning shows only my connected network on Big Sur

### ISSUE THREAD

**Issue by tikscr** [OpenIntelWireless/itlwm#308]
**Have You Read Our Docs**
Yes

**Are You Reporting A Bug**
Yes

**Environment**

- Kext Version: Airportitwlm beta
- WiFi Card Model: Intel AC-9560
- Product ID: 0x8086, 0x4030
- macOS Version: 11.0 beta 7

**Description**
After installation of Airportitwlm i see wi-fi working, but in list of networks there's only one network
![Screenshot 2020-09-21 at 10 13 16](https://user-images.githubusercontent.com/60230344/93740434-21bed280-fbf3-11ea-88be-fb6c2fe2df90.png)

**Bug Report Archive**
[Log_2020-09-21_11-38-38.log](https://github.com/OpenIntelWireless/itlwm/files/5254338/Log_2020-09-21_11-38-38.log)

**Kext Download Source**
Airportitwlm downloaded from 1.1.0 Release page

**Comment by zxystd** [comment]
attach is not a full log, can you wait some minutes for the network list display again?

**Comment by tikscr** [comment]
> attach is not a full log, can you wait some minutes for the network list display again?

I've waited for a 10 minutes

**Comment by unhoo28** [comment]
My card is BCM943602CD, it also shows only connected network on Big Sur, so it looks like normal

**Comment by williambj1** [comment]
@tikscr Is this still reproducible with the kext built from master https://github.com/OpenIntelWireless/itlwm/commit/9b60103c3369e950027286b2a0639a067ac93de0?

**Comment by tikscr** [comment]
> @tikscr Is this still reproducible with the kext built from master https://github.com/OpenIntelWireless/itlwm/commit/9b60103c3369e950027286b2a0639a067ac93de0?

How can i build airportitwlm from master? I see no manual for it.

**Comment by williambj1** [comment]
> > @tikscr Is this still reproducible with the kext built from master [9b60103](https://github.com/OpenIntelWireless/itlwm/commit/9b60103c3369e950027286b2a0639a067ac93de0)?
> 
> How can i build airportitwlm from master? I see no manual for it. Or xcodebuild would produce both itwlm and airportitwlm?

I haven't updated the docs, you can use our Ci config as a reference.

https://github.com/OpenIntelWireless/itlwm/blob/0120e171f6424a461d3c5973c3e55b5af8cd8603/.github/workflows/main.yml#L46

**Comment by Jh0817** [comment]
My notebook's WI-FI and bluetooth is working!
Thank you!
But AirDrop and Handoff is not working.

**Comment by Jh0817** [comment]
Airdrop and Handoff not working!

My device info :Samsung notebook 9 lite M58S,macOS 10.15.7, OpenCore 0.6.1

**Comment by Jh0817** [comment]
Unlock Mac with Apple Watch is not working too

**Comment by williambj1** [comment]
Feel free to request a reopen if this issue is still present using the latest alpha.
