### ISSUE TITLE
AX200  经常随机断线再重连

### ISSUE THREAD

**Issue by andy13106** [OpenIntelWireless/itlwm#309]
有时非常频繁，有时又工作很稳定，完全没有规律。断线时有时HeliPort的图标变成灰色，然后马上恢复，有时显示正常但点开连接列表就会发现连接的WIFI的SSID不见了，马上又会出现，确认不是路由器的问题，9月16号的合并版itlwm有很大改进，但仍然会出现，之前的版本严重时一整天几乎都无法使用，联上两三秒就断开，然后再联上再断开。16号的版本大部分时间都能正常工作了。大概有五分之一的时间会出问题吧，是随机出现的，有时两三次就恢复正常，有时持续半小时到一小时才能恢复正常。

电脑配置  技喜Z170HD3   6700K   核显     AX200无线网卡+蓝牙   MacOS Catalina 10.15.6

**Comment by williambj1** [comment]
Please use the issue format
