### ISSUE TITLE
曲线救国连接iPhone热点

### ISSUE THREAD

**Issue by Annie3310** [OpenIntelWireless/itlwm#310]
用线连接iPhone--开热点--拔掉iPhone

或者先点iPhone的热点,等提示类似“连接失败不在范围内”之后再线连手机就会连上.

![1600787662935.jpg](https://i.loli.net/2020/09/22/3by9FxvWp1O4mrJ.jpg)

**Comment by nn-666** [comment]
网卡慢慢有解，完美hackintosh指日可待

**Comment by M69W** [comment]
> 用线连接iPhone--开热点--拔掉iPhone
> 
> 或者先点iPhone的热点,等提示类似“连接失败不在范围内”之后再线连手机就会连上.
> 
> ![1600787662935.jpg](https://camo.githubusercontent.com/2bc8974c70e5c5ee085119b1788b9511d276540c/68747470733a2f2f692e6c6f6c692e6e65742f323032302f30392f32322f336279394678765770314f346d724a2e6a7067)

另外，
使用 `AirportItlwm.kext` ，先通过蓝牙连接，再连接iPhone 热点(`智能热点`)；
这种情况不稳定，可能十次只有一两次成功。
<img width="1007" alt="QQ20201008-105445@2x" src="https://user-images.githubusercontent.com/15809201/95409702-ca3f9700-0954-11eb-81f9-9b0ada72d5a4.png">

**Comment by win1010525** [comment]
对，是这样。。。问题出在不能p2p上，不能直连iPhone，手机先开电脑再联可以

**Comment by asd45183** [comment]
请教下，加载驱动的时候有提示签名无效么？ 还是说高版本系统才会出现

**Comment by win1010525** [comment]
不会的，你通过OC加载就好了

**Comment by asd45183** [comment]
好的，我通过OC 开机加载试试。需要先更改无线密码么？

**Comment by atomxing** [comment]
关掉电脑的蓝牙，再链接热点，成功率高
