### ISSUE TITLE
AirportItlwm does not report RSSI correctly

### ISSUE THREAD

**Issue by moutorde** [OpenIntelWireless/itlwm#314]
**Have You Read Our Docs**
Yes

**Are You Reporting A Bug**
Yes

**Environment**

- Kext Version: AirportItlwm 1.1.0
- WiFi Card Model: AC8265
- Product ID: 0x24FD
- macOS Version: 10.15.6

**Description**
Every network show as "perfectly received" / "very near", including networks that are far and show properly under Windows.
Under About this Mac->System Report->Wi-Fi, I can see all the networks around me and their Signal/Noise are all different.
-15 to -40 dBm / all 0 dBm except the connected network with -95dBm
![Screenshot 2020-09-23 at 18 05 50](https://user-images.githubusercontent.com/64887792/94039137-9b0f1e80-fdc7-11ea-8c85-60847bd368fd.png)

RSSI is reported correctly when using itlwm 1.1.0 + Heliport 1.0.1, or itlwm 1.2.0 + Heliport 1.0.1.

**Bug Report Archive**
[AirportItlwm.log](https://github.com/OpenIntelWireless/itlwm/files/5269342/AirportItlwm.log)

**Kext Download Source**
Github 1.1.0 stable release

**Comment by juniorzhou** [comment]
I also had this bug once. Does not know what trigger it.

**Comment by hybrid72** [comment]
Same issue here.

Kext Version: AirportItlwm 1.1.0
WiFi Card Model: AC7260
macOS Version: 10.15.7

Wifi Explorer Lite is showing all weak (neighbour) networks as 100%. Best Networks are below. My connected network is 64% (Should be about 80%).

**Comment by williambj1** [comment]
Fixed in b919444
