### ISSUE TITLE
Slow speeds on both 2.4 and 5 GHz networks - AirportItlwm

### ISSUE THREAD

**Issue by FaneCH** [OpenIntelWireless/itlwm#315]
**Have You Read Our Docs**
Yes

**Are You Reporting A Bug**
Yes

**Environment**

- Kext Version: AirportItlwm_v1.0_Beta
- WiFi Card Model: Intel AC-3165
- Product ID: 0x8086
- macOS Version: 10.15.6

**Description**
Slow speeds on 2.4/5 GHz networks.
Happens on both AirportItlwm and itlwm (latest versions).

![Screenshot 2020-09-23 at 19 01 10](https://user-images.githubusercontent.com/33597024/94039309-399f7d80-fdd0-11ea-9bd8-a132bd3e3d99.png)

**Bug Report Archive**

[AirportItlwm.log](https://github.com/OpenIntelWireless/itlwm/files/5269468/AirportItlwm.log)

**Kext Download Source**
https://github.com/OpenIntelWireless/itlwm/releases

**Comment by moutorde** [comment]
https://openintelwireless.github.io/itlwm/FAQ.html#performance-sucks

**Comment by FaneCH** [comment]
If i'll have the speeds from the website you gave me, i'll be more then pleased. But 35 mb/s it's not ideal.

**Comment by moutorde** [comment]
Probably due to your wifi card having 1x1 antenna compatibility.
The card used for the example is an AC9560 which is, at first, better on all points, and it also has 2x2 antennas compatibility.

**Comment by FaneCH** [comment]
It is what it is then. Thanks man for the answers. It is really stable on the other hand, works like a charm! :)
