### ISSUE TITLE
  Command ExternalBuildToolExecution failed with a nonzero exit code

### ISSUE THREAD

**Issue by wwwsky999** [OpenIntelWireless/itlwm#321]
xcode11

Uncategorized Group     :::::Command ExternalBuildToolExecution failed with a nonzero exit code

**Environment**

- Kext Version: 
- WiFi Card Model: 
- Product ID: 
- macOS Version: 10.15.7

**Description**

**Bug Report Archive**

**Kext Download Source**

**Comment by williambj1** [comment]
Please check your local environment, python, etc. Compilation works fine on both our machines and CI. Can't tell what's wrong based on your given information.
