### ISSUE TITLE
[AirPort] Can't connect to hotspots

### ISSUE THREAD

**Issue by GGorAA** [OpenIntelWireless/itlwm#326]
**Have You Read Our Docs**
Yes

**Are You Reporting A Bug**
Yes
**Environment**

- Kext Version: 1.1.0
- WiFi Card Model: Intel Wireless 8260
- Product ID: idk where it is, but here is Hackintool screenshots
![image](https://user-images.githubusercontent.com/61655029/94464447-2a04a800-01c7-11eb-8023-a8be950e3479.png)
![image](https://user-images.githubusercontent.com/61655029/94464501-37219700-01c7-11eb-9b06-4c66d5fd9310.png)
- macOS Version: Big Sur 11.0 20A5364e

**Description**
I can't connect to networks. Well, WiFi entry is created, I can see the hotspots, but I can't connect to them. When I was on `itlwm.kext` everything worked flawlessly. But when I switched to AirPort release, I lost my ability to connect to hotspots.
**Bug Report Archive**
Well, they are blank

**Kext Download Source**
This repo

**Comment by GGorAA** [comment]
found out Product ID. it was 0x24f3

**Comment by ErrorErrorError** [comment]
From @zxystd release notes for AiportIltmw.

`` Instant HotSpot from iPhone can be recognized but may likely fail to connect. Workaround: use itlwm.kext with HeliPort.``

**Comment by GGorAA** [comment]
Nope, my network is my normal home WiFi

**Comment by williambj1** [comment]
Will reopen once logs are provided. Read our docs for more info.

**Comment by GGorAA** [comment]
There are no logs, when I pasted the commands nothing was in output. That's why I said that this is blank

**Comment by GGorAA** [comment]
Nope, found logs. here they are
[AirportItlwm.log](https://github.com/OpenIntelWireless/itlwm/files/5297339/AirportItlwm.log)

**Comment by williambj1** [comment]
> Kext Download Source
> This repo

Sorry that I did not mention this earlier, could you please be specific about where did you get this kext? There are multiple versions of "Airport" in this repo. Please provide the URL.

The logs you provided are incomplete and not useful to identify your issue. Please follow our docs *strictly*.
