### ISSUE TITLE
Itlwm is not running after bios update

### ISSUE THREAD

**Issue by noxxex** [OpenIntelWireless/itlwm#327]
**Have You Read Our Docs**
Yes
**Are You Reporting A Bug**
Yes

**Environment**

- Kext Version: V.1.1.0 
- WiFi Card Model: AC7265
- Product ID: 8086
- macOS Version: 10.15.7

**Description**
I've just recently updated my bios version and somehow when im trying to boot the itlwm shows that it is not running. i've already tried several version but still has no idea what happened.

**Bug Report Archive**
[bugreport_34863.zip](https://github.com/OpenIntelWireless/itlwm/files/5302179/bugreport_34863.zip)

**Kext Download Source**

https://github.com/OpenIntelWireless/itlwm/releases/tag/v1.1.0

**Comment by williambj1** [comment]
Unrelated user mistake.
