### ISSUE TITLE
[Bug Report]Stability issue

### ISSUE THREAD

**Issue by lookingforsomefun** [OpenIntelWireless/itlwm#328]
**Have You Read Our Docs**

Yes
**Are You Reporting A Bug**

Yes
**Environment**

- Kext Version:         v1.1.0
- WiFi Card Model:  intel 7260-N
- Product ID:            0x808608B2
- macOS Version:    11.0beta4

**Description**

When I boot with OC, it does not always run, in fact, in about 80% cases, I log in with the waring "itlwm not running" from heliport, however, with a few reboots and a few "sudo kextcache -u /"(this may or may not help) it get to work again.
**Bug Report Archive**

[bugreport_17271.zip](https://github.com/OpenIntelWireless/itlwm/files/5303876/bugreport_17271.zip)

**Kext Download Source**

github

**Comment by williambj1** [comment]
Noting wrong according to the logs, try the latest version.
