### ISSUE TITLE
[喜讯]更新OC0.6.2后wifi开机秒连

### ISSUE THREAD

**Issue by lty2008one** [OpenIntelWireless/itlwm#334]
使用电脑:小新Pro13 2020 i5
使用网卡:AX201
使用系统:MacOS 10.15.7
使用驱动:AirportItlwm for Catalina

本来只是日常更新一下OC，结果发现了惊喜
给大伙分享一下
wifi群里也有人反馈不能开机秒连，可能和网卡或者路由器有关？

不过还是会出现随机性的断连情况，而且在连接我手机上的2.4G热点时疯狂断连（换成5G就没事）

**Comment by williambj1** [comment]
恭喜，但实际原理与上文描述、本驱动均无关。
