### ISSUE TITLE
[Bug] Wifi doesn't work anymore after wake from sleep

### ISSUE THREAD

**Issue by lucasrequile** [OpenIntelWireless/itlwm#336]
**Describe the bug**
WiFi can't connect after sleep, like when the lid was closed and opened again.

**To Reproduce**
Let the computer sleep, and wake it up again.

**Expected behavior**
Wifi will stay active, or will reload after sleep.

**Environment (please complete the following information):**

OS Version: macOS 11.0 beta 8
Software Version: latest git revision

**Comment by williambj1** [comment]
Will reopen once logs are provided.
