### ISSUE TITLE
itlwm disconnected every a few minutes

### ISSUE THREAD

**Issue by dengdaibian** [OpenIntelWireless/itlwm#345]
**Have You Read Our Docs**
yes

**Are You Reporting A Bug**
Yes 

**Environment**

- Kext Version: Itlwm 1.2.0
- WiFi Card Model: ax200
- Product ID: 0x2723
- macOS Version: 10.15.6

**Description**

wifi always disconnectd every a few minutes
i have to off and on it manually to connect to the wifi again.

**Bug Report Archive**

[bugreport_6147.zip](https://github.com/OpenIntelWireless/itlwm/files/5365579/bugreport_6147.zip)

**Kext Download Source**

from official OpenIntelWireless github

**Comment by williambj1** [comment]
The logs provided can't describe your issue. Try to capture the logs after it disconnects.

**Comment by dengdaibian** [comment]
but the logs are captured after it disconnectd and reconnected

**Comment by dengdaibian** [comment]
I'll try again tonight,thank you

**Comment by dengdaibian** [comment]
> The logs provided can't describe your issue. Try to capture the logs after it disconnects.

But the logs were captured after wifi disconnected and reconnected,i will try again tonight
thank you

**Comment by zxystd** [comment]
According to the log, the wifi disconnect by you manually click "close", the driver seems works fine, maybe is your wifi network environment related issue? thanks.
