### ISSUE TITLE
Slow boot caused by the Kext (a lot of Verbose releated)

### ISSUE THREAD

**Issue by EndLineTech03** [OpenIntelWireless/itlwm#353]
I'm testing Airportltlwm_v1.0_Beta_Catalina on my desktop Hackintosh running macOS Catalina 10.15.7. My wifi card is Intel Wireless AC 9260. I don't know if it's normal or if it's possible to improve something, but I realized that this Build increases a lot the boot time (60/70 %). Can you work on this problem? Or, am I using the Kext incorrectly?

This is a question post.

I have read the FAQ.

**Comment by seungjunProgramming** [comment]
Me too...
It takes about 20~30secs to include itlwmAirport + intelBluetooth Firmware
(Both downloaded at your GitHub)

**Comment by igorkulman** [comment]
I solved this by building both Airportitlwm and IntelBluetoothFirmware myself, removing firmware for all the cards except mine first. This results in much smaller kexts that load faster.

**Comment by williambj1** [comment]
Boot time increase should be expected but I really doubt your speculation. Because you opened this issue in Itlwm's repo, I assume you are talking about itlwm instead of IntelBluetoothFirmware.

In fact, the increase of boot time is more likely related to IO80211 wanting the system to be already connected to the Internet before the system enters userspace, based on my observation. You could try itlwm without Wi-Fi config in its plist and see if there's any difference.

Booting macOS requires reading quite a lot of data on the hard drive, injecting a 10MB Kext into the system is really not a big deal. What's more, using PCI DMA, uploading Wi-Fi firmware into the card is almost instantaneous. I've tried simplifying the kext before and it really made no difference.

Bluetooth is another story, sometimes it takes a significant amount of time to wait for the card's USB part to respond. Transfering firmware through USB is not as fast as through PCI as well.

**Comment by EndLineTech03** [comment]
Thanks for the responses. I will try also to debug the Kext, build it manually and I will try the other Kext.

**Comment by EndLineTech03** [comment]
> Boot time increase should be expected but I really doubt your speculation. Because you opened this issue in Itlwm's repo, I assume you are talking about itlwm instead of IntelBluetoothFirmware.
> 
> 
> 
> In fact, the increase of boot time is more likely related to IO80211 wanting the system to be already connected to the Internet before the system enters userspace, based on my observation. You could try itlwm without Wi-Fi config in its plist and see if there's any difference.
> 
> 
> 
> Verbose logs are essential ATM since itlwm is a kext that runs all the time. If people experienced a random runtime issue, they can quickly pull out the logs and submit them to us. However, it would be a nightmare to capture those random bugs not to mention wasting a lot of our time dealing with newbies if logs are removed.
> 
> 
> 
> Booting macOS requires reading quite a lot of data on the hard drive, injecting a 10MB Kext into the system is really not a big deal. What's more, using PCI DMA, uploading Wi-Fi firmware into the card is almost instantaneous. I've tried simplifying the kext before and it really made no difference.
> 
> 
> 
> Bluetooth is another story, sometimes it takes a significant amount of time to wait for the card's USB part to respond. Uploading firmware through USB is not as fast as through PCI as well.

What changes between Airportltlwm and itlwm?

**Comment by seungjunProgramming** [comment]
@williambj1 

> Boot time increase should be expected but I really doubt your speculation. Because you opened this issue in Itlwm's repo, I assume you are talking about itlwm instead of IntelBluetoothFirmware.
> 
> In fact, the increase of boot time is more likely related to IO80211 wanting the system to be already connected to the Internet before the system enters userspace, based on my observation. You could try itlwm without Wi-Fi config in its plist and see if there's any difference.
> 
> Verbose logs are essential ATM since itlwm is a kext that runs all the time. If people experienced a random runtime issue, they can quickly pull out the logs and submit them to us. However, it would be a nightmare to capture those random bugs not to mention wasting a lot of our time dealing with newbies if logs are removed.
> 
> Booting macOS requires reading quite a lot of data on the hard drive, injecting a 10MB Kext into the system is really not a big deal. What's more, using PCI DMA, uploading Wi-Fi firmware into the card is almost instantaneous. I've tried simplifying the kext before and it really made no difference.
> 
> Bluetooth is another story, sometimes it takes a significant amount of time to wait for the card's USB part to respond. Uploading firmware through USB is not as fast as through PCI as well.

Then can you please make the kext without verbose logs please?
You can publish it together with the original version(with the verbose log) for newbies or etc to use.
Some users like me need those options...
(Or maybe a boot flag (ex: itlwmnoverbose=1) option)

**Comment by EndLineTech03** [comment]
> @williambj1 
> 
> 
> 
> > Boot time increase should be expected but I really doubt your speculation. Because you opened this issue in Itlwm's repo, I assume you are talking about itlwm instead of IntelBluetoothFirmware.
> 
> > 
> 
> > In fact, the increase of boot time is more likely related to IO80211 wanting the system to be already connected to the Internet before the system enters userspace, based on my observation. You could try itlwm without Wi-Fi config in its plist and see if there's any difference.
> 
> > 
> 
> > Verbose logs are essential ATM since itlwm is a kext that runs all the time. If people experienced a random runtime issue, they can quickly pull out the logs and submit them to us. However, it would be a nightmare to capture those random bugs not to mention wasting a lot of our time dealing with newbies if logs are removed.
> 
> > 
> 
> > Booting macOS requires reading quite a lot of data on the hard drive, injecting a 10MB Kext into the system is really not a big deal. What's more, using PCI DMA, uploading Wi-Fi firmware into the card is almost instantaneous. I've tried simplifying the kext before and it really made no difference.
> 
> > 
> 
> > Bluetooth is another story, sometimes it takes a significant amount of time to wait for the card's USB part to respond. Uploading firmware through USB is not as fast as through PCI as well.
> 
> 
> 
> Then can you please make the kext without verbose logs please?
> 
> You can publish it together with the original version(with the verbose log) for newbies or etc to use.
> 
> Some users like me need those options...
> 
> (Or maybe a boot flag (ex: itlwmnoverbose=1) option) 

I hope they will do this. Because it's horrible to see all the logs when I boot in verbose mode. A non-debug version would be better.

**Comment by williambj1** [comment]
@seungjunProgramming @EndLineTech03 No we won’t, and I’ve already explained why. If you really hate those logs, you can delete them and build a custom version.

**Comment by seungjunProgramming** [comment]
@williambj1 How can I delete the verbose log??? Can you tell me the command which prints the verbose???
(Ex: in C printing in kernel is printf)

**Comment by EndLineTech03** [comment]
> @seungjunProgramming @EndLineTech03 No we won’t, and I’ve already explained why. If you really hate those logs, you can delete them and build a custom version.

Ok thanks. But I can't find the command related to the logs in the source code. And I can find only the source code of itlwm and not of AirportItlwm.

**Comment by LongCX** [comment]
> I solved this by building both Airportitlwm and IntelBluetoothFirmware myself, removing firmware for all the cards except mine first. This results in much smaller kexts that load faster.

Please share me kext affter build

**Comment by EndLineTech03** [comment]
Where is AirportItlwm source code???

**Comment by phu54321** [comment]
Verbose log doesnt really affect boot time. This is a hidden bootarg of macOS Darwin Kernel (not related to itlwn), but try adding `pci=1` to boot-args. A lot of new texts will appear, but it wont affect the boot time too much.

**Comment by racka98** [comment]
> I solved this by building both Airportitlwm and IntelBluetoothFirmware myself, removing firmware for all the cards except mine first. This results in much smaller kexts that load faster.

How did you go about this?? I tried removing the firmware and build failed showing a bunch of errors and missing files

**Comment by johnwtt** [comment]
> I solved this by building both Airportitlwm and IntelBluetoothFirmware myself, removing firmware for all the cards except mine first. This results in much smaller kexts that load faster.

Can you teach me how to do that ?

**Comment by racka98** [comment]
> > I solved this by building both Airportitlwm and IntelBluetoothFirmware myself, removing firmware for all the cards except mine first. This results in much smaller kexts that load faster.
> 
> Can you teach me how to do that ?

I finally got it to work. 
1. Clone the repo: `git clone https://github.com/OpenIntelWireless/itlwm.git`

2. Open the folder where it's cloned to

3. Open Xcode, press File -> New -> File.. on the Search bar/Filter type `shell` and choose to create a new shell script file

4. Copy this code below into it;

```shell
#!/bin/bash

# remove all local changes
git reset --hard HEAD
rm -rf build

# pull latest code
git pull

# remove generated firmware
rm include/FwBinary.cpp

# remove firmware for other wifi cards - DELETE OR CHANGE TO YOUR CARD
find itlwm/firmware/ -type f ! -name 'iwm-7265-*' -delete


# generate firmware
xcodebuild -project itlwm.xcodeproj -target fw_gen -configuration Release -sdk macosx

# build the kexts
## 1. itlwm.kext
xcodebuild -project itlwm.xcodeproj -target itlwm -configuration Release -sdk macosx

## 2. AirportItlwm Catalina
xcodebuild -project itlwm.xcodeproj -target AirportItlwm-Mojave -configuration Release -sdk macosx

## 3. AirportItlwm Catalina
xcodebuild -project itlwm.xcodeproj -target AirportItlwm-Catalina -configuration Release -sdk macosx

## 4. AirportItlwm Big Sur
xcodebuild -project itlwm.xcodeproj -target AirportItlwm-Big\ Sur -configuration Release -sdk macosx

# Location of Kexts
echo "You kexts are in build/Release!!"
echo " "
```

5. Change line 14: `find itlwm/firmware/ -type f ! -name 'iwm-7265-*' -delete` change `iwm-7265` to your firmware name and save the file.

6. Place the file in the root directory of the cloned itlwm folder.

7. Clone MacKernelSDK `git clone https://github.com/acidanthera/MacKernelSDK.git` and place it's folder inside itlwm folder

8. Run the script with sh command.
Ex: `sh script-name.sh` where 'script-name' is the name of the shell script you made.

Done, you'll find your kexts under build/Release

**Comment by EndLineTech03** [comment]
> > > I solved this by building both Airportitlwm and IntelBluetoothFirmware myself, removing firmware for all the cards except mine first. This results in much smaller kexts that load faster.
> 
> > 
> 
> > Can you teach me how to do that ?
> 
> 
> 
> I finally got it to work. 
> 
> 1. Clone the repo: `git clone https://github.com/OpenIntelWireless/itlwm.git`
> 
> 
> 
> 2. Open the folder where it's cloned to
> 
> 
> 
> 3. Open Xcode, press File -> New -> File.. on the Search bar/Filter type `shell` and choose to create a new shell script file
> 
> 
> 
> 4. Copy this code below into it;
> 
> 
> 
> ```shell
> 
> #!/bin/bash
> 
> 
> 
> # remove all local changes
> 
> git reset --hard HEAD
> 
> rm -rf build
> 
> 
> 
> # pull latest code
> 
> git pull
> 
> 
> 
> # remove generated firmware
> 
> rm include/FwBinary.cpp
> 
> 
> 
> # remove firmware for other wifi cards - DELETE OR CHANGE TO YOUR CARD
> 
> find itlwm/firmware/ -type f ! -name 'iwm-7265-*' -delete
> 
> 
> 
> 
> 
> # generate firmware
> 
> xcodebuild -project itlwm.xcodeproj -target fw_gen -configuration Release -sdk macosx
> 
> 
> 
> # build the kexts
> 
> ## 1. itlwm.kext
> 
> xcodebuild -project itlwm.xcodeproj -target itlwm -configuration Release -sdk macosx
> 
> 
> 
> ## 2. AirportItlwm Catalina
> 
> xcodebuild -project itlwm.xcodeproj -target AirportItlwm-Mojave -configuration Release -sdk macosx
> 
> 
> 
> ## 3. AirportItlwm Catalina
> 
> xcodebuild -project itlwm.xcodeproj -target AirportItlwm-Catalina -configuration Release -sdk macosx
> 
> 
> 
> ## 4. AirportItlwm Big Sur
> 
> xcodebuild -project itlwm.xcodeproj -target AirportItlwm-Big\ Sur -configuration Release -sdk macosx
> 
> 
> 
> # Location of Kexts
> 
> echo "You kexts are in build/Release!!"
> 
> echo " "
> 
> ```
> 
> 
> 
> 5. Change line 14: `find itlwm/firmware/ -type f ! -name 'iwm-7265-*' -delete` change `iwm-7265` to your firmware name and save the file.
> 
> 
> 
> 6. Place the file in the root directory of the cloned itlwm folder.
> 
> 
> 
> 7. Clone MacKernelSDK `git clone https://github.com/acidanthera/MacKernelSDK.git` and place it's folder inside itlwm folder
> 
> 
> 
> 8. Run the script with sh command.
> 
> Ex: `sh script-name.sh` where 'script-name' is the name of the shell script you made.
> 
> 
> 
> Done, you'll find your kexts under build/Release

Thanks a lot!! Is it possible also to remove boot logs?

**Comment by racka98** [comment]
> > > > I solved this by building both Airportitlwm and IntelBluetoothFirmware myself, removing firmware for all the cards except mine first. This results in much smaller kexts that load faster.
> > 
> > > 
> > 
> > > Can you teach me how to do that ?
> > 
> > 
> > 
> > I finally got it to work. 
> > 
> > 1. Clone the repo: `git clone https://github.com/OpenIntelWireless/itlwm.git`
> > 
> > 
> > 
> > 2. Open the folder where it's cloned to
> > 
> > 
> > 
> > 3. Open Xcode, press File -> New -> File.. on the Search bar/Filter type `shell` and choose to create a new shell script file
> > 
> > 
> > 
> > 4. Copy this code below into it;
> > 
> > 
> > 
> > ```shell
> > 
> > #!/bin/bash
> > 
> > 
> > 
> > # remove all local changes
> > 
> > git reset --hard HEAD
> > 
> > rm -rf build
> > 
> > 
> > 
> > # pull latest code
> > 
> > git pull
> > 
> > 
> > 
> > # remove generated firmware
> > 
> > rm include/FwBinary.cpp
> > 
> > 
> > 
> > # remove firmware for other wifi cards - DELETE OR CHANGE TO YOUR CARD
> > 
> > find itlwm/firmware/ -type f ! -name 'iwm-7265-*' -delete
> > 
> > 
> > 
> > 
> > 
> > # generate firmware
> > 
> > xcodebuild -project itlwm.xcodeproj -target fw_gen -configuration Release -sdk macosx
> > 
> > 
> > 
> > # build the kexts
> > 
> > ## 1. itlwm.kext
> > 
> > xcodebuild -project itlwm.xcodeproj -target itlwm -configuration Release -sdk macosx
> > 
> > 
> > 
> > ## 2. AirportItlwm Catalina
> > 
> > xcodebuild -project itlwm.xcodeproj -target AirportItlwm-Mojave -configuration Release -sdk macosx
> > 
> > 
> > 
> > ## 3. AirportItlwm Catalina
> > 
> > xcodebuild -project itlwm.xcodeproj -target AirportItlwm-Catalina -configuration Release -sdk macosx
> > 
> > 
> > 
> > ## 4. AirportItlwm Big Sur
> > 
> > xcodebuild -project itlwm.xcodeproj -target AirportItlwm-Big\ Sur -configuration Release -sdk macosx
> > 
> > 
> > 
> > # Location of Kexts
> > 
> > echo "You kexts are in build/Release!!"
> > 
> > echo " "
> > 
> > ```
> > 
> > 
> > 
> > 5. Change line 14: `find itlwm/firmware/ -type f ! -name 'iwm-7265-*' -delete` change `iwm-7265` to your firmware name and save the file.
> > 
> > 
> > 
> > 6. Place the file in the root directory of the cloned itlwm folder.
> > 
> > 
> > 
> > 7. Clone MacKernelSDK `git clone https://github.com/acidanthera/MacKernelSDK.git` and place it's folder inside itlwm folder
> > 
> > 
> > 
> > 8. Run the script with sh command.
> > 
> > Ex: `sh script-name.sh` where 'script-name' is the name of the shell script you made.
> > 
> > 
> > 
> > Done, you'll find your kexts under build/Release
> 
> Thanks a lot!! Is it possible also to remove boot logs?

As william said. It won't change anything. Every kexts has log, some are hidden but they are still there running. Disabling them won't change anything. Further delay may be caused by the network controller itself

**Comment by mhl221135** [comment]
> > > I solved this by building both Airportitlwm and IntelBluetoothFirmware myself, removing firmware for all the cards except mine first. This results in much smaller kexts that load faster.
> > 
> > Can you teach me how to do that ?
> 
> I finally got it to work. 
> 1. Clone the repo: `git clone https://github.com/OpenIntelWireless/itlwm.git`
> 
> 2. Open the folder where it's cloned to
> 
> 3. Open Xcode, press File -> New -> File.. on the Search bar/Filter type `shell` and choose to create a new shell script file
> 
> 4. Copy this code below into it;
> 
> ```shell
> #!/bin/bash
> 
> # remove all local changes
> git reset --hard HEAD
> rm -rf build
> 
> # pull latest code
> git pull
> 
> # remove generated firmware
> rm include/FwBinary.cpp
> 
> # remove firmware for other wifi cards - DELETE OR CHANGE TO YOUR CARD
> find itlwm/firmware/ -type f ! -name 'iwm-7265-*' -delete
> 
> 
> # generate firmware
> xcodebuild -project itlwm.xcodeproj -target fw_gen -configuration Release -sdk macosx
> 
> # build the kexts
> ## 1. itlwm.kext
> xcodebuild -project itlwm.xcodeproj -target itlwm -configuration Release -sdk macosx
> 
> ## 2. AirportItlwm Mojave
> xcodebuild -project itlwm.xcodeproj -target AirportItlwm-Mojave -configuration Release -sdk macosx
> 
> ## 3. AirportItlwm Catalina
> xcodebuild -project itlwm.xcodeproj -target AirportItlwm-Catalina -configuration Release -sdk macosx
> 
> ## 4. AirportItlwm Big Sur
> xcodebuild -project itlwm.xcodeproj -target AirportItlwm-Big\ Sur -configuration Release -sdk macosx
> 
> # Location of Kexts
> echo "You kexts are in build/Release!!"
> echo " "
> ```
> 
> 5. Change line 14: `find itlwm/firmware/ -type f ! -name 'iwm-7265-*' -delete` change `iwm-7265` to your firmware name and save the file.
> 
> 6. Place the file in the root directory of the cloned itlwm folder.
> 
> 7. Clone MacKernelSDK `git clone https://github.com/acidanthera/MacKernelSDK.git` and place it's folder inside itlwm folder
> 
> 8. Run the script with sh command.
> Ex: `sh script-name.sh` where 'script-name' is the name of the shell script you made.
> 
> Done, you'll find your kexts under build/Release

Thank yoy for your manual, it is work for me =) Maybe you also know how to remove other firmwares for bluetooth firmware kext ?

**Comment by racka98** [comment]
> > > > I solved this by building both Airportitlwm and IntelBluetoothFirmware myself, removing firmware for all the cards except mine first. This results in much smaller kexts that load faster.
> > > 
> > > 
> > > Can you teach me how to do that ?
> > 
> > 
> > I finally got it to work.
> > 
> > 1. Clone the repo: `git clone https://github.com/OpenIntelWireless/itlwm.git`
> > 2. Open the folder where it's cloned to
> > 3. Open Xcode, press File -> New -> File.. on the Search bar/Filter type `shell` and choose to create a new shell script file
> > 4. Copy this code below into it;
> > 
> > ```shell
> > #!/bin/bash
> > 
> > # remove all local changes
> > git reset --hard HEAD
> > rm -rf build
> > 
> > # pull latest code
> > git pull
> > 
> > # remove generated firmware
> > rm include/FwBinary.cpp
> > 
> > # remove firmware for other wifi cards - DELETE OR CHANGE TO YOUR CARD
> > find itlwm/firmware/ -type f ! -name 'iwm-7265-*' -delete
> > 
> > 
> > # generate firmware
> > xcodebuild -project itlwm.xcodeproj -target fw_gen -configuration Release -sdk macosx
> > 
> > # build the kexts
> > ## 1. itlwm.kext
> > xcodebuild -project itlwm.xcodeproj -target itlwm -configuration Release -sdk macosx
> > 
> > ## 2. AirportItlwm Mojave
> > xcodebuild -project itlwm.xcodeproj -target AirportItlwm-Mojave -configuration Release -sdk macosx
> > 
> > ## 3. AirportItlwm Catalina
> > xcodebuild -project itlwm.xcodeproj -target AirportItlwm-Catalina -configuration Release -sdk macosx
> > 
> > ## 4. AirportItlwm Big Sur
> > xcodebuild -project itlwm.xcodeproj -target AirportItlwm-Big\ Sur -configuration Release -sdk macosx
> > 
> > # Location of Kexts
> > echo "You kexts are in build/Release!!"
> > echo " "
> > ```
> > 
> > 
> > 
> > 1. Change line 14: `find itlwm/firmware/ -type f ! -name 'iwm-7265-*' -delete` change `iwm-7265` to your firmware name and save the file.
> > 2. Place the file in the root directory of the cloned itlwm folder.
> > 3. Clone MacKernelSDK `git clone https://github.com/acidanthera/MacKernelSDK.git` and place it's folder inside itlwm folder
> > 4. Run the script with sh command.
> >    Ex: `sh script-name.sh` where 'script-name' is the name of the shell script you made.
> > 
> > Done, you'll find your kexts under build/Release
> 
> Thank yoy for your manual, it is work for me =) Maybe you also know how to remove other firmwares for bluetooth firmware kext ?

The problem is for the bluetooth firmware the names aren't very specific. You need to know exactly what the firmware of you card is and they are not prefixed by your card name like the wifi ones.

**Comment by williambj1** [comment]
The firmware name is present in IOReg.

**Comment by racka98** [comment]
> The firmware name is present in IOReg.

Oh yeah. I see it now

**Comment by cristoiroberto** [comment]
Which firmware shall I keep for intel ax201? Thanks

**Comment by racka98** [comment]
> Which firmware shall I keep for intel ax201? Thanks

> The firmware name is present in IOReg.

**Comment by cristoiroberto** [comment]
> > Which firmware shall I keep for intel ax201? Thanks
> 
> > The firmware name is present in IOReg.

Where? I can't find IOReg.

**Comment by racka98** [comment]
> > > Which firmware shall I keep for intel ax201? Thanks
> > 
> > > The firmware name is present in IOReg.
> 
> Where? I can't find IOReg.
Here:
https://github.com/khronokernel/IORegistryClone/blob/master/ioreg-210.zip

**Comment by cristoiroberto** [comment]
> > > > Which firmware shall I keep for intel ax201? Thanks
> > > 
> > > 
> > > > The firmware name is present in IOReg.
> > 
> > 
> > Where? I can't find IOReg.
> 
> Here:
> https://github.com/khronokernel/IORegistryClone/blob/master/ioreg-210.zip

Could you please point me exactly to where is the firmware name? Thanks

**Comment by racka98** [comment]
> > > > > Which firmware shall I keep for intel ax201? Thanks
> > > > 
> > > > 
> > > > > The firmware name is present in IOReg.
> > > 
> > > 
> > > Where? I can't find IOReg.
> > 
> > 
> > Here:
> > https://github.com/khronokernel/IORegistryClone/blob/master/ioreg-210.zip
> 
> Could you please point me exactly to where is the firmware name? Thanks

Open the IORegistryExplorer I linked, on the search bar at the top right type bluetooth then click on intelbluetoothfirmware and you can see fw_name there
![Screenshot 2021-01-12 at 19 19 16](https://user-images.githubusercontent.com/41214249/104342344-c8fda780-550b-11eb-9344-83fbed207bb9.png)

**Comment by cristoiroberto** [comment]
@racka98 Thank you, you pointed me to bluetooth firmware. I want for wifi card to find which firmware to keep(build airportitlwm)

**Comment by racka98** [comment]
> @racka98 Thank you, you pointed me to bluetooth firmware. I want for wifi card to find which firmware to keep(build airportitlwm)

Search for "airportitlwm" or "itlwm" if you are using itlwm.kext then click on it. Look for IOModel you should see the name
![Screenshot 2021-01-12 at 20 20 14](https://user-images.githubusercontent.com/41214249/104349357-e0d92980-5513-11eb-9686-19994acf3d88.png)

**Comment by cristoiroberto** [comment]
@racka98 

I can see "Intel Wireless Card" at IoModel.

**Comment by cristoiroberto** [comment]
@racka98  Could you please provide the script you used to build Bluetooth kext?

**Comment by aspenluxxxy** [comment]
@racka98 your method of using IOReg only works with AirportItlwm, not itlwm it seems.
