### ISSUE TITLE
Itlwm is not running

### ISSUE THREAD

**Issue by callmeFumsek** [OpenIntelWireless/itlwm#357]
**Have You Read Our Docs**

Yes

**Are You Reporting A Bug**

Yes

**Environment**

- Kext Version: Lastest stable
- WiFi Card Model: AC9462
- Product ID: Intel wireless 9432
- macOS Version: macOS Catalina 10.15.7

**Description**

I put the kext on the kext folder of clover. Also i've tried to load it with kext utility and nothing everyTime at every reboot it does'nt work !

**Bug Report Archive**

**Kext Download Source**

Here from the last stable version !

**Comment by williambj1** [comment]
Check your personal configuration. Closing since no logs are provided.
