### ISSUE TITLE
AirPortITLWM doesn't load with RTL8111.kext. (Possible Conflict)

### ISSUE THREAD

**Issue by 0xPeero** [OpenIntelWireless/itlwm#358]
**Have You Read Our Docs**

Yes
**Are You Reporting A Bug**

Yes
**Environment**

- Kext Version: 1.2.0A (0028810)
- WiFi Card Model: 7260
- Product ID: 
- macOS Version: 10.15.7

**Description**

AirPortITLWM doesn't work if RTL8111.kext is loaded. An older version of AirPort worked.
ITLWM works though.

**Bug Report Archive**

**Kext Download Source**

The normal download site

**Comment by williambj1** [comment]
Any logs or evidence, I'm sure it is a userspace configuration issue. Try following our troubleshooting guide. Closing since the format is invalid.
