### ISSUE TITLE
[AirportItlwm] doesn't connect 

### ISSUE THREAD

**Issue by alessiomatricardi** [OpenIntelWireless/itlwm#359]
**Have You Read Our Docs**
Yes

**Are You Reporting A Bug**
Yes

**Environment**

- Kext Version: 1.2.0 7ae2ecd
- WiFi Card Model: AC7265
- Product ID: 0x095A
- macOS Version: 10.15.7

**Description**
Now driver doesn't connect to any WiFi network. If i click on icon, no Wifi networks are provided.

**Bug Report Archive**
[logs.zip](https://github.com/OpenIntelWireless/itlwm/files/5396063/logs.zip)

**Kext Download Source**
github actions last commit

**Comment by alessiomatricardi** [comment]
Aditional informations: I'm back to 324e157 commit and now everything works

**Comment by williambj1** [comment]
FW crashed.

CC @zxystd

**Comment by chriseg93** [comment]
I confirm, the latest debug version crashed AirportItlwm

**Comment by zxystd** [comment]
@alessiomatricardi have you tried click off and then click on?

**Comment by alessiomatricardi** [comment]
@zxystd yes, i tried 1/2 times to switch off/on but no networks appear. should be saved also into logs

**Comment by rediffusion** [comment]
Hello beautiful people ⭐ can someone share with me the `invite code` for the [PC Beta](http://www.pcbeta.com/) forum.
I'll be appreciated❗

![image](https://user-images.githubusercontent.com/30071027/96477551-5304df80-123f-11eb-8db3-937b86e5636f.png)

_...sorry for offtopic._

**Comment by williambj1** [comment]
Confirmed, bug fix WIP.

**Comment by zxystd** [comment]
fix in 204c965, please help to confirm. thanks.

**Comment by alessiomatricardi** [comment]
@zxystd fixed. I'll close the issue. Thank you 💯 

[logs.zip](https://github.com/OpenIntelWireless/itlwm/files/5417084/logs.zip)
