### ISSUE TITLE
Strange behaviour with AirportItlwm Beta v1.1.0 and Alpha v1.2.0

### ISSUE THREAD

**Issue by Remmed96** [OpenIntelWireless/itlwm#362]
Does anyone have a problem with AirportItlwm v1.1.0 Beta? I don't have continuity and universal clipboard working for me, while using the alpha verion everything works fine.

**Comment by williambj1** [comment]
Alpha versions are newer than AirportItlwm v1.0, but theoretically they should work the same ATM. Closed but feel free to report more details below.
