### ISSUE TITLE
Internet not working when connecting to a wifi network

### ISSUE THREAD

**Issue by mastercreeper66** [OpenIntelWireless/itlwm#365]
**Have You Read Our Docs**
Yes

**Are You Reporting A Bug**
Yes
**Environment**

- Kext Version: 1.1.0 Stable
- WiFi Card Model: Intel AC 3160
- Product ID: 0x08b4
- macOS Version: 10.14.6

**Description**

I installed a new router (Fritz!Box 7530) but when i connect to the network i get a (!) on the wi-fi icon

**Bug Report Archive**

[bugreport_12808.zip](https://github.com/OpenIntelWireless/itlwm/files/5431995/bugreport_12808.zip)

**Kext Download Source**
-compiled release
downloaded from pre

**Comment by zxystd** [comment]
everything seems to works fine in the log, have you check the wifi password is correct? or can you try to press the DHCP button in the network configurstion panel?

**Comment by mastercreeper66** [comment]
Yes, the password is correct. I tried to press "Renew DHCP Lease" but nothing changes

**Comment by phucnguyen2411** [comment]
please try to set ip manually, that should works.

**Comment by mastercreeper66** [comment]
Setting the IP manually works
