### ISSUE TITLE
WIFI切换问题

### ISSUE THREAD

**Issue by hsmliu** [OpenIntelWireless/itlwm#370]
**Have You Read Our Docs**

**Are You Reporting A Bug**

**Environment**

- Kext Version: 
- WiFi Card Model: 8265
- Product ID: 
- macOS Version: macos11 beta10

**Description**
我的笔记本连了公司和家里两个WIFI，但是在家办公后再拿到公司，就再也连不上公司的WIFI，必须要重启才能连上，这是因为我没有设置好，还是bug呢

**Comment by zxystd** [comment]
没有日志是要我给你算一卦么？

**Comment by williambj1** [comment]
Invalid issue format

**Comment by hsmliu** [comment]
> 没有日志是要我给你算一卦么？

不会看日志啊   尴尬
