### ISSUE TITLE
Handoff has some problems that shouldn't be

### ISSUE THREAD

**Issue by Theredmc** [OpenIntelWireless/itlwm#377]
**Have You Read Our Docs**
YES

**Are You Reporting A Bug**
YES

**Environment**

- Kext Version: newest available alpha 
- WiFi Card Model: 3165
- Product ID: 
- macOS Version: 10.15.7

**Description**
I am germany so sorry for my English. 
Handoff works except when you right click on the desktop and what to take a picture with your iPhone it always time out and WFI hotspot doesn't work neither it times out , but the other stuff is working

**Bug Report Archive**
I am not using heliport there is no need if the system stuff is working.

**Kext Download Source**
this website

**Comment by williambj1** [comment]
Other features are not advertised as "Handoff". You are probably looking for something else. Read our docs and the following URL for more info.

https://support.apple.com/en-us/HT204681

**Comment by williambj1** [comment]
BTW, we are working on supporting more features; stay tuned.

**Comment by Theredmc** [comment]
Bruh like bruh it’s working for everyone else and it’s a handoff thing 

Von meinem iPhone gesendet

**Comment by williambj1** [comment]
You did not understand the difference between "Continuity" and "Handoff".

**Comment by Theredmc** [comment]
It should work, it worked for everyone else, heck it’s even working for my brother 

Von meinem iPhone gesendet

**Comment by williambj1** [comment]
Those features are *not* supported right now. Please consider alternative solutions if you really need them.

**Comment by zxystd** [comment]
AirportItlwm is not a fake or patch driver, you should read our Docs. Thanks.
