### ISSUE TITLE
WiFi 信道更高带宽支持

### ISSUE THREAD

**Issue by CyrilTaylor** [OpenIntelWireless/itlwm#378]
**Have You Read Our Docs**

Yes

**Are You Reporting A Bug**

Yes

**Environment**

- Kext Version: AirportItlwm  v1.1.0
- WiFi Card Model: AX200
- Product ID: 联想Y9000X
- macOS Version: 10.15.7

**Description**

目前WiFi连接到5G的时候，只能用最低的20MHZ的信道带宽，导致WiFi的最高速率只有140Mbps，现在的路由器一般的都能达到80MHZ，而对于WiFi6的路由器，AX200可以达到160MHZ，所以希望可以支持40MHZ、80MHZ甚至160MHZ。

![image](https://user-images.githubusercontent.com/12631466/98064146-90e34400-1e8c-11eb-8c17-f1bcb157bade.png)

**Bug Report Archive**

**Kext Download Source**

**Comment by williambj1** [comment]
WIP

**Comment by zxystd** [comment]
不属于bug，在预期之内。
