### ISSUE TITLE
[Enhancement] Dependency fix for macOS Sierra 10.12.3

### ISSUE THREAD

**Issue by VoltaVX** [OpenIntelWireless/itlwm#379]
After some headaches, I finally got ITLWM to work on my macOS Sierra 10.12.3. There were some errors regarding the kext needing some libraries in iokit and kpi to be at least 16.7. However, in the info.plist, I changed the versions to 16.4 which were the version bundled in the operating system, and it worked perfectly. So yeah, just sharing my results here for the possibility of the dependency version needed for the kext to work to be lowered.

	<key>OSBundleLibraries</key>
	<dict>
		<key>com.apple.iokit.IONetworkingFamily</key>
		<string>3.2</string>
		<key>com.apple.iokit.IOPCIFamily</key>
		<string>2.9</string>
		<key>com.apple.kpi.bsd</key>
		<string>16.4</string>
		<key>com.apple.kpi.iokit</key>
		<string>16.4</string>
		<key>com.apple.kpi.libkern</key>
		<string>16.4</string>
		<key>com.apple.kpi.mach</key>
		<string>16.4</string>
	</dict>

**Comment by williambj1** [comment]
@VoltaVX 

Thanks for your report, could please you attach the output from `uname -a` and `kextlibs -undef-symbols itlwm.kext` as well? Thanks.

**Comment by VoltaVX** [comment]
@williambj1 Hi, unfortunately, I don't have macOS Sierra 10.12.3 since I managed to get macOS high sierra 10.13.6 working with full support. Will getting the info you'd like in the macOS Sierra installer work? From memory, I remember that when I ran the kextlibs command on the original ITLWM, I got that "com.apple.kpi.bsd, com.apple.kpi.iokit, com.apple.kpi.libkern, com.apple.kpi.mach" weren't compatible with my machine's libraries, that I needed to have at least versions 16.7.

**Comment by zxystd** [comment]
@VoltaVX I think it is fix now.

**Comment by zxystd** [comment]
Thank you.

**Comment by zcream** [comment]
For reference, which of the versions can be used on Sierra ? There is a version for High Sierra, Monterey and Big Sur.
