### ISSUE TITLE
Bluetooth does not work with latest AirportItlwm commit (AC-9462)

### ISSUE THREAD

**Issue by lgariv** [OpenIntelWireless/itlwm#381]
**Have You Read Our Docs**
Yes

**Are You Reporting A Bug**
Yes

**Environment**
- Kext Version: [`07cb669`](https://github.com/OpenIntelWireless/itlwm/commit/07cb669b5ecd6e069c9cff15fa76a1a80ab65563), AirportItlwm
- WiFi Card Model: AC-9462
- Product ID: `0x42A4`
- macOS Version: macOS Catalina 10.15.7 (before supplemental update)

**Description**
This commit broke Bluetooth completely - firmware is not uploading. reverting back to the previous commit resolves the issue for me.

**Bug Report Archive**
[AirItlDebug_2020-11-06_17-21-41.zip](https://github.com/OpenIntelWireless/itlwm/files/5501978/AirItlDebug_2020-11-06_17-21-41.zip)

**Kext Download Source**
Releases, latest compiled pre-release.

**Comment by win1010525** [comment]
Works fine for me. Same card

**Comment by lgariv** [comment]
> Works fine for me. Same card

Same product ID? Which boot loader do you use?

**Comment by zxystd** [comment]
@lgariv I don't think they have relationship with the commit... have you cleaned the recycle bin after you update the kext and before reboot?

**Comment by lgariv** [comment]
> @lgariv I don't think they have relationship with the commit... have you cleaned the recycle bin after you update the kext and before reboot?

I always clear it as soon as I'm done doing something. 
Anyway, just updated to the latest alpha and now everything works.

**Comment by lgariv** [comment]
Apparently, I am not the only one [having this problem](https://github.com/OpenIntelWireless/IntelBluetoothFirmware/issues/212
). Also, on the [latest commit](https://github.com/OpenIntelWireless/itlwm/commit/219b6178e40b45565d67fe1cc8e72fc16e783a11)

**Comment by dpatrongomez** [comment]
I have the same problem with Intel Wireless 8265

**Comment by luuknieuwdorp** [comment]
Same issue here with Intel Wireless 8265. After upgrading I can't connect to my remembered bluetooth device. After forgetting it to try and repair it no devices seem to show up in the bluetooth list at all when using the latest alpha.

**Comment by luuknieuwdorp** [comment]
Update: bluetooth is working for me again since updating to the latest alpha, built 7 hours ago (https://github.com/OpenIntelWireless/itlwm/commit/d9bd8d435b80c009c928156ef805e14b2a527fd7).

**Comment by dpatrongomez** [comment]
> Update: bluetooth is working for me again since updating to the latest alpha, built 7 hours ago ([d9bd8d4](https://github.com/OpenIntelWireless/itlwm/commit/d9bd8d435b80c009c928156ef805e14b2a527fd7)).

Well, even with that version it lets me turn off the bluetooth

**Comment by MenschLennart** [comment]
I do have the AC - 9260 and Bluetooth doesn't work at all. Already tried resetting Bluetooth completely with SHIFT-Option-LeftClick on Bluetooth icon in menu bar. But nothing helps. Wether Magic Mouse 2 nor Magic Keyboard is working.
