### ISSUE TITLE
itlwm loaded with error: unknown adapter type

### ISSUE THREAD

**Issue by blackberry4311** [OpenIntelWireless/itlwm#386]
**Have You Read Our Docs**
Yes

**Are You Reporting A Bug**
Yes/Maybe

**Environment**

- Kext Version: 1.1.0, itlwm
- WiFi Card Model: Intel Wifi AX201
- Product ID: 0x06F0
- macOS Version: 10.15.7

**Description**
itlwm loaded with error: unknown adapter type,
tried auto load via EFI inject with OC and manual via terminal follow instruction at https://openintelwireless.github.io/itlwm/Troubleshooting.html#getting-kext-logs-for-loading-failures

**Bug Report Archive**
[bugreport_24931.zip](https://github.com/OpenIntelWireless/itlwm/files/5507098/bugreport_24931.zip)

**Kext Download Source**
stable release of 1.1.0

**Comment by williambj1** [comment]
Does manually loading the kext after booting into the system give you the same result?

**Comment by zxystd** [comment]
@blackberry4311 can you upload your pcie info with Hackintool? like this:
<img width="656" alt="image" src="https://user-images.githubusercontent.com/16227538/98491126-cd3ce880-226e-11eb-9b74-ac3e88808b0c.png">

**Comment by blackberry4311** [comment]
@williambj1 I  got above log when manual load the kext, and it gives me the same result
@zxystd here you are
![image](https://user-images.githubusercontent.com/438441/98504450-97f1c400-2289-11eb-9e7e-e362238414f0.png)

**Comment by zxystd** [comment]
same card and same driver? now it shows unknown adapter type? @blackberry4311

**Comment by blackberry4311** [comment]
yes, it worked 2 days ago, I change nothing and it show the log like I uploaded yesterday.

**Comment by zxystd** [comment]
subdevice id is 0x0000, so weird, that should not work. do you have linux? can you check if the card can work on linux now?
I will compile a kext which will output more logs what I needed to you soon.
<img width="121" alt="image" src="https://user-images.githubusercontent.com/16227538/98509058-87e2e000-229b-11eb-939f-89cb5bd4763a.png">

**Comment by blackberry4311** [comment]
I don't have linux currently but I can install it for further checking.Is Ubuntu latest version ok?

**Comment by williambj1** [comment]
@blackberry4311 A Ubuntu 20 Live USB would be enough.

**Comment by blackberry4311** [comment]
work well on ubuntu 20
![Screenshot from 2020-11-09 07-50-07](https://user-images.githubusercontent.com/438441/98513822-67496480-2260-11eb-95eb-93e4e249d663.png)
![Screenshot from 2020-11-09 07-49-21](https://user-images.githubusercontent.com/438441/98513838-6b758200-2260-11eb-852b-ac57f08f1130.png)

**Comment by blackberry4311** [comment]
Wifi back and working like charm, after I'm boot to Ubuntu,
![image](https://user-images.githubusercontent.com/438441/98514613-53235880-229c-11eb-98f5-c722dd6a7fa2.png)
Sub Device change like in this image

Hmm, I don't know the reason why but let me try to make some test on this scenario first.
