### ISSUE TITLE
[Airportitlwm]Big Sur 11.0.1 wifi失效

### ISSUE THREAD

**Issue by citylcs** [OpenIntelWireless/itlwm#390]
Big Sur正式版更新以來就無法使用wifi，頂部選單中有wifi的標誌但無法搜索到任何接入點。

**Comment by williambj1** [comment]
Invalid issue format. Works perfectly for me in 11.0.1.

**Comment by bingzujia** [comment]
检查是否同时启用了 Airportitlwm 和 Itlwm
