### ISSUE TITLE
前几天可以搜索到蓝牙设备，这几天搜索不到了，wifi正常使用。

### ISSUE THREAD

**Issue by codecola** [OpenIntelWireless/itlwm#391]
Apple蓝牙软件版本：	7.0.6f7
  硬件、功能和设置：
  名称：	mac’s iMac
  地址：	00-00-00-00-00-00
  支持低功耗蓝牙：	否
  支持“接力”：	否
  支持智能热点：	否
  生产企业：	Ericsson
  传输：	USB
  固件版本：	0.0 (0.0)
  蓝牙电源：	打开
  可被发现：	关闭
  可连接：	否
  自动寻找点：	打开
  远程唤醒：	打开
  供应商ID：	0x8087
  产品ID：	0x0AAA
  蓝牙核心规范：	1.0b (0x0)
  HCI修正版：	0x00
  LMP版本：	1.0b (0x0)
  LMP子版本：	0x00
  自动寻找键盘：	打开
  服务：
  蓝牙文件传输：
  其他设备可以浏览的文件夹：	~/Public
  当接收项目时：	接受所有文件而不发出警告
  状态：	已停用
  蓝牙文件交换：
  存放已接受项目的文件夹：	~/Downloads
  当接受其他项目时：	存储到位置
  当接收项目时：	接受所有文件而不发出警告
  状态：	已停用
  蓝牙互联网共享：
  状态：	已停用
  传入串口：
  Bluetooth-Incoming-Port：
  RFCOMM通道：	3
  需要认证：	否

**Comment by williambj1** [comment]
Invalid issue format. User mistake.
