### ISSUE TITLE
I219-V 网卡无法有效驱动

### ISSUE THREAD

**Issue by dubhe-git** [OpenIntelWireless/itlwm#393]
情况如下：
win10情况下有线正常上网。
mac系统下，hackintool能够检测出来I219-V 但是网络里面没有以太网选项。
同时发现我用的博通的网卡 地址是en0，不知道这个会不会有影响。
安装时已经在驱动力放入了 intel的板载驱动，但是依然无效。

------
主板：ASUS B250M-PLUS

**Comment by williambj1** [comment]
RU Kidding me?
