### ISSUE TITLE
PHY mode is always 802.11n, even with 5GHz only network

### ISSUE THREAD

**Issue by grimfrost** [OpenIntelWireless/itlwm#396]
**Have You Read Our Docs**
Yes

**Are You Reporting A Bug**
Yes

**Environment**
- Kext Version: AirportItlwm_v1.0_Beta_Catalina
- WiFi Card Model: Intel Dual Band Wireless-AC 7260
- Product ID: 7260.HMW
- macOS Version: macOS Catalina 10.15.7

**Description**
PHY mode is always 802.11n, even with 5GHz only network. The card and router I'm using supports 802.11ac.
![image](https://user-images.githubusercontent.com/37805399/99184203-51e9a400-2752-11eb-9d68-7834731a8c58.png)

**Bug Report Archive**
"Read this guide if you are using AirportItlwm http://localhost:8080/itlwm/Troubleshooting.html#manually-for-airportitlwm" -> ** This description gives me a localhost link. So I'm pretty unable to follow.**

**Kext Download Source**
Gitlab Releases

**Comment by grimfrost** [comment]
Typo fix:
**Kext Download Source**
Github Releases

**Comment by williambj1** [comment]
This is correct

**Comment by grimfrost** [comment]
> This is correct

So I believe I missed the documented part where this issue mentioned?

**Comment by williambj1** [comment]
Read the FAQ for more information.

**Comment by grimfrost** [comment]
> Read the FAQ for more information.

Oh I just noticed "Performance Sucks". Thanks for your kind guidance.

**Comment by aspenluxxxy** [comment]
> It is recommended for daily use  
> 
> ...  
> # Performance SUCKS

kinda contradicting, no?

also, is it just me, or is niche stuff like AirDrop being prioritized above actual features that matter like 802.11ac? If I knew how to help, I would, though.

**Comment by grimfrost** [comment]
> > It is recommended for daily use
> > ...
> > # Performance SUCKS
> 
> kinda contradicting, no?
> 
> also, is it just me, or is niche stuff like AirDrop being prioritized above actual features that matter like 802.11ac? If I knew how to help, I would, though.

Well, Idk about you but that niche stuff is one of the reasons why I want to use Hackintosh instead of Windows. Of course I do appreciate performance but it is not most important point for me.

**Comment by 1Revenger1** [comment]
That stuff is being worked on in the background as far as I can tell - getting AMPDU/ac work is a huge task. I wouldn't be suprised if a lot of the AirDrop stuff is just from more stuff being reversed while working on ac (though I honestly have no clue and am not trying to speak for the team).

**Comment by aspenluxxxy** [comment]
Oh, thanks for the explanation!
