### ISSUE TITLE
[Airportitlwm 1.1] Airportitlwm stuck at loading itlwm on Big Sur

### ISSUE THREAD

**Issue by hoanghohuy** [OpenIntelWireless/itlwm#397]
**Have You Read Our Docs**
 Yes

**Are You Reporting A Bug**
 Yes

**Environment**

- Kext Version: AirportItlwm_v1.0_Beta_BigSur.kext
- WiFi Card Model: Intel AC-8265
- Product ID: 8086
- macOS Version: BigSur 11

**Description**
On Catalina it working
On BigSur, it stucked at loading itlwm on startup
Thanks.
Photo:
![125541682_377268690156588_8750481196297562246_n](https://user-images.githubusercontent.com/74502699/99190786-1cb57400-279b-11eb-9200-d7253c8829cf.jpg)

**Comment by FaneCH** [comment]
I have the same issue on big sur. Can't extract any logs cause it doesn't boot.

**Comment by win1010525** [comment]
Update to newest kext and try again.

**Comment by FaneCH** [comment]
@win1010525 it does the same thing.
I also tried to disable ASPM but nothing happens.

**Comment by win1010525** [comment]
Can you boot normally without itlwm?

**Comment by williambj1** [comment]
Unrelated

**Comment by FaneCH** [comment]
> Unrelated

Why the issue was closed?? This is a real bug that needs a fix!
