### ISSUE TITLE
ax200睡眠唤醒后断网 无法连接Wi-Fi

### ISSUE THREAD

**Issue by Alex-xwd** [OpenIntelWireless/itlwm#401]
**Have You Read Our Docs**
Yes

**Are You Reporting A Bug**
Yes

**Environment**

- Kext Version: AirportItlwm 1.1.0
- WiFi Card Model: intel Ax200
- Product ID: 0x8086,0x2723
- macOS Version: macOS Big Sur 11.0.1

**Description**

handoff电脑能完美接力手机，手机经常接力不了电脑。以及睡眠后唤醒断网，无法连接Wi-Fi。
**Bug Report Archive**

没有用heliport

**Kext Download Source**

AirportItlwm 1.1.0 从GitHub 最新release

**Comment by Orgnge** [comment]
ax200 断网无法恢复 目前只能重置efi然后打入驱动  使用版本最新发布的

從我的iPhone傳送

**Comment by williambj1** [comment]
No logs. Will reopen once provided.
