### ISSUE TITLE
AC9462刚发布的1.2.0版本无法进入系统

### ISSUE THREAD

**Issue by hqting** [OpenIntelWireless/itlwm#403]
**Have You Read Our Docs**

**Are You Reporting A Bug**

**Environment**

- Kext Version: V1.2.0-alpha
- WiFi Card Model: AC9462；
- Product ID: 0x8086
- macOS Version: big sur 正式版
- 设备 id：0x02f0

**Description**

**Bug Report Archive**

**Kext Download Source**

**Comment by chenyuyou** [comment]
我的也是。


Environment

Kext Version: V1.2.0-alpha
WiFi Card Model: AC9560；
Product ID: 0x8086
macOS Version: big sur 正式版
设备 id：0x34

**Comment by williambj1** [comment]
Confirmed

**Comment by williambj1** [comment]
[Panic-66f82e815a85920e6de61329881f5abeda3b7569.txt](https://github.com/OpenIntelWireless/itlwm/files/5559808/Panic-66f82e815a85920e6de61329881f5abeda3b7569.txt)

**Comment by williambj1** [comment]
@chenyuyou @hqting 请提供更多信息，如 panic 日志。

**Comment by zxystd** [comment]
please attach the panic log

**Comment by hqting** [comment]
> [Panic-66f82e815a85920e6de61329881f5abeda3b7569.txt](https://github.com/OpenIntelWireless/itlwm/files/5559808/Panic-66f82e815a85920e6de61329881f5abeda3b7569.txt)

我想请教一下如何操作才能取得panic log这个文件。

**Comment by williambj1** [comment]
Fixed in 69aaea39895ea7f78480315eab0cf4ac1f445250
