### ISSUE TITLE
我想问一下支持小米笔记本的英特尔8260吗

### ISSUE THREAD

**Issue by langengel** [OpenIntelWireless/itlwm#407]
**Have You Read Our Docs**

**Are You Reporting A Bug**

**Environment**

- Kext Version: 
- WiFi Card Model: 
- Product ID: 
- macOS Version: 

**Description**

**Bug Report Archive**

**Kext Download Source**

**Comment by win1010525** [comment]
你觉得呢？不看支持列表吗

**Comment by langengel** [comment]
在哪里？

**Comment by win1010525** [comment]
自己找去
