### ISSUE TITLE
Big Sur AX200的隔空投送功能  安卓设备认了

### ISSUE THREAD

**Issue by Tizcho** [OpenIntelWireless/itlwm#409]
Big Sur
AX200蓝牙+wifi驱动打上之后
隔空投送正版的ios搜索不到设备
但
非正版的魔趣的跃传却给认出来了？

![image](https://user-images.githubusercontent.com/35987023/99806909-a4bfc300-2b79-11eb-9f2f-36057ff03cdb.png)

**Comment by ruigemen** [comment]
这个太草了，哈哈哈。导演：？？？

**Comment by win1010525** [comment]
有反应，能发送吗

**Comment by Tizcho** [comment]
> 有反应，能发送吗

能从手机发送到电脑，但不能从电脑发送到手机

**Comment by win1010525** [comment]
电脑不能发正常

**Comment by meaverick** [comment]
请教各位老大，我把两个文件copy到系统EFI目录，SECURE BOOT设置成SETUP,怎么还是不工作呢？我的无线是AX200  2723.谢谢

**Comment by meaverick** [comment]
请教各位老大，我把两个文件copy到系统EFI目录，SECURE BOOT设置成SETUP,怎么还是不工作呢？我的无线是AX200  2723.谢谢
GIGABYTE B460  GTX650  INTEL I219V

**Comment by win1010525** [comment]
说明白点啊……

**Comment by win1010525** [comment]
哪两个文件啊，让z大来算卦吗？

**Comment by williambj1** [comment]
P2P is supposed to work.
