### ISSUE TITLE
Intel7265在macOS下面玩游戏延迟偏高切换到windows下就不会出现这种情况

### ISSUE THREAD

**Issue by uifor** [OpenIntelWireless/itlwm#410]
游戏是饥荒联机版，连接服务器后延迟很高，其他游戏暂时没有测试，切换到双系统到windows连接服务器延迟正常不会卡顿，所以觉得应该是itlwm驱动稳定性导致的，希望作者抽空之余看看就行，不是什么很重要的问题，谢谢🙏

**Comment by williambj1** [comment]
Invalid issue format

**Comment by win1010525** [comment]
看一下Doc里的Performance sucks.

**Comment by win1010525** [comment]
卡顿归卡顿，驱动延迟并不高
