### ISSUE TITLE
Sidecar seems to work , tx rate not accurate

### ISSUE THREAD

**Issue by samleong123** [OpenIntelWireless/itlwm#412]
**Have You Read Our Docs**
Yes

**Are You Reporting A Bug**
No. Only Info

**Environment**

- Kext Version: v1.1.0
- WiFi Card Model: Intel AX201
- Product ID: 8086,2f0
- macOS Version: 10.15.7

**Description**
Sidecar seems to be able to detect but unable to connect. Handoff and Universal Clipboard worked perfectly! Airdrop doesn't work.
![Sidecar Status Bar](https://i.loli.net/2020/11/22/XQ1nlBxuV2hEPac.png)
![Unable to connect](https://i.loli.net/2020/11/22/HtcpsEmI1oyP4vU.png)
![Handoff working](https://i.loli.net/2020/11/22/C2y3fwIzcgmZspj.png)
![Clipboard working](https://i.loli.net/2020/11/22/N3GPmLo4Y6nF17r.png)

And i found out that the tx rate is 140-150Mbps but even internal speed test is reaching only 50Mbps on 5GHz , kind of weird.
The speedtest server is connected through 1GBPS Cat 5e to my router with using IIS and i use WiFi 5GHz to connect it 

**Bug Report Archive**

**Kext Download Source**
Your Repo

**Comment by samleong123** [comment]
#### Latest Info : Sidecar seems to be work and connected to my iPad!
![Computer](https://i.loli.net/2020/11/22/2VzByCfKYmtwaOF.png)
![iPad](https://i.loli.net/2020/11/22/78hkLy1XbriDc3g.png)

**Comment by williambj1** [comment]
Tx rate is correct, please read our docs for more info. Sidecar is not supposed to work, please connect with a cable instead.
