### ISSUE TITLE
AirportItlwm is not connecting to WiFi AX200

### ISSUE THREAD

**Issue by shocker2** [OpenIntelWireless/itlwm#414]
Hello,
  With the latest version of AirportItlwm, I can detect the wifi networks but I cannot connect to them. Now everything is working fine with the Bluetooth toggle and wifi toggle but I cannot connect. After 5-10 reboots the wifi gets connected for a while and then I have the same behavior.
Chipset AX200 (0x0029 for bt and 0x2723 for wifi).
OS: BigSur 11.0.1 with the latest OC updates.
CPU: Ryzen 5950x
Version tested: AirportItlwm-Big_Sur-v1.2.0-DEBUG-alpha-d9bd8d4
kextstat:
74    0 0                  0xd46000   0xd46000   com.zxystd.AirportItlwm (1.2.0) 966D8E63-7E73-310A-9E57-8E9A6BBDE459 <73 49 14 6 5 3 1>
SMBIOS: MacPro 7,1
WiFi Router: Orbi RBK53

P.S. Initially I was able to use Bluetooth toggle without any issue and WiFi with iMacPro1,1 with an older version (1 week ago) of 1.2.0 alpha release. Not sure if that's related but worth mentioning it.

Cheers

**Comment by williambj1** [comment]
Please attach logs.

**Comment by shocker2** [comment]
> Please attach logs.

Sorry for my noob question, but how can I do that? I'm new to Hackintosh just installed a week ago the first one :) but I'm a mac user for 15 years :)

**Comment by shocker2** [comment]
[AirItlDebug_2020-11-23_16-34-16.zip](https://github.com/OpenIntelWireless/itlwm/files/5583650/AirItlDebug_2020-11-23_16-34-16.zip)
And another one

**Comment by shocker2** [comment]
Just tested with SMBIOS iMacPro1,1 and I have the same result, it's not related to this.

**Comment by zxystd** [comment]
> [AirItlDebug_2020-11-23_16-34-16.zip](https://github.com/OpenIntelWireless/itlwm/files/5583650/AirItlDebug_2020-11-23_16-34-16.zip)
> And another one

using dmesg, the log is not complete.

**Comment by shocker2** [comment]
> > [AirItlDebug_2020-11-23_16-34-16.zip](https://github.com/OpenIntelWireless/itlwm/files/5583650/AirItlDebug_2020-11-23_16-34-16.zip)
> > And another one
> 
> using dmesg, the log is not complete.

[dmesg.log](https://github.com/OpenIntelWireless/itlwm/files/5587971/dmesg.log)

**Comment by shocker2** [comment]
Updated to the latest release alpha-c231439 and wireless connected. Not sure if it's the one time thing or it will work (I'll keep testing). Now the bluetooth is not working again. If I toggle the enabled button it's not activating. Pressing bluetooth preferences gets me:
<img width="259" alt="Screenshot 2020-11-24 at 09 13 45" src="https://user-images.githubusercontent.com/24977727/100060552-5f2f1e80-2e35-11eb-9b0d-1b98fe98da68.png">

**Comment by shocker2** [comment]
After a reboot, I have the same situation. I can toggle Bluetooth on/off and the above error disappeared but wifi si not connecting. Let me know if I can provide something else.

Cheers

**Comment by Freddson** [comment]
Hey, I have the same problem in my issue, my friend had it and he told me to download the newest alpha version compiled by Github Actions, there is a fixed enum. It fixed his problem and I'm currently checking if it works for me.

**Comment by shocker2** [comment]
> Hey, I have the same problem in my issue, my friend had it and he told me to download the newest alpha version compiled by Github Actions, there is a fixed enum. It fixed his problem and I'm currently checking if it works for me.

I keep updating it to the latest releases. Now I'm using the one released 3h ago and it's still not working. Usually every 5-8 reboots I'm getting one connect. Now with the new update, I cannot activate the Bluetooth again.

**Comment by Freddson** [comment]
> > Hey, I have the same problem in my issue, my friend had it and he told me to download the newest alpha version compiled by Github Actions, there is a fixed enum. It fixed his problem and I'm currently checking if it works for me.
> 
> I keep updating it to the latest releases. Now I'm using the one released 3h ago and it's still not working. Usually every 5-8 reboots I'm getting one connect. Now with the new update, I cannot activate the Bluetooth again.

Try doing "sudo ifconfig en0 down" and then "sudo ifconfig en0 up", helped my friend make his wifi work.

**Comment by shocker2** [comment]
> > > Hey, I have the same problem in my issue, my friend had it and he told me to download the newest alpha version compiled by Github Actions, there is a fixed enum. It fixed his problem and I'm currently checking if it works for me.
> > 
> > 
> > I keep updating it to the latest releases. Now I'm using the one released 3h ago and it's still not working. Usually every 5-8 reboots I'm getting one connect. Now with the new update, I cannot activate the Bluetooth again.
> 
> Try doing "sudo ifconfig en0 down" and then "sudo ifconfig en0 up", helped my friend make his wifi work.

Tried that and Bluetooth is now active but it cannot discover any new devices. Also, wifi is not connecting to any networks.

**Comment by M69W** [comment]
Could you upload the config.plist？

**Comment by shocker2** [comment]
> Could you upload the config.plist？
https://opencore.slowgeek.com/?file=amd063iyIRF4&rs=amd063

**Comment by M69W** [comment]
> > Could you upload the config.plist？
> > https://opencore.slowgeek.com/?file=amd063iyIRF4&rs=amd063

![image](https://user-images.githubusercontent.com/15809201/100348856-7f700080-3022-11eb-9633-04e7b47a024e.png)
something setting for Bluetooth don like that?

**Comment by shocker2** [comment]
> > > Could you upload the config.plist？
> > > https://opencore.slowgeek.com/?file=amd063iyIRF4&rs=amd063
> 
> ![image](https://user-images.githubusercontent.com/15809201/100348856-7f700080-3022-11eb-9633-04e7b47a024e.png)
> something setting for Bluetooth don like that?

![image](https://user-images.githubusercontent.com/24977727/100349333-f391b080-2ff0-11eb-9282-36d8c309df88.png)

What should I do about that?

**Comment by shocker2** [comment]
Tested with the c2f2c51 release and I have the same issues. 
- Bluetooth cannot be opened nor connect to any device.
- Wireless can detect networks but I'm unable to connect to them.

<img width="249" alt="Screenshot 2020-12-06 at 21 25 57" src="https://user-images.githubusercontent.com/24977727/101290250-a50ebe00-3809-11eb-9dce-7d846ddb7e97.png">

**Comment by Playragnarok** [comment]
posible working on higt sierra ?

**Comment by Importlif** [comment]
Same issue .But i found it works well under recovery mode.So wired!
[Log_2020-12-18_20-47-39.log](https://github.com/OpenIntelWireless/itlwm/files/5718915/Log_2020-12-18_20-47-39.log)

**Comment by williambj1** [comment]
Please consider reinstalling your system. From what I've observed, this issue doesn't seem be be related to this kext.
