### ISSUE TITLE
iPhone热点无法连接，有线和蓝牙都连不了，刚需功能亟待解决

### ISSUE THREAD

**Issue by lifsux** [OpenIntelWireless/itlwm#415]
iPhone热点无法连接

**Comment by Misaaya** [comment]
？

**Comment by llkhs** [comment]
乱几把开issues，你一点信息都没提供你让人家怎么帮你？

**Comment by lifsux** [comment]
装b？死全家



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: llkhs <notifications@github.com&gt;
发送时间: 2020年11月24日 15:19
收件人: OpenIntelWireless/itlwm <itlwm@noreply.github.com&gt;
抄送: lifsux <853956801@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[OpenIntelWireless/itlwm] iPhone热点无法连接，有线和蓝牙都连不了，刚需功能亟待解决 (#415)






乱几把开issues，你一点信息都没提供你让人家怎么帮你？

**Comment by lifsux** [comment]
airportitlwm最新版不能连接iPhone热点



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: bb2b2bb <notifications@github.com&gt;
发送时间: 2020年11月24日 14:50
收件人: OpenIntelWireless/itlwm <itlwm@noreply.github.com&gt;
抄送: lifsux <853956801@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[OpenIntelWireless/itlwm] iPhone热点无法连接，有线和蓝牙都连不了，刚需功能亟待解决 (#415)






？

**Comment by zxystd** [comment]
按格式来。
