### ISSUE TITLE
Intel® Dual Band Wireless-AC 3168 Wifi connection issue

### ISSUE THREAD

**Issue by borasumer** [OpenIntelWireless/itlwm#417]
**Have You Read Our Docs**
Yes
**Are You Reporting A Bug**
Yes

**Environment**

- Kext Version: 
Latest
- WiFi Card Model: 
Intel® Dual Band Wireless-AC 3168
- Product ID: 
- macOS Version: 

**Description**
When I turn the pc on, first 10 mins internet is not working and wifi is not connected. I try to connect the wifi, it does, but there is no connection. I turn wifi on and off couple of times and it starts working. Not sure this is a common behaviour, if not then that could be a bug for Big Sur.

**Bug Report Archive**

Can't go this address ?

**Kext Download Source**
This repo

**Comment by zxystd** [comment]
attach log please.

**Comment by PriNcEFuL** [comment]
I had same problem but using latest alpha version fix the problem... now it happens rarely once a week but fixes it self after a min or 2

**Comment by borasumer** [comment]
> I had same problem but using latest alpha version fix the problem... now it happens rarely once a week but fixes it self after a min or 2

Good to hear, I can update the kext with the alpha one then, thanks a bunch mate.

**Comment by borasumer** [comment]
Yes alpha version/v1.2.0-alpha solved my issue. Closing the issue.
