### ISSUE TITLE
Itlwm is not running

### ISSUE THREAD

**Issue by keyviet** [OpenIntelWireless/itlwm#420]
It works sometimes but sometimes it doesn't and I've tried forcing it into the kernel, forcing the IONetworking as well, I'm not sure what to do. It is the right version of itlwm for my card.
IntelBluetoothFirmware and IntelBluetoothInjector work just fine.

[HeliPort_logs.log](https://github.com/OpenIntelWireless/itlwm/files/5604285/HeliPort_logs.log)
[itlwm_logs.log](https://github.com/OpenIntelWireless/itlwm/files/5604286/itlwm_logs.log)

**Comment by williambj1** [comment]
Your card is in a bad state, make sure you have fast boot disabled and don't reboot directly from Windows. Closed since the issue format is invalid.
