### ISSUE TITLE
Itlwm is not running

### ISSUE THREAD

**Issue by keyviet** [OpenIntelWireless/itlwm#421]
**Have You Read Our Docs:**
Yes

**Are You Reporting A Bug:**
No, but rather an issue

**Environment:**

- **Kext Version:** itlwm stable 1.1.0
- **WiFi Card Model:** Intel(R) Wireless-AC 9260
- **Product ID:**
- **macOS Version:** 10.13.6 High Sierra

**Description:**
It worked a few times but now it doesn't at all. I've tried forcing it into the kernel, forcing the IONetworking as well, I'm not sure what to do. It is the right version of itlwm for my card.
IntelBluetoothFirmware and IntelBluetoothInjector work just fine.
All BIOS settings are correct. Did not reboot directly from Windows.
sudo kextstat | grep -i "itlwm" does not return anything at all.

**Bug Report Archive:**
[HeliPort 2020-11-26.zip](https://github.com/OpenIntelWireless/itlwm/files/5605349/HeliPort.2020-11-26.zip)

**Kext Download Source:**
Directly from this GitHub

**Comment by zxystd** [comment]
check PCI properties.
