### ISSUE TITLE
Wireless-AC 9560 [Jefferson Peak] 无线网卡无法正常工作

### ISSUE THREAD

**Issue by snowy2004** [OpenIntelWireless/itlwm#423]
**Have You Read Our Docs**

**Are You Reporting A Bug**

**Environment**

- Kext Version: all
- WiFi Card Model: Wireless-AC 9560 [Jefferson Peak] 
- Product ID: 0xA370
- macOS Version: 10.15.7

**Description**
itlwm加载日志里提示：kernel: (itlwm) itlwm: itlwm: failed to read nvm

日志文件及设备信息如下：
[Log_2020-11-28_07-08-24.log](https://github.com/OpenIntelWireless/itlwm/files/5608544/Log_2020-11-28_07-08-24.log)
[pcidevices.txt](https://github.com/OpenIntelWireless/itlwm/files/5608547/pcidevices.txt)

**Comment by win1010525** [comment]
所有版本都不行？

**Comment by snowy2004** [comment]
@win1010525 就是提示 itlwm: failed to read nvm 难道这个网卡有问题吗

**Comment by williambj1** [comment]
Remove extra PCI device properties in your config.
