### ISSUE TITLE
How to build the kexts?

### ISSUE THREAD

**Issue by MichaelDevC** [OpenIntelWireless/itlwm#425]
**Have You Read Our Docs**
Yes

**Are You Reporting A Bug**
No

**Environment**

- Kext Version: AirportItlwm latest [alpha]
- macOS Version: BigSur latest

**Description**

Hi, i want to know how to build the kexts so i can speed up the boot time of my hackintosh by deleting all other ITLWM firwmare expect witch of i want, so only one for my card...

I suggest the Itlwm team to add into them website a small guide on how to compile itlwm kexts and speed up their hackintosh

Thanks ;)

**Comment by win1010525** [comment]
Duplicate of #392

**Comment by win1010525** [comment]
Use MacKernelSDK

**Comment by MichaelDevC** [comment]
Oh sorry, i close it!
