### ISSUE TITLE
Wi-Fi doesn’t work

### ISSUE THREAD

**Issue by TheFailureOne** [OpenIntelWireless/itlwm#426]
I recently updated from Catalina to Big Sur (and from 0.6.0 to 0.6.3) and since installing it the Wi-Fi doesn’t work.
By selecting the Wi-Fi in the info.plist it works at random intervals. It works for like a few minutes then it stops working and viceversa.
Changing the Wi-Fi using HeliPort it just gives me an exclamation Mark ti then search for internet and give me the exclamation Mark again.
Everything worked in Catalina OC, but it doesn’t work in Big Sur.
Please help

**Comment by williambj1** [comment]
Invalid issue format
