### ISSUE TITLE
itlwm not running

### ISSUE THREAD

**Issue by youbois** [OpenIntelWireless/itlwm#427]
**Have You Read Our Docs**
yes

**Are You Reporting A Bug**
yes

**Environment**

- Kext Version: v1.0.1 latest
- WiFi Card Model: 7260
- Product ID: 0x08b2
- macOS Version: 10.13.6

**Description**
when ever i try to use heliport it gives me the itlwm not running error
[bugreport_57513.zip](https://github.com/OpenIntelWireless/itlwm/files/5611684/bugreport_57513.zip)

**Bug Report Archive**

**Kext Download Source**
github page

**Comment by williambj1** [comment]
Your bootloader config is incorrect

**Comment by youbois** [comment]
How do
