### ISSUE TITLE
Heliport: "Turn on Wi-Fi" doesn't work

### ISSUE THREAD

**Issue by Rixxx-git** [OpenIntelWireless/itlwm#429]
**Have You Read Our Docs**
Yes

**Are You Reporting A Bug**
Yes

**Environment**

- Kext Version: itlwm 1.1.0 & Heliport 1.0.1.
- WiFi Card Model: Intel Wireless 8265 / 8275
- Product ID: HP 830 G5 - OpenCore 0.63
- macOS Version: 11.0.1.

**Description**
Heliport: "Turn on Wi-Fi" doesn't work
I did a Network Preference reset like described in Troubleshooting
I did a NVRAM reset
I cleared and rebuilt Kext Cache

**Bug Report Archive**
[bugreport_52973.zip](https://github.com/OpenIntelWireless/itlwm/files/5612182/bugreport_52973.zip)

**Kext Download Source**
Downloaded the kext here: https://github.com/OpenIntelWireless/itlwm/releases

**Comment by williambj1** [comment]
> For me it was all running fine but then I did a BIOS update and some other changes to the EFI folder and now I am at the stage where it doesn't show any networks. Not with itlwm and heliport or with airportitlwm.

If it was working for you before, it is clearly not our issue, please check your hardware/bios/configs.

**Comment by labrouss** [comment]
With same device Id, I’ve got Airportitlwm working. Try Alpha version.

Kind regards,
Konstantinos

**Comment by Rixxx-git** [comment]
> With same device Id, I’ve got Airportitlwm working. Try Alpha version. Kind regards, Konstantinos
> […](#)
> On 29 Nov 2020, at 14:57, Rixxx-git ***@***.***> wrote: ﻿ Have You Read Our Docs Yes Are You Reporting A Bug Yes Environment Kext Version: itlwm 1.1.0 & Heliport 1.0.1. WiFi Card Model: Intel Wireless 8265 / 8275 Product ID: HP 830 G5 - OpenCore 0.63 macOS Version: 11.0.1. Description Heliport: "Turn on Wi-Fi" doesn't work I did a Network Preference reset like described in Troubleshooting I did a NVRAM reset I cleared and rebuilt Kext Cache Bug Report Archive bugreport_52973.zip Kext Download Source Downloaded the kext here: https://github.com/OpenIntelWireless/itlwm/releases — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

I tried that already. Which BIOS version do you use?
