### ISSUE TITLE
ac9560 Big Sur oc 6.3  AirportItlwm-Big_Sur-v1.2.0-DEBUG-alpha-aa2f1a7.zip

### ISSUE THREAD

**Issue by w550** [OpenIntelWireless/itlwm#430]
ac9560 Big Sur oc 6.3  AirportItlwm-Big_Sur-v1.2.0-DEBUG-alpha-aa2f1a7.zip
上传的时候会卡住
把20M的压缩包，上传内网云盘里面卡住了。

**Comment by williambj1** [comment]
Invalid issue format.
