### ISSUE TITLE
AirportItlwm stops working after sleep/wake - BigSur - AC9260 & AX200

### ISSUE THREAD

**Issue by hrytskivr** [OpenIntelWireless/itlwm#433]
**Have You Read Our Docs**
Yes

**Are You Reporting A Bug**
Yes

**Environment**
- Kext Version: AirportItlwm_v1.0_Beta_BigSur.kext
- WiFi Card Model: AC 9260
- Product ID: vendor: 0x8086, device: 0x2526
- macOS Version: 11.0.1

**Description**
AirportItlwm.kext works fine until I put my laptop to sleep. After wake it will take long time to connect to network, and even if it succeeds in connecting, it will say that there is no internet connection and won't work, after restart everything works again.

**Bug Report Archive**
[AirItlDebug_2020-11-30_11-21-49.zip](https://github.com/OpenIntelWireless/itlwm/files/5614983/AirItlDebug_2020-11-30_11-21-49.zip)

**Kext Download Source**
https://github.com/OpenIntelWireless/itlwm/releases/tag/v1.1.0

**Comment by zxystd** [comment]
Try pressing `DHCP` button in wifi network panel when awake. Not sure if it is a bug on Big Sur because someone had told me that real Mac also have this problem.

**Comment by hrytskivr** [comment]
@zxystd I don't see such button, only Renew DHCP Lease in advanced/tcpip. I haven't had this issue when using Fenvi BCM94360NG.

**Comment by hrytskivr** [comment]
@zxystd I've just noticed same behaviour on my ax200 on desktop computer. Big Sur also, same kexts.

**Comment by teabyii** [comment]
I also encountered the same problem. 
AX200, macOS 11.0.1, AirportItlwm-Big_Sur-v1.2.0-DEBUG-alpha-c2f2c51.zip

**Comment by meaverick** [comment]
I also encountered the same problem.
AX200, macOS 11.0.1,

**Comment by ThePonyZ** [comment]
我发觉尝试连接Wi-Fi后可以看到PHY模式先是802.11s，然后断开，重连换成802.11g，又断开，然后再连802.11n才能获取到IP，不知道是否与这个有关？

**Comment by dvrkoo** [comment]
I'm also having this issue on Big Sur on an intel ac 7260

**Comment by Litarvan** [comment]
I'm also having this issue on two completely different computers, one with Intel 9560, I don't know about the other one. But it seems that "Renew DHCP" sometimes fixes the issue after waiting for a bit, thanks @zxystd

**Comment by dvrkoo** [comment]
airportilwm 1.2.0 fixed the issue for me

**Comment by eric2877** [comment]
airporttwlwm 1.2.0 debug fix that problem for me too，but it still not stable, loss connection sometime in daily usage, I have to reconnect by hand.

**Comment by hrytskivr** [comment]
airportilwm 1.2.0 debug fixed that in a way for me, but when waking with that version wifi is altogether not working until manually off/on, then I can connect.

**Comment by wqhqq1** [comment]
I have the same problem on 1.3.0 ax200

**Comment by wqhqq1** [comment]
It's fixed now or you may have to check your USB settings in Hackintool.

**Comment by williambj1** [comment]
Feel free to post comments with log files if the same behavior still occurs in the latest release.

**Comment by KenDxD** [comment]
I currently experiencing this issue on my IntelAC3165 wifi card on monterey, after waking my laptop from sleep the wifi is not working. checking it on terminal it says inactive
