### ISSUE TITLE
您好，我在使用中发现Wi-Fi所显示的地区是zz而非是cn（我在中国）

### ISSUE THREAD

**Issue by Zhangxh1011** [OpenIntelWireless/itlwm#438]

**Comment by Zhangxh1011** [comment]
我和苦恼并且不知道该怎么修改这个地区。如果您知道可以怎样操作进行修改，麻烦您告诉我。 非常感谢！

**Comment by kyleh356** [comment]
add "itlwm_cc=CN" in boot-args

**Comment by Zhangxh1011** [comment]
> 在引导参数中添加“ itlwm_cc = CN”

非常感谢！

**Comment by Zhangxh1011** [comment]
Thank you very much



在 2020-12-03 10:49:16，"Kyle Hwang" <notifications@github.com> 写道：

add "itlwm_cc=CN" in boot-args
