### ISSUE TITLE
不知是否有计划增加对其他型号intel网卡的支持？

### ISSUE THREAD

**Issue by attend2016** [OpenIntelWireless/itlwm#445]
首先感谢作者的辛苦工作，让intel网卡也有了希望。

不过这个不是bug report，因为手头的intel网卡不在支持范围里，想咨询一下有没有计划加上其他型号的网卡。我的网卡型号如下：
Intel WiFi card

Vendor: 0x8086
Device: 0x0082
Sub Vendor: 0x8066
Sub Device: 0x1301
Vendor Name: Intel Corporation
Device name: Centrino Advanced-N 6205 (Taylor Peak)

当然没有计划也没关系，再次感谢。

**Comment by williambj1** [comment]
已在 alpha release 中支持
