### ISSUE TITLE
supports 5gh network

### ISSUE THREAD

**Issue by davideakadudu** [OpenIntelWireless/itlwm#449]
**Have You Read Our Docs**
Yes

**Are You Reporting A Bug**
Yes

**Environment**

- Kext Version: airportitlwm v1.2.0-alpha
- WiFi Card Model: Intel 8265 / 8275
- Product ID: 0x24FD
- macOS Version: 11.0.1

**Description**
When I connect the internet from Windows, it gives me with a speed test 400 mbps in download and 220mbps in upload, doing the same test with the same machine using hackintosh the speed test gives 30mbps in download and 7 in upload. why?  

**Bug Report Archive**

**Kext Download Source**

**Comment by ErrorErrorError** [comment]
Same as this issue. Please read docs. https://github.com/OpenIntelWireless/itlwm/issues/315
