### ISSUE TITLE
【AirportItlwm】ax200无线网卡能可以驱动，不能正常连接。  

### ISSUE THREAD

**Issue by LonelyDeShadow** [OpenIntelWireless/itlwm#450]
你好，我自己在台式机安装了 AX200无线网卡和 Big Sur 系统。
网卡可以正常驱动并可以搜索到网络，但是连接一个网络就会提示搜索不到网络或不断提示输入密码。
如果我把一个网络设置为首选项的话，每次开机，并重启一次，电脑可以连上那个首选网络。但如果网络断开后，又无法连接。
我尝试过 itlwm 驱动方式，这个是可以正常使用的。请问 AirportItlwm 的问题如何解决？

**Comment by metro2450** [comment]
我的AX200没有问题，你可以试试换最新的AirportItlwm-Big_Sur-v1.2.0-DEBUG-alpha kext

**Comment by williambj1** [comment]
Invalid issue format.
