### ISSUE TITLE
macOS compatibility

### ISSUE THREAD

**Issue by Drovosek01** [OpenIntelWireless/itlwm#451]
Hi. Could you specify on which versions of mac OS your kext can work?
And, it seems to me, in the description of your repositories you need to change the link to https://openintelwireless.github.io/

Thank you for your contribution to the development of Hackintosh!

**Comment by williambj1** [comment]
AirportItlwm: macOS 10.15 & 11
itlwm: macOS 10.12+

The link is correct, you have been directed because you are in a specific region in the world.
