### ISSUE TITLE
Airportitlwm just stops working after macOS was in sleep mode for a long time

### ISSUE THREAD

**Issue by GGorAA** [OpenIntelWireless/itlwm#455]
**Have You Read Our Docs**
True

**Are You Reporting A Bug**
True
**Environment**

- Kext Version: Latest (1.2.0)
- WiFi Card Model: 8260
- Product ID: idk what it is, but here are the screenshots from Hackintool:
![image](https://user-images.githubusercontent.com/61655029/102414551-6514bb80-3fff-11eb-96bb-3ff87f01cfa8.png)
![image](https://user-images.githubusercontent.com/61655029/102414518-5a5a2680-3fff-11eb-92f2-f71347d35505.png)

- macOS Version: Big Sur 11.0.1 (20B29)

**Description**

Airportitlwm probably crashes when macOS goes to sleep mode for 15 minutes and longer. It is pretty annoying, because I probably need to restart the whole Hackintosh to make this thing work again

**Comment by richardkindom** [comment]
Currently do not sleep if plugged into an AC. This works for me for most cases.

**Comment by williambj1** [comment]
You have unsupported device properties that enable ASPM, please remove it.
