### ISSUE TITLE
[AirportItlwm]大流量传输后掉线，第二次掉线后自己重连的时候无法DHCP到IP

### ISSUE THREAD

**Issue by Basstorm** [OpenIntelWireless/itlwm#458]
**Have You Read Our Docs**

yes
**Are You Reporting A Bug**

yes
**Environment**

- Kext Version: 最新的自编译9000固件alpha
- WiFi Card Model: 9560
- Product ID: a370
- macOS Version: 10.15.7

**Description**

如题，大流量传输（第一次百度网盘下载，第二次speedtest）
**Bug Report Archive**

[itlwmerrorlog.txt](https://github.com/OpenIntelWireless/itlwm/files/5719809/itlwmerrorlog.txt)

**Kext Download Source**

**Comment by williambj1** [comment]
CC @zxystd

**Comment by Basstorm** [comment]
最新的build，无此问题了
