### ISSUE TITLE
Handoff and Airdrop not work!

### ISSUE THREAD

**Issue by MichaelDevC** [OpenIntelWireless/itlwm#460]
Hi, my Intel Wi-Fi Cards is 8260AC
I'm using the latest AirportItlwm ALPHA Build with MacOS BigSur 11.1

I'm using the custom boot args: **`itlwm_cc=IT`** to use my country code IT-Italy

I have tried use Handoff with an Iphone 11 - Ipad Mini 2 - Mac Mini 2010 (all failed to work)

**Comment by labrouss** [comment]
Try to logout of iCloud on OS X and log in again. That solved the issue in my case
