### ISSUE TITLE
itlwm+heliport,无法开启Wi-Fi

### ISSUE THREAD

**Issue by AndyZoeng** [OpenIntelWireless/itlwm#461]
**Have You Read Our Docs**
Yes

**Are You Reporting A Bug**
Yes

**Environment**

- Kext Version: 1.2
- WiFi Card Model: intel 3165
- Product ID: 
- macOS Version: 10.15.5

**Description**

进入屏保后，唤醒失败，强制关机，开机后，无法开启Wi-Fi。

**Bug Report Archive**
[bugreport_37204.zip](https://github.com/OpenIntelWireless/itlwm/files/5722743/bugreport_37204.zip)

**Kext Download Source**

**Comment by williambj1** [comment]
Hardware issue, reboot from other OSes to repair.
