### ISSUE TITLE
itlwm is not running

### ISSUE THREAD

**Issue by raagk** [OpenIntelWireless/itlwm#463]
Hey I have intel AC 8265.
I tried to use itlwm.kext with Heliport and get itlwm is not running after opening Heliport.
Please note that he kext is loaded as seen in terminal 
![Screen Shot 2020-12-22 at 10 02 09 AM](https://user-images.githubusercontent.com/66343753/102849278-d360e000-443c-11eb-983d-ac3bcdc2c072.png)

Also, i tried to take up logs,
[itlwm.log](https://github.com/OpenIntelWireless/itlwm/files/5727799/itlwm.log)
[Log_2.log](https://github.com/OpenIntelWireless/itlwm/files/5727800/Log_2.log) (heliport).

Please tell me if I am doing something wrong, I am using OpenCore for kext injection.

**Comment by raagk** [comment]
Here is dimes log 
[Log_2020-12-22_10-25-10.log](https://github.com/OpenIntelWireless/itlwm/files/5728020/Log_2020-12-22_10-25-10.log)

**Comment by zxystd** [comment]
There is no log in your attachment and 8265 is confirmed to work. please fix your system/EFI first. I think it is not a driver issue. Thanks. BTW, can you provide your card's product id?

**Comment by raagk** [comment]
Hey! Thanks for taking up my issue.
Product ID:	0x8001
  Vendor ID:	0x8087  (Intel Corporation)
  Version:	0.03
  Speed:	Up to 480 Mb/s
  Location ID:	0x1d100000 / 1
  Current Available (mA):	500
  Current Required (mA):	0
  Extra Operating Current (mA):	0

**Comment by raagk** [comment]
Also, can you tell what possibly could cause this issue in EFI? I have checked drivers and config sanity checker. It seems fine!

**Comment by williambj1** [comment]
Sorry but EFI related issues are off topic. Please use other sources for personal help.

**Comment by raagk** [comment]
@williambj1 Is the Product ID or Vendor ID correct? My WiFi module is detected as USB Hub.
