### ISSUE TITLE
因为这个 机器自动黑屏重启了几次，希望能解决

### ISSUE THREAD

**Issue by xinshani** [OpenIntelWireless/itlwm#464]
panic(cpu 2 caller 0xffffff8019ed5c5e): "sta already removed"@/Users/qcwap/Desktop/github_project/itlwm/itlwm/hal_iwx/ItlIwx.cpp:4565
Backtrace (CPU 2), Frame : Return Address
0xffffffa0d80339f0 : 0xffffff8015eb9aed 
0xffffffa0d8033a40 : 0xffffff8015ffc6e3 
0xffffffa0d8033a80 : 0xffffff8015fecd1a 
0xffffffa0d8033ad0 : 0xffffff8015e5ea2f 
0xffffffa0d8033af0 : 0xffffff8015eb938d 
0xffffffa0d8033c10 : 0xffffff8015eb9678 
0xffffffa0d8033c80 : 0xffffff80166be3ca 
0xffffffa0d8033cf0 : 0xffffff8019ed5c5e 
0xffffffa0d8033d40 : 0xffffff8019ed8d4a 
0xffffffa0d8033dd0 : 0xffffff8019eda199 
0xffffffa0d8033e40 : 0xffffff8019e714ff 
0xffffffa0d8033fa0 : 0xffffff8015e5e13e 
      Kernel Extensions in backtrace:
         com.zxystd.AirportItlwm(1.0)[2D543230-3E24-3B3D-90B4-B6DEC3CBC5C0]@0xffffff8019e70000->0xffffff801a897fff
            dependency: com.apple.iokit.IO80211Family(1200.12.2b1)[ABB341FB-8D9E-344D-8032-AFB070B29023]@0xffffff801783f000->0xffffff8017978fff
            dependency: com.apple.iokit.IONetworkingFamily(3.4)[9178A2AA-EFFD-3DA3-86C3-08EFD4DAF005]@0xffffff8018593000->0xffffff80185a9fff
            dependency: com.apple.iokit.IOPCIFamily(2.9)[D0F1BFB8-C28E-3E70-891B-73B783189394]@0xffffff801882c000->0xffffff8018853fff

Process name corresponding to current thread: kernel_task
Boot args: agdpmod=pikera igfxfw=2 igfxonln=1 alcid=1 gfxrst=1 alcdelay=500 shikigva=80 chunklist-security-epoch=0 -chunklist-no-rev2-dev

Mac OS version:
20C69

Kernel version:
Darwin Kernel Version 20.2.0: Wed Dec  2 20:39:59 PST 2020; root:xnu-7195.60.75~1/RELEASE_X86_64
Kernel UUID: 82E2050C-5936-3D24-AD3B-EC4EC5C09E11
KernelCache slide: 0x0000000015c00000
KernelCache base:  0xffffff8015e00000
Kernel slide:      0x0000000015c10000
Kernel text base:  0xffffff8015e10000
__HIB  text base: 0xffffff8015d00000
System model name: iMac19,1 (Mac-AA95B1DDAB278B95)
System shutdown begun: NO
Panic diags file available: YES (0x0)
Hibernation exit count: 0

System uptime in nanoseconds: 3706182094125
Last Sleep:           absolute           base_tsc          base_nano
  Uptime  : 0x0000035ee9aacf8a
  Sleep   : 0x0000000000000000 0x0000000000000000 0x0000000000000000
  Wake    : 0x0000000000000000 0x00000008af953ab8 0x0000000000000000

**Comment by williambj1** [comment]
Please attach the panic with `keepsyms=1` and use the issue template.
