### ISSUE TITLE
AX200通过heilport能够搜索并连接但是无网络（AX200 can search and connect to WIFI through heilport but no network）

### ISSUE THREAD

**Issue by VioletLing** [OpenIntelWireless/itlwm#468]
![image](https://user-images.githubusercontent.com/50896903/103140198-e0245300-471e-11eb-8dac-a109fe4993c7.png)
安装好itlwm与heilport之后，能够正常搜索到wifi，也能够正常链接，在路由器内部能够看到设备已成功链接。但是Wi-Fi标志会显示为一个叹号（图中是因为使用了USB共享网络，然后Wi-Fi标志为正常），网络设备中也没有显示有新的设备，无法进行网络连接。
After installing itlwm and heilport, the wifi can be searched normally, and the connection can be normal. You can see that the device has been successfully connected inside the router. However, the Wi-Fi logo will be displayed as an exclamation mark (the figure is because the USB shared network is used, and the Wi-Fi logo is normal), and there is no new device displayed in the network device, and the network connection cannot be made.

**Comment by VioletLing** [comment]
[system.log](https://github.com/OpenIntelWireless/itlwm/files/5742273/system.log)

**Comment by jiaxin96** [comment]
问题解决了吗？
