### ISSUE TITLE
Bluetooth stops functioning when wifi enabled

### ISSUE THREAD

**Issue by Xodiced** [OpenIntelWireless/itlwm#469]
**Have You Read Our Docs**
Yes

**Are You Reporting A Bug**
YES

**Environment**
- Kext Version: 1.2.0
- WiFi Card Model: Intel Wireless-AC 7265 + Bluetooth 4.2
- Product ID: 
- macOS Version: 11.1

**Description**
When WiFi is enabled with the AirPort driver Bluetooth stops functioning.  The minute you toggle WiFi off Bluetooth devices work instantly again.

**Bug Report Archive**

**Kext Download Source**
Latest source from git, using release kext no debug.

**Comment by williambj1** [comment]
Invalid report

**Comment by Xodiced** [comment]
what exactly is invalid so I can correct what I did wrong?

**Comment by williambj1** [comment]
Missing logs, product id, and test results using the non-airport version.
