### ISSUE TITLE
Random Occurred “from  localizable.Strings ” After Boot Up

### ISSUE THREAD

**Issue by albert97chn** [OpenIntelWireless/itlwm#470]
It's not  occurred everytimes ，just reboot it can solve。
![iShot2020-12-18 23 24 21](https://user-images.githubusercontent.com/44337571/103204212-c3139e00-4931-11eb-9a37-20373ef7fbe1.jpg)
How to fix it

**Comment by williambj1** [comment]
Reset your network config. Instructions can be found in our docs.
