### ISSUE TITLE
Add Tx A-MPDU support for 2nd generation devices.

### ISSUE THREAD

**Issue by zxystd** [OpenIntelWireless/itlwm#475]
Tx A-MPDU can improve upload/download speed And future 11ac support should base on A-MPDU implementation.

**Comment by RGarrido03** [comment]
Hi! How cool, thank you!! I didn’t understand one thing: is AMPDU the 40MHz implementation? Even searching for this on Google won’t help me. Thanks!


________________________________

**Comment by williambj1** [comment]
They are not related, however, [this research paper](https://arxiv.org/ftp/arxiv/papers/1704/1704.07015.pdf) might help you understand some stuff.

**Comment by win1010525** [comment]
Crash on high-speed upload. It will disconnect immediately when upload speed is above 100Mbps.
