### ISSUE TITLE
The wifi is often disconnected, and devices connected to the same wifi lost connections at the same time

### ISSUE THREAD

**Issue by Creedowl** [OpenIntelWireless/itlwm#477]
**Have You Read Our Docs**

Yes
**Are You Reporting A Bug**

Yes
**Environment**

- Kext Version: itlwm: 1.2.0 beta fw: 34.0.1
- WiFi Card Model: Intel AC 8265
- Product ID: 0x24fd
- macOS Version: 11.0.1

**Description**

After installing the recent alpha version, I encountered this issue. The wifi connection dropped constantly, and all devices connected to the same wifi lost connections for seconds. This issue seems like to be related to #419
However, the issue seems only happened on my home wifi. When I connected to an open wifi, it works well

**Bug Report Archive**

The files are exported right after disconnection 

[AirItlDebug_2021-01-01_22-07-27.zip](https://github.com/OpenIntelWireless/itlwm/files/5759030/AirItlDebug_2021-01-01_22-07-27.zip)
[Log_2021-01-01_22-12-34.log](https://github.com/OpenIntelWireless/itlwm/files/5759031/Log_2021-01-01_22-12-34.log)

**Kext Download Source**

[kext](https://github.com/OpenIntelWireless/itlwm/releases/download/v1.2.0-alpha/AirportItlwm-Big_Sur-v1.2.0-DEBUG-alpha-e059314.zip)

**Comment by zxystd** [comment]
have you check the MTU setting size? should be equal or lower than the ISP setting.
maybe you can get it in router?
by the way, the log is incomplete, itlwm log should be contain inside. 
<img width="651" alt="image" src="https://user-images.githubusercontent.com/16227538/103452080-96330280-4d06-11eb-8617-b2ce210db161.png">

**Comment by Creedowl** [comment]
@zxystd I've set my MTU to 1492 (the same as what I got in router), and will check if it solves this issue. But this issue didn't occur before, just after updating to the newest airportItlwm recently.
BTW, I followed the [manual](https://openintelwireless.github.io/itlwm/Troubleshooting.html) to generate the log by running the following commands

```bash
bash <(curl -sL https://git.io/AirportItlDebug)

sudo dmesg | grep -i "itlwm" > ~/Desktop/Log_"$(date '+%Y-%m-%d_%H-%M-%S')".log

```

 Is it incomplete? What show I do to get full log?

**Comment by Creedowl** [comment]
The issue happened again
[AirItlDebug_2021-01-02_16-13-48.zip](https://github.com/OpenIntelWireless/itlwm/files/5759926/AirItlDebug_2021-01-02_16-13-48.zip)
[Log_2021-01-02_16-13-27.log](https://github.com/OpenIntelWireless/itlwm/files/5759927/Log_2021-01-02_16-13-27.log)

**Comment by savvamitrofanov** [comment]
Same problem, I guess something wrong with taskq

**Comment by paranoiagu** [comment]
I have the same issue.
here is the logs.
[logs.zip](https://github.com/OpenIntelWireless/itlwm/files/5779628/logs.zip)

**Comment by StefanChimu** [comment]
Same issue for me. Big Sur 11.1 with AC-8265 and latest itlwm-1.2.0 alpha.

**Comment by KrimskiyMaxim** [comment]
Same problem. 8265

**Comment by rhydianbevan** [comment]
I've also got the same issue

**Comment by VGerris** [comment]
I have the same issue with 1.2.0 on an AX201, it seems stable on 1.1.0.

**Comment by win1010525** [comment]
Does this still happen on the latest 1.3-alpha? I think it have been fixed.

**Comment by ildarnm** [comment]
Yes it happens on the latest 1.3-alpha

**Comment by williambj1** [comment]
@ildarnm Please attach logs generated by the latest alpha. Also it would be nice if you can provide logs from your router as well

**Comment by ildarnm** [comment]
Disconnects happen when I connected to a router at work. But it doesn't happen when I connected to a router at home.
[Report_2021-03-15_09-43-13.log](https://github.com/OpenIntelWireless/itlwm/files/6139282/Report_2021-03-15_09-43-13.log)

**Comment by ronelio** [comment]
This happen often. Humax and AC12G Router. Same problem here.

The 1.3-alpha version, I noticed that is little better but still it happens.

**Comment by ildarnm** [comment]
Additional info it happens each hour at 34 minutes

**Comment by williambj1** [comment]
Hi all, does the same behavior still occur when using the latest release?

**Comment by otalonym** [comment]
544.348151]: itlwm: setAWDL_SYNCHRONIZATION_CHANNEL_SEQUENCE
[  544.348155]: itlwm: dumpAWDLChannelSeqs length

**Comment by ildarnm** [comment]
I don't see this behavior anymore.

**Comment by VGerris** [comment]
Same here, seems ok now

**Comment by williambj1** [comment]
Thanks for the feedback.
