### ISSUE TITLE
AX200无线网卡和 Big Sur 系统，网卡可以正常驱动并可以搜索到网络，但是连接一个网络就会提示搜索不到网络或不断提示输入密码。

### ISSUE THREAD

**Issue by jiaxin96** [OpenIntelWireless/itlwm#478]
你好，我自己在台式机安装了 AX200无线网卡和 Big Sur 系统。
使用OC0.6.5
网卡可以正常驱动并可以搜索到网络，但是连接一个网络就会提示搜索不到网络或不断提示输入密码。
**Have You Read Our Docs**

**Are You Reporting A Bug**

**Environment**

- Kext Version: 
- WiFi Card Model: 
- Product ID: 
- macOS Version: 

**Description**

**Bug Report Archive**

**Kext Download Source**

**Comment by williambj1** [comment]
Invalid issue format.
