### ISSUE TITLE
7265AC蓝牙不能和WIFI一起用BUG反馈

### ISSUE THREAD

**Issue by zncs520** [OpenIntelWireless/itlwm#482]
我有2个机器(NUC8和GPD P2MAX)
NUC8的9560AC基本没有问题,  WIFI 和蓝牙都很完美(就是4.0的蓝牙鼠标连不上)

P2MAX的7265AC蓝牙不能和WIFI一起用
一起用的话蓝牙基本连不上外设(非常不稳定,容易断或者连不上)
关闭WIFI后, 蓝牙就正常了

**Comment by wqianglxf** [comment]
7265ac，这个蓝牙我也没有搞定，和你的情况差不多

**Comment by vimcaw** [comment]
修改一下加载顺序试一下：https://github.com/OpenIntelWireless/itlwm/issues/291

**Comment by klzbw** [comment]
Wi-Fi与蓝牙都2.4G,目前没什么好办法解决干扰问题！

**Comment by royatgh** [comment]
我是根本不显示蓝牙，wifi可用就是慢，（bluetoothinject/bluetoothFirmware/airportitlwm）顺序怎么调都是一样结果：看不到蓝牙。而且“log show --last boot | grep IntelFirmware”无日志。

Environment

Kext Version: AirportItlwm_v1.2.0_stable_BigSur.kext.zip
WiFi Card Model: Intel Dual Band Wireless AC 7265   （NUC5i7RYH原配Wi-Fi）
Product ID: 这个不知道怎么获取
macOS Version: BigSur 11.2.1

**Comment by win1010525** [comment]
> 我是根本不显示蓝牙，wifi可用就是慢，（bluetoothinject/bluetoothFirmware/airportitlwm）顺序怎么调都是一样结果：看不到蓝牙。而且“log show --last boot | grep IntelFirmware”无日志。
> 
> Environment
> 
> Kext Version: AirportItlwm_v1.2.0_stable_BigSur.kext.zip
> WiFi Card Model: Intel Dual Band Wireless AC 7265 （NUC5i7RYH原配Wi-Fi）
> Product ID: 这个不知道怎么获取
> macOS Version: BigSur 11.2.1

你是当时群里问我的那个人吗

**Comment by win1010525** [comment]
> > 我是根本不显示蓝牙，wifi可用就是慢，（bluetoothinject/bluetoothFirmware/airportitlwm）顺序怎么调都是一样结果：看不到蓝牙。而且“log show --last boot | grep IntelFirmware”无日志。
> > Environment
> > Kext Version: AirportItlwm_v1.2.0_stable_BigSur.kext.zip
> > WiFi Card Model: Intel Dual Band Wireless AC 7265 （NUC5i7RYH原配Wi-Fi）
> > Product ID: 这个不知道怎么获取
> > macOS Version: BigSur 11.2.1
> 
> 你是当时群里问我的那个人吗

如果是的话，你驱动根本没加载，自己调整efi设置
Your kext didn't load at all. Adjust your efi settings.

**Comment by win1010525** [comment]
> 我是根本不显示蓝牙，wifi可用就是慢，（bluetoothinject/bluetoothFirmware/airportitlwm）顺序怎么调都是一样结果：看不到蓝牙。而且“log show --last boot | grep IntelFirmware”无日志。
> 
> Environment
> 
> Kext Version: AirportItlwm_v1.2.0_stable_BigSur.kext.zip
> WiFi Card Model: Intel Dual Band Wireless AC 7265 （NUC5i7RYH原配Wi-Fi）
> Product ID: 这个不知道怎么获取
> macOS Version: BigSur 11.2.1

Sorry but that's not you. Wi-Fi performance low is a known issue. If there is no log for bluetooth, that means your kext didn't load at all. You can confirm it with `kextstat`.

**Comment by win1010525** [comment]
> 我有2个机器(NUC8和GPD P2MAX)
> NUC8的9560AC基本没有问题, WIFI 和蓝牙都很完美(就是4.0的蓝牙鼠标连不上)
> 
> P2MAX的7265AC蓝牙不能和WIFI一起用
> 一起用的话蓝牙基本连不上外设(非常不稳定,容易断或者连不上)
> 关闭WIFI后, 蓝牙就正常了

连不上外设是驱动的锅，已知了

**Comment by win1010525** [comment]
你可以买苹果的外设，能连上（🐶保命）

**Comment by xjy37-me** [comment]
The same boat. Bluethooth device can’t connect well on my 7265AC, ASUS Laptop, while it works fine when Wifi is off. I’ve tried different orders of Airportitwm & IntelBluethooth kexts but no sense.

**Comment by zxystd** [comment]
hmmm, I don't have this card... ac 7265/7260 have lots of variants, some works fine while others not, I don't know if I buy one of them can reproduce the issue.

**Comment by sirius-2** [comment]
同样的7265AC，买了免驱USB蓝牙在macOS BigSur上同样出现了这样的问题。即USB蓝牙能正常开关，但是连上后几秒断开。不确定是否是Airportitlwm自身的问题，以我的体验原生板载蓝牙适配更好至少能连上虽然不稳定听歌。供参考 @zxystd

**Comment by wqianglxf** [comment]
我现在用的是绿联USB蓝牙对应方案。可以正常用鼠标、耳机、键盘（罗技375每次要手动连）。内置的蓝牙和WIFI不能同时用，不然蓝牙连不上或者连上就掉线了。

**Comment by zxystd** [comment]
[ac7265.zip](https://github.com/OpenIntelWireless/itlwm/files/6853576/ac7265.zip)
Is there anyone have BT/WIFI coex problems with 7265 can help me to test? using the kext and see the firmware version.

**Comment by sirius-2** [comment]
笔记本可以吗，刚好有这个型号

**Comment by sirius-2** [comment]
Bluetooth Firmware Version : `8.4096`

AirportItlwm: `AirportItlwm_7265.kext`

Bluetooth Driver updated to the newest as 1.1.3.

![截屏2021-07-22 下午12 29 58](https://user-images.githubusercontent.com/38793146/126592374-084d3ac3-4857-47f9-80d9-20b0859f3760.png)

Status: Disconnection still appears after pair successfully.
[7265.log](https://github.com/OpenIntelWireless/itlwm/files/6860105/7265.log)

**Comment by sirius-2** [comment]
Bluetooth Firmware Version : `8.4096`

AirportItlwm: `AirportItlwm_7265.kext`

Bluetooth Driver updated to the newest as 1.1.3.

![截屏2021-07-22 下午12 29 58](https://user-images.githubusercontent.com/38793146/126592374-084d3ac3-4857-47f9-80d9-20b0859f3760.png)

Status: Disconnection still appears after pair successfully.
[7265.log](https://github.com/OpenIntelWireless/itlwm/files/6860105/7265.log)

**Comment by zxystd** [comment]
@sirius-2 Thanks, can you also capture the wifi info?

**Comment by sirius-2** [comment]
Absolutely, please **feel free** to ask for more details for debugging.
![截屏2021-07-22 下午3 18 32](https://user-images.githubusercontent.com/38793146/126602770-f688cfda-70fe-413d-8e27-98c7497e203d.png)

> No more useful info. for wifi list following.

**Comment by zxystd** [comment]
So your card variant is 7265D, before, we don't distinguish between 7265 and 7265D and they are using the same firmware, but yesterday I am doubting if the coex issue is related to the different firmware(I think there is some hardware bugs in 7265 variants, so Intel make different firmwares to them), so I change to code like before:
<img width="335" alt="image" src="https://user-images.githubusercontent.com/16227538/126605187-e0df60dc-a247-422a-a575-5fdfdb5a4fa7.png">
But according to your description it behave the same, still buggy.

**Comment by sirius-2** [comment]
The key point is to find out the right firmware for each of 7265 variants. Isn't it ? I don't have enough knowledge about how it works yet. So you just try it. 

Remind me if any problems or breakthrough process. Thanks for your work again !

**Comment by zxystd** [comment]
@sirius-2 Linux iwlwifi distinguish the firmwares, I don't know why OpenBSD code not doing this(but the newest code is changed), so I just have a try.
Another question, when did the Bluetooth not work? when the wifi is scanning? or connected?

**Comment by sirius-2** [comment]
@zxystd Whenever Wifi is turned off or not, bluetooth disconnects after several seconds as it sends pair request and paired successfully. Result just takes responsibility for test  of this time.
> [For reference](https://github.com/sirius-2/OpenCore-EFI-ASUS)

**Comment by zxystd** [comment]
[ac7265_enable_coex_flags.zip](https://github.com/OpenIntelWireless/itlwm/files/6867779/ac7265_enable_coex_flags.zip)
@sirius-2 How about this one?

**Comment by sirius-2** [comment]
> nvram reset done

Bluetooth Firmware Version : `8.4096`

![截屏2021-07-23 下午8 44 04](https://user-images.githubusercontent.com/38793146/126785195-a0668c23-1648-4a5a-8929-751888e4ec33.png)

![sfdf](https://user-images.githubusercontent.com/38793146/126785615-4039880e-d4ce-48e2-8407-01113787701a.png)

> Status: It seems last more time before disconnect that is  from 2-3 seconds to 4 seconds
[7265_1.log](https://github.com/OpenIntelWireless/itlwm/files/6868899/7265_1.log)

**Comment by sirius-2** [comment]
@zxystd Feel free to learn more details. 
> Status: It disconnects whenever wifi is turned on or not.

**Comment by zxystd** [comment]
[ac7265D_2.zip](https://github.com/OpenIntelWireless/itlwm/files/6869288/ac7265D_2.zip)
@sirius-2 please try this one.

**Comment by sirius-2** [comment]
@zxytsd Well, there is no change but log changes.
> Status: It disconnects after 4 seconds as connected.

[ac7265D_2.log](https://github.com/OpenIntelWireless/itlwm/files/6869726/ac7265D_2.log)

**Comment by wqianglxf** [comment]
我有台电脑和@zncs520 一样GPD P2 Max，7265AC的网卡。我用了最新的蓝牙和itlwm驱动，wifi可以正常使用，Airportitlwm无法热点。蓝牙可以搜索到设备，但无法正常连接上。连接后几秒后就会断开。
<img width="838" alt="截屏2021-07-24 14 07 38" src="https://user-images.githubusercontent.com/66858128/126859395-121272db-9de3-480e-9168-a7c1986d6340.png">
<img width="887" alt="截屏2021-07-24 14 07 59" src="https://user-images.githubusercontent.com/66858128/126859407-e956262c-d627-43e7-8495-8fe3b35db343.png">
[ac7265.log](https://github.com/OpenIntelWireless/itlwm/files/6871984/ac7265.log)

**Comment by melihcoban** [comment]
I am having the same issue in Thinkpad T440p with Intel(R) Dual Band Wireless-N 7260 wifi card. I can use the bluetooth and wifi together but there are stutters and choppy audio with my AirPods and sometimes sound drops randomly. However, when I close the WiFi Airpods works fine with the ethernet cable.

**Comment by zxystd** [comment]
@sirius-2 不介意的话麻烦加QQ群(1132224334)帮忙测试ac7265的问题，目前群里没有找到有跟你遇到一样问题的人。

**Comment by rboldini** [comment]
With latest Alphas and 7265AC, bluetooth has the same problem.
AirPods and ZK606(low budget speaker ) work but at a ridiculous distance from my laptop, like (for AirPods less than) ~ 4-5cm.
Try to cover proximity sensors on your AirPods and then bring them close to the laptop near the WiFi card, they will ring.

![Screen Shot 2021-08-03 at 22 47 54](https://user-images.githubusercontent.com/51327886/128086299-b11e127c-4d87-4090-bb7c-a3fbeba356b4.png)
![Screen Shot 2021-08-03 at 22 48 15](https://user-images.githubusercontent.com/51327886/128086367-f67d3bfe-7336-4ba6-91d8-9c8394f24c7a.png)
![Screen Shot 2021-08-03 at 23 14 37](https://user-images.githubusercontent.com/51327886/128087338-b7ee7e45-d4bb-49d3-a550-28eea7bb5496.png)

**Comment by singhalrishi27** [comment]
Issue is quite similar on wireless ac  7260 As well while Bluetooth and wifi works at the same time but audio gets stuttered Every now and then

**Comment by williambj1** [comment]
Chinese discussion moved to QQ, English discussion can be continued in #692
