### ISSUE TITLE
频繁掉线 fatal firmware error

### ISSUE THREAD

**Issue by Basstorm** [OpenIntelWireless/itlwm#483]
**Have You Read Our Docs**

Yes
**Are You Reporting A Bug**

Yes
**Environment**

- Kext Version: latest
- WiFi Card Model: ac9560
- Product ID: a370
- macOS Version: 10.15.7

**Description**

如题，路由器是k2p，之前在宿舍是Redmi AX6 无此问题，放假回来之后家里的是k2p。无大流量传输操作，甚至没怎么动，十分钟之内掉线四五次，掉线后会快速重连。
**Bug Report Archive**
[fatalerror.log](https://github.com/OpenIntelWireless/itlwm/files/5781746/fatalerror.log)

**Kext Download Source**

**Comment by zxystd** [comment]
可以看一下你的路由器设置么？

**Comment by Basstorm** [comment]
![image](https://user-images.githubusercontent.com/37471354/103898834-806f7400-5130-11eb-8201-2e0bbf87c1d4.png)

**Comment by Creedowl** [comment]
同一个问题 #477

**Comment by zxystd** [comment]
1.1.0的版本就不会是吧？

**Comment by Basstorm** [comment]
没试过1.1.0，我去测试一下

**Comment by zxystd** [comment]
内测体验群：1132224334

**Comment by Creedowl** [comment]
@zxystd 我在最近几个alpha版更新后出现的这个问题，之前一直跟随最新alpha版都是正常的

**Comment by Basstorm** [comment]
> 1132224334

找不到这个群

**Comment by Basstorm** [comment]
> 1.1.0的版本就不会是吧？

目前看来1.1.0很稳定，没这个情况

**Comment by williambj1** [comment]
@Basstorm 尝试一下这个版本

**Comment by Basstorm** [comment]
> @Basstorm 尝试一下这个版本 [5cb203e](https://github.com/OpenIntelWireless/itlwm/commit/5cb203e49b2ae5a69cc8453cf4ea510ddb8b0b57)
> 
> [5cb203e.zip](https://github.com/OpenIntelWireless/itlwm/files/5782018/5cb203e.zip)

这个版本也没问题

**Comment by zxystd** [comment]
现在可以搜索到群了。

**Comment by paranoiagu** [comment]
> 1.1.0的版本就不会是吧？

大概1个月前的1.2.0版本也也不会。

**Comment by liuzhaobo1999** [comment]
> > 1.1.0的版本就不会是吧？
> 
> 目前看来1.1.0很稳定，没这个情况

弱弱的问下，是如何做到随意切换版本的？@Basstorm

**Comment by Basstorm** [comment]
> > > 1.1.0的版本就不会是吧？
> > 
> > 目前看来1.1.0很稳定，没这个情况
> 
> 弱弱的问下，是如何做到随意切换版本的？@Basstorm

下不同版本efi重启就行了

**Comment by williambj1** [comment]
Discussion continued in QQ

**Comment by win1010525** [comment]
QQ is prohibited
![782307F244BE1310237F2FDC64D42682](https://user-images.githubusercontent.com/50404193/109144161-ca252400-779b-11eb-90de-d8257effb3d9.gif)
