### ISSUE TITLE
itlwm与vmvare fusion冲突，占用vmvare虚拟网卡名称

### ISSUE THREAD

**Issue by HiMetre** [OpenIntelWireless/itlwm#484]
**Have You Read Our Docs** 
Yes

**Are You Reporting A Bug** 
Yes

**Environment**

- Kext Version: v1.1.0 stable
- WiFi Card Model: AX200
- Product ID: unknow
- macOS Version: 11.1

**Description**
itlwm与vmvare冲突，占用vmvare虚拟网卡名称，导致vmware网络(共享网络)无法使用。理论上网卡名称应该是 Ethernet3的。
<img width="668" alt="Snipaste_2021-01-07_11-27-55" src="https://user-images.githubusercontent.com/2725742/103994979-bc5b1580-51d2-11eb-8278-23148f1664df.png">

<img width="351" alt="Screenshot 2020-11-15 at 11 06 49" src="https://user-images.githubusercontent.com/2725742/103995217-22e03380-51d3-11eb-901d-307d3da3436a.png">

**Bug Report Archive**
暂时删除了itlwm,无法生成

**Kext Download Source**
https://github.com/OpenIntelWireless/itlwm/releases/tag/v1.1.0

**Comment by williambj1** [comment]
Reset your network interface preferences, instructions can be found in our docs.
