### ISSUE TITLE
ax200 在系统10.15.4下速率只有140 

### ISSUE THREAD

**Issue by libra1010** [OpenIntelWireless/itlwm#486]
Thinkpad T480S使用clover安装黑苹果系统10.15.4
AX200网卡驱动成功，但是连接速率只有140
是所有AX200都只有140速率吗？

**Comment by williambj1** [comment]
802.11n 20MHz

The value is correct

**Comment by libra1010** [comment]
@williambj1  意思是现在还不支持 802.11.ax 是吧？ 谢谢
