### ISSUE TITLE
Can you force a 5GHz connection?

### ISSUE THREAD

**Issue by satyrnhub** [OpenIntelWireless/itlwm#487]
Title says all.

**Comment by williambj1** [comment]
Yes, but you ***must*** disable `band steering` on your router.

itlwm chooses the band automatically; if the RSSI value of the 5GHz band is lower than approximately -70dBm, it will switch to 2GHz

https://github.com/OpenIntelWireless/itlwm/blob/040a5e8ba7ef86e98feb57ac85bd4c47a7347075/itl80211/openbsd/net80211/ieee80211_node.c#L1359-L1380

**Comment by satyrnhub** [comment]
Ok, thanks!
