### ISSUE TITLE
Charles,Proxyman等抓包软件和iPhone或者Android手机连接不上

### ISSUE THREAD

**Issue by liuzhaobo1999** [OpenIntelWireless/itlwm#490]
Have You Read Our Docs
Yes

Are You Reporting A Bug
Yes

Environment

- OpenCore0.6.1
- Kext Version: itlwm 1.1.0 stable / 1.2.0
- WiFi Card Model: intel AX200
- macOS Version: 10.15.7

Description
如题，使用Charles抓包手机时，同一个Wi-Fi下，手机设置电脑的IP代理后，手机的网络连接就不能使用了

**Comment by liuzhaobo1999** [comment]
Charles设置和手机代理设置没问题，已经使用USB-RJ45网线测试正常

**Comment by zxystd** [comment]
<img width="900" alt="image" src="https://user-images.githubusercontent.com/16227538/104428101-02431f80-55bf-11eb-866c-e9ded1fd53e1.png">
有图有真相，先自己找找原因吧。
