### ISSUE TITLE
Hotspot support

### ISSUE THREAD

**Issue by MichaelDevC** [OpenIntelWireless/itlwm#491]
**Have You Read Our Docs**
Yes

**Are You Reporting A Bug**
No

**Environment**

- Kext Version: v1.2.0-alpha
- WiFi Card Model: AC 8260
- Product ID: 0x24f4
- macOS Version: MacOS BigSur 11.1

**Description**

I can't use iPhone Hotspot... i read in the docs that is not compatible yet, but i'm opening that issue to ask developers to add that feature as soon as possible!
I'm here to test and help developers with Hotspot support development!
Thanks

**Bug Report Archive**

[Report_2021-01-13_08-59-01.log](https://github.com/OpenIntelWireless/itlwm/files/5807211/Report_2021-01-13_08-59-01.log)

**Kext Download Source**

AiportItlwm v1.2.0-alpha#9cc2c4e

**Comment by lgariv** [comment]
It works fine for me...

Catalina (latest), AirportItlwm, AC-9462 gen 1 (same firmware as 9560).

Note that for _automatic_ hotspot, you need to have both Bluetooth and WiFi turned on on both of your devices.

**Comment by Sansyyxd** [comment]
![image](https://user-images.githubusercontent.com/24302674/104454492-d6fc0880-559d-11eb-8271-13480747a020.png)
Is this the error you also get?

**Comment by MichaelDevC** [comment]
That's my setup!

iPhone 11

Bluetooth and Wi-Fi enabled on my hackintosh...

![photo_2021-01-13 14 52 25](https://user-images.githubusercontent.com/57275048/104461108-2a2a8700-55af-11eb-93a7-8377662620a7.jpeg)
![Schermata 2021-01-13 alle 14 50 48](https://user-images.githubusercontent.com/57275048/104461111-2ac31d80-55af-11eb-8cd3-8b51c9b45a66.png)
![Schermata 2021-01-13 alle 14 51 24](https://user-images.githubusercontent.com/57275048/104461118-2c8ce100-55af-11eb-9403-5b6f0cbe30b4.png)

**Comment by Sansyyxd** [comment]
yeah having some issue on Catalina I guess it just doesn't have support yet

**Comment by labrouss** [comment]
Well there is always the alternative of using the usb cable to share internet ... just saying ...

**Comment by MichaelDevC** [comment]
> Well there is always the alternative of using the usb cable to share internet ... just saying ...
> […](#)
> On 13 Jan 2021, at 17:08, Sansyy ***@***.***> wrote: ﻿ yeah having some issue on Catalina I guess it just doesn't have support yet — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.


Yes... but wireless sharing is better!

I open that issue to help and ask developers to add that feature ;)

**Comment by MichaelDevC** [comment]
> yeah having some issue on Catalina I guess it just doesn't have support yet

Also for me on MacOS BigSur

**Comment by williambj1** [comment]
Someone posted a solution in Chinese #310, maybe it will help you.

**Comment by MichaelDevC** [comment]
Yes, sometimes this works for me, but isn't stable and when i need that (when i'm not at home) is very intricate

**Comment by williambj1** [comment]
I guess the best way to solve your issue right now is to use HeliPort with itlwm instead of AirportItlwm before we have a deeper understanding of Instant Hotspot's mechanism.

**Comment by MichaelDevC** [comment]
> I guess the best way to solve your issue right now is to use HeliPort with itlwm instead of AirportItlwm before we have a deeper understanding of Instant Hotspot's mechanism.

Thanks I know that!

Leave issue open so that feature can be added in the next v1.3.0 AiportItlwm

**Comment by MichaelDevC** [comment]
Can we mark that as a feature request?

**Comment by williambj1** [comment]
I guess this could be part of #292
