### ISSUE TITLE
MacOs 11.1 - Wi-Fi Scans and Finds Other Networks but Does Not Connect and Experiencing Kernel Panics When Forcing IO8211 Family

### ISSUE THREAD

**Issue by phanuelmutuma** [OpenIntelWireless/itlwm#496]
**Have You Read Our Docs**
Yes

**Are You Reporting A Bug**
Yes

**Environment**

- Kext Version: 1.2.0
- WiFi Card Model: AC 7650
- Product ID: 
- macOS Version: 11.1

**Description**
Cannot Connect to Wifi and everytime I try to it freezes or mostly doesn't respond even after typing the correct passcode. Sometimes it does connect but disconnects after a minute or two

**Bug Report Archive**

**Kext Download Source**

**Comment by williambj1** [comment]
Please treat this bug report seriously and fill in all the required blanks as I am assuming you are disrespecting developers and wasting their time.
