### ISSUE TITLE
Set "itlwm_cc=COUNTRY_CODE" into properties of WLAN/WIFI device in Config.plist or DSDT/SSDT

### ISSUE THREAD

**Issue by andreszerocross** [OpenIntelWireless/itlwm#498]
Can we set this BootArgument to Properties of WLAN / Wifi device in Config.plist, DSDT or SSDT?? Like CountryCode in AirportBRCMFixUp>

Thank you

**Comment by zxystd** [comment]
No, we don't want to rely on the type of bootloader, it can also run on a real Mac.
