### ISSUE TITLE
用1.2.0的AirportItlwm，type-c扩展坞接的网线不能用了，设置里边也没有扩展坞的网卡信息。

### ISSUE THREAD

**Issue by iwsbiwy** [OpenIntelWireless/itlwm#501]
机型：`小新pro13-2020`
网卡：`ax201`
设置里边也没有扩展坞的网卡信息。之前的1.1.0没有这个问题。Wifi是正常的。

**Comment by williambj1** [comment]
Follow our documentation and reset your network interface preferences.

**Comment by itendtostare** [comment]
this is my same issue, did you find a solution @iwsbiwy ?
