### ISSUE TITLE
下载速度问题

### ISSUE THREAD

**Issue by Toyide** [OpenIntelWireless/itlwm#503]
感谢大佬的辛苦工作！
汇报一个情况
新版stable 1.2 和 1.3速度（下载40mbps， ping 40）
都不如12月26号下载的1.2测试版本快（下载100mbps， ping 1）
系统11.1 BigSur网卡是 AC9560 （CNVi 802.11ac 2x2 Wave 2 Wi-Fi）
*但12月26号1.2测试版本有偶尔断链情况

**Comment by williambj1** [comment]
Tx aggregation support was reverted, please wait for future commits.
