### ISSUE TITLE
AX1650X在BIG SUR上面显示已连接，但是每八分钟断流一次。

### ISSUE THREAD

**Issue by AdamYoung66** [OpenIntelWireless/itlwm#504]
AX1650X在BIG SUR上面显示已连接，但是每八分钟断流一次。无论是5G还是2.4G都一样断流，但是切换一下又能正常使用，能正常使用的时间大概是八分钟，过了八分钟就会显示连接 但是无法使用。 刚安装上的时候还有自动关闭wifi 打开wifi开关，但不能连接使用的无限循环，后经过24日更新修复，请问断流问题是否有解，还是就AX1650X不行？

**Comment by AdamYoung66** [comment]
使用版本是heliport+itlwm1.3.0

**Comment by williambj1** [comment]
Will reopen once the template is properly filled
