### ISSUE TITLE
wifi热点

### ISSUE THREAD

**Issue by daxiewang** [OpenIntelWireless/itlwm#506]
我用了itlwm和heliport，可以正常使用wifi，信号也挺好的，不过我就是想问一下，我发现在我互联网共享里面找不到wifi选项，我是想试一下能不能开wifi热点，现在好像开不了wifi热点，这是我系统的问题吗
**Have You Read Our Docs**

**Are You Reporting A Bug**

**Environment**

- Kext Version: 
- WiFi Card Model: 
- Product ID: 
- macOS Version: 

**Description**

**Bug Report Archive**

**Kext Download Source**

**Comment by williambj1** [comment]
Unsupported, read the docs for more info
