### ISSUE TITLE
802.11ax Support/优先适配802.11ax

### ISSUE THREAD

**Issue by wqhqq1** [OpenIntelWireless/itlwm#510]
**Are You Reporting A Bug**
No

**Environment**

- Kext Version: 1.3 alpha
- WiFi Card Model: ax200
- macOS Version: macOS 11.4

**Description**
希望先进行802.11ax适配，感觉三代卡可以再等等，速度更加重要

**Comment by williambj1** [comment]
Feel free to submit pull requests
