### ISSUE TITLE
AX200 Stop Working after wake from sleep state/睡眠唤醒后AX200停止工作

### ISSUE THREAD

**Issue by wqhqq1** [OpenIntelWireless/itlwm#511]
**Have You Read Our Docs**
Yes

**Are You Reporting A Bug**
Yes

**Environment**

- Kext Version:  1.3.0(commit 90b14a4b3ceb8a051223fb2b9e605c8c127092be)
- WiFi Card Model: AX200
- Product ID: 0x2723
- macOS Version: 11.4

**Description**
After wake from sleep state, both wifi and Bluetooth stops working/睡眠唤醒后，Wi-Fi和蓝牙都停止工作

**Kext Download Source**
Github Release

**Comment by williambj1** [comment]
No logs
