### ISSUE TITLE
Application starts with a low speed when wifi is connecting

### ISSUE THREAD

**Issue by ProbabilityA** [OpenIntelWireless/itlwm#515]
**Have You Read Our Docs**

Yes

**Are You Reporting A Bug**

Yes

**Environment**

- Kext Version: AirportItlwm_v1.2.0_stable_Catalina.kext
- WiFi Card Model: AC9560
- Product ID: Not Sure
- macOS Version: 10.15.7

**Description**

Wifi is working correctly. But all applications starts with very low speed when wifi is connecting, the icons of application just jump under the dock all the time. When I turn off wifi or disconnecting wifi, applications immediately load and the main interface appears.

**Bug Report Archive**

i can't open that website

**Kext Download Source**

Github releases

**Comment by williambj1** [comment]
Whenever you launch an app when you are connected to the Internet, macOS will access `ocsp.apple.com` to validate that app. Thus your application launch speed depends on the network quality between your device and Apple's server. There is really nothing related to this kext. Closing as off-topic.
