### ISSUE TITLE
隐藏的Wi-Fi不能使用，自己添加网络名称，和密码也不能链接，

### ISSUE THREAD

**Issue by QQ911air** [OpenIntelWireless/itlwm#517]
**Have You Read Our Docs**

**Are You Reporting A Bug**

**Environment**

- Kext Version: 
- WiFi Card Model: 
- Product ID: 
- macOS Version: 

**Description**

**Bug Report Archive**

**Kext Download Source**

**Comment by win1010525** [comment]
Invalid issue format.

**Comment by win1010525** [comment]
Duplicate of #294

**Comment by win1010525** [comment]
@williambj1
