### ISSUE TITLE
ax200网络不稳定，频繁闪断

### ISSUE THREAD

**Issue by lcg2015** [OpenIntelWireless/itlwm#518]
驱动版本1.20
intel ax200
同一台机器，win10下没有问题，mac下速度下降到win10的1/10,使用pip等安装稍大的包经常超时，怀疑频繁断开连接。

[Log_2021-02-03_14-46-49.log](https://github.com/OpenIntelWireless/itlwm/files/5916624/Log_2021-02-03_14-46-49.log)

**Comment by dawn-cgj** [comment]
我也是AX200，速率能到30M左右，大概十分钟断一次，需要开关一下WiFi

**Comment by win1010525** [comment]
Invalid

**Comment by win1010525** [comment]
https://docs.oiw.workers.dev/itlwm/FAQ.html

**Comment by win1010525** [comment]
Performance sucks has been written down in doc.

**Comment by mahoshojoHCG** [comment]
我用的也是AX200，之前用的1.2.0的正式版。遇到这个问题之后试着更新使用1.3.0的测试版，问题似乎就解决了。

**Comment by shasen1235** [comment]
Probably Big Sur is the one to blame. I have disconnect, DHCP refresh problems and so on.
But my same AX200 works perfectly fine on Catalina and Mojave.

**Comment by MicalShow** [comment]
同AX200，网速很猛，最新的测试版基本能跑满200m宽带了，峰值能到233m，就是断流有点频繁，希望修复

**Comment by hexiosr** [comment]
ax201,也有这个问题

**Comment by M69W** [comment]
建议把系统版本，哪个驱动以及版本等信息描述一下

**Comment by hexiosr** [comment]
> 建议把系统版本，哪个驱动以及版本等信息描述一下
电脑：xiaoxin 13 pro 2020
网卡：AX201
系统版本：bigsur11.2.2 
驱动：AirportItlwm v1.3.0 alpha
大概10分钟内会断开网络，但是WiFi还处于连接状态

**Comment by thep0y** [comment]
> 我用的也是AX200，之前用的1.2.0的正式版。遇到这个问题之后试着更新使用1.3.0的测试版，问题似乎就解决了。

请问你在上传文件时速度正常马？我这边用speedtest跑的时候上行是30M，但是真正传文件时，只有几十K的速度

**Comment by thep0y** [comment]
> 同AX200，网速很猛，最新的测试版基本能跑满200m宽带了，峰值能到233m，就是断流有点频繁，希望修复

你好，我也同ax200，300M的宽带只能跑到130M左右，请问你用的是哪个版本的驱动，用的系统版本是什么

**Comment by williambj1** [comment]
Feel free to post comments if the same behavior still occurs in the latest release.
