### ISSUE TITLE
Itlwm does not work after sleep

### ISSUE THREAD

**Issue by lilov-zz** [OpenIntelWireless/itlwm#519]
I am using Mojave 10.14.6 on an HP Elitebook 830 G5. The wifi card is Intel Ac 8265. I am using latest kext 1.2.0. and Heliport.
The issue is after sleep Heliport WiFi icon is empty and turn wifi on does not work. Same thing happens when I manually turn WIFi off, there is no way to put it manually back on.  Only restart fixes it.
I have read previous threads and tried Itlwmx from previous issues but it does not work.

**Comment by lilov-zz** [comment]
[log.txt](https://github.com/OpenIntelWireless/itlwm/files/5920614/log.txt)

**Comment by williambj1** [comment]
No itlwm logs. Please follow the instructions in the docs.

**Comment by lilov-zz** [comment]
Trying to export log from Heliport but I get this. I am sorry, I am new to this can you tell me how to get the log out?
![Uploading Screenshot 2021-02-04 at 11.29.56.png…]()

**Comment by lilov-zz** [comment]
Trying to export log from Heliport but I get this. I am new to this can you help how to bypass this error
![Screenshot 2021-02-04 at 11 29 56](https://user-images.githubusercontent.com/5635676/106874090-d7d81400-66dd-11eb-9566-902dee4543ce.png)

**Comment by lilov-zz** [comment]
I think I have managed to do it :-)
[Log_2021-02-04_19-38-42.log](https://github.com/OpenIntelWireless/itlwm/files/5927524/Log_2021-02-04_19-38-42.log)

**Comment by williambj1** [comment]
Try toggling wifi off and on

**Comment by lilov-zz** [comment]
Same thing, been trying this for the last two days.

**Comment by lilov-zz** [comment]
Problem is sleep, I can turn wifi on and off when working normally but after sleep Itlwm does not wake.

**Comment by williambj1** [comment]
Did you add `msgbuf=1048576` to boot-args? A lot of logs are missing.

**Comment by lilov-zz** [comment]
Hi, you are correct. I have now added it and enclose the updated log taken after sleep and being unable to turn wifi ON.
[Log_2021-02-10_15-17-10.log](https://github.com/OpenIntelWireless/itlwm/files/5958435/Log_2021-02-10_15-17-10.log)
If i can do anything else let me know.

**Comment by Qiangong2** [comment]
I'm having the same issue on big sur with my AC 9462

**Comment by win1010525** [comment]
@williambj1 have you seen the latest provided log?

**Comment by afzl-wtu** [comment]
working fine on intel 6205 except i have to turn of and then On it, and it connects again

**Comment by lilov-zz** [comment]
I do not have the option to turn it off, after sleep Heliport state/ itlwm is OFF and I can only try to turn it on, but with no success regardless of how many tries I attempt.

**Comment by zxystd** [comment]
can you try the latest alpha release.

**Comment by lilov-zz** [comment]
Same thing, enclosed is the new log with the alpha 1.30
[Log_2021-03-07_20-15-57.log](https://github.com/OpenIntelWireless/itlwm/files/6097721/Log_2021-03-07_20-15-57.log)

**Comment by williambj1** [comment]
Looks like your card is operating with PCI ASPM L1 mode, itlwm does not support ASPM ATM. Make sure you did not inject invalid ASPM values in device properties / _DSM, etc.

**Comment by lilov-zz** [comment]
I am afraid you got me here. Do not know what to do and no nelpful Google search found. If not too much trouble can you tell me what and where to look for ? Thanks.

**Comment by GGorAA** [comment]
same issue on HP EliteBook 840 G3 with Intel Wireless 8260

**Comment by hectorox** [comment]
same here with Intel Wireless-N 7260

**Comment by adeg** [comment]
I have the same issue with Intel® Wi-Fi 6 AX201. Using the alpha AirportItlwm-Big Sur build from 2021-03-10.

**Comment by zeyugao** [comment]
Same issue with AC 8265 in Big Sur using AirportItlwm

[Report_2021-03-21_19-07-05.log](https://github.com/OpenIntelWireless/itlwm/files/6177271/Report_2021-03-21_19-07-05.log)

**Comment by Nels2** [comment]
same as hectorox

**Comment by ubun222** [comment]
nuc8在关闭或者睡眠后AirPlay不能用然后会断连，开机第一次连接上Wi-Fi是没问题的

**Comment by GGorAA** [comment]
UPDATE: latest 1.3.0 fixed dis issue, now WiFi works even after going to sleep

**Comment by lilov-zz** [comment]
@GGorAA Hi, you mean the 1.3.0 alpha? I am running it but nothing changes. Are you using any specific options?

**Comment by GGorAA** [comment]
> @GGorAA Hi, you mean the 1.3.0 alpha? I am running it but nothing changes. Are you using any specific options?

Yes, i mean 1.3.0. And also i'm not using any specific options other than Airportitlwm explicitly needs (everything is in the docs)

**Comment by karelo911** [comment]
Same problem on same card. Tried itlwm version 2 alpha. I can't turn on wifi after I turn it off, either manually or through sleep.
[bugreport_30678.zip](https://github.com/OpenIntelWireless/itlwm/files/6948614/bugreport_30678.zip)

**Comment by williambj1** [comment]
@lilov-zz Hi! Have you tried the latest alpha? What about the ASPM related configs? Thanks.

@karelo911 The log file does not contain any errors or signs of sleeping / toggling on and off.

**Comment by SesshomaruVN** [comment]
Hi, I am using AX 201 wifi card. My problem as the same this thread issue. I have read some thread issue at Issuses tab. And try to config aspm = 0 for my wifi card in devices tree. But, wifi still not working after sleep.
I am using this kext [AirportItlwm-Big_Sur-v2.1.0-DEBUG-alpha-3ee6b6a.zip](https://github.com/OpenIntelWireless/itlwm/releases/download/v2.1.0-alpha/AirportItlwm-Big_Sur-v2.1.0-DEBUG-alpha-3ee6b6a.zip)
![Screen Shot 2021-12-01 at 06 37 54](https://user-images.githubusercontent.com/89727677/144145344-e36c2cd9-0d38-41b2-a82c-17a95c73b193.png)
This is aspm config.
And here is the log of itlwm after boot (wifi work well}
[Log_2021-12-01_06-30-08.log](https://github.com/OpenIntelWireless/itlwm/files/7629565/Log_2021-12-01_06-30-08.log) 
And here is the log after sleep (can't find any network name)
[Log_2021-12-01_06-31-16.log](https://github.com/OpenIntelWireless/itlwm/files/7629566/Log_2021-12-01_06-31-16.log)
Wifi will work after restart.
Please help me to fix. Thanks so much.

**Comment by zxystd** [comment]
[Big Sur.zip](https://github.com/OpenIntelWireless/itlwm/files/7632046/Big.Sur.zip)
@SesshomaruVN your system disable the network card when sleep, so it will never work after wakeup, I have done something in the kext to try to enable the network card again, please try.

**Comment by SesshomaruVN** [comment]
> [Big Sur.zip](https://github.com/OpenIntelWireless/itlwm/files/7632046/Big.Sur.zip)
> @SesshomaruVN your system disable the network card when sleep, so it will never work after wakeup, I have done something in the kext to try to enable the network card again, please try.

Thank you so much for helping me.
I have used your kext file above, but It is still not working after sleep.
After inject your kext file, the only one time I can wake from sleep with wifi working (but lost the current wifi in the list) - sorry because of no log file in this case.
After that time, still not working. Here is my log after used above kext.
[Log_2021-12-01_16-33-41.log](https://github.com/OpenIntelWireless/itlwm/files/7632669/Log_2021-12-01_16-33-41.log)
Here is my sleep config, hope this useful.
![Screen Shot 2021-12-01 at 16 40 18](https://user-images.githubusercontent.com/89727677/144210265-95d8534a-0449-4166-8ac9-dbec2b5169bd.png)

**Comment by zxystd** [comment]
@SesshomaruVN 
Your card's rfkill switch is persist closed after wakeup, the driver can't enable it.
<img width="449" alt="image" src="https://user-images.githubusercontent.com/16227538/144212723-3972ad6b-2e23-478e-92a7-c4d02e2659fa.png">

**Comment by SesshomaruVN** [comment]
> @SesshomaruVN
> Your card's rfkill switch is persist closed after wakeup, the driver can't enable it.
> <img alt="image" width="449" src="https://user-images.githubusercontent.com/16227538/144212723-3972ad6b-2e23-478e-92a7-c4d02e2659fa.png">

is there any way I can fix it?

**Comment by zxystd** [comment]
I tried forcing write the rfkill switch in driver now, although it should not do like this and should be managed by ACPI or BIOS.
[AirportItlwm.kext.zip](https://github.com/OpenIntelWireless/itlwm/files/7632959/AirportItlwm.kext.zip)

**Comment by SesshomaruVN** [comment]
> I tried forcing write the rfkill switch in driver now, although it should not do like this and should be managed by ACPI or BIOS.
> [AirportItlwm.kext.zip](https://github.com/OpenIntelWireless/itlwm/files/7632959/AirportItlwm.kext.zip)

Unfortunate it is still not working. Thank for your help.
Maybe I should patch ACPI, but I don't know where to start. So could you recommend some useful knowledge that I can start from that. (I checked my bios setings and not relative to that one)
Thanks so much.

**Comment by SesshomaruVN** [comment]
Hi guys, finally I found how to fix this problem.

If you are facing that one, you can try step by step - level of recommendation decreases.

1. You can try kext file that patched by @zxystd. I have found 2 version for [Bigsur](https://github.com/OpenIntelWireless/itlwm/files/7632046/Big.Sur.zip) and [Monterey](https://github.com/OpenIntelWireless/itlwm/files/7019815/Monterey.zip)
2. For the system as I described above, you need to turn off sleep mode. If you are using OC, you can try [their guide](https://dortania.github.io/OpenCore-Post-Install/universal/sleep.html) before. If not affect, you can use the command below in your terminal. ([Credit](https://gist.github.com/pwnsdx/2ae98341e7e5e64d32b734b871614915))
`sudo pmset -a sleep 0; sudo pmset -a hibernatemode 0; sudo pmset -a disablesleep 1;`
if you want to revert to default value, you can search in google or try this command:
`sudo pmset -a sleep 1; sudo pmset -a hibernatemode [original hibernatemode value]; sudo pmset -a disablesleep 0;`

Thanks @zxystd for helping me. Hope this guide can help more else guys.

**Comment by Fuzail-maker** [comment]
@SesshomaruVN If you turn off sleep mode, doesn't it mean your laptop won't sleep?

**Comment by Overc1ocker** [comment]
AC7265 Rev B, Monterey 12.2 sleep works properly with the latest 2.1.0 kext. Wifi instantly connects on wakeup.

**Comment by williambj1** [comment]
@Overc1ocker Sounds more likely to be a motherboard flaw rather than a kext or wifi card issue. The card is dead locked by RFKILL after sleep.

**Comment by usr-sse2** [comment]
For me, it doesn't work after sleep is `pci-aspm-default` is set to 0 (ASPM is disabled). If I remove this property (enable ASPM), then it works after sleep.

**Comment by ferdysopian** [comment]
Don't know if it's the same on every motherboard, but on the "HP 14s dq1013tu" it has a Prepare to Sleep and Wake method that sets the WiFi and Bluetooth state.

I'm no expert on this but trying to figure it out.

First you need to verify what the WLBT device is trying to set on your DSDT.
<img width="450" alt="Screenshot 2022-11-13 at 09 58 09" src="https://user-images.githubusercontent.com/20509247/201501879-164db3c7-b9d6-417a-8722-35df11f8c135.png">

Once you know what WLBT is trying to set up, check your MWAK and MPTS. There are some codes that are the same as those that appear on WLBT to save the current WiFi and Bluetooth status but for some reason, it's not working properly.
<img width="375" alt="Screenshot 2022-11-13 at 10 01 10" src="https://user-images.githubusercontent.com/20509247/201502038-e65e2339-9480-4778-95c1-94e3d541672a.png">

So you can rename MWAK and MPTS so they can be paired with a custom SSDT to force set WiFi and Bluetooth state on Wake.
<img width="276" alt="Screenshot 2022-11-13 at 11 17 25" src="https://user-images.githubusercontent.com/20509247/201503974-efe6bacf-c7a7-4c37-bb95-e4d95a3aef95.png">

With this configuration, WiFi and Bluetooth on my laptop will turn on when it wakes up.

**Comment by VGerris** [comment]
> With this configuration, WiFi and Bluetooth on my laptop will turn on when it wakes up.
@ferdysopian 

I have the exact same issue and the same code in BIOS.
I am stuck trying to compile the SSDT, can you post yours?
I just add a rename for MWAK to XWAK and then want to add the SSDT.aml for the last picture you sent.
Would be nice to get saving working but this is a good start, thanks a lot for sharing!

[update]
I was able to get the rename to work and the SSDT to compile but when I add the .aml I do not get the method in there...
Greatly appreciated if you can share all the relevant steps, thank you!

**Comment by 1alessandro1** [comment]
@VGerris here you go
[ssdt.zip](https://github.com/user-attachments/files/18386205/ssdt.zip)
