### ISSUE TITLE
System unresponsive after playing music through airplay/用AirPlay播放音乐后系统未响应

### ISSUE THREAD

**Issue by wqhqq1** [OpenIntelWireless/itlwm#521]
**Have You Read Our Docs**
Yes

**Are You Reporting A Bug**
Yes

**Environment**

- Kext Version: 1.2.0
- WiFi Card Model: ax200
- Product ID: 0x8086(0x2723)
- macOS Version: 11.3(20E5172i)

**Description**

When I try to connect appletv and play music through airplay, system will be unresponsive until I disconnected appletv
**Bug Report Archive**

![image](https://user-images.githubusercontent.com/53130008/106865434-2699a400-6706-11eb-934d-60d23adc45b2.png)

**Kext Download Source**

Github Release

**Comment by win1010525** [comment]
Whole log please. Isn’t it a bug of Big Sur? Have you tried to restart your computer?

**Comment by zxystd** [comment]
Nothing related to this driver.

**Comment by wqhqq1** [comment]
你是说这是macOSbeta版的bug对吧

**Comment by win1010525** [comment]
对，11.3bug特别多，我都服了

**Comment by wqhqq1** [comment]
我换了好几个itwm还是如此，昨天作死升级的
