### ISSUE TITLE
Airport-itlwm speed is slow. 下载速度 40<100；上传速度 20 <36

### ISSUE THREAD

**Issue by HsunGong** [OpenIntelWireless/itlwm#522]
**Environment**

- Kext Version: 1.2.0 stable
- WiFi Card Model: intel ac8265
- Product ID: thinkpad x1 carbon 6th
- macOS Version: 10.15.7

- standard device: huawei m30p
- router version: D128G, China Tel.
- Wifi: 5GHz

**Description**

![image](https://user-images.githubusercontent.com/32933986/106889617-3a9fce80-6723-11eb-8f1a-4bbf78db9f72.png)

![image](https://user-images.githubusercontent.com/32933986/106889955-b00b9f00-6723-11eb-9728-cd2215a76c0e.png)

**Kext Download Source**

https://github.com/OpenIntelWireless/itlwm/releases/download/v1.2.0/AirportItlwm_v1.2.0_stable_Catalina.kext.zip

**Comment by williambj1** [comment]
Known and expected.
