### ISSUE TITLE
AC3165 faced scan and connect problem

### ISSUE THREAD

**Issue by Just-Prog** [OpenIntelWireless/itlwm#523]
**Have You Read Our Docs**

Yes
**Are You Reporting A Bug**

Yes

**Environment**

- Kext Version: 1.3.0-DEBUG-ecf78fc (AirportItlwm & Itlwm)
- WiFi Card Model: AC3165
- Product ID: MacBookPro 15,3
- macOS Version: 10.14.6/10.15.7

**Description**

有时可以扫描到Wi-Fi，但无法进行连接，同时在连接失败后无法继续扫描Wi-Fi。

**Bug Report Archive**

**Kext Download Source**

GitHub Releases

**Comment by williambj1** [comment]
No logs
