### ISSUE TITLE
AC3165 faced scan and connect problem

### ISSUE THREAD

**Issue by Just-Prog** [OpenIntelWireless/itlwm#524]
**Have You Read Our Docs**

Yes

**Are You Reporting A Bug**

Yes

**Environment**

- Kext Version: 1.3.0-DEBUG-ecf78fc (Both AirportItlwm and Itlwm)
- WiFi Card Model: AC3165 (iwm)
- Product ID: MacBookPro 15,3
- macOS Version: 10.14.6 / 10.15.7

**Description**

有时可以扫描到Wi-Fi，但无法进行连接（无法连接的Wi-Fi信号频段均为40MHz），同时在连接失败后短暂性无法继续扫描Wi-Fi。
将Wi-Fi频段切换至20mhz后均恢复正常。

System can scan Wi-Fi normally, but can't connect to Wi-Fi in 40MHz.
**Bug Report Archive**

[AirItlDebug_2021-02-04_20-11-06.zip](https://github.com/OpenIntelWireless/itlwm/files/5925617/AirItlDebug_2021-02-04_20-11-06.zip)
[Log_2021-02-04_20-03-17.log](https://github.com/OpenIntelWireless/itlwm/files/5925618/Log_2021-02-04_20-03-17.log)

**Kext Download Source**

GitHub Releases

**Comment by zxystd** [comment]
日志不完整，重新操作收集一遍吧，目测应该是跟路由器协商40mhz有问题

**Comment by Just-Prog** [comment]
> 日志不完整，重新操作收集一遍吧，目测应该是跟路由器协商40mhz有问题

用dmesg重抓了一遍
[Log_2021-02-05_08-30-15.log](https://github.com/OpenIntelWireless/itlwm/files/5929343/Log_2021-02-05_08-30-15.log)

用AirItlDebug抓了60秒
[AirItlDebug_2021-02-05_08-35-05.zip](https://github.com/OpenIntelWireless/itlwm/files/5929346/AirItlDebug_2021-02-05_08-35-05.zip)

**Comment by zxystd** [comment]
[归档.zip](https://github.com/OpenIntelWireless/itlwm/files/5930949/default.zip)
@Just-Prog 试试这个。

**Comment by Just-Prog** [comment]
> [归档.zip](https://github.com/OpenIntelWireless/itlwm/files/5930949/default.zip)
> @Just-Prog 试试这个。

可以连接了，在speedtest.cn下测试速率基本在30-40Mbps之间波动，偶尔能达到50Mbps，路由器后台提供的协商速率为120。
谢谢您。

**Comment by zxystd** [comment]
@Just-Prog 单天线这么差劲啊？上面显示的是40mhz吗？我回去用3165试试

**Comment by Just-Prog** [comment]
> @Just-Prog 单天线这么差劲啊？上面显示的是40mhz吗？我回去用3165试试

显示的参数是“信道36，5GHz，40mHz”

**Comment by kidonng** [comment]
FYI, I can get a maximum download speed of 116Mpbs with the latest commit (dbdbf007ac5bc102cd3d487b3084f5949a383978) and AC 9461.

**Comment by win1010525** [comment]
> FYI, I can get a maximum download speed of 116Mpbs with the latest commit ([dbdbf00](https://github.com/OpenIntelWireless/itlwm/commit/dbdbf007ac5bc102cd3d487b3084f5949a383978)) and AC 9461.

Network is very slow because AC 3165 sucks.

**Comment by zxystd** [comment]
fixed in dbdbf007ac5bc102cd3d487b3084f5949a383978.
