### ISSUE TITLE
Internet Speeds very Low

### ISSUE THREAD

**Issue by harshsingh7** [OpenIntelWireless/itlwm#525]
**Have You Read Our Docs**
Yes

**Are You Reporting A Bug**
Yes

**Environment**

- Kext Version: 1.2.0 (Stable)
- WiFi Card Model:  Intel v3165
- Product ID: MacBookPro13,3
- macOS Version: macOS Big Sur (11.2)

**Description**
My Internet connection is 500mbit, was really happy to see intel wifi card support natively, but the speed has taken a significant hit, it only reaches a max of 25mbit

**Bug Report Archive**
Unable to create any Diagnostics report, no such option

**Kext Download Source**
official GitHub

**Comment by williambj1** [comment]
Feel free to submit pull requests that would enhance the performance.
