### ISSUE TITLE
Heliport can't scan any wifi(AC3165)

### ISSUE THREAD

**Issue by James-Shadow** [OpenIntelWireless/itlwm#527]
**Have You Read Our Docs**
Yes

**Are You Reporting A Bug**
Yes

**Environment**

- Kext Version: AirportItlwm_v1.2.0 stable HighSierra and itlwm_1.2.0 stable 
- WiFi Card Model: AC3165
- Product ID: iMac18,1
- macOS Version: 10.13.6(17G65)

**Description**
驱动均通过Clover安装，Heliport也设置了开机启动项，但是菜单栏里没有任何Wi-Fi信息，“Wi-Fi：关闭”为灰色

**Bug Report Archive**

[终端存储的输出.log](https://github.com/OpenIntelWireless/itlwm/files/5941599/default.log)

**Kext Download Source**
GitHub Releases

**Comment by win1010525** [comment]
![截屏2021-02-08 下午2 23 35](https://user-images.githubusercontent.com/50404193/107183173-41775b80-6a19-11eb-985d-10f77b8002b8.png)

**Comment by win1010525** [comment]
Use Heliport to get logs.

**Comment by James-Shadow** [comment]
> Use Heliport to get logs.

How to use it? I can't see the picture which you send

**Comment by win1010525** [comment]
Please read doc first.

**Comment by James-Shadow** [comment]
> Please read doc first 我通过阅读设置了boot-args，但是导出的log是空白的

**Comment by James-Shadow** [comment]
> Please read doc first.

我通过阅读设置了boot-args，但是导出的log是空白的

**Comment by James-Shadow** [comment]
> > Please read doc first.
> 
> 我通过阅读设置了boot-args，但是导出的log是空白的

用Heliport导出时总会报错

**Comment by win1010525** [comment]
> > > Please read doc first.
> > 
> > 
> > 我通过阅读设置了boot-args，但是导出的log是空白的
> 
> 用Heliport导出时总会报错

Can you upload a screenshot of Heliport?

**Comment by James-Shadow** [comment]
> > > > Please read doc first.
> > > 
> > > 
> > > 我通过阅读设置了boot-args，但是导出的log是空白的
> > 
> > 
> > 用Heliport导出时总会报错
> 
> Can you upload a screenshot of Heliport?

[bugreport_55282.zip](https://github.com/OpenIntelWireless/itlwm/files/5943272/bugreport_55282.zip)
Is this ?

**Comment by James-Shadow** [comment]
> > > > > Please read doc first.
> > > > 
> > > > 
> > > > 我通过阅读设置了boot-args，但是导出的log是空白的
> > > 
> > > 
> > > 用Heliport导出时总会报错
> > 
> > 
> > Can you upload a screenshot of Heliport?
> 
> [bugreport_55282.zip](https://github.com/OpenIntelWireless/itlwm/files/5943272/bugreport_55282.zip)
> Is this ?

![屏幕快照 2021-02-09 下午12 29 29](https://user-images.githubusercontent.com/78692295/107318332-806be680-6ad7-11eb-9c3b-9de7187b2a6a.jpg)
点击开启没反应，网络设置中也没有显示

**Comment by zxystd** [comment]
1.0版本可以用吗

**Comment by James-Shadow** [comment]
> 1.0版本可以用吗

不能，各个版本都试过，点开Heliportwifi是关闭的

**Comment by James-Shadow** [comment]
> > 1.0版本可以用吗
> 
> 不能，各个版本都试过，点开Heliportwifi是关闭的

![CE355F30-BB13-48A6-99D0-C81444EA75AC(20210209-163](https://user-images.githubusercontent.com/78692295/107337165-f3d02100-6af4-11eb-82dc-c994cc5f7e87.PNG)

**Comment by James-Shadow** [comment]
> > > 1.0版本可以用吗
> > 
> > 
> > 不能，各个版本都试过，点开Heliportwifi是关闭的
> 
> ![CE355F30-BB13-48A6-99D0-C81444EA75AC(20210209-163](https://user-images.githubusercontent.com/78692295/107337165-f3d02100-6af4-11eb-82dc-c994cc5f7e87.PNG)
