### ISSUE TITLE
偶发性出现不能正常联网，查看WiFi情况，提示已连接但没有有效的ip地址

### ISSUE THREAD

**Issue by imzhengziyi** [OpenIntelWireless/itlwm#528]
偶发性出现不能正常联网，查看WiFi情况，提示已连接但没有有效的ip地址

基本出现在重启电脑，或者休眠后点亮屏幕后出现此情况，提示已连接，但没有有效的ip地址，获取到的IP地址不是正常的192.168.x.x号段，多次开关WiFi开关后能正常连接

使用版本v1.2.0 stable
![截屏2021-02-09 12 15 32](https://user-images.githubusercontent.com/46698724/107314953-b9548d00-6ad0-11eb-859a-542fac7812a3.png)
![截屏2021-02-09 12 15 40](https://user-images.githubusercontent.com/46698724/107314965-bd80aa80-6ad0-11eb-87a4-2e1c423fcff6.png)

**Comment by James-Shadow** [comment]
![屏幕快照 2021-02-09 下午12 29 29](https://user-images.githubusercontent.com/78692295/107316087-edc94880-6ad2-11eb-9f49-946e58f897e4.jpg)
你的无线网卡型号是什么，我是AC3165，为啥你会显示的那么正常😂

**Comment by imzhengziyi** [comment]
我是asrock b365m itx/ac主板自带的网卡，型号我没看，我用的是最新版bigsur，看你图里还有英伟达驱动，你用的是10.13.6系统吧，应该是系统问题，我的网卡使用这个驱动，联网界面和白果网卡差不多的，没有测试别的功能！

**Comment by imzhengziyi** [comment]
> ![屏幕快照 2021-02-09 下午12 29 29](https://user-images.githubusercontent.com/78692295/107316087-edc94880-6ad2-11eb-9f49-946e58f897e4.jpg)
> 你的无线网卡型号是什么，我是AC3165，为啥你会显示的那么正常😂

我是asrock b365m itx/ac主板自带的网卡，型号我没看，我用的是最新版bigsur，看你图里还有英伟达驱动，你用的是10.13.6系统吧，应该是系统问题，我的网卡使用这个驱动，联网界面和白果网卡差不多的，没有测试别的功能！

**Comment by SeptemberHX** [comment]
点击 WiFi设置->高级->TCP/IP->DHCP续租 试试看，我在切换WIFI的时候发现没有dhcp获取新IP导致切换网络后没法联网，只能手动点击续租获取IP

**Comment by imzhengziyi** [comment]
> 点击 WiFi设置->高级->TCP/IP->DHCP续租 试试看，我在切换WIFI的时候发现没有dhcp获取新IP导致切换网络后没法联网，只能手动点击续租获取IP

你说的这个方法我用过，偶尔可以解决问题，大部分情况还是不行，或者一直点，直到它正常获取IP

**Comment by win1010525** [comment]
Please provide valid logs, otherwise, bat.bat will close this issue. @williambj1

**Comment by williambj1** [comment]
Invalid issue format
