### ISSUE TITLE
你这驱动是不是挑频道？

### ISSUE THREAD

**Issue by mendax1234** [OpenIntelWireless/itlwm#530]
**Have You Read Our Docs**

Yes
**Are You Reporting A Bug**

Yes
**Environment**
macOS Big sur
- Kext Version: Airporitlwm 1.2.0
- WiFi Card Model: Intel AC 9560
- Product ID: 0x8086, 0x34
- macOS Version:Big Sur

**Description**

我把自家Wi-Fi换了个5G的频道，就能正常且稳定的链接，但是用之前2.4G频道的时候就一直提示没有IP地址
**Bug Report Archive**

**Kext Download Source**

从GitHub的release上直接下载的

**Comment by williambj1** [comment]
Will consider reopening once logs are properly provided.

**Comment by mendax1234** [comment]
How to provide right log

发送自 Windows 10 版邮件应用

发件人: Bat.bat
发送时间: 2021年2月9日 15:27
收件人: OpenIntelWireless/itlwm
抄送: mendax1234; Author
主题: Re: [OpenIntelWireless/itlwm] 你这驱动是不是挑频道？ (#530)

Will consider reopening once logs are properly provided.

**Comment by mendax1234** [comment]
> Will consider reopening once logs are properly provided.

I update my issue,

**Comment by williambj1** [comment]
Did you add `msgbuf=1048576` to boot-args? According to the logs, you only tried to connect to a 5GHz network.

**Comment by mendax1234** [comment]
I actually didn’t add this code , I will try it right now, thanks a lot !

发送自 Windows 10 版邮件应用

发件人: Bat.bat
发送时间: 2021年2月10日 16:02
收件人: OpenIntelWireless/itlwm
抄送: mendax1234; Author
主题: Re: [OpenIntelWireless/itlwm] 你这驱动是不是挑频道？ (#530)

Did you add msgbuf=1048576 to boot-args? According to the logs, you only tried to connect to a 5GHz network.

**Comment by mendax1234** [comment]
Actually it doesn’t work at all , I still can’t connect to my 2.4G Wi-Fi, but I can’t connect to my 5G Wi-Fi

**Comment by williambj1** [comment]
Please provide valid logs

**Comment by mendax1234** [comment]
I have already provided the valid log!

发送自 Windows 10 版邮件应用

发件人: Bat.bat
发送时间: 2021年2月10日 20:40
收件人: OpenIntelWireless/itlwm
抄送: mendax1234; Author
主题: Re: [OpenIntelWireless/itlwm] 你这驱动是不是挑频道？ (#530)

Please provide valid logs

**Comment by williambj1** [comment]
You still did not provide logs with `msgbuf=1048576`

**Comment by mendax1234** [comment]
This maybe the logs with the boot-args you’ve provided.

**Comment by mendax1234** [comment]
I still have another question , what’s the exact use of this code?

**Comment by mendax1234** [comment]
OK， maybe this time it’s OK

发送自 Windows 10 版邮件应用

发件人: Bat.bat
发送时间: 2021年2月10日 22:00
收件人: OpenIntelWireless/itlwm
抄送: mendax1234; Author
主题: Re: [OpenIntelWireless/itlwm] 你这驱动是不是挑频道？ (#530)


still nothing

**Comment by mendax1234** [comment]
[Report_2021-02-10_21-52-26.log](https://github.com/OpenIntelWireless/itlwm/files/5958622/Report_2021-02-10_21-52-26.log)
What a fxxx , the win 10 and macOS mail app is so disgusting

**Comment by mendax1234** [comment]
perhaps this time it is OK

**Comment by mendax1234** [comment]
> ![image](https://user-images.githubusercontent.com/45396585/107519548-5e638880-6beb-11eb-8f77-fce11884e3c4.png)
> 
> still nothing

So ， what's the problem ?
