### ISSUE TITLE
[AirportItlwm]9560AC第一次系统启动WIFI无法驱动，重启后正常

### ISSUE THREAD

**Issue by stone222** [OpenIntelWireless/itlwm#533]
**Have You Read Our Docs**
YES

**Are You Reporting A Bug**
YES

**Environment**

- Kext Version: AirportItlwm-Big_Sur-v1.3.0-DEBUG-alpha
- WiFi Card Model: INTEL9560AC
- Product ID: 
- macOS Version: BigSur 11.2.1

**Description**

每次第一次开机，WIFI无法驱动，需重新启动，无论重启到WINDOWS后再切换回macos，还是直接重启到macos，第二次启动后WIFI都是正常使用的。

**Bug Report Archive**
[不正常的Report_2021-02-21_07-10-41.log](https://github.com/OpenIntelWireless/itlwm/files/6016860/Report_2021-02-21_07-10-41.log)
[正常的Report_2021-02-21_07-17-15.log](https://github.com/OpenIntelWireless/itlwm/files/6016861/Report_2021-02-21_07-17-15.log)

**Comment by williambj1** [comment]
You should not reboot directly, read our docs for more info.
