### ISSUE TITLE
小小心愿 A Small Wish

### ISSUE THREAD

**Issue by Xingming-Lin** [OpenIntelWireless/itlwm#534]
一群中国朋友希望能在airdrop上用到网卡上。我们是一笔记本爱好者，因为笔记本接口的限制，不能更换博通网卡，我们只剩下这个airdrop功能了更好的使用黑苹果，希望开发人员能破解Airdrop功能，谢谢！

We are the user from China,we love to use the macOS.for a better using experience ,we hope to use the Airdrop on this chip.
Thank you!

**Comment by win1010525** [comment]
z大在未来会做适配的

**Comment by M69W** [comment]
破解意味着对系统的干扰，可能带来不稳定。
但我们学习这个功能，说不定在未来能实现类似的功能。

**Comment by williambj1** [comment]
> 破解意味着对系统的干扰，可能带来不稳定。
> 但我们学习这个功能，说不定在未来能实现类似的功能。

False assumption

**Comment by williambj1** [comment]
Duplicate of #292
