### ISSUE TITLE
This has happend both in Airportitlwm and in itlwm

### ISSUE THREAD

**Issue by tst05000** [OpenIntelWireless/itlwm#538]
So I installed itlwm (Hackintosh Catalina laptop with intel wireless AC Dual Band 1360 chip and Broadwell-U cpu) and i used heliport to try to connect and i even configured the wifi's before, but when i enabled it it didn't connect, so i tried heliport and i saw that it wasn't seeing any networks, and so i switched to Airportitlwm but again after clearing the network preferences in /Library/Preferences nothing showed up in scanning for new networks, thankfully i have ethernet working but wifi would be very nice in this system since this is a laptop. I don't know if i'm doing something wrong or what, nontheless some help would be saving me, Thank you in advantage.

**Comment by williambj1** [comment]
invalid issue format
