### ISSUE TITLE
Intel Dual Band Wireless-AC 7265 AC 2x2 HMCv Can't connect to WIFI

### ISSUE THREAD

**Issue by bindaomin** [OpenIntelWireless/itlwm#540]
Intel Dual Band Wireless-AC 7265 AC 2x2 HMCv Can't connect to WIFI 
I tried 10.12-11 and used itlwm and AirportItlwm.  I can search for the SSID, but I just can’t connect.
Machine Thinkpad x250    CPU I5 5300U 4G RAM GPU HD5500 BIOS 1.4

**Comment by williambj1** [comment]
Incorrect format, no logs, no respect, sorry
