### ISSUE TITLE
Conflicts with video on a Lenovo m93m Tiny system.

### ISSUE THREAD

**Issue by ratsalad** [OpenIntelWireless/itlwm#544]
**Have You Read Our Docs**

Yes

**Are You Reporting A Bug**

Yes
**Environment**

- Kext Version:  v1.2.0 stable
- WiFi Card Model: Intel Centrino Wireless-N 105 (105BNHMW) PCIe Half Mini
- Product ID: Lenovo m93p Tiny
- macOS Version: Big Sur .2

**Description**

Attempting to use itlwm causes a conflict with the video on the Lenovo m93p Tiny so the screen flickers continuously.  The card is the one that came with the system and one of the few cards that will work with the system.

**Bug Report Archive**

Cannot do while the kext is in use.

**Kext Download Source**

https://github.com/OpenIntelWireless/itlwm/releases/tag/v1.2.0

**Comment by williambj1** [comment]
Completely unrelated issue, fix your graphics driver
