### ISSUE TITLE
802.11n USB Wireless LAN Card not working

### ISSUE THREAD

**Issue by developerss** [OpenIntelWireless/itlwm#545]
**Have You Read Our Docs**
 yes

**Are You Reporting A Bug**
 yes 

**Environment**

- Kext Version: AirportItlwm-Catalina-v1.3.0-DEBUG-alpha-890f771 (3)
- WiFi Card Model: 802.11n USB Wireless LAN Card
- Product ID: alpha-890f771
- macOS Version: 10.15.7

**Description**

wifi not working at install mac requared wifi

**Bug Report Archive**

wifi not working

**Kext Download Source**

i downloaded it from here

**Comment by williambj1** [comment]
Hello?
