### ISSUE TITLE
[AirportITLWM] Wi-Fi works but shows up as Ethernet

### ISSUE THREAD

**Issue by martibravo** [OpenIntelWireless/itlwm#550]
AirportItlwm was working fine, even Airdrop was kind of working. Now, when I start my computer it connects to my home Wi-Fi, but it shows up as Ethernet on Network settings panel and I can't switch networks. 

**System:**
Laptop: Matebook D 14 
Processor: Intel i5 8250u
OS: Big Sur 11.2
RAM: 8gb
Wifi Card: Intel AC8625

![Screen Shot 2021-03-19 at 5 28 15 PM](https://user-images.githubusercontent.com/7605780/111812517-7f995200-88d8-11eb-8aca-709b9419d777.png)

**Comment by r33int** [comment]
Try resetting your network interfaces:
`sudo rm /Library/Preferences/SystemConfiguration/NetworkInterfaces.plist
sudo rm /Library/Preferences/SystemConfiguration/preferences.plist`

**Comment by williambj1** [comment]
Read our docs and reset your network interface preferences.

**Comment by martibravo** [comment]
It was my fault, I updated OpenCore and forgot to delete itlwm and leave AirportItlwm only. Sorry!
