### ISSUE TITLE
Defect with big sur and opencore ax200

### ISSUE THREAD

**Issue by Nosis** [OpenIntelWireless/itlwm#551]
**Have You Read Our Docs**

**Are You Reporting A Bug**

**Environment**

- Kext Version: v1.2.0
- WiFi Card Model: AX200
- Product ID: it does not appear in wifi. but it appears to me with the bluetoth: 0x0029
- macOS Version: 11.2.3

**Description**
I see the icon and the available wifi connection networks, it manages to link, but if an rj45 cable is not connected to the computer, it does not recognize wifi signals

**Bug Report Archive**
it is not possible to create the report

**Kext Download Source**
official github

**Comment by williambj1** [comment]
Not a bug. Fix your config.
