### ISSUE TITLE
Reason wifi and bluetooth not connect same time

### ISSUE THREAD

**Issue by nhatminhhp1999** [OpenIntelWireless/itlwm#552]
I think the problem bluetooth can not use at the same time with wifi the main problem is due to the 5ghz wave frequency and the channel bandwidth 80mhz 40mhz band. Some laptop use bluetooth and wifi connect to one anten, They will use different frequency bands to avoid signal interference. Supporting more frequencies in the future will completely fix the bluetooth problem.
Sorry i use google translate for thus issue

**Comment by sojab0on** [comment]
only issue I found with connections on Bluetooth is mice or keyboards my love 101 , jabra t110bt and JBL care 2 speakers connect without issue to my intel Bluetooth from the intel 9560AC 160mhz card

**Comment by rboldini** [comment]
Actually this issue is found on 7XXX and 8XXX series, with my 7265AC (2 antennas), speakers with low audio codec (SBC I think) works with wifi connected but with a low range distance from laptop, devices like AirPods or newer headphones don't work .

**Comment by fredimartins** [comment]
i have issues with bluetooth and wifi at same time, bluetooth headphones are popping audio if the headphones are more than 20cm. When i disable wifi, bluetooth audio stay smoothly even i stay 2 meters from notebook.

**Comment by williambj1** [comment]
I don't think that's the case, might be related to coex configs with Gen 1 Bluetooth but still not sure at this point. https://github.com/OpenIntelWireless/IntelBluetoothFirmware/blob/master/IntelBluetoothFirmware/IntelBluetoothFirmware.cpp#L152

The range issue discussion can be continued in #692
