### ISSUE TITLE
ITWLM Slow performance wifi adaptor not seen as wifi

### ISSUE THREAD

**Issue by sojab0on** [OpenIntelWireless/itlwm#553]
Hi i have an issue with ITWLM kext to get my intel wifi card up and seen as a wifi card 
I have an Intel Wireless-AC 9560 160mhz 

After booting with OpenCore an injecting the itwlm kext for Catalina stable 1.2 release a second Ethernet en1 is detected but I need heliport to get wifi working. also I have slow performance of the wifi heliport states its connected to my 5ghz network (unifi ap lite with an 500 mbps uplink ) in windows I have no issues with connection speed 

Speed test doesn't reach above 50 mbps in Mac OS , windows it goes trough to the max the card can handle. 

System specs 
I7 1065G7 quad core 
16GB 3200mhz der 4 ram 
1tb NVME ssd
so spec wise there. should be no bottleneck

am I doing something wrong or is my card not completely supported yet, also my Bluetooth has issues with connecting to devices .

**Comment by williambj1** [comment]
READ THE DOCS
