### ISSUE TITLE
Didn't load AirportItlwm.kext on Catalina

### ISSUE THREAD

**Issue by ducltv** [OpenIntelWireless/itlwm#555]
Hi guys. I have some issues with AirportItlwm kext on catalina, i have put that in the OC/Kexts/ and add it in config but when i turn on the pc it doesn't load the Airportitlwm althrough the IO80211Family loaded
![image](https://user-images.githubusercontent.com/55396215/112738351-c3552100-8f94-11eb-98e2-5069d35ac12b.png)

**Comment by ducltv** [comment]
I confirmed i save the config before restart the pc.

**Comment by ducltv** [comment]
![image](https://user-images.githubusercontent.com/55396215/112738478-e2a07e00-8f95-11eb-9bf8-ddf18af3f0f8.png)
Well after i change something in the config it work :l I don't know how the config can make me confused about 30 mins.

**Comment by Malumen** [comment]
> ![image](https://user-images.githubusercontent.com/55396215/112738478-e2a07e00-8f95-11eb-9bf8-ddf18af3f0f8.png)
> Well after **i change something in the config** it work :l I don't know how the config can make me confused about 30 mins.

What did you change? I am also having trouble getting it to work!

**Comment by zcream** [comment]
I've got a similar problem. Do let us know what you changed?

**Comment by ducltv** [comment]
@zcream i remember it about the kind of arch each kext i guess

**Comment by joshrogershak** [comment]
please tell us what you changed exactly - i rlly need it for something @fishudroid
