### ISSUE TITLE
Timemashine not working 

### ISSUE THREAD

**Issue by sojab0on** [OpenIntelWireless/itlwm#556]
**Have You Read Our Docs**
Yes 

**Are You Reporting A Bug**
Yes

**Environment**

- Kext Version: itlwm 1.2.0 stable with heliport
- WiFi Card Model: intel AC9560 160mhz pci-e 
- Product ID: product id of the card can't find it at the moment
- macOS Version: 10.15.7

**Description**
Backup tools like timemashine and Acronis won't connect to network drives trough the wifi 

**Bug Report Archive**

Will follow after next reboot with right boot flag set 

**Kext Download Source**
From relates page on this GitHub

**Comment by williambj1** [comment]
Userspace software are very unlikely related to this kext, we have tested Time Machine and it works flawlessly. Sorry but you might have to debug this issue yourself.
