### ISSUE TITLE
WP2企业认证连接困难

### ISSUE THREAD

**Issue by Hmm-zhang** [OpenIntelWireless/itlwm#557]
**Have You Read Our Docs**

yes
**Are You Reporting A Bug**

yes
**Environment**

- Kext Version: /v1.3.0-alpha
- WiFi Card Model: Intel AC 8265
- Product ID: 
- macOS Version: Big Sur 11.2.3

**Description**

WP2企业认证连困难，经常连很久才能连接成功，而且不会自动重连，每次都需要手动重连，重连时要关闭WIFI几次并且每次都要重新输入账号密码。不知道大神能抽空看看这个问题没。感谢*1000！！
**Bug Report Archive**

**Kext Download Source**

**Comment by williambj1** [comment]
日志？
