### ISSUE TITLE
T440s with airpirtitlwm 1.2.0 or 1.3.0 Slow speed

### ISSUE THREAD

**Issue by xxx090909** [OpenIntelWireless/itlwm#559]
**Have You Read Our Docs**

**Are You Reporting A Bug**

**Environment**

- Kext Version: 1.3.0
- WiFi Card Model: AC7260
- Product ID: 
- macOS Version: BigSur

**Description**
Hallo,

after the clean install first time i habe the Maximum Speed in down and Upload. 
If i restart there are only 10mps for down and 0.5 MPs gor Upload. 

**Kext Download Source**
Guthaben

**Comment by williambj1** [comment]
No logs, closed as complaining.
