### ISSUE TITLE
Itlwm + HeliPort works OK, but cannot migrate to AirPortItlwm

### ISSUE THREAD

**Issue by Malumen** [OpenIntelWireless/itlwm#560]
I had been using the `HeliPort` and `Itlwm.kext` combination for a few weeks OK. 

I wanted the AirDrop and other improvements that come with using `AirPortItlwm` so I removed `Itlwm.kext` and used "clean snapshot" feature of `ProperTree`. WiFi did not show up. Cleaned NVRam and still no WiFi. I looked and `IO80211Family.kext` was not loaded. I followed the Dortania guide for `Kernel -> Force -> IO80211Family` but it is still not loaded.

The other method of enabling `SecureBootModel -> Default` causes my system to ask for macOS reinstall. I am thinking this is because my `ApECID` value is **not** _0_.

I am using OpenCore 0.6.5 as part of [Osy's HaC mini project](https://github.com/osy/HaC-Mini).

**Comment by zxystd** [comment]
Airdrop is not work expected. Issue format is invalid and we will not provide any personal help, please turn to other Hacking forums.
