### ISSUE TITLE
大佬是否有时间研究一下杀手网卡系列

### ISSUE THREAD

**Issue by linianqing** [OpenIntelWireless/itlwm#561]
好像很多主板集成网卡的笔记本都搭载得杀手网卡，如戴尔的一大堆轻薄本和外星人系列，好像杀手网卡和intel网卡有点类似。

**Comment by zxystd** [comment]
没时间。另外请看支持列表。

**Comment by linianqing** [comment]
不好意思啊大佬，因为我去年在远景问过你这个问题，当时是不支持的，然后年初我也测试了我的1535杀手网卡还是不行，我以为还没有支持杀手网卡，虽然我用不了，但是还是很感谢大佬得付出。

**Comment by yuenwah** [comment]
> 不好意思啊大佬，因为我去年在远景问过你这个问题，当时是不支持的，然后年初我也测试了我的1535杀手网卡还是不行，我以为还没有支持杀手网卡，虽然我用不了，但是还是很感谢大佬得付出。

是不是还不支持，我用最新的也不行
