### ISSUE TITLE
ac9560网卡不能自动切换WIFI

### ISSUE THREAD

**Issue by chtbit** [OpenIntelWireless/itlwm#562]
我的网卡系统显示为intel ac9560，目前使用airportitlwm 1.3.0 alpha板，在WIFI切换的时候无法连接，需要重启。
![WechatIMG10](https://user-images.githubusercontent.com/58623488/113822316-dc897900-97af-11eb-9a40-1c281fa89f79.jpeg)

**Comment by williambj1** [comment]
Use 10.15 with airport or 11 with itlwm. Closed since the issue format is invalid.
