### ISSUE TITLE
和AppleBacklightFixup.kext冲突

### ISSUE THREAD

**Issue by DaiZhaoedu** [OpenIntelWireless/itlwm#563]
[AppleBacklightFixup.kext.zip](https://github.com/OpenIntelWireless/itlwm/files/6271595/AppleBacklightFixup.kext.zip)

和IntelBluetoothFirmware.kext、IntelBluetoothInjector.kext冲突。附件kext为调节屏幕亮度驱动，添加后蓝牙使用不了，你能帮忙看看什么原因吗

**Comment by williambj1** [comment]
Invalid issue format, use other sources for personal support.

**Comment by DaiZhaoedu** [comment]
> Invalid issue format, use other sources for personal support.

waht?I do not know

**Comment by jackjack1-su** [comment]
Don't use the AppleBackLightFixup.
Plz use the WEG instead.
The WEG has already integrated the background light patches.
And your issue is invalid as well.
This problem should be asked in the Gitter Chat Room instead of here.
