### ISSUE TITLE
AirportItlwm can see SSID but unable to connect

### ISSUE THREAD

**Issue by theballkyo** [OpenIntelWireless/itlwm#569]
**Have You Read Our Docs**
Yes

**Are You Reporting A Bug**
Yes

**Environment**

- Kext Version: 1.3.0 Alpha
- WiFi Card Model: Intel 9560
- Product ID: 0x8086 0x9df0
- macOS Version: 11.2.3 (20D91)

**Description**
AirportItlwm can see SSID but unable to connect

**Bug Report Archive**
[Report_2021-04-15_15-05-46.log](https://github.com/OpenIntelWireless/itlwm/files/6316203/Report_2021-04-15_15-05-46.log)

**Kext Download Source**
Github release

**Comment by williambj1** [comment]
Have you tried itlwm.kext?

**Comment by zxystd** [comment]
Please try the latest version

**Comment by williambj1** [comment]
Feel free to comment below if this issue still exists. Will reopen.
