### ISSUE TITLE
AirportItlwm断流

### ISSUE THREAD

**Issue by EntityBug** [OpenIntelWireless/itlwm#570]
**Have You Read Our Docs**

Yes

**Are You Reporting A Bug**

Yes

**Environment**
AC9462 macOS 11.2.3 AirportItlwm 1.3.0 OC 0.6.6

- Kext Version: 1.3.0
- WiFi Card Model: AC9462
- Product ID: 找不到
- macOS Version: 11.2.3

**Description**

存在两种断流
1.系统显示正常，但无法访问任何网站，一般重新开启可在一段时间内稳定连接
2.系统显示正常，但无法访问任何网站，App在关闭Wi-Fi后仍会认为有网络连接（微信、qq不显示未联网，Chrome尝试加载网页），重新连接需要较长时间，且只能保持不到1分钟的连接，在17:00到22:30中，一般发生在19:00到21:00
连的是5g频段，调MTU没用，没有同时运行itlwm

**Bug Report Archive**

[Report_2021-04-15_18-38-43.log](https://github.com/OpenIntelWireless/itlwm/files/6318251/Report_2021-04-15_18-38-43.log)

**Kext Download Source**

[AirportItlwm_1.3.0_bigsur.kext.zip](https://github.com/OpenIntelWireless/itlwm/files/6318257/AirportItlwm_1.3.0_bigsur.kext.zip)

**Comment by win1010525** [comment]
你应该研究一下驱动是如何做到分时间断流的

**Comment by zxystd** [comment]
有没有试过2.0.0版本？

**Comment by EntityBug** [comment]
> 有没有试过2.0.0版本？

试过，问题仍存在

**Comment by joaovictorsouza** [comment]
Same problem here with both versions described.

**Comment by williambj1** [comment]
@EntityBug Have you tired `itlwm.kext`?

**Comment by EntityBug** [comment]
> @EntityBug Have you tired `itlwm.kext`?

Yes.

**Comment by zxystd** [comment]
Use the latest one.
