### ISSUE TITLE
关于intelWiFi翻墙

### ISSUE THREAD

**Issue by beilvla** [OpenIntelWireless/itlwm#573]
您阅读过我们的文件了吗
是
您是否正在报告错误
否
环境
Mac 11.2.3
Kext版本：1.2
WiFi卡型号：ac3165
产品编号：
macOS版本：Mac 11.2.3
描述
使用WiFi连接后，打开蓝灯，发现蓝灯始终连接不上
错误报告存档

Kext下载源 github

**Comment by zxystd** [comment]
能不能翻墙跟驱动没有关系。
