### ISSUE TITLE
无法连接WPA/WPA2 PSK

### ISSUE THREAD

**Issue by Haaooo** [OpenIntelWireless/itlwm#575]
**Have You Read Our Docs**

YES
**Are You Reporting A Bug**

YES
**Environment**

- Kext Version: AirportItlwm_v1.3.0_stable_BigSur.kext
- WiFi Card Model: intel ac 9462
- Product ID: 
- macOS Version:11.3 Beta版(20E5186e)
- **Description**

![截屏2021-04-20 20 03 41](https://user-images.githubusercontent.com/71207318/115392759-838bfd00-a213-11eb-9eff-9051dfb95a7c.png)
我想连接的是openwrt,但是一直是转圈状态一直连接不上
**Bug Report Archive**

**Kext Download Source**
https://github.com/OpenIntelWireless/itlwm/releases/download/v1.3.0/AirportItlwm_v1.3.0_stable_BigSur.kext.zip

**Comment by zxystd** [comment]
log?

**Comment by Haaooo** [comment]
> 日志？

我是小白，不知道在哪找日志

**Comment by win1010525** [comment]
小白就不要来开issue了

**Comment by williambj1** [comment]
Will consider reopening if logs are correctly provided.

**Comment by Haaooo** [comment]
> 如果日志提供正确，将考虑重新开放。I have uploaded the log, but I don't know if it is this one

**Comment by Haaooo** [comment]
> 如果日志提供正确，将考虑重新开放。
I have uploaded the log, but I don't know if it is this one

**Comment by zxystd** [comment]
日志不对，你要按照文档里面说的来，加了bootargs之后用heliport来收集日志也可以

**Comment by Haaooo** [comment]
> 日志不对，你按照文档说的，用直升机收集日志后，也可以

[Uploading AirItlDebug_2021-04-28_22-14-07.zip…]()
