### ISSUE TITLE
Github Action doesn't push alpha release

### ISSUE THREAD

**Issue by wqhqq1** [OpenIntelWireless/itlwm#576]
**Have You Read Our Docs**

**Are You Reporting A Bug**

**Environment**

- Kext Version: 
- WiFi Card Model: 
- Product ID: 
- macOS Version: 

**Description**

**Bug Report Archive**

**Kext Download Source**

**Comment by williambj1** [comment]
CI bug fixed, too late for me to open my laptop at mid night!
