### ISSUE TITLE
Unable to find and connect 11ax Wi-Fi

### ISSUE THREAD

**Issue by wqhqq1** [OpenIntelWireless/itlwm#577]
**Have You Read Our Docs**

Yes
**Are You Reporting A Bug**

Yes
**Environment**

- Kext Version: 2.0.0
- WiFi Card Model: ax200
- Product ID: nop
- macOS Version: 11.2.3

**Description**

I use the latest alpha version.But I can’t find the card supports 11ax in system info, and the driver only gives me the speed of 11ac 160mhz.
**Kext Download Source**

Github Release

**Comment by williambj1** [comment]
Implemented doesn't mean it is enabled, AX was disabled due to some bugs. Be patient as stay tuned.

**Comment by wqhqq1** [comment]
got it thanks

**Comment by alessaba** [comment]
Are there any updates on this?
