### ISSUE TITLE
AX200 with v2.0 Alpha get DL > 50Mb/s and UL > 40Mb/s

### ISSUE THREAD

**Issue by samleong123** [OpenIntelWireless/itlwm#579]
**Have You Read Our Docs**

Yes

**Are You Reporting A Bug**

No

**Environment**

- Kext Version:  v2.0 Alpha
- WiFi Card Model: AX200
- Product ID: Dunno where to find it
- macOS Version: Big Sur 11.2.3

**Description**

After using v2.0.0 Alpha Kexts , im able to get Download of over 50Mb/s and upload over 40Mb/s!
Almost near as AC performance!

![Screenshot 2021-04-24 at 14 27 56](https://user-images.githubusercontent.com/58818070/115949745-bda61900-a509-11eb-9ba2-9dcb05289671.png)
![Screenshot 2021-04-24 at 14 18 11](https://user-images.githubusercontent.com/58818070/115949747-c139a000-a509-11eb-969b-97f34975956e.png)
![Screenshot (2334)](https://user-images.githubusercontent.com/58818070/115949758-cd256200-a509-11eb-8d37-026d69cf8fad.png)
![Screenshot (2330)](https://user-images.githubusercontent.com/58818070/115949763-d6163380-a509-11eb-8960-c26cfabab6e1.png)

**Bug Report Archive**

**Kext Download Source**

Github Release

**Comment by win1010525** [comment]
Known
