### ISSUE TITLE
AX201 disconnect issue.

### ISSUE THREAD

**Issue by LuxuryWasTaken** [OpenIntelWireless/itlwm#581]
**Have You Read Our Docs**
Yes
**Are You Reporting A Bug**
Yes
**Environment**

- Kext Version: 1.3.0
- WiFi Card Model: AX201
- Product ID: Razer Blade 15 2020 Base
- macOS Version: Big Sur
- 
**Description**
Sometimes wifi is disconnecting and when I try to connect (it happens usually) it says password changed.

**Bug Report Archive**

**Kext Download Source**

**Comment by williambj1** [comment]
No logs
