### ISSUE TITLE
开机五分钟内会出现一次冻屏，卡死

### ISSUE THREAD

**Issue by w550** [OpenIntelWireless/itlwm#583]
**Have You Read Our Docs**

Yes
**Are You Reporting A Bug**

Yes
**Environment**

- Kext Version: 1.3.0
- WiFi Card Model: Wireless-AC 9560
- Product ID: Wireless-AC 9560
- macOS Version:  11.2.3

**Description**

开机五分钟内会出现一次冻屏，卡死。结果要么死机自动重启，要么，恢复，恢复后看了一下CPU跑满，（有个峰值）再降下来。所有的网络变得非常慢，主动关闭WI-FI后，再次打开Wi-Fi后，网络恢复。
必现。可以反复复现。
**Bug Report Archive**

**Kext Download Source**

**Comment by williambj1** [comment]
Will consider reopening if logs are provided.

**Comment by w550** [comment]
@williambj1  log 已上传
