### ISSUE TITLE
DHCP connecting problem

### ISSUE THREAD

**Issue by MaxSYC** [OpenIntelWireless/itlwm#584]
**Have You Read Our Docs**
Yes

**Are You Reporting A Bug**
Yes

**Environment**

Kext Version: latest v2.0.0 alpha #c448fbd
WiFi Card Model: ax200
Product ID: 0x2723
macOS Version: Big Sur 11.3
Description
After using the 1.3.0_stable or latest 2.0.0_alpha version, I can't get the right DHCP IP with certain router, such as OpenWRT, but work fine with other router ex, Aruba AP. 
This problem appears for both 2.4g and 5G, and setting IP manually doesn't work. The solving  way I currently use is rolling back to 1.2.0_stable, but with much lower speed.
 

**Bug Report Archive**
Update logs 0607
alpha -9af1571 logs:
[Log_2021-06-07_13-00-25.log](https://github.com/OpenIntelWireless/itlwm/files/6618261/Log_2021-06-07_13-00-25.log)

2.0.0 logs:
[Log_2021-04-28_14-06-59_2.0_alpha.log](https://github.com/OpenIntelWireless/itlwm/files/6389821/Log_2021-04-28_14-06-59_2.0_alpha.log)
1.3.0 logs:
[1.3.0_stable.log](https://github.com/OpenIntelWireless/itlwm/files/6389866/1.3.0_stable.log)

It always get the self-assigned IP address 169.254.xxx.xxx and will not be able to connect to the Internet.
![with dhcp issue](https://user-images.githubusercontent.com/82926244/116362893-24db0a80-a835-11eb-9cbb-f1cd5c4a3aab.png)
![dhcp issue](https://user-images.githubusercontent.com/82926244/116362908-29072800-a835-11eb-9edd-6136e3ea5a5f.png)
Works fine on 1.2.0
![1 2 0_no issue](https://user-images.githubusercontent.com/82926244/116363614-e7c34800-a835-11eb-934f-bafb8898679e.png)

**Kext Download Source**
Releases page.

**Comment by xx569029747** [comment]
手动更新DHCP无效吗？

**Comment by utteryu** [comment]
> 手动更新DHCP无效吗？
對，似乎根本無法和DHCP server溝通

**Comment by ske1996** [comment]
I've got same problem,too

but it was a few days ago and i forgot to grab a log,sry for that.

**Comment by win1010525** [comment]
CC. @zxystd 🌝

**Comment by Grant07** [comment]
Having the same issue on 1.3.0, on 11.3.1.
Though I am able to bypass the problem easily by simply turning the wireless radio, on and off again, then DHCP works

**Comment by tuancuong92** [comment]
Im having same issue. After renew DHCP, everything works. But sometimes, it suddenly disconnect and I cant renew DHCP again

**Comment by zxystd** [comment]
So please try the latest alpha.

**Comment by utteryu** [comment]
I have tried the latest alpha version #3e63230 but the issue is still there😥
[Log_2021-06-27.zip](https://github.com/OpenIntelWireless/itlwm/files/6733962/Log_2021-06-27.zip)

**Comment by ske1996** [comment]
> So please try the latest alpha.

dhcp works great in lastest version,thank you so much

**Comment by zxystd** [comment]
Thank you for the feedback.

**Comment by MaxSYC** [comment]
I have tested the  #fc497c1 alpha, and all works properly. If any logs needed please let me know, many thanks for your help.
