### ISSUE TITLE
SPAM

### ISSUE THREAD

**Issue by openviso** [OpenIntelWireless/itlwm#586]
磁盘空间不足，无法拷贝“AirportItlwm.kext”

还需要4 MB磁盘空间才能拷贝此文件。您可以在“关于本机”的“储存空间”部分中移除部分项目来管理磁盘空间。

Catania

**Comment by win1010525** [comment]
GO AND BUY A DISK

**Comment by ske1996** [comment]
所以你觉得你没法把kext复制进esp分区是这个项目主的错？🤣🤣🤣🤣🤣🤣

我国素质教育普及了二十多年了，总有漏网之鱼，哎

**Comment by LiuLiujie** [comment]
在复制kext进ESP时，不要采用“替换"的方式，先删除旧的再复制
