### ISSUE TITLE
airportitlwm 连接不上2.4Gwifi，只能连接5Gwifi

### ISSUE THREAD

**Issue by caicaiget** [OpenIntelWireless/itlwm#587]
**Have You Read Our Docs**
Yes 

**Are You Reporting A Bug**
Yes 

**Environment**

- Kext Version:  1.3.0 稳定版  airportitlwm bigsur
- WiFi Card Model:  AC9560 
- Product ID:  0x8086, 0x2A4
- macOS Version:  big sur 11.3.1
- Opencore Version:  0.6.8 稳定版

**Description**
airportitlwm连接不上2.4Gwifi，只能连接5Gwifi 

**Bug Report Archive**
运行时log
[Report_2021-05-07_12-40-42.log](https://github.com/OpenIntelWireless/itlwm/files/6439058/Report_2021-05-07_12-40-42.log)
加载日志
[Log_2021-05-10_15-55-10.log](https://github.com/OpenIntelWireless/itlwm/files/6456925/Log_2021-05-10_15-55-10.log)

**Kext Download Source**
github release

**Comment by zxystd** [comment]
请按照issue模板提供信息，不要浪费大家的时间，谢谢。

**Comment by zxystd** [comment]
@caicaiget

**Comment by caicaiget** [comment]
@zxystd 请问还有什么需要提供的吗？

**Comment by caicaiget** [comment]
@zxystd 请问这个能重现我这个问题不，不能的话我可以配合你测试。

**Comment by zxystd** [comment]
你试试在路由器中禁用2.4g的40mhz，看看是不是可以连上了

**Comment by caicaiget** [comment]
好的，我明天才有机会去尝试，我最近试了itlwm.kext，发现这个也不能连接2.4G wifi 版本也是1.3.0以及2.0

**Comment by caicaiget** [comment]
airportitlwm.kext最近又发现一个问题，就是睡眠一个晚上过后，wifi会自动断开，第二天早上来需要重新连接，我不确定这是kext的原因还是big sur的原因。

**Comment by caicaiget** [comment]
昨天又发现一个问题，同一个wifi，我带着电脑走动十几米左右就会断开连接，需要重新手动连接wifi，wifi信号是满格的。
