### ISSUE TITLE
9260AC WIFI is not working.

### ISSUE THREAD

**Issue by WarsFeng** [OpenIntelWireless/itlwm#588]
**Have You Read Our Docs**
Yes

**Are You Reporting A Bug**
Yes

**Environment**

- Kext Version: v1.3.0 stable / v1.2.0 stable
- WiFi Card Model: Wireless-AC 9260
- Product ID:  Vendor: **0x8086**, Device: **0x2526**
- macOS Version: BigSur 11.2.3

**Description**

9260AC WIFI is not working.

**Bug Report Archive**
[bugreport_40165.zip](https://github.com/OpenIntelWireless/itlwm/files/6445249/bugreport_40165.zip)

**Kext Download Source**
https://github.com/OpenIntelWireless/itlwm/releases/tag/v1.3.0

**Comment by zxystd** [comment]
I am also using AC9260 for testing and it works fine.
can you help me to use this debug kext and then generate the log again? I need more  debug info, thanks. @WarsFeng 
[itlwm.kext.zip](https://github.com/OpenIntelWireless/itlwm/files/6447647/itlwm.kext.zip)

**Comment by WarsFeng** [comment]
This is the new kext log:
[bugreport_55517.zip](https://github.com/OpenIntelWireless/itlwm/files/6456048/bugreport_55517.zip)

bluetooth is working properly.

**Comment by zxystd** [comment]
@WarsFeng Have you tried linux, is this card work properly?

**Comment by WarsFeng** [comment]
Oh my god, linux-firmware(Ubuntu/Arch livecd) not work... not show WiFi device, but Windows works.

**Comment by zxystd** [comment]
@WarsFeng seems that your card didn't have REGULATORY section info, which is help to decide channel/country code. I think this is a bug about Linux iwlwifi or a hardware bug.
<img width="455" alt="image" src="https://user-images.githubusercontent.com/16227538/117762700-3b815880-b25c-11eb-8d2f-3894e86be12f.png">
I think you can see this error message in linux.

**Comment by zxystd** [comment]
@WarsFeng I have mod something, can you see if it can load?
[itlwm.kext.zip](https://github.com/OpenIntelWireless/itlwm/files/6456767/itlwm.kext.zip)

**Comment by zxystd** [comment]
@WarsFeng Hello?

**Comment by WarsFeng** [comment]
@zxystd It doesn't seem to load =.=, this is the new log:
[bugreport_55517.zip](https://github.com/OpenIntelWireless/itlwm/files/6471279/bugreport_55517.zip)

Want to give up and change ax200 QAQ.

**Comment by WarsFeng** [comment]
The manual load log is as follows:
```
Executing: /usr/bin/kmutil load -p /Users/wars/Downloads/itlwm.kext
Error Domain=KMErrorDomain Code=30 "Validating extension failed: Kext com.zxystd.itlwm v2.0.0 in executable kext bundle com.zxystd.itlwm at /private/var/db/KernelExtensionManagement/Staging/com.zxystd.itlwm.7LScJi/itlwm.kext:

Filesystem error: Invalid ownership (501:20) should be (0:0) on /private/var/db/KernelExtensionManagement/Staging/com.zxystd.itlwm.7LScJi/itlwm.kext
Filesystem error: Invalid ownership (501:20) should be (0:0) on /private/var/db/KernelExtensionManagement/Staging/com.zxystd.itlwm.7LScJi/itlwm.kext/Contents
Filesystem error: Invalid ownership (501:20) should be (0:0) on /private/var/db/KernelExtensionManagement/Staging/com.zxystd.itlwm.7LScJi/itlwm.kext/Contents/MacOS
Filesystem error: Invalid ownership (501:20) should be (0:0) on /private/var/db/KernelExtensionManagement/Staging/com.zxystd.itlwm.7LScJi/itlwm.kext/Contents/MacOS/itlwm
Filesystem error: Invalid ownership (501:20) should be (0:0) on /private/var/db/KernelExtensionManagement/Staging/com.zxystd.itlwm.7LScJi/itlwm.kext/Contents/Info.plist
Authenticating extension failed: Bad code signature" UserInfo={NSLocalizedDescription=Validating extension failed: Kext com.zxystd.itlwm v2.0.0 in executable kext bundle com.zxystd.itlwm at /private/var/db/KernelExtensionManagement/Staging/com.zxystd.itlwm.7LScJi/itlwm.kext:

Filesystem error: Invalid ownership (501:20) should be (0:0) on /private/var/db/KernelExtensionManagement/Staging/com.zxystd.itlwm.7LScJi/itlwm.kext
Filesystem error: Invalid ownership (501:20) should be (0:0) on /private/var/db/KernelExtensionManagement/Staging/com.zxystd.itlwm.7LScJi/itlwm.kext/Contents
Filesystem error: Invalid ownership (501:20) should be (0:0) on /private/var/db/KernelExtensionManagement/Staging/com.zxystd.itlwm.7LScJi/itlwm.kext/Contents/MacOS
Filesystem error: Invalid ownership (501:20) should be (0:0) on /private/var/db/KernelExtensionManagement/Staging/com.zxystd.itlwm.7LScJi/itlwm.kext/Contents/MacOS/itlwm
Filesystem error: Invalid ownership (501:20) should be (0:0) on /private/var/db/KernelExtensionManagement/Staging/com.zxystd.itlwm.7LScJi/itlwm.kext/Contents/Info.plist
Authenticating extension failed: Bad code signature}
```
