### ISSUE TITLE
ac9560网卡无法连接2.4gWi-Fi

### ISSUE THREAD

**Issue by Yep-Wei** [OpenIntelWireless/itlwm#589]
**Have You Read Our Docs**

yes
**Are You Reporting A Bug**

yes
**Environment**

- Kext Version: 2.0 alpha/1.3 stable
- WiFi Card Model: ac9560
- Product ID: 0x8086, 0x2A4
- macOS Version: Big Sur 11.3.1

**Description**

ac9560使用1.3稳定版和2.0测试版都无法连接2.4g的Wi-Fi，使用1.2的驱动可以连接但是切换网络需要手动续租dhcp，且无法通过直接点击个人热点来连接，需要在其他网络手动输入ssid和密码
<img width="1008" alt="截屏2021-05-11 下午2 42 47" src="https://user-images.githubusercontent.com/26838085/117770134-2958e780-b267-11eb-83c5-649260bc2002.png">

这是airportitlwm的运行日志，希望能有帮助 

[Report_2021-05-11_14-25-07.log](https://github.com/OpenIntelWireless/itlwm/files/6457040/Report_2021-05-11_14-25-07.log)

**Bug Report Archive**

**Kext Download Source**

release发布页

**Comment by zxystd** [comment]
@caicaiget @Yep-Wei Try the latest alpha please.

**Comment by caicaiget** [comment]
@zxystd  现在可以连接2.4G wifi了。
