### ISSUE TITLE
AX200 Not working under 10.15.7

### ISSUE THREAD

**Issue by logibeak** [OpenIntelWireless/itlwm#591]
**Have You Read Our Docs**

**Are You Reporting A Bug**

**Environment**

- Kext Version: itwlm 1.3.0

- WiFi Card Model: AX200

- Product ID: 
![image](https://user-images.githubusercontent.com/58615441/118325868-1a29a200-b4d2-11eb-8a5a-521540fcc0e8.png)

- macOS Version: 10.15.7

-Intel Core i5-10400
-ASUS B460-I GAMING

**Description**
HeliPort reports itwlm is not running even though it is installed when checked

**Bug Report Archive**
[HeliPort_logs.log](https://github.com/OpenIntelWireless/itlwm/files/6481083/HeliPort_logs.log)
[itlwm_logs.log](https://github.com/OpenIntelWireless/itlwm/files/6481085/itlwm_logs.log)

**Kext Download Source**
https://github.com/OpenIntelWireless/itlwm/releases/download/v1.3.0/itlwm_v1.3.0_stable.kext.zip

**Comment by zxystd** [comment]
efi issue.
