### ISSUE TITLE
Kernel Panic On My Centrino N1000

### ISSUE THREAD

**Issue by dopaemon** [OpenIntelWireless/itlwm#598]
https://github.com/KernelPanic-OpenSource/hackintosh-HP-ProBook-640-G1  <----- My folder EFI Without KEXT wifi and bluetooth

i use itlwm and i get Kernel panic
This IntelBluetoothFirmware Kernel panic
And AirportItlwm + IO80211Family I get Kernel Panic, Pls help me check this

Very very Thanks

**Comment by williambj1** [comment]
Will reopen if panic logs are correctly provided.
