### ISSUE TITLE
Could you package them into an EFI driver for OC or Clover ?

### ISSUE THREAD

**Issue by 1457384613gh** [OpenIntelWireless/itlwm#608]
Could you package them into an EFI driver for OC or Clover ?
As is known to us, Macintosh can connect to the WiFi when user choose to boot a choice, which is used for booting from wireless network.
If them could be package into an EFI driver for both OC and Clover, everything would be superior and more similar to Macintosh.

**Comment by williambj1** [comment]
UEFI drivers are not the same as IOKit ones. Feel free to start a new project based on this one if you are interested.

**Comment by win1010525** [comment]
You should try by yourself before asking.
