### ISSUE TITLE
itlwm cause mac panic

### ISSUE THREAD

**Issue by zhoushiqian** [OpenIntelWireless/itlwm#609]
**Have You Read Our Docs**

Yes
**Are You Reporting A Bug**

Yes
**Environment**

- Kext Version: AirPortItlwm 1.3.0
- WiFi Card Model: intel
- Product ID: 7260AC
- macOS Version: 11.4

**Description**

panic(cpu 0 caller 0xffffff8005cbf0cb): itlwm: mac gone to sleep
Backtrace (CPU 0), Frame : Return Address
0xffffffb0b9c4b8e0 : 0xffffff8000c8e0dd 
0xffffffb0b9c4b930 : 0xffffff8000dd4f33 
0xffffffb0b9c4b970 : 0xffffff8000dc552a 
0xffffffb0b9c4b9c0 : 0xffffff8000c32a2f 
0xffffffb0b9c4b9e0 : 0xffffff8000c8d8fd 
0xffffffb0b9c4bb00 : 0xffffff8000c8dbf3 
0xffffffb0b9c4bb70 : 0xffffff800149d81a 
0xffffffb0b9c4bbe0 : 0xffffff8005cbf0cb 
0xffffffb0b9c4bc10 : 0xffffff8005cbf356 
0xffffffb0b9c4bc50 : 0xffffff8005cbf27e 
0xffffffb0b9c4bca0 : 0xffffff8005ce884a 
0xffffffb0b9c4bd70 : 0xffffff8005ce870d 
0xffffffb0b9c4bdb0 : 0xffffff8005cf7d00 
0xffffffb0b9c4bde0 : 0xffffff80013f4465 
0xffffffb0b9c4be50 : 0xffffff80013f4366 
0xffffffb0b9c4be80 : 0xffffff8000cd46c5 
0xffffffb0b9c4bef0 : 0xffffff8000cd5634 
0xffffffb0b9c4bfa0 : 0xffffff8000c3213e 
      Kernel Extensions in backtrace:
         com.zxystd.AirportItlwm(1.3)[A2ED57F8-46E0-3D99-A26D-55A1B1FD7873]@0xffffff8005c47000->0xffffff8006997fff
            dependency: com.apple.iokit.IO80211Family(1200.12.2b1)[0B5A2E80-490B-307B-B524-26379C9475CA]@0xffffff8002711000->0xffffff8002890fff
            dependency: com.apple.iokit.IONetworkingFamily(3.4)[B6F28D28-0733-3358-B9F0-0825BE36BD88]@0xffffff80034de000->0xffffff80034f4fff
            dependency: com.apple.iokit.IOPCIFamily(2.9)[99A70889-A31C-3B25-8E88-ADD3F317E4E4]@0xffffff800376a000->0xffffff8003792fff

Process name corresponding to current thread: kernel_task
Boot args: debug=0x100 igfxonln=1 alcid=3 igfxcflbklt=force -wegnoegpu chunklist-security-epoch=0 -chunklist-no-rev2-dev

Mac OS version:
20F71

Kernel version:
Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64
Kernel UUID: 52A1E876-863E-38E3-AC80-09BBAB13B752
KernelCache slide: 0x0000000000a00000
KernelCache base:  0xffffff8000c00000
Kernel slide:      0x0000000000a10000
Kernel text base:  0xffffff8000c10000
__HIB  text base: 0xffffff8000b00000
System model name: MacBookPro11,5 (Mac-06F11F11946D27C5)
System shutdown begun: NO
Panic diags file available: YES (0x0)
Hibernation exit count: 0

System uptime in nanoseconds: 4268800427001
Last Sleep:           absolute           base_tsc          base_nano
  Uptime  : 0x000003e1e85548da
  Sleep   : 0x0000000000000000 0x0000000000000000 0x0000000000000000
  Wake    : 0x0000000000000000 0x000000091e8904a1 0x0000000000000000
**Bug Report Archive**

**Kext Download Source**

**Comment by zxystd** [comment]
fix your system please.
