### ISSUE TITLE
英特尔 Wireless-AC 9462 wifi 经常断开

### ISSUE THREAD

**Issue by Ronein** [OpenIntelWireless/itlwm#611]
**Have You Read Our Docs**

yes
**Are You Reporting A Bug**

yes
**Environment**

- Kext Version:  AirportItlwm 1.30 （一开始用Itlwm 1.30 也同样问题才换的）
- WiFi Card Model: 英特尔 Wireless-AC 9462 
- macOS Version: 10.15.6

**Description**

wifi 正常联网约 3-5分钟后，会自动断开，然后重连，这个时候要么连不上，要么正常连上获取IP地址，但是无法访问互联网（如百度）
**Bug Report Archive**

**Kext Download Source**

https://github.com/OpenIntelWireless

**Comment by zxystd** [comment]
日志

**Comment by Ronein** [comment]
> 日志
我发现应该是公司网络问题，昨晚我在家用，一个晚上都是正常使用的。还是非常感谢大佬的付出！
