### ISSUE TITLE
正常使用，但是没有下载流量显示

### ISSUE THREAD

**Issue by GaryDoooo** [OpenIntelWireless/itlwm#615]
**Have You Read Our Docs**

读了
**Are You Reporting A Bug**

算个小bug吧
**Environment**
11.4黑苹果
- Kext Version: 1.3。0 
- WiFi Card Model: ac7260
- Product ID: 
- macOS Version: 11.4

**Description**

正常使用，速度没问题，也很稳定。但是用腾讯柠檬只显示上载流量，没有下载流量。换了iStat也是一样。之前用serria的时候，上下载流量都是正常显示的。

**Bug Report Archive**

**Kext Download Source**

都是在github上面下载的。

**Comment by zxystd** [comment]
<img width="340" alt="image" src="https://user-images.githubusercontent.com/16227538/120956030-507ed800-c785-11eb-8348-204d3c393496.png">
可以正常显示
