### ISSUE TITLE
Boot loop when booting macos in verbose mode

### ISSUE THREAD

**Issue by naveenkrdy** [OpenIntelWireless/itlwm#616]
**Have You Read Our Docs**
Yes

**Are You Reporting A Bug**
Yes

**Environment**

- Kext Version: latest [2.0.0 alpha](https://github.com/OpenIntelWireless/itlwm/commit/d97c0d23f5f52840282da4858de6e0800c1fdb7c)
- WiFi Card Model: AX200
- Product ID: 0x8086, 0x1654
- macOS Version: 11.4

**Description**
just updated to latest alpha and if i boot macos in verbose mode (-v) then it just boot loops with same message again and again as shown in below pic.

 
![IMG_2139](https://user-images.githubusercontent.com/18463250/121070330-33312480-c7ec-11eb-896a-e7fc48f034f0.jpg)

**Comment by t0niX** [comment]
Same with OpenCore 0.7.0 and AirportItlwm_v1.3.0_stable_BigSur.kext.zip.

Happened to me the first time after updating to OpenCore 0.7.0 today. After lots (~50) of loops MacOS finished booting though.

**Comment by naveenkrdy** [comment]
seems to be fixed now with latest commits 
thanks !

**Comment by t0niX** [comment]
This is not fixed with the latest official build. You might want to release a hotfix if you don’t plan to rollout a major update soon.

**Comment by t0niX** [comment]
I can confirm that the issue is not fixed in the latest alpha as well. I still get the boot loop.

Can you please re-open the issue - thanks.

**Comment by zxystd** [comment]
> I can confirm that the issue is not fixed in the latest alpha as well. I still get the boot loop.
> 
> Can you please re-open the issue - thanks.

what's your card?

**Comment by t0niX** [comment]
I‘m using an ASUS Z390 XI Maximus Hero Wifi.

The card is an Intel 9560.

**Comment by zxystd** [comment]
@t0niX I am rewriting the whole IntelBluetoothFirmware driver, although it is still in process, can you test it?
[IntelBluetoothFirmware.kext.zip](https://github.com/OpenIntelWireless/itlwm/files/6681630/IntelBluetoothFirmware.kext.zip)
