### ISSUE TITLE
Find it hard to connect a 802.1x network via a profile

### ISSUE THREAD

**Issue by richardkindom** [OpenIntelWireless/itlwm#618]
**Have You Read Our Docs**
Yes

**Are You Reporting A Bug**
Yes

**Environment**
MacOS 10.15.7

- Kext Version: 1.3.0Stable
- WiFi Card Model: 8260
- Product ID: 0x1130
- macOS Version: 10.15.7

**Description**
Find it hard to connect a 802.1x network via a profile. Sometimes connect/disconnect frequently to a 802.1x network after sleep.

**Bug Report Archive**
[itlwm.log](https://github.com/OpenIntelWireless/itlwm/files/6612655/itlwm.log)

**Kext Download Source**
On official GitHub page.

**Comment by richardkindom** [comment]
BTW: network name is Office and its MAC address has been shadowed due to privacy consideration.

**Comment by richardkindom** [comment]
Hello, after several trials, I found out this issue was related to v1.3.0 and above. So I guess this problem relied on implementation of frequency selection? Or something like this?
After all I rolled back to 1.2.0. And it works perfectly

**Comment by williambj1** [comment]
CC @zxystd

**Comment by zxystd** [comment]
@richardkindom I had tried v2.0.0-alpha with gen1 cards, and it works fine, have you try that?

**Comment by richardkindom** [comment]
> @richardkindom I had tried v2.0.0-alpha with gen1 cards, and it works fine, have you try that?

hey, finally I found out this issue was related to authentication hardware, not airportitlwm. So I would close this issue. Thanks for ur effort.
