### ISSUE TITLE
often needs to renew the dhcp lease after sleep or when switching to an access point

### ISSUE THREAD

**Issue by Enjoy-Combi** [OpenIntelWireless/itlwm#620]
[Log_2021-06-08_21-46-19.log](https://github.com/OpenIntelWireless/itlwm/files/6619200/Log_2021-06-08_21-46-19.log)

**Have You Read Our Docs**

Yes 

**Are You Reporting A Bug**

Yes
**Environment**

- Kext Version: 81    0 0                  0xd74000   0xd74000   com.zxystd.AirportItlwm (2.0.0) 46664866-845F-3ABC-8B51-49265E17F3F0 <80 46 14 6 5 3 1>
- WiFi Card Model: Intel Wireless-AC 9560
- Product ID: 0x8086 0x9DF0
- macOS Version: Mac OS Big Sur

**Description**

After sleep, the status of the connection appears active but sometime there is no connection. In that case I have to renew the dhcp lease and it works back.
Everytime I switch to an acces point (from a smartphone for instance), I have to renew the dhcp lease. If not the ip address, dns...are not updated to the one from the access point.

**Bug Report Archive**

**Kext Download Source**

I download the source from your github repository. Before that I add the same issue from a release from your github as well.
[AirItlDebug_2021-06-08_21-55-03.zip](https://github.com/OpenIntelWireless/itlwm/files/6619264/AirItlDebug_2021-06-08_21-55-03.zip)

**Comment by the-eric-kwok** [comment]
This is a known issue, related to #363

**Comment by williambj1** [comment]
There is an issue with using Apple Supplicant and setting the link status, still investigating.

**Comment by CoolApker** [comment]
可以试试手动填写IPv6地址，这样应该就不用每次都续租了。

**Comment by phu54321** [comment]
Looks like we have a new commit referencing this?

https://github.com/OpenIntelWireless/itlwm/commit/3e63230703f11d6daf13f5fa69d6e77a65b8cf3c

**Comment by williambj1** [comment]
> Looks like we have a new commit referencing this?
> 
> [3e63230](https://github.com/OpenIntelWireless/itlwm/commit/3e63230703f11d6daf13f5fa69d6e77a65b8cf3c)

Yes, please try

**Comment by zxystd** [comment]
Hi, is there any update about this issue?

**Comment by kidonng** [comment]
I can confirm DHCP works well with the latest commit 👍 Thanks @zxystd

**Comment by zxystd** [comment]
Ok, thank you.
