### ISSUE TITLE
AX200 Unstable Speed with <10Mbps 

### ISSUE THREAD

**Issue by samleong123** [OpenIntelWireless/itlwm#621]
**Have You Read Our Docs**

Yes

**Are You Reporting A Bug**

Yes

**Environment**

- Kext Version: 2.0.0 Alpha 
- WiFi Card Model: AX200
- Product ID: I don't know where to find it
- macOS Version: 11.4

**Description**

Unstable speed with speed below 10Mbps all the time 
My ISP provide me a 500Mbps synchronous speed
I can gain full speed via my iPad connected to the same 5GHz network and also ethernet to my computer
iPad : 
![Screenshot 2021-06-09 at 11 26 51](https://user-images.githubusercontent.com/58818070/121288320-c44fea80-c915-11eb-9330-210b42fa3a40.png)
Ethernet : 
![Screenshot 2021-06-09 at 11 27 56](https://user-images.githubusercontent.com/58818070/121288336-ca45cb80-c915-11eb-8410-bd31c0e3858d.png)
But when i connect to my computer , i can only get <10Mbps speed 
![Screenshot 2021-06-09 at 11 20 55](https://user-images.githubusercontent.com/58818070/121288166-7fc44f00-c915-11eb-897e-451df4020d11.png)
![Screenshot 2021-06-09 at 11 21 07](https://user-images.githubusercontent.com/58818070/121288173-82bf3f80-c915-11eb-9f91-f7ae21a8c1ed.png)

**Bug Report Archive**

[AirItlDebug_2021-06-09_11-30-15.zip](https://github.com/OpenIntelWireless/itlwm/files/6620920/AirItlDebug_2021-06-09_11-30-15.zip)

**Kext Download Source**

Github Releases , 9af1571

**Comment by williambj1** [comment]
Did you try itlwm instead of AirportItlwm?

**Comment by samleong123** [comment]
itlwm work perfectly 
![Screenshot 2021-06-09 at 13 34 16](https://user-images.githubusercontent.com/58818070/121299024-64623f80-c927-11eb-9558-1df237ba1d20.png)

so currently AirportItlwm will be more unstable than itlwm?

**Comment by williambj1** [comment]
AirportItlwm does a scan whenever airport requests it to do so. As a result, AirportItlwm scans much more frequently than itlwm, which significantly slows down the network speed, but there might be other issues involved as well.

**Comment by zxystd** [comment]
duplicate with #602
