### ISSUE TITLE
macos12下驱动竟然是工作的

### ISSUE THREAD

**Issue by liyulong214** [OpenIntelWireless/itlwm#623]
本人主板为ROG B360I，无线网卡型号Intel Wireless-AC 9560，macos12下一直显示无法连接wifi
但偶然的机会禁用有线，发现wifi竟然是通的，处了显示不正确，其他一切正常

**Comment by zxystd** [comment]
itlwm.kext是万金油，可以支持各个版本的macOS，只要苹果不修改以太网接口，不用更新就可以直接驱动。
