### ISSUE TITLE
蓝牙键盘(4.0、4.1、5.0)配对问题

### ISSUE THREAD

**Issue by caijillx** [OpenIntelWireless/itlwm#627]
**Have You Read Our Docs**
Yes
**Are You Reporting A Bug**
Yes
**Environment**

- Kext Version: 1.12
- WiFi Card Model: Intel ax201
- macOS Version: 10.15.6

**Description**
我发现很多支持蓝牙4.0、4.1、5.0的键盘在蓝牙连接时，绝大多数都是可以连接的，虽然能够成功打字，但键盘会一直处于配对模式。我大概试了5款左右的键盘，包括keydous，NIZ，雷蛇。目前未在蓝牙3.0的键盘上发现此问题。

**Comment by win1010525** [comment]
您分不清哪个仓库是蓝牙？

**Comment by caijillx** [comment]
> 您分不清哪个仓库是蓝牙？

chrome开太多窗口了，没注意，发完就发现了，直接关闭问题了，我不知道怎么取消问题。
