### ISSUE TITLE
AC9461 wifi on-off looping and disconnecting

### ISSUE THREAD

**Issue by Pl1y** [OpenIntelWireless/itlwm#628]
**Have You Read Our Docs**
Yes

**Are You Reporting A Bug**
Yes

**Environment**

- Kext Version: 1.2.0 and 1.3.0
- WiFi Card Model: Intel Wireless-AC 9461 Wireless Network Adapter
- PCI Product ID: PCI\VEN_8086&DEV_34F0&SUBSYS_02648086 and PCI\VEN_8086&DEV_34F0&CC_0280 
![2021-06-15 143151](https://user-images.githubusercontent.com/64156310/122071715-4305c580-cdf7-11eb-99cd-7784363dc9c3.png)

- macOS Version: 11.4 Big Sur

**Description**
When I connect to any of my two Wi-Fi networks, there are 3 possible outcomes:

1. the Wi-Fi connects, it says that everything is good, and then, after approx. 10 seconds or when I open something that needs internet, it loses the connection and stops showing the networks, sometimes it also says that Wi-Fi is off, then it enables Wi-Fi again and starts again from the beginning.
2. the Wi-Fi connects and stays connected, but it says that the internet isn't available
3. it tries to connect and pops up with the password window even though the network is saved and says: "Connection failed."

**Bug Report Archive**
([bugreport_51961.zip](https://github.com/OpenIntelWireless/itlwm/files/6656246/bugreport_51961.zip)

**Kext Download Source**
GitHub, releases page, itlwm_v1.3.0_stable.kext.zip and itlwm_v1.2.0_stable.kext.zip
Note: It happens with the same versions of AirportItlwm, too (I only used one at a time but I tried all four)

**Comment by zxystd** [comment]
Have you tried v2.0.0-alpha?

**Comment by Pl1y** [comment]
I have just now and its stuck on "calling mpo_policy_init for". [Here's the image of the panic.](http://imgur.com/a/L2slmgy)

**Comment by zxystd** [comment]
> I have just now and its stuck on "calling mpo_policy_init for". [Here's the image of the panic.](http://imgur.com/a/L2slmgy)

itlwm will never trigger such kind of error, it is most likely a user mistake.

**Comment by Pl1y** [comment]
The kext probably corrupted in the copying process because I transferred it from my phone, now I tried using a Linux boot USB and downloading from there and it still does it BUT after 3 minutes of trial and error, it finally connects once and it works after until I restart.

**Comment by JBramauer** [comment]
Sounds a lot like what's happening on the 9462 chips, probably related?
https://github.com/OpenIntelWireless/itlwm/issues/607
(Issue closed, even though it shouldn't be...)

**Comment by zxystd** [comment]
@Pl1y If the v2.0.0-alpha version is still having problems, please attach log, we don't know what is happening without log.

**Comment by kpostekk** [comment]
[AirItlDebug_2021-06-20_12-23-00.zip](https://github.com/OpenIntelWireless/itlwm/files/6682107/AirItlDebug_2021-06-20_12-23-00.zip)

As far I remember from #607, only some network types were affected. For me 2.4 and 5GHz standalone routers work fine, but not mesh network.

**Comment by zxystd** [comment]
Seems that there is really exists problems on AC9461/9462, but I don't know what's wrong, so I need more online testing and logs feedback(I don't have neither of the two cards), is anyone can help here?

**Comment by kpostekk** [comment]
I can send some logs.

**Comment by zxystd** [comment]
I think I got it working now, please check and test. @kpostekk @JBramauer @Pl1y 
[fix.zip](https://github.com/OpenIntelWireless/itlwm/files/6868076/fix.zip)

**Comment by ultinux** [comment]
@zxystd I was having the same issue with ac9462 https://github.com/OpenIntelWireless/itlwm/issues/652, 
and just tried your file. It is working flawlessly now! Thanks.

**Comment by kpostekk** [comment]
Works for me too. Connected quickly, no performance issues. Everything works fine.

![Screenshot 2021-07-23 at 17 16 25](https://user-images.githubusercontent.com/30326322/126803443-aece5543-d93f-4044-a454-6f9e9c2f708a.png)
![Screenshot 2021-07-23 at 17 17 14](https://user-images.githubusercontent.com/30326322/126803554-5b49fdc0-92ec-4ec0-b1ae-f1f9ffa5a4f3.png)

**Comment by JBramauer** [comment]
Is the fix merged into the latest alpha already or should I try the fix.zip from this issue thread?

**Comment by zxystd** [comment]
@JBramauer It is merged now.

**Comment by zxystd** [comment]
@kpostekk OK, thank you for the testing and feedback!

**Comment by JBramauer** [comment]
@zxystd today's Alpha build is working fine on 9462 as well. Quite a speed improvement over 1.2.0 stable (which was the latest version working on 9462 prior to this fix). Thank you!

**Comment by zxystd** [comment]
Fixed in 375d8a514b7772133e233135ab636a458e69447c, thank you all.
