### ISSUE TITLE
can't be turn wifi on after turn off wifi on heliport

### ISSUE THREAD

**Issue by yaza-putu** [OpenIntelWireless/itlwm#629]
**Have You Read Our Docs**
Yes

**Are You Reporting A Bug**
Yes

**Environment**

- Kext Version: V1.3.0
- WiFi Card Model: Intel(R) Centrino(R) Advanced-N 6205
- Vendor ID : 0x8086
- Device ID : 0x0085
- macOS Version: 10.15.7 (Catalina)

**Description**
After click turn off wi-fi in heliport , turn off wi-fi is success but after turn off i will turn on this wifi and i click a turn wi-fi on in heliport, wifi can't be turn on, LED turn off in my laptop

I restart this laptop , after restart wifi is turn-on.

Thanks

**Comment by williambj1** [comment]
No logs, closed.
