### ISSUE TITLE
Intel 9560ngw Catalina, it has bluetooth but can not detect the wifi....

### ISSUE THREAD

**Issue by JonathanSum** [OpenIntelWireless/itlwm#633]
IntelBluetooth.zip
AirportItlwm_v1.3.0_stable_Catalina.kext.zip
itlwm_v1.3.0_stable.kext.zip
I installed the brcm bluetooth and wifi first, but later I found out my card is intel. Thu, I installed the intel wifi and Bluetooth after. But I found out the Bluetooth works but not the wifi.

**Comment by williambj1** [comment]
Wrong issue format and no logs. Sorry but this issue will be closed.
