### ISSUE TITLE
QCA9377_WiFi_use

### ISSUE THREAD

**Issue by dzoo15** [OpenIntelWireless/itlwm#635]
information:
laptop_i5_7300HQ_HD630 for WiFi connect problem.I add airportitlwm.kext and itlwm(test for one by one) it look don't work for my laptop that used the stable vosion.

**Environment**

- Kext Version: 1.30stable
- WiFi Card Model: qca9377
- PCI Product ID: i5_7300HQ_HD630
- macOS Version:catalina10.15.7

**Comment by zxystd** [comment]
QCA means Qualicom cards, not Intel.
