### ISSUE TITLE
Very slow speed on intel 9260

### ISSUE THREAD

**Issue by guestofhonor3000** [OpenIntelWireless/itlwm#639]
I know it is a known issue, but I wasn't expecting such slow speed, from 60Mbps to 5Mbps. I just want to know if it is a issue from my other kexts(thinking that the ethernet kext might be the problem) or if i should upgrade to alpha 2.0?

Kexts: AppleALC, AppleMCEReporterDisabler, Lilu, SmallTreeIntel, VirtualSMC, WhateverGreen

**Comment by williambj1** [comment]
Have you tried v2.0.0 before? Closing since this is not a valid report.
