### ISSUE TITLE
Please, can you adapt quickly for AX210.

### ISSUE THREAD

**Issue by FuJin888** [OpenIntelWireless/itlwm#640]
**Have You Read Our Docs**

**Are You Reporting A Bug**

**Environment**

- Kext Version: 
- WiFi Card Model: 
- PCI Product ID: 
- macOS Version: 

**Description**

**Bug Report Archive**

**Kext Download Source**

**Comment by williambj1** [comment]
Feel free to submit a patch

**Comment by win1010525** [comment]
Please, can you adapt quickly for AX210? @FuJin888 We are waiting for your PR!
There’s no point in asking others to work for you, as we don’t have a card!

**Comment by FuJin888** [comment]
> 请问，你能快速适应AX210吗？@FuJin888我们在等你的公关！
> 要求别人为你工作是没有意义的，因为我们没有卡！
Sorry, looking forward to the good news from your team, I have troubled you all.
