### ISSUE TITLE
黑果启动时的Wi-Fi问题

### ISSUE THREAD

**Issue by CANBAAA** [OpenIntelWireless/itlwm#641]
**Have You Read Our Docs**
 Yes

**Are You Reporting A Bug**
 Yes

**Environment**

- Kext Version:  v1.3.0 stable
- WiFi Card Model:  ax200
- PCI Product ID: 
- macOS Version:  Catalina 10.15.7

**Description**
- 开机后，在登陆页面显示Wi-Fi已经连接
   ![IMG_0965](https://user-images.githubusercontent.com/39176450/124701133-9a8fe080-df20-11eb-8d03-0312c850c1e5.JPG)
- 输入密码进入桌面后，需要重新连接Wi-Fi
  ![IMG_0966](https://user-images.githubusercontent.com/39176450/124701149-a7accf80-df20-11eb-8378-00608a9d7bbd.JPG)

**Comment by Derekxxzzyy** [comment]
2.0.0 debug把这个问题解决了

**Comment by zxystd** [comment]
Status in login windows is not the real.
