### ISSUE TITLE
AC9560 使用 AirportItlwm v2.0.0-alpha 22a83ab 连接不上wifi

### ISSUE THREAD

**Issue by caicaiget** [OpenIntelWireless/itlwm#642]
**Have You Read Our Docs**
YES

**Are You Reporting A Bug**
YES

**Environment**

- Kext Version:   AirportItlwm   v2.0.0-alpha 22a83ab
- WiFi Card Model:  AC9560
- PCI Product ID: 
- macOS Version: BigSur 11.4

**Description**
AirportItlwm
使用最新的v2.0.0-alpha 22a83ab 会连接不上wifi。
使用  以前的版本 v2.0.0-alpha 858c31a 可以连接上

**Bug Report Archive**
[Log_2021-07-08_20-36-23.log](https://github.com/OpenIntelWireless/itlwm/files/6784664/Log_2021-07-08_20-36-23.log)

**Kext Download Source**
github

**Comment by zxystd** [comment]
你确定？有没有再换回最新的测试一遍看看

**Comment by caicaiget** [comment]
测试过了，采用目前最新的kext会连接不上，状态是wifi已连接，但是无法连接互联网，并且没有ip地址。

**Comment by zxystd** [comment]
已连接跟你说的这个问题是两码事

**Comment by caicaiget** [comment]
好的，请问有排查到是什么问题导致的吗

**Comment by zxystd** [comment]
3e63230703f11d6daf13f5fa69d6e77a65b8cf3c 这个提交修改了连接状态，但是内测群的群友都测试过了没有问题（mac10.15，mac11，mac12），而且可以正常DHCP。

**Comment by caicaiget** [comment]
有没有用AC9560测试呢，或者还需要我提供日志配合调查。

**Comment by caicaiget** [comment]
![截屏2021-07-12 下午6 11 28](https://user-images.githubusercontent.com/40875969/125278005-c35f0e00-e344-11eb-9b09-4c2f9f50147a.png)
刚开机会遇到zh这个情况。我换了个wifi就好了。

**Comment by caicaiget** [comment]
我刚刚测试，开机启动，连接5Gwifi就会这样，有ip地址，无法连接互联网，切换为2.4G就好了就可以连接成功。
![Uploading 截屏2021-07-12 下午7.08.16.png…]()

**Comment by caicaiget** [comment]
感觉像是开机后的首次连接会有问题，可以通过切换wifi解决

**Comment by zxystd** [comment]
内测群

1132224334

**Comment by caicaiget** [comment]
申请了，同意一下。
