### ISSUE TITLE
a mistake in Mojave with OC v0.6.0

### ISSUE THREAD

**Issue by pzw1999** [OpenIntelWireless/itlwm#644]
yesterday I set macos 10.14.6 on my matebook  which version is 2019,the wifi wasn't work.i can not notice the wifi ico in the status bar.Network setting has not wifi option,either.Airportitlm version is 1.3 on Mojave,i do not know what shohld i do next.Appreciate for your help.
ps. matebook hardware list:
CPU:i3 of 8th
RAW:8g
GPU:UHD 620
networkcard:9560
hard disk:rc500
![1626049542502](https://user-images.githubusercontent.com/50543440/125214649-d35fea80-e27d-11eb-9578-157971cfd31b.jpg)
![1626049574343](https://user-images.githubusercontent.com/50543440/125214668-dfe44300-e27d-11eb-8c9e-63ac1148ea7d.jpg)
![Uploading 1626049628135..jpg…]()

**Comment by zxystd** [comment]
Works fine on Mojave.

**Comment by pzw1999** [comment]
clover or OC?
