### ISSUE TITLE
always rest and hard connect N7265

### ISSUE THREAD

**Issue by edwardwich** [OpenIntelWireless/itlwm#649]
**Have You Read Our Docs**
Yes

**Are You Reporting A Bug**
Yes

**Environment**
Kext Version: v2.0.0-alpha/v1.3.0 stable
WiFi Card Model: Intel Wireless-N 7265 Wireless Network Adapter
PCI Product ID: 0x8086 0x95A
macOS Version: 11.4 (20F71)
Description

**Description**

rest when connect to home wifi(show no ip adders)and rest after show this  
in v1.3 dont show any wifi and if show my wifi rest( no ip adders)Find it hard to connect a 802.1x network via a profile
in  v2.0.0-alpha show all wifi and only have rest problem 

PLZ Help
![Screen Shot 2021-07-18 at 3 13 17 PM](https://user-images.githubusercontent.com/35195176/126064443-96f64bfd-452d-4190-b15c-7d3a1f96c341.png)
![Screen Shot 2021-07-18 at 3 13 20 PM](https://user-images.githubusercontent.com/35195176/126064449-06263941-1957-4c8a-88bf-c97c8feb44b5.png)

**Kext Download Source**
https://github.com/OpenIntelWireless/itlwm/releases

**Comment by williambj1** [comment]
No logs.
