### ISSUE TITLE
The error occurs when I use wifi and bluetooth headphone at the same time at 2.4GHz band.

### ISSUE THREAD

**Issue by 19521679** [OpenIntelWireless/itlwm#650]
My wifi device is intel 9461, bluetooth kext ver: 1.1.3 and all versions airportiltwm , when i was using soundpeat MAC headset and connect wifi on same 2.4GHz band the, 1 of 2 lost connection or was very weak. This does not happen when I use the 5GHz band.

**Comment by williambj1** [comment]
Physical limitation, use 5GHz instead.
