### ISSUE TITLE
VT-D on ?

### ISSUE THREAD

**Issue by Omanuar** [OpenIntelWireless/itlwm#654]
**Have You Read Our Docs**
<!---Yes ---!>

**Are You Reporting A Bug**
<!---Yes---!> 

**Environment**

- Kext Version: 1.3.0
- WiFi Card Model: cnvi GB aorus z390
- PCI Product ID: 
- macOS Version: 11.5

**Description**
BIOS CPU -VT-D enable (for apple thunderbolt ethernet adapter to load driver) unload itlwm.kext.
Can load both?

**Comment by Omanuar** [comment]
Hopefully it not   bother... i did no understand why invalid?
Only When I disable VT-d at cpu bios itlmw back running .
Is there a demand vt-d disable for itlmw to load?
Thanks ahead.

**Comment by williambj1** [comment]
VT-D is not required. The invalid is marked as invalid since it did not come with a correct format and did not contain any logs.
