### ISSUE TITLE
ax210 在网速跑满的情况下(例如网络测速)可能突然造成电脑卡死

### ISSUE THREAD

**Issue by FuJin888** [OpenIntelWireless/itlwm#655]

**Comment by win1010525** [comment]
新版应该不会了啊

**Comment by win1010525** [comment]
如果什么都不提供的话，我们只能close掉这个issue

**Comment by williambj1** [comment]
Invalid issue format

**Comment by FuJin888** [comment]
> 卡死具体指的是什么，方便提供一下kp日志吗？

[wifi的副本.log](https://github.com/OpenIntelWireless/itlwm/files/6950096/wifi.log)
你好 ni xu yao你需要的是这个吗 我也不太懂你需要的是啥 我刚入手黑苹果 小白一个

**Comment by win1010525** [comment]
看doc.
