### ISSUE TITLE
AC9260ngw not detected

### ISSUE THREAD

**Issue by calibra43** [OpenIntelWireless/itlwm#661]
**Have You Read Our Docs**

**Are You Reporting A Bug**

**Environment**

- Kext Version: 2.0
- WiFi Card Model: intel ac9260ngw
- PCI Product ID: pci 8086 2526
- macOS Version: 10.15.7 catalina and big sur 11.3

**Description**
HI. my pc not detected wifi card.i read log 
 itlwm: itlwm: failed to read nvm 
What solution for repaired?
Thanks
[Log_2021-08-12_19-07-55.log.zip](https://github.com/OpenIntelWireless/itlwm/files/6977399/Log_2021-08-12_19-07-55.log.zip)
![Снимок экрана 2021-08-12 в 19 28 57](https://user-images.githubusercontent.com/88733593/129241720-11d5952c-9eb0-4438-9cdd-682c3a971b34.png)

**Comment by williambj1** [comment]
Hi, could you please check if wifi works in Linux as well? Looks like the card is locked into airplane mode.

**Comment by calibra43** [comment]
Ubuntu 21.04
Carte not detected,just detect Windows

**Comment by williambj1** [comment]
> Ubuntu 21.04
> Carte not detected,just detect Windows

Unfortunately this is a hardware issue and we can't do anything from our side. Consider contacting the OEM for help.

**Comment by calibra43** [comment]
Hardware intel wifi? or Pc?
Thank you

**Comment by williambj1** [comment]
We are not sure either, maybe consider checking both.

**Comment by calibra43** [comment]
i bought another card. Intelc ac3165.will install let you know
Thank you for support
