### ISSUE TITLE
Bluetooth headphone signal is weak

### ISSUE THREAD

**Issue by ftitreefly** [OpenIntelWireless/itlwm#662]
**OS**: MacOS Big Sur 11.2.3
**WIFI+BLUETOOTH Adapter**:  Intel AX200
**KEXT**: 2.0.0

Thanks for the **KEXT** you developed, which allows me to use Bluetooth on my hackintosh.

My Bluetooth headset - *AirPods2* - is working properly，but when I am about 5-6 meters away from the Bluetooth adapter, the Bluetooth signal will automatically disconnect. 

I press *OPTION* button and click the bluetooh icon in the upper right corner, the RSSI value always displays 0 dBm, whether the signal connection was successful or not.

Are there any good solutions?

**Comment by williambj1** [comment]
Unfortunately there isn't. Does it perform the same in Windows? Are you using 2.4GHz Wi-Fi at the same time?

Closed since it is unrelated to this kext, which is only a firmware uploader, read the docs for more info.
