### ISSUE TITLE
Building error

### ISSUE THREAD

**Issue by startergo** [OpenIntelWireless/itlwm#663]
May I suggest adding ```$(SRCROOT)/MacKernelSDK-master/Headers``` to the ```System Header Search Path``` in the ```Search Paths``` to enable successful build after adding ```MacKernelSDK``` to the project folder?
Without it it will not correctly build.

**Comment by zxystd** [comment]
The SDK name is `MacKernelSDK`, not `MacKernelSDK-master`. User mistakes are out of our control and we will not considering about that.
Anyway, thank you for the advice.

**Comment by startergo** [comment]
It depends. I download the ```MacKernelSDK-master``` from source so that is how it is labeled by default in my folder. It can be renamed of course. My point is that ```MacKernelSDK``` is not set by default in the search path and the user has to add it before the building process.

**Comment by williambj1** [comment]
It has, otherwise it won't compile at all. Read the Xcode project file and the GitHub Actions yaml for details.

**Comment by zxystd** [comment]
```
git clone https://github.com/OpenIntelWireless/itlwm.git
cd itlwm
git clone --depth=1 https://github.com/acidanthera/MacKernelSDK.git
```
This is the correct usage of GitHub project.
