### ISSUE TITLE
[Help] Heliport wifi not turning on

### ISSUE THREAD

**Issue by hanlywijaya** [OpenIntelWireless/itlwm#664]
**Describe the bug**
I try to turn on wifi but nothing happens. Have tried injecting IOFamily80211.kext but nothing.
**To Reproduce**
1. Use Opencore
2. Force enable IOFamily80211.kext
3. Install heliport and itlwm.kext
4. Try to enable or connect to other networks

**Expected behavior**
I expect the wifi to turn on and show all available networks.
**Screenshots**

**Environment (please complete the following information):**
 - OS Version: 11.5.2
 - Software Version: latest stable of 18 Aug 2021

**Additional context**
When attempt to connect with other networks, it does the connecting animation repeatedly. I can check what model of wifi card of intel I have and send a log if needed.

**Comment by williambj1** [comment]
Use other sources for personal help.
