### ISSUE TITLE
[Feature] OpenWirelessLink with OpenIntelWireless

### ISSUE THREAD

**Issue by JJTech0130** [OpenIntelWireless/itlwm#665]
[OpenWirelessLink](https://seemoo-lab/owl) is an open source version of Apple Wireless Direct Link that allows you to use their [open-source reimplementation of AirDrop](https://github.com/seemoo-lab/opendrop). This would allow users to use AirDrop, even when using itlwm+HeliPort, and would make the entire thing independent from IOFamily patching.

Obviously this would require some work, and not all wireless cards would be supported, but I wanted to make you aware of the possibility.

**Comment by JJTech0130** [comment]
Just saw https://github.com/OpenIntelWireless/HeliPort/issues/144. Can this be done completely in the user-space, without changes to the kernel driver? Need to investigate.

**Comment by zxystd** [comment]
@JJTech0130 No, `owl` projects use active monitor mode to listen and inject frames to communicate with other Apple devices, most of the wireless cards don't support active monitor mode(be careful to distinguish with monitor mode), so does Intel card.
Too much works(P2P client, P2P GO, AWDL, NAN etc.) should be done in driver side and will affect the station mode(current itlwm framework is not satisfied with the works). I don't have too much effort and time to focus on doing these works.
