### ISSUE TITLE
5Ghz wifi can't get an IP using kext version 2.0.0 and up.

### ISSUE THREAD

**Issue by DLordStarkiller** [OpenIntelWireless/itlwm#667]
**Have You Read Our Docs**
Yes

**Are You Reporting A Bug**
No / Not sure if this is a bug

**Environment**

- Kext Version: 2.0.0 & 2.1.0 alpha
- WiFi Card Model: Intel Wireless 3160 AC
- PCI Product ID: 0x8086
- macOS Version: 11 Big Sur

**Description**
5Ghz wifi can't get an IP address when using kext version 2.0.0 and up. Downgrading to 1.3.0 gets an IP no problem 

**Kext Download Source**
From this GitHub page

**Comment by williambj1** [comment]
Will reopen once logs are correctly provided.
