### ISSUE TITLE
ipv6网速特别慢

### ISSUE THREAD

**Issue by lifsux** [OpenIntelWireless/itlwm#668]
<img width="1552" alt="截屏2021-08-20 下午10 07 47" src="https://user-images.githubusercontent.com/16937498/130246891-76b21c6f-927a-4656-806d-f77f86be6378.png"><img width="1552" alt="截屏2021-08-20 下午10 11 59" src="https://user-images.githubusercontent.com/16937498/130246935-90e9cd7d-2ea9-4023-89f0-db2bceb281bc.png">
如图，版本itlwm: 2.1.0_217d74c fw: 34.0.1，macOS 12.0 Beta版(21A5304g)

**Comment by williambj1** [comment]
用户层与本驱动无关
