### ISSUE TITLE
Fix Supported Devices and general issues

### ISSUE THREAD

**Issue by Emanuele-1998** [OpenIntelWireless/itlwm#670]
![3EB365AB-25C5-4A08-8A8F-9361564E8FB9](https://user-images.githubusercontent.com/67318166/130411252-6f96a92f-7fb3-477a-b423-3aab9a1ce649.jpeg)
![2D21F363-C836-4EC4-B540-B815EE3AB266](https://user-images.githubusercontent.com/67318166/130411263-05ca9647-664f-4751-be3a-6fa7ffe48e61.jpeg)

Is the same, and fix this because is blank

https://openintelwireless.github.io/General/Issues.html

**Comment by williambj1** [comment]
No they are not, only Intel knows WTF is going on with the product names.

Will write the issue guideline eventually, if I have enough free time lol.

Anyways, thanks for your feedback.
