### ISSUE TITLE
Intel wireless 8260 

### ISSUE THREAD

**Issue by alkindivv** [OpenIntelWireless/itlwm#675]
**Have You Read Our Docs**

**Are You Reporting A Bug**

**Environment**

- Kext Version: 2.0.0 & 1.3.0
- WiFi Card Model: Intel Dual band Wirelees 8260
- PCI Product ID: 
- macOS Version: macOS Big Sur 11.2 and 11.5.2

**Description**

**Bug Report Archive**

Terminal Output 

**Kext Download Source**

**Comment by alkindivv** [comment]
[bugreport_20194.zip](https://github.com/OpenIntelWireless/itlwm/files/7150105/bugreport_20194.zip)

idk why the bug file, cannot be attach on the template

**Comment by zxystd** [comment]
@alkindivv please attach the pci info, you can get it with `Hackintool`, like below:
<img width="656" alt="image" src="https://user-images.githubusercontent.com/16227538/133010776-1563838c-9a90-4828-b19b-e0601b223002.png">
<img width="656" alt="image" src="https://user-images.githubusercontent.com/16227538/133010792-10e02a5b-5f12-45df-abec-17565ea79615.png">

**Comment by williambj1** [comment]
Closed due to inactivity.
