### ISSUE TITLE
No wifi after sleep

### ISSUE THREAD

**Issue by christianjosias** [OpenIntelWireless/itlwm#677]
Hi

Wifi is working great, but when it wakes up from sleep, then wifi does not work, then i have to reboot my laptop, and then it works again.

Best greetings from Christian Josiassen

**Comment by williambj1** [comment]
Logs?

**Comment by christianjosias** [comment]
Hi where do i find the logs?

**Comment by williambj1** [comment]
Please consider reading the docs and filling out the issue template correctly, thanks.
