### ISSUE TITLE
AirportItlwm无法正常使用，但是recovery可以

### ISSUE THREAD

**Issue by hgqyy** [OpenIntelWireless/itlwm#682]
**Have You Read Our Docs**
Yes

**Are You Reporting A Bug**
No

**Environment**

- Kext Version: 2.0.0
- WiFi Card Model: Centrino Ultimate-N 6300
- PCI Product ID: 
- macOS Version: 10.15.2

**Description**
itlwm + heilport 可以正常连接wifi, 但是过几分钟就掉线了。
AirportItlwm 根据教程修改配置后，重启报错：OC：Prelinked injection AirportItlwm.kext () - Invalid Parameter.   正常进入系统后网络配置里没有无线网卡，如果启动时选择recovery，则可以正常连接wifi，也没有报错，ping也正常。

**Comment by williambj1** [comment]
Read the docs.

**Comment by Jimmy-312** [comment]
我也一样，你怎么解决的
