### ISSUE TITLE
可以查看到wifi但是无法连接

### ISSUE THREAD

**Issue by MKingWang** [OpenIntelWireless/itlwm#686]
感谢开发者提供intel黑苹果驱动。
在使用您的驱动时遇到了一个问题，可以搜索都附近的wifi，但是无法进行连接。劳烦开发者帮忙指导一下，是哪里配置有问题。谢谢
网卡型号： intel 8260 ngw
操作系统：Mac os 11.2 
驱动版本： 2.0.0

![截屏2021-09-28 下午8 11 45](https://user-images.githubusercontent.com/32352403/135084330-ad2239a8-2322-422d-85d9-d81cef7e2725.png)
![截屏2021-09-28 下午8 12 34](https://user-images.githubusercontent.com/32352403/135084423-4b95f27b-1ece-4991-b729-d318a931bc2c.png)

**Comment by williambj1** [comment]
Invalid issue format
