### ISSUE TITLE
no networks

### ISSUE THREAD

**Issue by Cheesecake8069** [OpenIntelWireless/itlwm#690]
**Have You Read Our Docs**
yes

**Are You Reporting A Bug**
yes

**Environment**

- Kext Version: All
- WiFi Card Model: 7265AC
- PCI Product ID: 0x095a
- macOS Version: catalina 10.15.7

**Description**
the kext can see what card I'm using, the wifi infinity searches for networks but none ever show up, this was not an issue with clover, but since doing a clean install using open core 6.7.2 i haven't been able to connect to a single wifi network.

**Bug Report Archive**
[bugreport_14407.zip](https://github.com/OpenIntelWireless/itlwm/files/7265148/bugreport_14407.zip)

**Kext Download Source**
official GitHub

**Comment by Cheesecake8069** [comment]
![Uploading IMG_20211001_000134818.jpg…]()

**Comment by Cheesecake8069** [comment]
new symptom now m wifi won't even friggin turn on....... ergghhhhhhhhhh

**Comment by williambj1** [comment]
Sorry but this is not the right place for EFI related issues.

**Comment by Cheesecake8069** [comment]
I would love to know what user mistake I've made, my apple secure boot is enabled(j680).  sanity checker says my config.plist is fine. All my kexts load and report correctly. I just can't see networks.
