### ISSUE TITLE
Wise Tiger AX210NGW WIFI 6 on Big Sur

### ISSUE THREAD

**Issue by iii0s** [OpenIntelWireless/itlwm#693]
Hi;

I have downloaded the latest alpha release and tried it on my Asus Rog Hackintosh with the following WIFI card.
https://www.amazon.de/gp/product/B08NSSJNV1/ref=ppx_yo_dt_b_asin_title_o00_s00?ie=UTF8&psc=1

The thing is that it does not work if I boot into Big Sur directly, however, when I boot into Windows 10 and restart choosing Big Sur, the card works fine. I am actually writing this now using my Big Sur and connected to WIFI.

One thing I have noticed though is that I cannot connect to hidden networks!

I am not using the Airport version, but the itlwm v2.1.0-alpha.

Does this help anyway?

**Comment by williambj1** [comment]
Will consider reopening once the issue format is filled in properly with details and logs.
