### ISSUE TITLE
NUC 8 i5 英特尔 Wireless-AC 9560 网卡的蓝牙不稳定，无法连接蓝牙音响

### ISSUE THREAD

**Issue by yemingjkl** [OpenIntelWireless/itlwm#698]
**Have You Read Our Docs**

yes

**Are You Reporting A Bug**

yes
**Environment**

- Kext Version: 2.1.0
- WiFi Card Model: 英特尔 Wireless-AC 9560
- PCI Product ID: 0x15BE
- macOS Version: 11.6 (20G165)

**Description**

连接苹果鼠标键盘后，偶尔会出现开机之后蓝牙音响无法连接的问题，移除蓝牙设备之后会出现蓝牙设置界面卡死的现象，隔空投递可以发现设备，但无法传送内容，点击发送，目标设备不会有接受提示，使用iphone7 plus向黑苹果主机隔空投递图片，手机上显示等待接受，但黑苹果主机并无提示，隔空投递未曾正常运行过。
**Bug Report Archive**

**Kext Download Source**

**Comment by williambj1** [comment]
Read the docs for more info
