### ISSUE TITLE
[Bug] "itlwm is not running" even though kext is loaded

### ISSUE THREAD

**Issue by sataset** [OpenIntelWireless/itlwm#699]
**Have You Read Our Docs**
Yes

**Are You Reporting A Bug**
Yes

**Environment**

- Kext Version: 2.0.0 stable
- WiFi Card Model: Wi-Fi 6 AX201 160MHz
- PCI Product ID: 0x06F0
- macOS Version: 11.6

**Description**
I had working itlwm + HeliPort bundle but recently it stopped working: receiving HeliPort error message itlwm is not running. Kext is loaded:

![image](https://user-images.githubusercontent.com/28687456/137113219-b46f4091-fa1f-42cc-bd3a-64ddcfadb786.png)

From logs I see that firmware is not loaded / initialized:
```
[    3.404470]: itlwm: : could not load firmware
[    3.404657]: itlwm: : failed to load init firmware
```

I have more debug information uploaded to issue thread in HeliPort repo [HeliPort/#237](https://github.com/OpenIntelWireless/HeliPort/issues/237)

What I've done so far:

- went through troubleshooting page and found out that kext is loaded
- reset network configs
- updated all kexts
- updated OpenCore
- reinstalled itlwm
- tried AirportItlwm
- tried alpha versions of kexts
- WiFi is working in Linux and Windows
- updated macOS

**Bug Report Archive**
- [itlwm: bugreport_17847.zip](https://github.com/OpenIntelWireless/itlwm/files/7356315/bugreport_17847.zip)
- [AirportItlwm: Log_2021-10-18_15-06-58.log](https://github.com/OpenIntelWireless/itlwm/files/7362871/Log_2021-10-18_15-06-58.log)

Linux LiveCD logs:
- [lshw.log](https://github.com/OpenIntelWireless/HeliPort/files/7347737/lshw.log)
- [lsmod.log](https://github.com/OpenIntelWireless/HeliPort/files/7347738/lsmod.log)
- [modinfo.log](https://github.com/OpenIntelWireless/HeliPort/files/7347740/modinfo.log)
- [dmesg.log](https://github.com/OpenIntelWireless/HeliPort/files/7347741/dmesg.log)

Old initial logs:
- [bugreport_64734.zip](https://github.com/OpenIntelWireless/HeliPort/files/7337144/bugreport_64734.zip)

**Kext Download Source**
Official Github releases page

**Comment by sataset** [comment]
@williambj1 may be I can test something in the meantime we are waiting for @zxystd investigation?

**Comment by sataset** [comment]
Found an issue with similar symptoms but different log output: https://github.com/OpenIntelWireless/itlwm/issues/386

**Comment by Leslie-DD** [comment]
@sataset I got the same error, have you solved it?

**Comment by sataset** [comment]
@Leslie-DD not using Hackintosh right now but as far as I remember I followed the guide from scratch and had no problems with this card anymore. By looking at config now I see that I have used `AirportItlwm.kext`.
