### ISSUE TITLE
各位好，更新了1028晚上的最新版本之后，睡眠容易睡死，不过同时使用WiFi加蓝牙，蓝牙终于不断了（BugSur 11.5.2  [20G95]）

### ISSUE THREAD

**Issue by fredeason** [OpenIntelWireless/itlwm#703]
#网卡型号为：intel Dual Band Wireless-AC 7265
#详细的错误报告为：

panic(cpu 4 caller 0xffffff801507b640): itlwm: nic locks counter 0
Backtrace (CPU 4), Frame : Return Address
0xffffffa06acf3530 : 0xffffff8010e8e04d 
0xffffffa06acf3580 : 0xffffff8010fd4e13 
0xffffffa06acf35c0 : 0xffffff8010fc540a 
0xffffffa06acf3610 : 0xffffff8010e32a2f 
0xffffffa06acf3630 : 0xffffff8010e8d86d 
0xffffffa06acf3750 : 0xffffff8010e8db63 
0xffffffa06acf37c0 : 0xffffff801169dc0a 
0xffffffa06acf3830 : 0xffffff801507b640 
0xffffffa06acf3850 : 0xffffff801507b673 
0xffffffa06acf3880 : 0xffffff801507bcbd 
0xffffffa06acf38c0 : 0xffffff801507bcff 
0xffffffa06acf38f0 : 0xffffff80150817a9 
0xffffffa06acf3970 : 0xffffff801508211c 
0xffffffa06acf39b0 : 0xffffff80150aa460 
0xffffffa06acf39e0 : 0xffffff80150aa512 
0xffffffa06acf3a20 : 0xffffff80150af6fa 
0xffffffa06acf3a50 : 0xffffff80150b8d7c 
0xffffffa06acf3a80 : 0xffffff80150b8d3a 
0xffffffa06acf3ab0 : 0xffffff80136e9aad 
0xffffffa06acf3ae0 : 0xffffff80136eb38e 
0xffffffa06acf3b10 : 0xffffff80115f0aaf 
0xffffffa06acf3b70 : 0xffffff80136eb406 
0xffffffa06acf3bd0 : 0xffffff80136eb487 
0xffffffa06acf3bf0 : 0xffffff80136e506f 
0xffffffa06acf3c20 : 0xffffff80136e4a90 
0xffffffa06acf3c60 : 0xffffff80136e5b26 
0xffffffa06acf3c90 : 0xffffff80136eb38e 
0xffffffa06acf3cc0 : 0xffffff80115f0aaf 
0xffffffa06acf3d20 : 0xffffff80136eb406 
0xffffffa06acf3d80 : 0xffffff80136ee863 
0xffffffa06acf3dc0 : 0xffffff80115d3efc 
0xffffffa06acf3e60 : 0xffffff80115d3934 
0xffffffa06acf3e80 : 0xffffff8010ed4605 
0xffffffa06acf3ef0 : 0xffffff8010ed5574 
0xffffffa06acf3fa0 : 0xffffff8010e3213e 
      Kernel Extensions in backtrace:
         com.apple.iokit.IONetworkingFamily(3.4)[81C90C05-9E8E-30E7-AB18-C559422910E4]@0xffffff80136e0000->0xffffff80136f6fff
         com.zxystd.AirportItlwm(2.1)[849793EB-BE59-3986-B798-3C856E8A7C33]@0xffffff8014ffa000->0xffffff8015efffff
            dependency: com.apple.iokit.IO80211Family(1200.12.2b1)[D9018D72-BFC9-3615-8AA1-30D6A4A80BDF]@0xffffff8012913000->0xffffff8012a92fff
            dependency: com.apple.iokit.IONetworkingFamily(3.4)[81C90C05-9E8E-30E7-AB18-C559422910E4]@0xffffff80136e0000->0xffffff80136f6fff
            dependency: com.apple.iokit.IOPCIFamily(2.9)[F7AA4BAF-35CF-3784-A50C-5FD9CDCBE488]@0xffffff801396c000->0xffffff8013994fff

Process name corresponding to current thread: kernel_task

Mac OS version:
20G95

Kernel version:
Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:31 PDT 2021; root:xnu-7195.141.2~5/RELEASE_X86_64
Kernel UUID: FECBF22B-FBBE-36DE-9664-F12A7DD41D3D
KernelCache slide: 0x0000000010c00000
KernelCache base:  0xffffff8010e00000
Kernel slide:      0x0000000010c10000
Kernel text base:  0xffffff8010e10000
__HIB  text base: 0xffffff8010d00000
System model name: MacBookPro15,2 (Mac-827FB448E656EC26)
System shutdown begun: NO
Panic diags file available: YES (0x0)
Hibernation exit count: 0

System uptime in nanoseconds: 1876161042148
Last Sleep:           absolute           base_tsc          base_nano
  Uptime  : 0x000001b4d3e999f2
  Sleep   : 0x000001b49c8e1482 0x0000000048966f32 0x000001ab56e96754
  Wake    : 0x000001b49fb38788 0x00000000484f1218 0x000001b49cde4de7

**Comment by xiangfeidexiaohuo** [comment]
我ax200  蓝牙还是gg呢

**Comment by zfdx123** [comment]
> 我ax200蓝牙还是gg呢

log？

**Comment by zxystd** [comment]
@fredeason Any progress?

**Comment by fredeason** [comment]
> @fredeason Any progress?

已经完美修复了，感谢！！！我看包小了很多，是专为7265打包的版本么，哈哈哈

**Comment by zxystd** [comment]
> 已经完美修复了，感谢！！！我看包小了很多，是专为7265打包的版本么，哈哈哈

Thank you! Yes, Only for 7265. Close issue 3aab4a6952982db08922c42fca145e0bec82d2e2.
