### ISSUE TITLE
The WIFI signal cannot be searched

### ISSUE THREAD

**Issue by Smile9996** [OpenIntelWireless/itlwm#704]
**Have You Read Our Docs**

Yes
**Are You Reporting A Bug**

Yes
**Environment**
OpenCore 0.7.3，macOS 11.6，AirportItlwm2.1.0 alpha, Intel Wireless-AC 9560 160Mhz
- Kext Version: AirportItlwm2.1.0 alpha
- WiFi Card Model: Intel Wireless-AC 9560 160Mhz
- PCI Product ID: PCI\VEN_8086&DEV_A370&SUBSYS_00348086&REV_10
- macOS Version: macOS Big Sur 11.6

**Description**

After I updated this kext, my system recognized my wireless network card, the WIFI can be turned on and off normally, but the WIFI signal cannot be searched.
**Bug Report Archive**

None
**Kext Download Source**

This github.

**Comment by williambj1** [comment]
no logs
