### ISSUE TITLE
after sleep wifi not work

### ISSUE THREAD

**Issue by Edwardwich** [OpenIntelWireless/itlwm#716]
**Have You Read Our Docs**
Yes

**Are You Reporting A Bug**
Yes

**Environment**

- Kext Version: 2.1alpha
- WiFi Card Model: n-7265
- PCI Product ID: 0x095a
- macOS Version: Mac OS 12.1beta2

**Description**
after sleep wifi not work
and need tern off and on agin

**Bug Report Archive**

[Log_2021-11-22_12-04-05.log](https://github.com/OpenIntelWireless/itlwm/files/7579309/Log_2021-11-22_12-04-05.log)

 kextstat | grep -i "itlwm"
Executing: /usr/bin/kmutil showloaded
No variant specified, falling back to release
   85    0 0                  0xf11000   0xf11000   com.zxystd.AirportItlwm (2.1.0) D1540328-950C-36B0-B4D7-CA53AA299A58 <84 49 16 7 6 3 1>

![Screen Shot 2021-11-22 at 12 00 42 PM](https://user-images.githubusercontent.com/35195176/142828207-43c6615d-e135-44a1-a8e5-81348792c4b5.png)

![Screen Shot 2021-11-22 at 12 05 06 PM](https://user-images.githubusercontent.com/35195176/142828822-d9bb6b85-dc9b-4f75-b93f-8ad369c679e6.png)

**Kext Download Source**

<https://github.com/OpenIntelWireless/itlwm/releases>

**Comment by zxystd** [comment]
The log doesn't contains any useful information, you should collect the log ASAP the issue happened.

**Comment by Edwardwich** [comment]
> The log doesn't contains any useful information, you should collect the log ASAP the issue happened.

How ?
Can you send terminal Command ؟
