### ISSUE TITLE
Itlwm doesn’t work

### ISSUE THREAD

**Issue by CharlieJiangXXX** [OpenIntelWireless/itlwm#717]
This is a sample spam issue. Don’t close this, bat. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

For some reason the Wi-Fi on my intel card is not working after I installed AirportBrcmFixup! I tried to solve this by installing all of AiportItlwm, itlwm, and AirportOpenBSD simultaneously but that doesn’t work either. Help!

Logs:
![C9B92311-2A78-406C-B72C-F24770BA6F81](https://user-images.githubusercontent.com/45895922/142913271-62e62451-c349-4b3e-8c8d-2db2765bf2ea.jpeg)

**Comment by QSL1** [comment]
吃饭了！
