### ISSUE TITLE
Wifi doesn't work if not used with HeliPort

### ISSUE THREAD

**Issue by hellisabove** [OpenIntelWireless/itlwm#719]
**Have You Read Our Docs**
Yes

**Are You Reporting A Bug**
No

**Environment**

- Kext Version: 2.0.0
- WiFi Card Model: IWM
- PCI Product ID: 
- macOS Version: 11.6.1

**Description**
Until now, wifi worked without using heliport but I changed my EFI and now it doesn't work anymore without using heliport even the stable version

**Bug Report Archive**

**Kext Download Source**
https://github.com/OpenIntelWireless/itlwm/releases/tag/v2.0.0

**Comment by williambj1** [comment]
Edit the plist file
