### ISSUE TITLE
Intel(R) Centrino(R) Wireless-N + WiMAX 6150 0x0886

### ISSUE THREAD

**Issue by jief666** [OpenIntelWireless/itlwm#720]
Hi.
I have a Intel(R) Centrino(R) Wireless-N + WiMAX 6150, pci id 8086:0886.
It looks like it's in your compatibility list, but not in the pci id list in the source.

Is it supported ?

Thanks.

**Comment by zxystd** [comment]
[itlwm.kext.zip](https://github.com/OpenIntelWireless/itlwm/files/7655621/itlwm.kext.zip)
@jief666  Can you try this one?

**Comment by jief666** [comment]
Thanks. It kind of works.
I have variable ping time to my router. Can go from 15 ms to 300ms. Same computer with another card was always 15ms.
I'm testing it since 2 minutes. Once, packets stopped going through although HeliPort was still reporting the connection as connected. I turned wifi off and on and it came back.

**Comment by jief666** [comment]
Lost connection again, but it came back without me turning wifi off and on.

**Comment by zxystd** [comment]
can you please follow our doc to collect running logs when it is disconnected?

**Comment by jief666** [comment]
It's now running since 10 minutes. Ping time is still variable but mostly between 15 and 30ms. I've just thought trying Windows and ping time is also variable between 15-30ms.
I've just rebooted. Ping start go up to 800ms at first and seems to mostly decrease after few seconds.
I'm letting ping running to see if there is some break up.

**Comment by jief666** [comment]
Works ok since 26 minutes now...
Nice work. Thanks.

**Comment by zxystd** [comment]
@jief666 Can you help to test the latest v2.1.0-alpha version also works fine? Thank you.

**Comment by jief666** [comment]
Hi. I'm sorry. I wish I could help.
I installed the driver you sent me on my friend's computer. Now I'm away with no access to the computer anymore.

**Comment by zxystd** [comment]
@jief666 Ok, Thank you.
