### ISSUE TITLE
IP address shown 169.254.234.137 and no network connection

### ISSUE THREAD

**Issue by GiantTeddy** [OpenIntelWireless/itlwm#722]
**Have You Read Our Docs**

Yes

**Are You Reporting A Bug**

Yes

**Environment**

- Kext Version: v2.0.0 Stable Airpoditlwm
- WiFi Card Model:  Killer AX1650
- PCI Product ID: 0xa36d
- macOS Version: 11.6.1 BigSur

**Description**

When the laptop wake up from sleep, it sometimes will appear 169.254.234.137 as allocated IP address and no network connection. This can be fixed sometimes by delete and re-create the WIFI in Network Setting, but this is not always working. 

**Bug Report Archive**

Can not open HeliPort, shows itlwm is not working. 

**Kext Download Source**

[From release page of GitHub](https://github.com/OpenIntelWireless/itlwm/releases/download/v2.0.0/AirportItlwm_v2.0.0_stable_BigSur.kext.zip)

**Comment by zxystd** [comment]
No log.
