### ISSUE TITLE
Bigsur11.6.2 无法搜索到任何网络

### ISSUE THREAD

**Issue by LeoYule** [OpenIntelWireless/itlwm#724]
**Have You Read Our Docs**
<Yes>

**Are You Reporting A Bug**
<Yes>

**Environment**

- Kext Version: 2.0.0
- WiFi Card Model: 7265AC
- PCI Product ID: OEMN-By-HP-15-ax250wm
- macOS Version: 11.6.2

**Description**
搜索不到任何网络信号 但是确认已经驱动了kext 
![8611B378-0D9D-4C6D-83A4-EB742A1E8B52](https://user-images.githubusercontent.com/47467594/146752462-70e67523-cac6-438f-9b02-d6891adc9553.jpeg)
![8B2BA3A8-D60D-4237-B661-560BAB38A28E](https://user-images.githubusercontent.com/47467594/146752478-952bf7ce-0fcd-4109-86e4-bc231e997b97.jpeg)

**Comment by LeoYule** [comment]
不知道是不是国家码那里的问题 因为正常不应该显示ZZ啊 求大佬们解惑 谢谢！

**Comment by williambj1** [comment]
no logs
