### ISSUE TITLE
[Request] Hotspot not working...

### ISSUE THREAD

**Issue by gnpaone** [OpenIntelWireless/itlwm#729]
I am using the latest 2.1.0 Monterey Kext and I am in 12.1 version mac. I enabled hotspot (will be available in network and sharing settings), it gets enabled and AP is activated using SSID (according to the settings app) but the hotspot doesn't appear in any of my devices. (FYI there is no hide ssid option in mac ig)

**Comment by williambj1** [comment]
https://openintelwireless.github.io/itlwm/FAQ.html#can-i-use-it-to-create-a-personal-hotspot

**Comment by williambj1** [comment]
Won’t be supported in the near future due to the poor performance Intel cards provide in AP mode,
