### ISSUE TITLE
掉网卡，机器自动重启

### ISSUE THREAD

**Issue by SnowsonZ** [OpenIntelWireless/itlwm#735]
**Environment**

- Kext Version: 2.1.0
- WiFi Card Model: Wireless 8265/8275
- PCI Product ID: 0x8086 0x24FD
- macOS Version: 12.0.1

**Description**
 看网页视频时频繁出现掉网卡，机器自动重启。必现。

**Bug Report Archive**

**Log**
[Log_2022-01-12_18-34-59.log](https://github.com/OpenIntelWireless/itlwm/files/7853993/Log_2022-01-12_18-34-59.log)

[Log_2022-01-12_18-35-23.log](https://github.com/OpenIntelWireless/itlwm/files/7853994/Log_2022-01-12_18-35-23.log)

<img width="645" alt="Xnip2022-01-12_18-36-11" src="https://user-images.githubusercontent.com/12555482/149127901-c5d0bdfd-f328-4d28-b779-3f472103fd9f.png">

**Comment by zxystd** [comment]
机器自动重启以后弹框的内容呢？

**Comment by SnowsonZ** [comment]
> 机器自动重启以后弹框的内容呢？

你是说重启后提示发送给apple的log？

**Comment by SnowsonZ** [comment]
> 是的
[system.log](https://github.com/OpenIntelWireless/itlwm/files/7855875/system.log)

**Comment by SnowsonZ** [comment]
> 是的
看清晰度高(2k,4k)的视频更容易发生这个问题。

**Comment by zxystd** [comment]
哪个版本开始出现的这个问题，可以试一下2.0.0和1.3.0，看看是不是都有这个问题?

**Comment by SnowsonZ** [comment]
> 哪个版本开始出现的这个问题，可以试一下2.0.0和1.3.0，看看是不是都有这个问题?

2.0.0版本试过也有这个问题，1.3好像是没事。我再试一下。

**Comment by SnowsonZ** [comment]
> 哪个版本开始出现的这个问题，可以试一下2.0.0和1.3.0，看看是不是都有这个问题?

1.3没有Monterey版本

**Comment by zxystd** [comment]
@SnowsonZ 用itlwm.kext + Heliport试试吧，我让人测试了8k 4k视频播放都没有问题

**Comment by williambj1** [comment]
@SnowsonZ 方便进群测试吗 https://github.com/OpenIntelWireless/itlwm/issues/731#issuecomment-1008572120

**Comment by SnowsonZ** [comment]
> @SnowsonZ 方便进群测试吗 [#731 (comment)](https://github.com/OpenIntelWireless/itlwm/issues/731#issuecomment-1008572120)

已申请

**Comment by SnowsonZ** [comment]
> @SnowsonZ 方便进群测试吗 https://github.com/OpenIntelWireless/itlwm/issues/731#issuecomment-1008572120

又测了下，用chrome不会出现这个问题。safari必现

**Comment by williambj1** [comment]
duplicate of #730

**Comment by singhalrishi27** [comment]
You had private relay turned on?

**Comment by 778280151** [comment]
+1 同样的问题

**Comment by zhuofan-16** [comment]
+1 Same Issue Encountered, I am also using 8265
