### ISSUE TITLE
Wifi shows it is connected but doesn't work. 

### ISSUE THREAD

**Issue by CraftyCranberry** [OpenIntelWireless/itlwm#742]
Hi, I don't like to shutdown my laptop so I usually just close the lid to put it to sleep. I don't really know how to reproduce this, it happens randomly that the wifi toggle shows I'm connected to the wifi but if I try to load something like google.com, it doesn't load. Toggling off the wifi, tho the wifi toggle switches to off position , the wifi remains connected and the 3 signal bars stay there. Only a reboot fixes this!

I do not have any logs right now as it happens randomly, I'll try to grab them next time. But meanwhile, [here's](https://imgur.com/a/fY9rZTN) the wifi card that came with my laptop. And [this](https://drive.google.com/drive/folders/1p5BzVDh9_jvmC9zerKlp6BRRImyMvcu3?usp=sharing) is my EFI.

**Comment by stefan89** [comment]
Maybe a silly question, but is the card correctly wired? See red circle:
![Pop1uVV](https://user-images.githubusercontent.com/1457137/151758502-373edbb9-bb0a-4e54-b357-6ff02277fb0d.jpeg)

**Comment by stefan89** [comment]
PS. have you tried itwlm.kext instead of AirportItlwm.kext? If I understand it correctly, it should be more stable

**Comment by Fuzail-maker** [comment]
@stefan89 yup, the black antennae cable came out when I took the card out for taking a picture, I did put it back before installing it. Nope I haven't tried just the itwlm, ill have a look. Thanks

**Comment by stefan89** [comment]
If you're trying itwlm.kext, don't forget to install heliport app first: https://github.com/OpenIntelWireless/HeliPort

**Comment by Fuzail-maker** [comment]
@stefan89 ohh tysm, I'll try it tomorrow and update here

**Comment by Fuzail-maker** [comment]
@stefan [rip](https://i.imgur.com/qdIREfp.jpg) I am a student and I use the my university's wifi all the time. Unfortunately heliport doesn't support it :/

Works with airportitlwm tho.

**Comment by williambj1** [comment]
Please upload logs.
