### ISSUE TITLE
802.1x doesn't work in 2.2.0-alpha

### ISSUE THREAD

**Issue by terminet85** [OpenIntelWireless/itlwm#744]
**Have You Read Our Docs**
Yes

**Are You Reporting A Bug**
Yes
**Environment**

- Kext Version:  v2.2.0-alpha
- WiFi Card Model: Intel Wireless AC-7265
- PCI Product ID: PCI VEN 8086, DEV 095A
- macOS Version: 12.2

**Description**
802.1.x and iPhone paring doesn't work on 2.2.0-alpha. In 2.1.0 works but mostly buggy

**Comment by williambj1** [comment]
@terminet85 

> iPhone paring

Not sure what this means, could you please explain a bit more?

> In 2.2.1 works

AFAIK this version does not exist. Is it from another source?

Logs are mandatory to help identify the issue.

**Comment by terminet85** [comment]
> Not sure what this means, could you please explain a bit more?

I’m talking about Instant Hotspot 

> AFAIK this version does not exist. Is it from another source?

2.1.0 mistype…
 
> Logs are mandatory to help identify the issue.

no problem. Any hints or manual how to collect?

**Comment by williambj1** [comment]
> I’m talking about Instant Hotspot

Not supposed to work right now, you'll need to manually turn it on from your iPhone.

> no problem. Any hints or manual how to collect?

Can be found in the docs.

**Comment by williambj1** [comment]
@terminet85 Hi, any progress?

**Comment by terminet85** [comment]
Sorry I’m busy with my work… I’m closing this and make new one when I can.

**Comment by williambj1** [comment]
@terminet85  Just for ref, I've managed to successfully connect to a local library's Wi-Fi that uses 802.1x WPA2-Enterprise for authentication using AirportItlwm without facing any issues. Take your time and have a nice day.
