### ISSUE TITLE
Wifi only works on cold boot

### ISSUE THREAD

**Issue by murilopereirame** [OpenIntelWireless/itlwm#752]
**Have You Read Our Docs**
Yes

**Are You Reporting A Bug**
Yes

**Environment**

- Kext Version: 2.1.0
- WiFi Card Model: AX200
- PCI Product ID: 2723
- macOS Version: 12.2.1

**Description**
Wifi only works on cold boot, if I reboot the system it doesn't work anymore and when the wifi works the bluethooth doesn't connect to any device, when wifi doesn't work, the bluethooth works fine. I'm using the latest stable version of  Wifi and Bluethooth kext.

**Kext Download Source**
GitHub Release

**Comment by lim417dev** [comment]
I also encountered the situation that WiFi does not work. Bluetooth works normally. The configuration is the same as yours. There are the same problems with version 2.2

**Comment by williambj1** [comment]
Warm reboots from others OSes leaves the card with unsupported firmware and an unsupported states. Cold boots are always recommended when switching between OSes.

**Comment by murilopereirame** [comment]
I'm not switching OSes, the Wifi stop working after rebooting the OSX

**Comment by williambj1** [comment]
@murilopereirame Please provide logs after the reboot.
