### ISSUE TITLE
PCIE GC-WBAX200 (AX200) not working at all

### ISSUE THREAD

**Issue by joshhhhyyyy** [OpenIntelWireless/itlwm#755]
**Have You Read Our Docs**
Yes

**Are You Reporting A Bug**
Yes

**Environment**

- Kext Version: [v2.1.0 stable](https://github.com/OpenIntelWireless/itlwm/releases/tag/v2.1.0)
- WiFi Card Model: [GC-WBAX200](https://www.gigabyte.com/sg/Motherboard/GC-WBAX200-rev-10#kf)
- PCI Product ID: to be checked
- macOS Version: Tested on Big Sur and currently on Monterey 12.2.1

**Additional Info**
- Cpu: AMD 5600X (19h)
- Motherboard: Asrock X570M Pro4
- Bluetooth is functional and works great with bluetooth file transfer
- macos is the only os on the ssd (windows on different nvme ssd)

**Description**

Bluetooth works perfectly, but wifi doesnt show up in sysprefs or the menu bar icon, cant add it, system diagnostics dont show it.

Have tried installing normally, forcing loading, securebootmodel is set to default, fast boot is off, i have read the troubleshooting docs and have deleted all my preferences, nothing works

**My main question:**
```do PCIE wifi cards work?```
cus if not ill just pickup a m.2 ax200 card.

**Bug Report Archive**

Heliport says that Itlwm is not loaded even after i did the kextshow command with both “airportitlwm” and “itlwm” showed up properly. and no i did not install both at the same time and made sure to do command+r in propertree before rebooting. i am also using the monterey release and was using the big sur release when i was on big sur

**Kext Download Source**

prebuilt from https://github.com/OpenIntelWireless/itlwm/releases/tag/v2.1.0 (montrey airportitlwm and itlwm normal)

any and all help would be appreciated as appleigb doesnt work for me either so im stuck using a 100mbps usb ethernet dongle right now

**Comment by williambj1** [comment]
Please attach logs. If you're using Monterey make sure to use the latest build of DebugEnhaner from CI artifacts (not release).
