### ISSUE TITLE
英特尔 Wireless-AC 9560 

### ISSUE THREAD

**Issue by jlynet** [OpenIntelWireless/itlwm#758]
**Have You Read Our Docs**

**Are You Reporting A Bug**

**Environment**

- Kext Version: itlwm: 2.1.0_dc62349 fw: 34.3125811985.0
- WiFi Card Model: Wi-Fi  (0x8086, 0x34)
- PCI Product ID: 
- macOS Version: 12.2.1 (21D62)

**Description**

In the process of use, there will be the problem of sudden drive failure and sudden failure to drive.

**Bug Report Archive**

**Kext Download Source**

**Comment by zxystd** [comment]
log please?

**Comment by jlynet** [comment]
How to export this log?

**Comment by jlynet** [comment]
这个日志怎么导出啊？是在出问题情况下导出日志是吧！

**Comment by zxystd** [comment]
@jlynet 对，出问题了再导出日志，尽快操作，否则会被系统的其他日志刷掉。
导出方法：https://docs.oiw.workers.dev/itlwm/Troubleshooting.html#runtime-logs

**Comment by jlynet** [comment]
![image](https://user-images.githubusercontent.com/6250892/158925501-9c9917d0-6e8e-4744-8cf5-e1348153859e.png)
执行这些命令就可以了吗？

**Comment by zxystd** [comment]
[DebugEnhancer-1.0.6-DEBUG.zip](https://github.com/OpenIntelWireless/itlwm/files/8300401/DebugEnhancer-1.0.6-DEBUG.zip)
要先加载这个。
另外你可以换成2.1.0稳定版或者2.2.0-alpha版再试么？

**Comment by jlynet** [comment]
[Log_2022-03-21_11-06-17.log](https://github.com/OpenIntelWireless/itlwm/files/8312944/Log_2022-03-21_11-06-17.log)

日志导出了。使用的是2.1.0稳定版

**Comment by zxystd** [comment]
日志不对，debugenhance要用上

**Comment by jlynet** [comment]
执行：
```
sudo /System/Library/PrivateFrameworks/Apple80211.framework/Versions/A/Resources/airport debug +AllUserland +AllDriver +AllVendor
```
报错：
```
Unable to retrieve vendor debug flags...ignoring error.
Unable to set vendor debug flags...ignoring error.
```

**Comment by zxystd** [comment]
Can be reopened once the necessary information for this issue is provided.
