### ISSUE TITLE
Intel AC 9560 160 MHz dont scan wi-fi 

### ISSUE THREAD

**Issue by DinizDev** [OpenIntelWireless/itlwm#759]
**Have You Read Our Docs**

**Are You Reporting A Bug**

**Environment**

- Kext Version: airportlwm 2.1.0
- WiFi Card Model: Intel AC 9560 160mhz
- PCI Product ID: 0x8086 0x02F0
- macOS Version: Monterey 12.0.3

**Description**

**Bug Report Archive**
[Photo bug ](https://serving.photos.photobox.com/4416484417bd365a519507c55bee35f66dd806eb2f04baadc35f002646f84275f715a181.jpg) 

**Kext Download Source**

**Comment by zxystd** [comment]
log?
