### ISSUE TITLE
universal clipboard not fully working in monterey 12.3 

### ISSUE THREAD

**Issue by hohoho123456** [OpenIntelWireless/itlwm#761]
**Have You Read Our Docs**
Yes

**Are You Reporting A Bug**
Yes

**Environment**

- Kext Version: AirportItlwm-Monterey-v2.2.0-DEBUG-alpha-17f1d6f.zip
- WiFi Card Model: Intel Dual Band Wireless-AC 3160
- PCI Product ID: 0x24FB
- macOS Version: Monterey 12.3
![Screen Shot 2022-03-23 at 8 59 03 AM](https://user-images.githubusercontent.com/44559677/159602398-ecaba99e-42ac-4e7d-bfa5-71fb1ce112ad.png)

**Description**
universal clipboard only works one way: from ipad/iphone to mac. it doesn't work the other way: from mac to ipad and iphone. when i copy text from my macos 12.3 it doesn't get recognized on my ipad and iphone so i can't paste it. but when i copy from my ipad and iphone it gets recognized on my macos 12.3 and i can paste it on my macos 12.3.
- i already tried singing out from my icloud and singing back in from my mac and my ipad. and it's still the same.

**Bug Report Archive**

**Kext Download Source**
https://github.com/OpenIntelWireless/itlwm/releases - i downloaded the kext from here and installed it as it is without making changes to it.

**Comment by williambj1** [comment]
https://github.com/OpenIntelWireless/IntelBluetoothFirmware/issues/384
