### ISSUE TITLE
WIFI is frequently disconnected, but reconnects after a few seconds. （WI-FI频繁断线，但是几秒后会自动重连，循环往复）

### ISSUE THREAD

**Issue by KIKOcaoyue** [OpenIntelWireless/itlwm#762]
**Have You Read Our Docs**

Yes
**Are You Reporting A Bug**

Yes
**Environment**

- Kext Version: 2.2.0
- WiFi Card Model: intel 
- PCI Product ID: 
- macOS Version:  12.0.1

**Description**

WIFI is frequent disconnected, looks like the WIFI was restarting. The problem does not appear regularly, but it occurs everyday. 
**Bug Report Archive**

**Kext Download Source**

**Comment by zxystd** [comment]
掉线的日志呢？

**Comment by KIKOcaoyue** [comment]
> 掉线的日志呢？

日后收集到会反馈。
