### ISSUE TITLE
请问是否会造成win11 wifi重复断连两次

### ISSUE THREAD

**Issue by ghsssss** [OpenIntelWireless/itlwm#766]
win11 ax200经常性的断连，每次开机的时候，而且好像是进入macos以后造成的，
win11驱动版本：22.120.1.9
macos驱动版本：2.1.0

**Comment by williambj1** [comment]
File a report to intel.

**Comment by ghsssss** [comment]
[WlanReport.zip](https://github.com/OpenIntelWireless/itlwm/files/8457206/WlanReport.zip)
这个日志是否可以？

**Comment by ghsssss** [comment]
@williambj1

**Comment by ghsssss** [comment]
@zxystd
