### ISSUE TITLE
Network disconnection. Slow ping time.

### ISSUE THREAD

**Issue by jief666** [OpenIntelWireless/itlwm#768]
**Have You Read Our Docs**
Yes

**Are You Reporting A Bug**
Yes

**Environment**

- Kext Version: Airportitlwm 2.1
- WiFi Card Model: Wireless 3165
- PCI Product ID: 0x3165
- macOS Version: 10.14.6

**Description**
Network disconnection. Slow ping time.

I'm connecting to a hotel network. No encryption. There is 2 network with the same name (maybe that's the reason). It's working for some time, like 20 seconds. Then, the connection is lost. I have to turn wifi off and on. Sometime ping are good (30-50ms). Sometime it's very variable 100 to 300ms.
After few wifi on and off (3 to 5), it seems to work ok for a longer period with better ping time.

I've compared with a macbook on the same desk and also by rebooting on Windows without moving my computer.

To be able to write this, I had to turn on and off 4 times. It's now working perfectly.

I'll stay here only 4 days...

**Bug Report Archive**
[Log_2022-04-15_23-28-57.log.zip](https://github.com/OpenIntelWireless/itlwm/files/8498338/Log_2022-04-15_23-28-57.log.zip)

**Kext Download Source**
Got from your releases

**Comment by jief666** [comment]
Also : kext was loaded from terminal. Can't have it to load at boot when I put in Library/Extensions.
I'm gonna try itlwm.kext, loaded by clover.

**Comment by jief666** [comment]
I've rebooted with itlwm.kext. This time, it connected at boot and stayed connected. Ping time are ok. Forgot to check BSSID.
I've turned wifi off and on. It re-connected easily, but ping time are bad. Maybe one router is bad and one is ok. On the macbook, I'm always connected to the good one. Here, when I select the other network with the same name, I got a disconnect and then it reconnect to the previous one.

**Comment by jief666** [comment]
Ok. Did a bit more tests. I've noticed that there is more than 2 networks with the same name by using "airport -s". I have channel 1, 6 and 11.
The mac sometime change. Here, I am always connected to channel 1.

**Comment by zxystd** [comment]
Work as expected.

**Comment by jief666** [comment]
I wouldn't say that it works as expected. It works fine in Windows, which means the card can do it. It works fine on the macbook.
Today, maybe because it's more busy, I can't have it working more than 10 seconds.
The hackintosh only connect to channel 1. The mac never connect to channel 1. Only 6 and 11.
So yes, at 1am, I got it working fine, but I guess it was by chance and by low usage of wifi.

**Comment by jief666** [comment]
It's been 9 times turning wifi on and off. Each time it worked for approx 10 seconds. Last try was 11.2 seconds. Sometime, the hackintosh tris to reconnect by itself. Again 10 seconds. Most of the time it never tries to re-connect.
Without another computer, I couldn't have written this message.
NOTE : I don't know if the channel matters or not.
That's why I wouldn't say it works as expected.

**Comment by jief666** [comment]
Hi. Could we re-open this ?

**Comment by zxystd** [comment]
@jief666 The best solution is not using 2.4Ghz band WiFi because the 2.4Ghz band wifi performance is bad, and the channel selection is depends on the router, not the driver. I have two ac3165 and they all work fine.

**Comment by jief666** [comment]
Well, I have one and it doesn't work as expected.
I guess it's just easier to close issue that way than trying to fix the problem...

**Comment by jief666** [comment]
I can't believe you never had a look on that issue ! You kept it close, stating it's working as expected when it's obviously false.
Very dismissive indeed.
