### ISSUE TITLE
Unable to connect from the latest prerelease version

### ISSUE THREAD

**Issue by 19521679** [OpenIntelWireless/itlwm#769]
**Have You Read Our Docs**
Yes

**Are You Reporting A Bug**
Yes

**Environment**

- Kext Version: 2.2.0 - alpha
- WiFi Card Model: 9461
- PCI Product ID: 0x8086
- macOS Version: 12.3.0

**Description**
Cannot connect any wifi since i has updated commit number 570cc2d0c7903e9dac9f075bb02c9b97391a1cba

**Bug Report Archive**
Airportitlwm

**Kext Download Source**
from pre release

**Comment by zxystd** [comment]
Please upload the running log.

**Comment by 19521679** [comment]
it shows wifi name but cant connect. there aren't any anomalies in the log.

**Comment by zxystd** [comment]
https://docs.oiw.workers.dev/itlwm/Troubleshooting.html#runtime-logs

Here is the guide to get the running log.

**Comment by zxystd** [comment]
@19521679  This issue is fixed, please use the latest alpha version to check.

**Comment by 19521679** [comment]
> @19521679 Hi?

sorry because I haven't used hackintosh for a long time, thanks for the fix.
