### ISSUE TITLE
Download/Upload speed drop to 0, websites load very slowly

### ISSUE THREAD

**Issue by axemre** [OpenIntelWireless/itlwm#770]
**Have You Read Our Docs**
 Yes

**Are You Reporting A Bug**
 Yes

**Environment**

- Kext Version: AirportItlwm 2.1.0 stable
- WiFi Card Model: Wireless-AC 9260 160MHz (iwx)
- PCI Product ID: 0x2526
- macOS Version: Monterey 12.3.1

**Description**
 

Somehow, the download and upload speed drops to 0 and then increases again, this makes downloads and uploads extremely slow. And websites load very slowly as well. Don't know what could be wrong. 

**Bug Report Archive**

**Kext Download Source**
 Downloaded from GitHub under Releases

**Comment by zxystd** [comment]
Test v2.2.0-alpha instead, and use 5GHz wifi as well. Also please attach log.

**Comment by axemre** [comment]
> Test v2.2.0-alpha instead, and use 5GHz wifi as well. Also please attach log.

2.2.0 seems to do great here now, there are no drops, downloading a 5GB file now.

**Comment by axemre** [comment]
It seems to be working just fine now. Thanks for the tip with using 2.2.0, it really worked. There's no drop and it doesn't panic anymore.
