### ISSUE TITLE
Unable to establish hidden ssid connection.

### ISSUE THREAD

**Issue by Helakres** [OpenIntelWireless/itlwm#771]
AirportItlwm there is no problem connecting to non-hidden networks with ssid, but networks that are hidden from ssid cannot be connected. Can there be a solution ?

Wifi Card : Intel AC 9560

**Comment by williambj1** [comment]
Use itlwm instead.

**Comment by Helakres** [comment]
My problem is solved with itlwm, but I need to use extra heliport in this.

Can this problem be solved with AirportItlwm update?

**Comment by haol666** [comment]
测试可用，啥时候并入主版本啊
