### ISSUE TITLE
Frequent Kernel Panic After Upgrading to Monterey 12.3.1

### ISSUE THREAD

**Issue by techandrew** [OpenIntelWireless/itlwm#772]
panic(cpu 2 caller 0xffffff801c6ab56a): mbuf_watchdog: 1 waiters stuck for 41 secs
60737/60795 mbufs in use:
	60731 mbufs allocated to data
	6 mbufs allocated to packet headers
	58 mbufs allocated to caches
574/1364 mbuf 2KB clusters in use
28507/28508 mbuf 4KB clusters in use
0/1 mbuf 16KB clusters in use
132388 KB allocated to network (approx. 98% in use)
0 KB returned to the system
VM allocation failures: contiguous 0, normal 0, one page 0
worker thread runs: 1838, expansions: 442, cl 0/0, bigcl 1837/273313, 16k 0/0
worker thread last run time: 2174 (42 seconds ago)

mbuf leak detection table:
	total captured: 2308 (one per 500)
	total allocs outstanding: 237
	new hash recorded: 2298 allocs, 1633 traces
	hash collisions: 95 allocs, 4 traces
	overwrites: 1741 allocs, 0 traces
	lock conflicts: 0

top 5 outstanding traces:
[1] 68 outstanding alloc(s), 69 hit(s), 0 collision(s)
[2] 52 outstanding alloc(s), 61 hit(s), 0 collision(s)
[3] 39 outstanding alloc(s), 46 hit(s), 0 collision(s)
[4] 29 outstanding alloc(s), 580 hit(s), 0 collision(s)
[5] 26 outstanding alloc(s), 65 hit(s), 0 collision(s)

    trace [1]           trace [2]           trace [3]       	trace [4]           trace [5]      
    ------------------  ------------------  ------------------      ------------------  ------------------ 
 1: 0xffffff80008a9d0a  0xffffff80008a9d0a  0xffffff80008a9d0a  0xffffff80008a9d0a  0xffffff80008a9d0a  
 2: 0xffffff800088373f  0xffffff80008836a9  0xffffff800088373f  0xffffff80008836a9  0xffffff800088373f  
 3: 0xffffff80008a8c8d  0xffffff80008a8c3a  0xffffff80008b0635  0xffffff80008adf98  0xffffff80008adf98  
 4: 0xffffff800088361e  0xffffff800088361e  0xffffff800087d96a  0xffffff80008b21eb  0xffffff80008b21eb  
 5: 0xffffff80008b0635  0xffffff80008b0635  0xffffff8002b750bd  0xffffff800087cd33  0xffffff800087cd33  
 6: 0xffffff800087d96a  0xffffff800087d96a  0x0  0x0  0x0  
 7: 0xffffff8002b750bd  0xffffff8002b750bd  0x0  0x0  0x0  
 8: 0x0  0x0  0x0  0x0  0x0  
 9: 0x0  0x0  0x0  0x0  0x0  
10: 0x0  0x0  0xffffff8000a47454  0x0  0x0  
11: 0x0  0x0  0xffffff8000a45d0e  0x0  0x0  
12: 0xffffff8000a47454  0xffffff8000a47454  0xffffff8000a45337  0x0  0x0  
13: 0xffffff8000a45d0e  0xffffff8000a45d0e                      0x0  0x0  
14: 0xffffff8000a45337  0xffffff8000a45337                      0x0  0x0  
15:                                                             0x0  0x0  
16:                                                             0xffffff8000a47454  0xffffff8000a47454  

Panicked task 0xffffff9043e28d10: 9 threads: pid 732: com.apple.WebKit
Backtrace (CPU 2), panicked thread: 0xffffff9516e3caa8, Frame : Return Address
0xffffffe082c7b590 : 0xffffff801c083e2d mach_kernel : _handle_debugger_trap + 0x41d
0xffffffe082c7b5e0 : 0xffffff801c1e3cb6 mach_kernel : _kdp_i386_trap + 0x116
0xffffffe082c7b620 : 0xffffff801c1d350d mach_kernel : _kernel_trap + 0x51d
0xffffffe082c7b670 : 0xffffff801c023a60 mach_kernel : _return_from_trap + 0xe0
0xffffffe082c7b690 : 0xffffff801c0841fd mach_kernel : _DebuggerTrapWithState + 0xad
0xffffffe082c7b7b0 : 0xffffff801c0839b6 mach_kernel : _panic_trap_to_debugger + 0x2b6
0xffffffe082c7b810 : 0xffffff801c9164bf mach_kernel : _panic + 0x84
0xffffffe082c7b900 : 0xffffff801c6ab56a mach_kernel : _mbuf_class_under_pressure + 0x355a
0xffffffe082c7b990 : 0xffffff801c6a9287 mach_kernel : _mbuf_class_under_pressure + 0x1277
0xffffffe082c7ba00 : 0xffffff801c68361e mach_kernel : _cantrace + 0x1e7e
0xffffffe082c7ba80 : 0xffffff801c6a8c8d mach_kernel : _mbuf_class_under_pressure + 0xc7d
0xffffffe082c7bb20 : 0xffffff801c68361e mach_kernel : _cantrace + 0x1e7e
0xffffffe082c7bba0 : 0xffffff801c6b0635 mach_kernel : _m_mclfree + 0x17c5
0xffffffe082c7bc30 : 0xffffff801c3e40b2 mach_kernel : _nstat_ifnet_to_flags_extended + 0x6342
0xffffffe082c7bcb0 : 0xffffff801c3eacd2 mach_kernel : _nstat_provider_stats_event + 0x172
0xffffffe082c7bd00 : 0xffffff801c42facb mach_kernel : _necp_client_register_socket_flow + 0xe5b
0xffffffe082c7bd40 : 0xffffff801c43f252 mach_kernel : _necp_client_action + 0x2b82
0xffffffe082c7bef0 : 0xffffff801c43c92c mach_kernel : _necp_client_action + 0x25c
0xffffffe082c7bf40 : 0xffffff801c78ad2b mach_kernel : _unix_syscall64 + 0x1fb
0xffffffe082c7bfa0 : 0xffffff801c024226 mach_kernel : _hndl_unix_scall64 + 0x16

Process name corresponding to current thread (0xffffff9516e3caa8): com.apple.WebKit.Networking
Boot args: darkwake=1 keepsyms=1 debug=0x100 -v igfxonln=1 -cdfon alcid=11 chunklist-security-epoch=0 -chunklist-no-rev2-dev chunklist-security-epoch=0 -chunklist-no-rev2-dev

Mac OS version:
21E258

Kernel version:
Darwin Kernel Version 21.4.0: Fri Mar 18 00:45:05 PDT 2022; root:xnu-8020.101.4~15/RELEASE_X86_64
Kernel UUID: B6F8637B-0844-355F-8C82-60FA06149384
KernelCache slide: 0x000000001be00000
KernelCache base:  0xffffff801c000000
Kernel slide:      0x000000001be10000
Kernel text base:  0xffffff801c010000
__HIB  text base: 0xffffff801bf00000
System model name: MacBookPro13,1 (Mac-473D31EABEB93F9B)
System shutdown begun: NO
Panic diags file available: YES (0x0)
Hibernation exit count: 0

System uptime in nanoseconds: 2215753349427
Last Sleep:           absolute           base_tsc          base_nano
  Uptime  : 0x00000203e530fdd5
  Sleep   : 0x0000004ce6d881d5 0x00000011cad6541e 0x0000000000000000
  Wake    : 0x0000004cf055d0d6 0x00000001242c42b4 0x0000004cebde69d0
Compressor Info: 0% of compressed pages limit (OK) and 0% of segments limit (OK) with 0 swapfiles and OK swap space
Zone info:
  Foreign : 0xffffff802b2b3000 - 0xffffff802b2c1000
  Native  : 0xffffff8042f98000 - 0xffffffa042f98000
  Readonly: 0xffffff850fc64000 - 0xffffff86a95fd000
  Metadata: 0xfffffff9eb657000 - 0xfffffffa0b7d4000
  Bitmaps : 0xfffffffa0b7d4000 - 0xfffffffa117d4000

**Comment by zxystd** [comment]
Apple Webkit crash, I don't know what had apple do from Monterey, but I guess you are using Safari, have you tried Chrome?
