### ISSUE TITLE
Kernel panic when wake up from sleep state, Catalina.

### ISSUE THREAD

**Issue by sungoku** [OpenIntelWireless/itlwm#773]
panic(cpu 2 caller 0xffffff801403ba50): "_dmaReferences underflow"@/AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/xnu/xnu-6153.141.59/iokit/Kernel/IOMemoryDescriptor.cpp:2298
Backtrace (CPU 2), Frame : Return Address
0xffffff83c992b920 : 0xffffff801391b54d 
0xffffff83c992b970 : 0xffffff8013a55c85 
0xffffff83c992b9b0 : 0xffffff8013a4780e 
0xffffff83c992ba00 : 0xffffff80138c1a40 
0xffffff83c992ba20 : 0xffffff801391ac17 
0xffffff83c992bb20 : 0xffffff801391b007 
0xffffff83c992bb70 : 0xffffff80140c010c 
0xffffff83c992bbe0 : 0xffffff801403ba50 
0xffffff83c992bc60 : 0xffffff8014032be0 
0xffffff83c992bc80 : 0xffffff7f9878c55c 
0xffffff83c992bcb0 : 0xffffff7f9878d571 
0xffffff83c992bcf0 : 0xffffff7f987946aa 
0xffffff83c992bd50 : 0xffffff7f987a564d 
0xffffff83c992bdf0 : 0xffffff7f987aa945 
0xffffff83c992be40 : 0xffffff7f9872e5af 
0xffffff83c992bfa0 : 0xffffff80138c113e 
      Kernel Extensions in backtrace:
         com.zxystd.AirportItlwm(2.1)[41BC6B1C-F573-309E-9504-B7B8C989CA70]@0xffffff7f9872b000->0xffffff7f99655fff
            dependency: com.apple.iokit.IO80211Family(1200.12.2b1)[EC960EFB-4864-3DD8-9E55-843163175EC9]@0xffffff7f9526b000
            dependency: com.apple.iokit.IONetworkingFamily(3.4)[CD14FFB5-FBC4-358B-A8AD-CFE766FB1971]@0xffffff7f946b0000
            dependency: com.apple.iokit.IOPCIFamily(2.9)[44DCA245-066B-3D21-BDC0-0E277FF16E4A]@0xffffff7f94312000

BSD process name corresponding to current thread: kernel_task
Boot args: brcmfx-country=#a agdpmod=vit9696 darkwake=0 igfxfw=2 alcdelay=500 chunklist-security-epoch=0 -chunklist-no-rev2-dev chunklist-security-epoch=0 -chunklist-no-rev2-dev

Mac OS version:
19H1824

Kernel version:
Darwin Kernel Version 19.6.0: Tue Feb 15 21:39:11 PST 2022; root:xnu-6153.141.59~1/RELEASE_X86_64
Kernel UUID: 65FD3451-F0B1-3202-9C67-023D8D1B4D44
Kernel slide:     0x0000000013600000
Kernel text base: 0xffffff8013800000
__HIB  text base: 0xffffff8013700000
System model name: MacBookPro15,1 (Mac-937A206F2EE63C01)
System shutdown begun: NO
Panic diags file available: YES (0x0)

System uptime in nanoseconds: 3070285279397

**Comment by zxystd** [comment]
Seems that you machine is in bad state after wakeup, You can try the latest alpha version that I have done something related to avoid the race.
