### ISSUE TITLE
AirportItlwm connection problem to hidden networks

### ISSUE THREAD

**Issue by Helakres** [OpenIntelWireless/itlwm#774]
**Have You Read Our Docs**
Yes

**Are You Reporting A Bug**
Yes

**Environment**

- Kext Version: AirportItlwm_v2.1.0
- WiFi Card Model: Intel AC 9560
- PCI Product ID: 
- macOS Version: Monterey 12.1

**Description**
Network hidden ssid is available. Can't connect to them. When I open the hidden ssid, there is no problem. It would be great if there is a method that we can solve the hidden ssid connection problem.

**Bug Report Archive**

**Kext Download Source**
https://github.com/OpenIntelWireless/itlwm/releases/download/v2.1.0/AirportItlwm_v2.1.0_stable_Monterey.kext.zip

**Comment by zxystd** [comment]
See the doc.

**Comment by Helakres** [comment]
What exactly are you talking about doctor?

**Comment by rboldini** [comment]
[Doc](https://openintelwireless.github.io/itlwm/FAQ.html#features) means documentation.
Look for 'hidden'.

**Comment by Helakres** [comment]
Thanks
