### ISSUE TITLE
[Request Test] Hidden Wi-Fi connection support for AirportItlwm

### ISSUE THREAD

**Issue by zxystd** [OpenIntelWireless/itlwm#776]
Hi, Today I paid some time to resolve this kind of issue #294 #771 and finally got it working, Now we can connect to the hidden Wi-Fi by click the wifi icon and then choose 'Join other network'.

Test ok with Catalina-ax201 by myself. Can anyone help to test also? Thanks!
Note: Please pay attention to whether there is a disconnection during scanning after installing this version of kext.

[High Sierra.zip](https://github.com/OpenIntelWireless/itlwm/files/8694761/High.Sierra.zip)
[Catalina.zip](https://github.com/OpenIntelWireless/itlwm/files/8694762/Catalina.zip)
[Big Sur.zip](https://github.com/OpenIntelWireless/itlwm/files/8694763/Big.Sur.zip)
[Mojave.zip](https://github.com/OpenIntelWireless/itlwm/files/8694764/Mojave.zip)
[Monterey.zip](https://github.com/OpenIntelWireless/itlwm/files/8694765/Monterey.zip)

**Comment by qqsir-dev** [comment]
太牛了！！！大赞！！Awsome!!!!

**Comment by yasapurnama** [comment]
tried, and it's working
but every reboot need to join manual again, seems the session is not persistent

**Comment by alangsecond** [comment]
tried in Monterey,AX210,both 2.4G and 5G working,very good.
trid in Ventura beta2,non-hidden Wi-Fi connection working ,but hidden Wi-Fi connection not working
Can you resolve it ?Thanks!

**Comment by trihutama** [comment]
tested on 3168NGW monterey 12.5.1, connecting to hidden Wi-Fi working normal

**Comment by jinkunyyy** [comment]
AX210 AX working on Monterey 12.5(21G72),connecting to hidden Wi-Fi

**Comment by javasoul95** [comment]
Hello, Could you fix the hidden network for ventura?

**Comment by jinkunyyy** [comment]
> Hi, Today I paid some time to resolve this kind of issue #294 #771 and finally got it working, Now we can connect to the hidden Wi-Fi by click the wifi icon and then choose 'Join other network'.
> 
> Test ok with Catalina-ax201 by myself. Can anyone help to test also? Thanks! Note: Please pay attention to whether there is a disconnection during scanning after installing this version of kext.
> 
> [High Sierra.zip](https://github.com/OpenIntelWireless/itlwm/files/8694761/High.Sierra.zip) [Catalina.zip](https://github.com/OpenIntelWireless/itlwm/files/8694762/Catalina.zip) [Big Sur.zip](https://github.com/OpenIntelWireless/itlwm/files/8694763/Big.Sur.zip) [Mojave.zip](https://github.com/OpenIntelWireless/itlwm/files/8694764/Mojave.zip) [Monterey.zip](https://github.com/OpenIntelWireless/itlwm/files/8694765/Monterey.zip)

大佬什么时候可以修复一下Ventura的隐藏无线不能连接的问题，万分感谢！

**Comment by Abdullah-Albanna** [comment]
works like a charm on Big Sur with Intel Centrino Advanced-N 6205, connects to a hidden networks and remembers it.

thank you so much

**Comment by haol666** [comment]
working on Monterey 12.5.1 , connecting to hidden Wi-Fi
