### ISSUE TITLE
Status of AWDL on Monterey, (Handoff, Continuity, AirDrop, Apple Watch unlock) with [AirPort Itlwm] 

### ISSUE THREAD

**Issue by pp611** [OpenIntelWireless/itlwm#780]
Since #292 is locked for general public and there is not much systematic summary on the AWDL support status with Monterey, I'd like to see how people are doing with these functions, just to get a clear picture on what works .  In my case:

Environment

- Kext Version: AirPortItlwm 2.1.0
- WiFi Card Model: Intel AX200
- Product ID: 0x8086, 0x84
- macOS Version: macOS Monterey 12.4

AWDL functions:

- Universal Clipboard: can copy iPhone text and paste on Mac, not working in other direction
- AirDrop: Mac can see iPhone, but won't drop. iPhone cannot see Mac, "No People Found"

**Comment by williambj1** [comment]
Read the docs for more info. Closed since issues are for bug tracking only right now.
