### ISSUE TITLE
itlwm and WirelessItlwm opencore

### ISSUE THREAD

**Issue by that-one-gamer1015** [OpenIntelWireless/itlwm#786]
Yes I've read the documentation. I can not get any versions of the itlwm to load. I have opencore and MacOS Monterey. I have 802.11ac. I attached a picture of my config.plist section where I have put itlwm. 
![16549682981976017280785314992297](https://user-images.githubusercontent.com/98918237/173198274-b756b91c-faa3-4464-9c70-fee1d8c866a6.jpg)

**Comment by stevezhengshiqi** [comment]
@that-one-gamer1015 What do you mean by "can not get any versions of the itlwm to load"? Please use `kextstat` to verify that. Also, did you install Heliport?

**Comment by riccardo-briccola** [comment]
You should set the "Enabled" property to "true" in order to load the kext.
