### ISSUE TITLE
5GHz Network does not work on Airportitlwm Ventura

### ISSUE THREAD

**Issue by xfwdrev** [OpenIntelWireless/itlwm#787]
**Have You Read Our Docs**
Yes
**Are You Reporting A Bug**
Yes

**Environment**

- Kext Version: 2.2.0 Alpha
- WiFi Card Model: Intel Wireless AC 8265
- PCI Product ID:  0X24FD
- macOS Version: MacOS 13 Ventura Beta 1

**Description**
Airportitlwm now works without kernel panic on Ventura, but it cannot connect to 5GHz network. Either it displays Network not Found or Password Incorrect. 2.4GHz Network works.

**Kext Download Source**
https://github.com/OpenIntelWireless/itlwm/releases

**Comment by williambj1** [comment]
please attach logs
