### ISSUE TITLE
Problems using itlwm (AirportItlwm) and Bluetooth Intel combination

### ISSUE THREAD

**Issue by Duy-Thanh** [OpenIntelWireless/itlwm#789]
**Have You Read Our Docs**
 Yes

**Are You Reporting A Bug**
 Yes

**Environment**

- Kext Version: 2.2.0-alpha (built by github-actions 4 days ago)
- WiFi Card Model: Intel Wireless AC-9461
- PCI Product ID: Vendor 0x8086 Device 0x9DF0 SubVendor 0x8086 SubDevice 0x0264
- macOS Version: macOS Monterey 12.4
- My bootloader: OpenCore 0.8.1 build RELEASE

**Description**

When using Intel Bluetooth with itlwm (AirportItlwm also had this problem because I used AirportItlwm before, after having this problem changed to itlwm hoping for some luck, but they still get the error), with the Bluetooth device as a Bluetooth headset, and the Wi-Fi is already in the connected state, I have the following two scenarios:

Case 1: If the Bluetooth has successfully paired and successfully connected to my Bluetooth headset, the constant drop from the Wifi network occurs, and I am forced to turn off the Wi-Fi connections and open them again , but can only endure up to 5 minutes before falling out of network connection again

Case 2: If Bluetooth device connected successfully and Wi-Fi connection is established, Wi-Fi network loss occurs and when I follow the steps (Turn Wi-Fi on/off) , if I do it more than 5 times, the Wi-Fi connection is stable, but the Bluetooth completely crashes. And when I go to System Preferences I get the colorful wheel and after about 2 minutes the following message shows up:

`Preferences Error: Could not load Bluetooth preference pane.`

And I have to reboot the system to be able to continue, but the problem keeps happening (When Bluetooth connects, Wi-Fi loses connection, when Wi-Fi connects successfully, Bluetooth completely crashes)

In particular, this only happens with Bluetooth devices, but when opening System Preferences of Wi-Fi, everything is fine

For that, my temporary workaround is as follows (This workaround works on Android devices):

- Clone the HoRNDIS repo, and build it with the newer SDK (Pre-builds can't be loaded in newer versions of macOS, if you want, I'll send a copy of this prebuilt kext to those who need it, I build it on SDK and macOS Big Sur, and still work fine on Monterey)
- Install the HoRNDIS kext **into the bootloader** (don't copy it to `/Library/Extensions`)
- Reboot the system
- Now, turn on Wi-Fi on your phone, and also open Wi-Fi broadcast mode
- Using a USB cable, plug the cable into your computer and phone
- Open the Wi-Fi broadcast settings page (The place you frequent to change the base station password and SSID), and turn on the **"USB tethering"** feature
- Then turn off Wi-Fi on your computer (use HeliPort if using kext itlwm)
- Now everything worked

However, there will be a few cases of bluetooth crashing, but it's intermittent (even rare) if the above workaround is used.

However, this is only a temporary workaround, so I hope the development team will fix this soon.

**Bug Report Archive**

[bugreport_26507.zip](https://github.com/OpenIntelWireless/itlwm/files/8928635/bugreport_26507.zip)

**Kext Download Source**

Download from release page on this repo

**Comment by zxystd** [comment]
1. use 5GHz channel Wi-Fi instead.
2. add `-noht40` to bootargs, this option disable 40Mhz on 2.4GHz channels to reduce the channel conflict between WiFi and BT.
WiFI and BT conflict on 2.4GHz channels is a worldwide problem and can't be resolve even the WiFi card Vendors, there is nothing need to be done of the driver.
