### ISSUE TITLE
升级OC，opencore版本后，我的intel网卡wifi无效了，搜索不到wifi。

### ISSUE THREAD

**Issue by JinElias** [OpenIntelWireless/itlwm#790]
1，big sur下，OC0.74升级OC0.81后，我的intel网卡wifi搜索不到了。
2，换回老版本0.74的OC EFI  就正常了。在新版本下0.81的OC EFI下重装系统bigsur，wifi也能正常驱动。
3，就是0.7.1下OC已经安装过的系统big sur下，再升级OC0.8.1就不能驱动intel 的WiFi了 。

**Comment by williambj1** [comment]
Has nothing to do with this project.
