### ISSUE TITLE
A210 - physical modification necessary?

### ISSUE THREAD

**Issue by peddy22** [OpenIntelWireless/itlwm#792]
**Have You Read Our Docs**

Yes
**Are You Reporting A Bug**

Yes
**Environment**

- Kext Version: 2.1
- WiFi Card Model: AX210
- PCI Product ID: OpenPCI
- macOS Version: Monterey

**Description**
I can't see devices using Airdrop and the Bluetooth dialog hangs

**Bug Report Archive**

   81    0 0                  0xfa4000   0xfa4000   com.zxystd.AirportItlwm (2.1.0) FA02D059 <80 50 16 7 6 3 1>

**Kext Download Source**

main gh release

**Comment by peddy22** [comment]
Regarding the title, I have taped pin 51 according to some instructions (it's an mPCIE card)

**Comment by williambj1** [comment]
AFAIK no hardware mod is necessary, read the docs to learn more about continuity
