### ISSUE TITLE
Support PROSet/Wireless 3945 and devices from iwlegacy

### ISSUE THREAD

**Issue by Vexcited** [OpenIntelWireless/itlwm#796]
**Have You Read Our Docs**
Yes

**Are You Reporting A Bug**
No

**Environment**
Mac OS X El Capitan

- Kext Version: v2.1.0
- WiFi Card Model: Intel PROSet/Wireless 3945
- PCI Product ID: (i dont know)
- macOS Version: 10.11.6

**Description**
Hello ! This is not a bug but a feature request. Since this repository supports Wi-Fi cards from iwlwifi, can't you also support cards from iwlegacy ? I saw [this project](https://code.google.com/archive/p/iwidarwin/) but it seems old and the 3945 is still in beta.

**Bug Report Archive**
(none since not a bug)

**Kext Download Source**
From this GitHub repository.

**Comment by zxystd** [comment]
Not planed. Thank you for the advise.
