### ISSUE TITLE
Intel ac 7265 not connecting and speed extremely slow

### ISSUE THREAD

**Issue by Human7900** [OpenIntelWireless/itlwm#797]
WARNING!!! YOUR ISSUE WILL BE CLOSED AND DELETED IMMEDIATELY IF YOU DID NOT USE THE FOLLOWING TEMPLATE

**Have You Read Our Docs**
Yes

**Are You Reporting A Bug**
Yes

**Environment**

- Kext Version: 2.2.0 Alpha
- WiFi Card Model: Intel ac 7265
- PCI Product ID: 0x095A
- macOS Version: Ventura db2

**Description**
The wifi doesn't not connect most of the times and the wifi speed is extremely slow when it connects, When using the itwlm 1.2.0, it connects but the speed is very slow.

**Bug Report Archive**
[bugreport_31185 itwlm.zip](https://github.com/OpenIntelWireless/itlwm/files/9091036/bugreport_31185.itwlm.zip) (for 1.2.0)
I am facing this issue while getting the logs for airportitwlm.
[img](https://user-images.githubusercontent.com/84245065/178444637-7473d18f-625c-48c7-abf3-640340f134e4.png)

**Kext Download Source**
https://github.com/OpenIntelWireless/itlwm/releases

**Comment by zxystd** [comment]
```
The wifi doesn't not connect most of the times
```
Will consider to reopen once you provide this 'not connect' log of v2.2.0-alpha, we are not going to trace the 'history version'.

**Comment by Human7900** [comment]
Sorry!!, I am following the FAQ, and I get stuck at this command. Could you help me?
![](https://user-images.githubusercontent.com/84245065/178444637-7473d18f-625c-48c7-abf3-640340f134e4.png)
ps: I am not good at this so pls bare with me.

**Comment by Human7900** [comment]
Okay, so I just realised how stupid I am.
Here's the diagnostic report ( for airportitwlm 2.2.0 Alpha)
[bugreport_35278.zip](https://github.com/OpenIntelWireless/itlwm/files/9099278/bugreport_35278.zip)
Also, here's the issue I face while manually collecting logs.
![piccc](https://user-images.githubusercontent.com/84245065/178660360-939772ea-9585-427d-a725-26362395d124.png)

**Comment by Human7900** [comment]
@zxystd  Can we reopen this now?
