### ISSUE TITLE
Location services doesn't work \w AirportItlwm on macOS Ventura

### ISSUE THREAD

**Issue by kpostekk** [OpenIntelWireless/itlwm#799]
**Have You Read Our Docs**
Yes

**Are You Reporting A Bug**
Yes

**Environment**

- Kext Version: 2.2.0 (build from d9f129454ee15d81e039acc2dc5e785465cd65f9)
- WiFi Card Model: Intel Wireless AC 9462
- PCI Product ID: uhhhh, 0x2A4 *(not sure)*
- macOS Version: 13.0 Beta (22A5295i)

**Description**
Location services doesn't work. They were (2.1.0) working just fine on Monterey.
Edit: build d9f129454ee15d81e039acc2dc5e785465cd65f9 doesn't work that well on Monterey too.

**Bug Report Archive**
[Log_2022-07-14_18-33-02.log](https://github.com/OpenIntelWireless/itlwm/files/9113602/Log_2022-07-14_18-33-02.log)

**Kext Download Source**
This repo

**Comment by ameenjuz** [comment]
Also wifi do not scan the network and connection issue it is not finding network on macOS ventura 13 beta 5
Please fix this for macOS ventura 13
I compiled kext from your source with latest commit changes but not luck

**Comment by xuewencao** [comment]
俺也一样

**Comment by melxman** [comment]
我现在发现了一个现象：
首先我系统是13.0 Beta6版(22A5331f)
1，如果我在系统重启前关掉了wifi开关，重启后能连上之前连过的wifi(但是距离过远50m左右，也会出现偶尔发现不了这个信号的情况)。但是无法发现新的信号源
2，如果我重启前没有关闭wifi开关。重启后自动链接之前连过的wifi。且可以发现其他周围的信号源。但是无法链接(偶尔能连上)

这两种情况能自动连上的那个wifi，是我在更新到13beta6(从12直接更新的)第一次链接的，现在我也不敢忽略后重新再连了。哈哈

如果作者需要日志文件的话。我后续会上传的

**Comment by usr-sse2** [comment]
Scanning is the reason, and location services is the consequence, because location services use BSSIDs of nearby networks, and if networks are not seen, then the location can't be determined, so this should be renamed to "Network scanning doesn't work on macOS Ventura"

**Comment by zxystd** [comment]
@usr-sse2 Yes, seems that scanning is problematic on Ventura, I can see the airportd always log not scan but use the scan cache in the output console, and the scanning operation signal is not dispatched the to kernel space, do you have some conclusion?

**Comment by usr-sse2** [comment]
I see that networks are scanned and sometimes displayed in System Profiler and System Preferences, but very rarely in the Wi-Fi menu. It seems that it has become slightly better after I changed noise to always be 0 (because on Broadcom it's either 0 or negative, but itlwm reports it as a positive value, which is incorrect), but still it has problems. I'll continue experimenting and debugging. I'm also beginning to write a Lilu plugin to add logging of ioctl arguments and results in Broadcom driver to help understanding its operation.

**Comment by zxystd** [comment]
> I see that networks are scanned and sometimes displayed in System Profiler and System Preferences, but very rarely in the Wi-Fi menu. It seems that it has become slightly better after I changed noise to always be 0 (because on Broadcom it's either 0 or negative, but itlwm reports it as a positive value, which is incorrect), but still it has problems. 

I am also doubted that I post the wrong scan results to the airportd. I have also test at virtual machine that the airportd always think it already has scan cache although the wifi driver is first time loaded and never scan before, it is weird.

> I'll continue experimenting and debugging. I'm also beginning to write a Lilu plugin to add logging of ioctl arguments and results in Broadcom driver to help understanding its operation.

It is a good idea, it is suggested that save the IOCTL full result to file, because the log will not print if its length is too long.

**Comment by GotierLdl** [comment]
Hello, Same issue for me.

**Comment by bootlegseahorse** [comment]
Same on my Intel AX200.

**Comment by FieryFlames** [comment]
Having the same issue on my Intel Dual Band Wireless AC 8260

**Comment by uifor** [comment]
Same on my Intel 7265.

**Comment by Boos4721** [comment]
same on AX210

**Comment by usr-sse2** [comment]
> > I see that networks are scanned and sometimes displayed in System Profiler and System Preferences, but very rarely in the Wi-Fi menu. It seems that it has become slightly better after I changed noise to always be 0 (because on Broadcom it's either 0 or negative, but itlwm reports it as a positive value, which is incorrect), but still it has problems.
> 
> I am also doubted that I post the wrong scan results to the airportd. I have also test at virtual machine that the airportd always think it already has scan cache although the wifi driver is first time loaded and never scan before, it is weird.
> 
> > I'll continue experimenting and debugging. I'm also beginning to write a Lilu plugin to add logging of ioctl arguments and results in Broadcom driver to help understanding its operation.
> 
> It is a good idea, it is suggested that save the IOCTL full result to file, because the log will not print if its length is too long.

Here is the mentioned logger: https://github.com/usr-sse2/AirPortDebug (I made it work only now, as I had no prior experience in making Lilu plugins).

**Comment by alsdk98** [comment]
Same on AX201

**Comment by uifor** [comment]
Nic model: Intel 7265
System version: macOS13.0.1

It has been found that when the computer is just started, the location icon appears, the location can work briefly, then the location will not work

**Comment by anaander** [comment]
adding the boot-arg io80211.awdl=0 to opencore fixed location service for me. Still not seeing anything show up in the wifi network scan but at the very least location services are working again.

**Comment by AkikoKumagara** [comment]
> adding the boot-arg io80211.awdl=0 to opencore fixed location service for me. Still not seeing anything show up in the wifi network scan but at the very least location services are working again.

Thanks for sharing! This works for me.

**Comment by bootlegseahorse** [comment]
> adding the boot-arg io80211.awdl=0 to opencore fixed location service for me. Still not seeing anything show up in the wifi network scan but at the very least location services are working again.

Thank you for sharing, but my location service is still broken after adding "io80211.awdl=0" in boot-args with my Intel AX200 card.

**Comment by anaander** [comment]
I think I was wrong, the boot arg was a red herring and didn't fix it. Location service would work ONCE after boot but then fail to work after that. Strangely, mapping my USB ports properly seems to have had some effect. It's the only thing I've changed today and location services are working with my AX210 card 100% of the time now. 

Specifically I set the USB port associated with the bluetooth to internal. I mean I mapped all the other ports, but that's the only one that could possibly interact with the wireless in any capacity.

![Screenshot 2022-12-03 at 23 13 48](https://user-images.githubusercontent.com/31294634/205474097-f3cb0a39-57e1-4d47-ad14-9978e5a4a795.png)

**Comment by FieryFlames** [comment]
> Having the same issue on my Intel Dual Band Wireless AC 8260

The latest 2.2.0 Alpha fixed this for me.

**Comment by qiqco** [comment]
> adding the boot-arg io80211.awdl=0 to opencore fixed location service for me. Still not seeing anything show up in the wifi network scan but at the very least location services are working again.

我是AX200，添加这个参数后定位正常。Ventura13.1。谢谢🙏

**Comment by bootlegseahorse** [comment]
FYI: There is no permanent solution yet, but "sudo pkill airportd" fixes the location/scan issue instantly. 

If you're lucky enough you might get it to work constantly (until your computer sleeps), but in most cases (90% at least) it would only work for a minute or two. 

Anyway, anytime you need location service with your Intel WiFi card, just do sudo pkill airportd. It's only a temporary fix but it will work.

**Comment by williambj1** [comment]
Fixed in https://github.com/OpenIntelWireless/itlwm/releases/tag/v2.2.0
