### ISSUE TITLE
AIRDROP (don't get excited it doesn't work)

### ISSUE THREAD

**Issue by Mifaxav** [OpenIntelWireless/itlwm#801]
I was going through system Information and using airportlwm, airdrop was showing as supported in the WI-FI menu and also, showed channel 149. Was looking at a previous post to see the channel was '0' but uhh... does this make any difference

screenie below
![Screenshot 2022-07-31 at 6 22 54 PM](https://user-images.githubusercontent.com/84403807/182027334-3e3767d5-09d5-41e7-807c-7a67f1ea4aa4.png)
?

**Comment by williambj1** [comment]
No, :p

**Comment by Mifaxav** [comment]
I was able to airdrop myself tho... Using opendrop. Same machine but used the airdrop protocol
