### ISSUE TITLE
Is Intel Double Connect Technology in a AX411 wifi card supported?

### ISSUE THREAD

**Issue by essereio** [OpenIntelWireless/itlwm#803]
I'm aware that AX411 is supported by [Compatibility | OpenIntelWireless](https://openintelwireless.github.io/itlwm/Compat.html#dvm-iwn) however does anyone know if DCT(Double Connect Technology) is supported in MacOS?

https://www.intel.com/content/www/us/en/products/docs/wireless/double-connect-icps-wi-fi-6e-infographic.html

https://www.intel.com/content/www/us/en/products/sku/217242/intel-wifi-6e-ax411-gig/specifications.html

**Comment by zxystd** [comment]
Killer AX1690i which have the same chip with Intel ax411 is confirmed to work by using the latest alpha version driver, so it is not a problem. macOS doesn't support any 802.11 features, the features are all implemented by ourself(with openbsd based), and we don't have any plan on supporting DCT in short.
