### ISSUE TITLE
itlwm唤醒日志有错误

### ISSUE THREAD

**Issue by oxygen-02** [OpenIntelWireless/itlwm#804]
**Have You Read Our Docs**
Yes

**Are You Reporting A Bug**
No

**Environment**

- Kext Version: 2.2.0
- WiFi Card Model:  AC8265
- PCI Product ID: 0x8086
- macOS Version:  macos 10.15.7

**Description**
唤醒日志中有大量通过WiFi网卡的唤醒情况，都是not found，不影响机器使用，只是想知道这个是否正常？

![image](https://user-images.githubusercontent.com/51152413/185822852-958ad2f4-fb42-4e3e-ad5b-c1ea207c04d0.png)

**Comment by williambj1** [comment]
This message is not from itlwm. Should be completely fine to ignore.
