### ISSUE TITLE
一个小建议：可否让WiFi列表以信号强弱来排序 (手动狗头)

### ISSUE THREAD

**Issue by Yeswwq** [OpenIntelWireless/itlwm#812]
**Have You Read Our Docs**
Yes 

**Are You Reporting A Bug**
Yes 

**Environment**

- Kext Version: [AirportItlwm-Ventura-v2.2.0-DEBUG-alpha-bb86d9f.zip](https://github.com/OpenIntelWireless/itlwm/releases/download/v2.2.0-alpha/AirportItlwm-Ventura-v2.2.0-DEBUG-alpha-bb86d9f.zip)
- WiFi Card Model: AX1650I
- PCI Product ID: PciRoot(0x0)/Pci(0x14,0x3)/0x06f0
- macOS Version: 13.0 Beta版(22A5352e)

**Description**

一个小建议：可否让WiFi列表以信号强弱来排序 (手动狗头)

<img width="461" alt="截屏2022-09-26 19 46 56" src="https://user-images.githubusercontent.com/29864361/192268618-b6a400e3-c14a-4910-9402-2b6622237944.png">

**Bug Report Archive**

目前各项工作正常
**Kext Download Source**

**Comment by zxystd** [comment]
这个你只能找库克了
