### ISSUE TITLE
Not seeing wifi

### ISSUE THREAD

**Issue by herotm** [OpenIntelWireless/itlwm#813]
Hackintosh (Monterey 12.6) is installed on a Proxmox VM

Passthrough the M2 Wifi+Bluetooth AX210 to the VM ( Tested passthrough on Windows 10, works perfectly fine so i would assume hardware is okay here )

Downloaded the Airportitlwm Monterey release(2.1.0), pasted the kext to my bootloader kext folder, used Propertree and edited the config to include the kext, rebooted.

tom@iMac-Pro ~ % kextstat | grep -i "Air*"       
Executing: /usr/bin/kmutil showloaded
No variant specified, falling back to release
Index Refs Address            Size       Wired      Name (Version) UUID <Linked Against>
   94    0 0                  0xfa4000   0xfa4000   com.zxystd.AirportItlwm (2.1.0) FA02D059-D593-3D8E-A031-1F99EA4D67EB <93 49 16 7 6 3 1>
tom@iMac-Pro ~ % 

tom@iMac-Pro ~ % sudo /System/Library/PrivateFrameworks/Apple80211.framework/Versions/A/Resources/airport debug +AllUserland +AllDriver +AllVendor
Password:
Unable to retrieve AirPort interface list
Unable to retrieve AirPort interface list
tom@iMac-Pro ~ % 

Fastboot disabled in BIOS.

Deleted system preference files and rebooted as well.

No Wifi options in network preferences at all.

System: NUC
Bootloader: OpenCore [0.8.1]
OS: Monterey 12.6 On a Proxmox VM
Wifi/Bluetooth Adapter: AX210 (M2)

Sorry, total newb here let me know what other infos are missing.

**Comment by williambj1** [comment]
Please follow the instructions from the documentation and post logs from dmesg.

**Comment by herotm** [comment]
I do apologize, its a problem with me not enabling pcie passthrough option, it works dandy now.

Thank you
