### ISSUE TITLE
Wireless detects as Wi-Fi only on Monterey + but macOS Big Sur Below it's detected as a real Airport Extreme

### ISSUE THREAD

**Issue by bruhmeme1234** [OpenIntelWireless/itlwm#819]
**Have You Read Our Docs**
YES

**Are You Reporting A Bug**
YES

**Environment**

- Kext Version: v2.2.0-alpha
- WiFi Card Model: Intel AX201
- PCI Product ID: (0x8086, 0x74)
- macOS Version: 13.0 (22A380)

**Description**
Hi. I have a question about the continuity features of my Intel Card. On macOS Catalina and Big Sur, the System Info identifies both Bluetooth and Wireless as a real Airport Extreme card making the continuity feature run. But on macOS Monterey + Continuity features are like gone. Is there any way for the devs to fix it?

**Bug Report Archive**
N/A

**Kext Download Source**
https://github.com/OpenIntelWireless/itlwm/releases/tag/v2.2.0-alpha

**Comment by ameenjuz** [comment]
> **Have You Read Our Docs** YES
> 
> **Are You Reporting A Bug** YES
> 
> **Environment**
> 
> * Kext Version: v2.2.0-alpha
> * WiFi Card Model: Intel AX201
> * PCI Product ID: (0x8086, 0x74)
> * macOS Version: 13.0 (22A380)
> 
> **Description** Hi. I have a question about the continuity features of my Intel Card. On macOS Catalina and Big Sur, the System Info identifies both Bluetooth and Wireless as a real Airport Extreme card making the continuity feature run. But on macOS Monterey + Continuity features are like gone. Is there any way for the devs to fix it?
> 
> **Bug Report Archive** N/A
> 
> **Kext Download Source** https://github.com/OpenIntelWireless/itlwm/releases/tag/v2.2.0-alpha

did you test it  Continuity features on catalina & Big sur ? is it working like Airdrop Handoff  feature on catalina & Big Sur in intel wifi card?

**Comment by r1ghty** [comment]
Continuity works on Monterey, but not on Ventura. AX200 identified as WiFi in the System Info, but on Monterey all is fine

**Comment by williambj1** [comment]
Read the docs for accurate information.
