### ISSUE TITLE
ax201 macos13  wifi崩溃，蓝牙正常

### ISSUE THREAD

**Issue by songkea** [OpenIntelWireless/itlwm#821]
**Have You Read Our Docs**

**Are You Reporting A Bug**
蓝牙使用正常可以接力，但是wifi只要开机启动就会崩溃重启电脑； 事情发生在进入桌面一分钟左右，wifi打开则电脑崩溃。 
而系统崩溃报告中显示，确实是wifi问题导致崩溃，请大神帮看看是哪里的问题。
AirportItlwm.kext 2.2.0

**Environment**

- Kext Version: 
- WiFi Card Model: ax201
- PCI Product ID: 
- macOS Version: macOS 13 ventura

**Description**

panic(cpu 10 caller 0xffffff800074aee3): Kernel trap at 0xffffff8000301057, type 13=general protection, registers:
CR0: 0x000000008001003b, CR2: 0x0000700005e74fd8, CR3: 0x0000000007923000, CR4: 0x00000000003626e0
RAX: 0xaaaaaaaaaaaaaaaa, RBX: 0xffffffe2685ff610, RCX: 0x0000000000000141, RDX: 0x0000000000000141
RSP: 0xffffffe2685ff528, RBP: 0xffffffe2685ff560, RSI: 0xffffff903f2e0d08, RDI: 0xaaaaaaaaaaaaaaaa
R8:  0x0000000000000141, R9:  0x00000000ffffffff, R10: 0x0000000000000001, R11: 0x0000000000000002
R12: 0x0000000000000002, R13: 0x0000000000000030, R14: 0xffffff950e6a22f0, R15: 0xffffff950e6a22f0
RFL: 0x0000000000010286, RIP: 0xffffff8000301057, CS:  0x0000000000000008, SS:  0x0000000000000010
Fault CR2: 0x0000700005e74fd8, Error code: 0x0000000000000000, Fault CPU: 0xa, PL: 0, VF: 0

Panicked task 0xffffff9042458218: 238 threads: pid 0: kernel_task
Backtrace (CPU 10), panicked thread: 0xffffff950f317b30, Frame : Return Address
0xffffff80003111a0 : 0xffffff80005edf9d 
0xffffff80003111f0 : 0xffffff800075b786 
0xffffff8000311230 : 0xffffff800074aa10 
0xffffff8000311280 : 0xffffff8000588951 
0xffffff80003112a0 : 0xffffff80005ee27d 
0xffffff8000311390 : 0xffffff80005ed929 
0xffffff80003113f0 : 0xffffff8000de0ecb 
0xffffff80003114e0 : 0xffffff800074aee3 
0xffffff8000311660 : 0xffffff800074abd2 
0xffffff80003116b0 : 0xffffff8000588951 
0xffffff80003116d0 : 0xffffff8000301057 
0xffffffe2685ff560 : 0xffffff80045c76b5 
0xffffffe2685ff5e0 : 0xffffff800230f57d 
0xffffffe2685ffa40 : 0xffffff800230da87 
0xffffffe2685ffbf0 : 0xffffff80022db761 
0xffffffe2685ffc60 : 0xffffff800451e970 
0xffffffe2685ffce0 : 0xffffff800451661b 
0xffffffe2685ffd50 : 0xffffff8000d162f4 
0xffffffe2685ffdb0 : 0xffffff8004516536 
0xffffffe2685ffdf0 : 0xffffff800458f547 
0xffffffe2685ffe50 : 0xffffff800458fbc6 
0xffffffe2685ffed0 : 0xffffff8000d14d04 
0xffffffe2685fff20 : 0xffffff8000d135fe 
0xffffffe2685fff60 : 0xffffff8000d12c37 
0xffffffe2685fffa0 : 0xffffff800058819e 
      Kernel Extensions in backtrace:
         com.apple.iokit.IO80211FamilyLegacy(1200.12.2b1)[E84C2807-ECFC-38F9-9EFB-91740FDC2199]@0xffffff800223f000->0xffffff8002384fff
            dependency: com.apple.driver.AppleMobileFileIntegrity(1.0.5)[2E7C729D-2485-32DC-B478-D490A81E1419]@0xffffff8001b91000->0xffffff8001bbffff
            dependency: com.apple.driver.corecapture(1.0.4)[EB19F50F-F267-3463-BBCF-777D4AAFD797]@0xffffff80037ee000->0xffffff8003810fff
            dependency: com.apple.iokit.CoreAnalyticsFamily(1)[72620FD1-D89B-3033-B43E-D883078906E1]@0xffffff8001edb000->0xffffff8001ee4fff
            dependency: com.apple.iokit.IONetworkingFamily(3.4)[B4C9DF98-D9E5-3460-967C-55853B28D162]@0xffffff8002d9e000->0xffffff8002db4fff
            dependency: com.apple.iokit.IOSkywalkFamily(1.0)[91CA74BE-8DD8-38F9-9584-6C872AC07072]@0xffffff80030e8000->0xffffff8003115fff
            dependency: com.apple.kec.corecrypto(12.0)[A589451C-2D9B-3094-B16B-9FBA03EF7EAD]@0xffffff800381f000->0xffffff8003896fff
         com.zxystd.AirportItlwm(2.0)[8D72B887-C419-3630-9D5A-1538E67DFD89]@0xffffff8004516000->0xffffff80051fbfff
            dependency: com.apple.iokit.IO80211FamilyLegacy(1200.12.2b1)[E84C2807-ECFC-38F9-9EFB-91740FDC2199]@0xffffff800223f000->0xffffff8002384fff
            dependency: com.apple.iokit.IONetworkingFamily(3.4)[B4C9DF98-D9E5-3460-967C-55853B28D162]@0xffffff8002d9e000->0xffffff8002db4fff
            dependency: com.apple.iokit.IOPCIFamily(2.9)[E2CE416B-59DA-3836-9985-FDC527C5E6C7]@0xffffff8002fff000->0xffffff800302efff

Process name corresponding to current thread (0xffffff950f317b30): kernel_task
Boot args: -v -alcbeta -lilubetaall

Mac OS version:
22A380

Kernel version:
Darwin Kernel Version 22.1.0: Sun Oct  9 20:14:54 PDT 2022; root:xnu-8792.41.9~2/RELEASE_X86_64
Kernel UUID: BF7C9676-EF23-3E8D-A2E2-25DAC63091B6
roots installed: 0
KernelCache slide: 0x0000000000200000
KernelCache base:  0xffffff8000400000
Kernel slide:      0x00000000002dc000
Kernel text base:  0xffffff80004dc000
__HIB  text base: 0xffffff8000300000
System model name: iMac20,1 (Mac-CFF7D910A743CAAF)
System shutdown begun: NO
Panic diags file available: YES (0x0)
Hibernation exit count: 0

System uptime in nanoseconds: 113477366331
Last Sleep:           absolute           base_tsc          base_nano
  Uptime  : 0x0000001a6bc734ae
  Sleep   : 0x0000000000000000 0x0000000000000000 0x0000000000000000
  Wake    : 0x0000000000000000 0x0000002c386b0c10 0x0000000000000000
Compressor Info: 0% of compressed pages limit (OK) and 0% of segments limit (OK) with 0 swapfiles and OK swap space
Zone info:
  Zone map: 0xffffff80414da000 - 0xffffffa0414da000
  . PGZ   : 0xffffff80414da000 - 0xffffff80434db000
  . VM    : 0xffffff80434db000 - 0xffffff850fcda000
  . RO    : 0xffffff850fcda000 - 0xffffff86a94da000
  . GEN0  : 0xffffff86a94da000 - 0xffffff8b75cda000
  . GEN1  : 0xffffff8b75cda000 - 0xffffff90424da000
  . GEN2  : 0xffffff90424da000 - 0xffffff950ecda000
  . GEN3  : 0xffffff950ecda000 - 0xffffff99db4da000
  . DATA  : 0xffffff99db4da000 - 0xffffffa0414da000
  Metadata: 0xffffffefb7dae000 - 0xffffffefd7dae000
  Bitmaps : 0xffffffefd7dae000 - 0xffffffefdddae000

last started kext at 22901631903: @kext.AMDFramebuffer	4.0.9 (addr 0xffffff7f8118a000, size 155648)
loaded kexts:
com.zxystd.!I!BFirmware	2.2.0
com.insanelymac.LucyRTL8125Ethernet	1.1.0
ru.joedm.SMCSuperIO	1.2.9
com.dhinakg.USBToolBox.kext	1.1.1
com.zxystd.AirportItlwm	2.0.0
as.vit9696.SMCProcessor	1.2.9
as.vit9696.VirtualSMC	1.2.9
as.vit9696.!AALCU	1.7.5
as.vit9696.!AALC	1.7.1
as.acidanthera.BlueToolFixup	2.6.4
as.vit9696.WhateverGreen	1.5.8
org.acidanthera.NVMeFix	1.0.9
as.vit9696.Lilu	1.6.2
@kext.AMDFramebuffer	4.0.9
>AudioAUUC	1.70
>AGPM	131
>!APlatformEnabler	2.7.0d0
>X86PlatformShim	1.0.0
@filesystems.autofs	3.0
>!AHDAHardwareConfigDriver	400.3
@filesystems.msdosfs	1.10
>!AHDA	400.3
@kext.AMDRadeonX4000	4.0.9
>!AUpstreamUserClient	3.6.9
>!AMCCSControl	1.16
@kext.AMDRadeonServiceManager	4.0.9
>!AGFXHDA	200.2
>!A!IKBLGraphics	20.0.2
>!AGraphicsDevicePolicy	7.1.16
@AGDCPluginDisplayMetrics	7.1.16
>pmtelemetry	1
@filesystems.nfs	1
|IOUserEthernet	1.0.1
>usb.!UUserHCI	1
>!AHV	1
>!ADiskImages2	198.40.3
@kext.AMD9500!C	4.0.9
>!A16X50ACPI	3.2
>!A!ISlowAdaptiveClocking	4.0.0
>!A!ICFLGraphicsFramebuffer	20.0.2
>!AFIVRDriver	4.1.0
>ACPI_SMC_PlatformPlugin	1.0.0
@private.KextAudit	1.0
>!AAHCIPort	370
>!AFileSystemDriver	3.0.1
@filesystems.tmpfs	1
@filesystems.lifs	1
@filesystems.apfs	2142.41.2
@filesystems.hfs.kext	627.40.1
@BootCache	40
@!AFSCompression.!AFSCompressionTypeZlib	1.0.0
@!AFSCompression.!AFSCompressionTypeDataless	1.0.0d1
>!ARTC	2.0.1
>!AACPIButtons	6.1
>!AHPET	1.8
>!ASMBIOS	2.1
>!AAPIC	1.7
$!AUserConsent	1
@!ASystemPolicy	2.0.0
@nke.applicationfirewall	403
|IOKitRegistryCompatibility	1
|EndpointSecurity	1
@Dont_Steal_Mac_OS_X	7.0.0
@kec.Compression	1
@kec.!AEncryptedArchive	1
@kext.AMDRadeonX4000HWLibs	1.0
>DspFuncLib	400.3
@kext.OSvKernDSPLib	530
@kext.AMDRadeonX4000HWServices	4.0.9
>!ASMBus!C	1.0.18d1
|IOSMBus!F	1.1
>!AHDA!C	400.3
|IOHDA!F	400.3
>!AGraphicsControl	7.1.16
>!UAudio	500.2
|IOAudio!F	400.3
@vecLib.kext	1.2.0
>!AAudioClockLibs	200.5
@kext.triggers	1.0
>IOHIDPowerSource	1
|IO!BSerialManager	9.0.0
|IO!BPacketLogger	9.0.0
|IO!BHost!CUSBTransport	9.0.0
|IO!BHost!CUARTTransport	9.0.0
|IO!BHost!CTransport	9.0.0
>IO!BHost!CPCIeTransport	9.0.0
|IOAVB!F	1100.24
|CSR!BHost!CUSBTransport	9.0.0
|Broadcom!BHost!CUSBTransport	9.0.0
|Broadcom!B20703USBTransport	9.0.0
>!ARSMChannel	1
|IORSM!F	1
>!AIPAppender	1.0
>!ASMBusPCI	1.0.14d1
|IONDRVSupport	597
@kext.AMDSupport	4.0.9
>!A16X50Serial	3.2
@plugin.IOgPTPPlugin	1110.13
>driverkit.serial	6.0.0
|IOSerial!F	11
@!AGPUWrangler	7.1.16
|IOSlowAdaptiveClocking!F	1.0.0
|IOAccelerator!F2	475
@!AGraphicsDeviceControl	7.1.16
|IOGraphics!F	597
>IOPlatformPluginLegacy	1.0.0
>X86PlatformPlugin	1.0.0
>IOPlatformPlugin!F	6.0.0d8
|IOAHCIBlock!S	345
>usb.IOUSBHostHIDDevice	1.2
>usb.cdc	5.0.0
>usb.networking	5.0.0
>usb.!UHostCompositeDevice	1.2
>usb.!UHub	1.2
>!AXsanScheme	3
|IONVMe!F	2.1.0
>!UMergeNub	900.4.2
>usb.!UXHCIPCI	1.2
>usb.!UXHCI	1.2
|IOAHCI!F	301
|IO80211!FLegacy	1200.12.2b1
>corecapture	1.0.4
>!ABSDKextStarter	3
|IOSurface	334.0.1
@filesystems.hfs.encodings.kext	1
>!ASyntheticGame!C	10.2.9
>usb.!UHostPacketFilter	1.0
|IOUSB!F	900.4.2
>!AEFINVRAM	2.1
>!AEFIRuntime	2.1
|IOHID!F	2.0.0
|IOTimeSync!F	1110.13
|IOSkywalk!F	1.0
>mDNSOffloadUserClient	1.0.1b8
|IONetworking!F	3.4
>DiskImages	493.0.0
|IO!B!F	9.0.0
|IOReport!F	47
$quarantine	4
$sandbox	300.0
@kext.!AMatch	1.0.0d1
>!ASSE	1.0
>!AKeyStore	2
>!UTDM	547
|IOUSBMass!SDriver	232
|IOSCSIBlockCommandsDevice	476
|IO!S!F	2.1
|IOSCSIArchitectureModel!F	476
>!AMobileFileIntegrity	1.0.5
$!AImage4	5.0.0
@kext.CoreTrust	1
>!AFDEKeyStore	28.30
>!AEffaceable!S	1.0

**Comment by zxystd** [comment]
你的已加载的kext列表里明明白白地写着: com.zxystd.AirportItlwm 2.0.0

**Comment by songkea** [comment]
感谢回复，问题确实是这样的，是我的疏忽，当我换成2.2版本后，确实正常了，wifi功能和蓝牙功能稳如老狗... 
ax201 ，接力正常；  感谢您，祝您生活愉快
