### ISSUE TITLE
Wifi with 5GHz

### ISSUE THREAD

**Issue by papimigas** [OpenIntelWireless/itlwm#822]
Have You Read Our Docs
Yes

Are You Reporting A Bug
Yes

Kext Version: 2.1.0 Stable
WiFi Card Model: 7260
PCI Product ID: 8086 08B1
macOS Version: Big Sur 11.7.1

Hi team

Great job with this project.
I have Intel 7260 running in Big Sur.
I found that I can connect to my network but only 2.4GHz works ok.
If I try to connect on 5GHz my DHCP server receive IP request and send answer but my PC just don't get IP.
I get APIPA in IPv4 and the strangest thing is that I have IPv6.
![apipa](https://user-images.githubusercontent.com/2511652/198898793-7c03afe2-8b72-4902-b328-568b817bfa84.png)

Any help?
Thanks

**Comment by papimigas** [comment]
Update: with latest Alpha itlwm-v2.2.0-DEBUG-alpha-ee56708 works!

**Comment by zxystd** [comment]
So it was resolved?

**Comment by papimigas** [comment]
Well, yes! 
Thanks
