### ISSUE TITLE
ipv6链接网速奇慢，使用有线连接正常，切到windows下wifi也正常

### ISSUE THREAD

**Issue by wimdoan** [OpenIntelWireless/itlwm#829]
这种情况，问题应该还是在驱动吧？

视频中是爱奇艺的网页，视频流下载特别慢

https://user-images.githubusercontent.com/1529662/203931273-8ebb9790-d179-42b6-bf49-be7250ee2efc.mov

**Comment by williambj1** [comment]
Duplicate of #805
