### ISSUE TITLE
"Turn on wifi" doesn't work after using ax210 in hackintosh ventura, Windows 11

### ISSUE THREAD

**Issue by perr0r** [OpenIntelWireless/itlwm#836]
**Have You Read Our Docs**

No

**Are You Reporting A Bug**

No

**Environment**

- Kext Version: itlwm v2.2.0 DEBUG alpha
- WiFi Card Model: Intel AX210
- PCI Product ID: AX210
- macOS Version: Ventura (13.0)

**Description**

My wifi card ax210 doesn't work in any OS.
In Windows device manager, my wifi card looks like activating correctly. But when I try to turn on wifi, wifi button become disabled.

**Bug Report Archive**

**Kext Download Source**

**Comment by Boos4721** [comment]
what motherboard u using?

**Comment by perr0r** [comment]
> what motherboard u using?

I don't know certain name but my laptop is DELL inspiron 3576

**Comment by superbogie** [comment]
Disable WiFi in System Settings. If you don't have Heliport.app, DL it from the OpenIntelWireless/Heliport repo, place it in the Application folder, and then run it. You should now have a new "WiFi" icon in your Menu Bar that will have a list of available WiFi networks..

**Comment by ShroomKing** [comment]
> My wifi card ax210 doesn't work in any OS.

Very likely broken wifi module

I put an Intel AX210 in my Dell Latitude 7480 and it's working perfectly in Linux, Windows and MacOS
