### ISSUE TITLE
频繁断网重连

### ISSUE THREAD

**Issue by oxygen-02** [OpenIntelWireless/itlwm#844]
**Have You Read Our Docs**
Yes

**Are You Reporting A Bug**
Yes

**Environment**

- Kext Version: 2.2.0#https://github.com/OpenIntelWireless/itlwm/commit/acc7ff95937b9fd8c347e9c5a4211eadb128723a
- WiFi Card Model: Wireless 8265
- PCI Product ID: 0x8086
- macOS Version: 10.15.7 (19H15)

**Description**
使用中频繁断网重连，无法控制，必发生
**Log**
[Log_2022-12-31_00-48-04.log](https://github.com/OpenIntelWireless/itlwm/files/10325573/Log_2022-12-31_00-48-04.log)

**Comment by williambj1** [comment]
日志不完整，仅有的一小部分能看到网络在几个 RSSI 近似的节点漫游。可以加 #750 的群里讨论。

**Comment by oxygen-02** [comment]
> 

好的
