### ISSUE TITLE
Big Sur 11.7.2: itlwm won't load (isn't signed)

### ISSUE THREAD

**Issue by Ziggites** [OpenIntelWireless/itlwm#849]
**Have You Read Our Docs**
Yes

**Are You Reporting A Bug**
Yes

**Environment**

- Kext Version: 2.1.0
- WiFi Card Model: Intel 8265NGW
- PCI Product ID: Unknown (card came with Gigabyte B250N Phoenix Wifi board)
- macOS Version: 11.7.2

**Description**
Did a fresh OpenCore install of macOS Big Sur 11.7.2 hackintosh (Kaby Lake i3, GA-B250N Phoenix Wifi mobo) and installed itlwm in /EFI/EFI/OC/Kexts but itlwm.kext does not load on boot. HeliPort reports itlwm isn't running. The kext doesn't seem to be signed?

codesign -dv -verbose=4 itlwm.kext
**code object is not signed at all**

What's strange is this exact same kext works perfectly fine on this same computer booted with Catalina.

**Bug Report Archive**
When I open HeliPort, there is no "Option." There is only "Quit HeliPort" and "Dismiss." I've also tried pressing Option- and Cmd- open of HeliPort with the same result.

**Kext Download Source**
(https://github.com/OpenIntelWireless/itlwm/releases/tag/v2.1.0)

**Comment by zxystd** [comment]
User mistakes.
