### ISSUE TITLE
macOS Ventura 13.2: No WiFi networks found; No location service available.

### ISSUE THREAD

**Issue by t0niX** [OpenIntelWireless/itlwm#855]
**Have You Read Our Docs**
Yes

**Are You Reporting A Bug**
Yes

**Environment**

- Kext Version: https://airportitlwm-ventura-v2.2.0-debug-alpha-ddd2768.zip/
- WiFi Card Model: Intel(R) Wi-Fi 6E AX211 160MHz
- PCI Product ID: PCI\VEN_8086&DEV_7A70&SUBSYS_00948086&REV_11
- macOS Version: macOS Ventura 13.2

**Description**
The wifi card is available in macOS, it won't show any networks though. Another issue is that no location service is available (even with sudo pkill airportd).

PS: Thank you so much for developing .kexts for WiFi and Bluetooth support. Love your work, this surely is just an issue to be fixed.

**Bug Report Archive**
[Log_2023-02-11_23-04-56.log](https://github.com/OpenIntelWireless/itlwm/files/10714826/Log_2023-02-11_23-04-56.log)

**Kext Download Source**
https://airportitlwm-ventura-v2.2.0-debug-alpha-ddd2768.zip/

**Comment by wwoltz** [comment]
Did you see issue #830, seems similar to what you submitted.
