### ISSUE TITLE
wifi works every other time

### ISSUE THREAD

**Issue by ArtMov19** [OpenIntelWireless/itlwm#856]
Extremely unstable

**Have You Read Our Docs**
yes

**Are You Reporting A Bug**
yes

**Environment**

- Kext Version:  2.2.0 Ventura
- WiFi Card Model:  Intel AX201
- PCI Product ID: card type 0x8086, 0x74
- -macOS Version: 13.2.1

**Description**
wifi works every other time, you have to do 2 reboots to make it work, extremely unstable
**Bug Report Archive**

[Log_2023-02-14_23-19-49.log](https://github.com/OpenIntelWireless/itlwm/files/10740280/Log_2023-02-14_23-19-49.log)
**Kext Download Source**
your GitHub

**Comment by zxystd** [comment]
Not related.
