### ISSUE TITLE
MacOS Monterey 12.6.3：Very slow network speed with Intel AX210

### ISSUE THREAD

**Issue by tyultra** [OpenIntelWireless/itlwm#857]
The Airportitlwm [v2.1.0 stable] has been installed，everything is fine but the WiFi download speed only 4Mbps ( while 400Mbps in Win11). Anything I can do to accelerate the speed?
CPU: Intel i5-12400
MB: Maxsun B660M Terminator
Memory: 16GB *2 DDR4 3200Mhz
SSD: ZHITAI Tiplus5000 1TB
Video Card: Sapphire Radeon RX570
Network: Intel AX210

**Comment by maoxikun** [comment]
试试5g频段，我ax201的2.4g也才100mbps左右
