### ISSUE TITLE
小米笔记本PRO TM1701  KBL ， OC，AirportItlwm_Ventura.kext 加载慢 (Intel Wireless 8265)

### ISSUE THREAD

**Issue by xjh169** [OpenIntelWireless/itlwm#861]
Ventura 开机加载 Wi-Fi 需要一分钟以上才能连接上网络，导致状态栏其他图标延迟显示。
如果禁用AirportItlwm_Ventura.kext ，开机进入桌面就直接看到 状态栏 的所有图标 那就不用等待加载了
测试使用Big_Sur、Catalina、Monterey版本 Wi-Fi加载速度没有异常。可能是Ventura的问题
希望AirportItlwm_Ventura.kext 加载速度可以得到优化！
![224718738-1981a1ca-4126-46af-9ee6-9dacb25f95fb](https://user-images.githubusercontent.com/28785981/224957461-2dd6a2c8-19e2-44fa-8e9d-9b63e1e0d2ee.png)
![224718992-e613eb7b-35f4-4dd3-876d-cb407918921f](https://user-images.githubusercontent.com/28785981/224957543-37910458-a525-4147-81ed-2db00e446e3e.png)

**Comment by w43322** [comment]
是因为debug build的原因吧，性能肯定赶不上release build

**Comment by biless** [comment]
似乎不是 我这边编译了一个 release build速度上感觉没有快很多

**Comment by xialiu666i** [comment]
一样

**Comment by zxystd** [comment]
https://github.com/OpenIntelWireless/itlwm/issues/823#issuecomment-1564129817

**Comment by panmili** [comment]
> Ventura 开机加载 Wi-Fi 需要一分钟以上才能连接上网络，导致状态栏其他图标延迟显示。 如果禁用AirportItlwm_Ventura.kext ，开机进入桌面就直接看到 状态栏 的所有图标 那就不用等待加载了 测试使用Big_Sur、Catalina、Monterey版本 Wi-Fi加载速度没有异常。可能是Ventura的问题 希望AirportItlwm_Ventura.kext 加载速度可以得到优化！ ![224718738-1981a1ca-4126-46af-9ee6-9dacb25f95fb](https://user-images.githubusercontent.com/28785981/224957461-2dd6a2c8-19e2-44fa-8e9d-9b63e1e0d2ee.png) ![224718992-e613eb7b-35f4-4dd3-876d-cb407918921f](https://user-images.githubusercontent.com/28785981/224957543-37910458-a525-4147-81ed-2db00e446e3e.png)

最新版本的已经可以了
