### ISSUE TITLE
ax210睡眠后重启发生错误

### ISSUE THREAD

**Issue by starlifezzz** [OpenIntelWireless/itlwm#865]
**Have You Read Our Docs**
yes

**Are You Reporting A Bug**
yes

**Environment**
gt710+ryzen 3600+32G DDR4 memory

- Kext Version: 
- WiFi Card Model: ax210
- PCI Product ID: 
- macOS Version: 13..3

**Description**
睡眠后重启发生错误

**Bug Report Archive**

panic(cpu 6 caller 0xffffff801c1e20c5): zfree_drop: double free of 0xffffff984873fc00 to zone default.kalloc.32 @zalloc.c:812
Panicked task 0xffffff98431e8038: 190 threads: pid 0: kernel_task
Backtrace (CPU 6), panicked thread: 0xffffffa1db5bb598, Frame : Return Address
0xfffffff3b3713700 : 0xffffff801ba705fd 
0xfffffff3b3713750 : 0xffffff801bbc4b84 
0xfffffff3b3713790 : 0xffffff801bbb4619 
0xfffffff3b37137f0 : 0xffffff801ba10951 
0xfffffff3b3713810 : 0xffffff801ba708dd 
0xfffffff3b3713900 : 0xffffff801ba6ff87 
0xfffffff3b3713960 : 0xffffff801c1dd09b 
0xfffffff3b3713a50 : 0xffffff801c1e20c5 
0xfffffff3b3713a80 : 0xffffff801bae1303 
0xfffffff3b3713ab0 : 0xffffff801c0d55fb 
0xfffffff3b3713ad0 : 0xffffff80203211e4 
0xfffffff3b3713b00 : 0xffffff8020329ba1 
0xfffffff3b3713c10 : 0xffffff8020332364 
0xfffffff3b3713c70 : 0xffffff802032c285 
0xfffffff3b3713cf0 : 0xffffff802032bf3e 
0xfffffff3b3713dc0 : 0xffffff802032d4f9 
0xfffffff3b3713e40 : 0xffffff80202d0697 
0xfffffff3b3713fa0 : 0xffffff801ba1019e 
      Kernel Extensions in backtrace:
         com.zxystd.AirportItlwm(2.2)[6E7AC534-751D-37FB-AAF6-1000269403F3]@0xffffff80202cd000->0xffffff8021215fff
            dependency: com.apple.iokit.IO80211FamilyLegacy(1200.12.2b1)[1BF2E75C-8CD9-3196-9276-23F6560EAE23]@0xffffff801d6d0000->0xffffff801d816fff
            dependency: com.apple.iokit.IONetworkingFamily(3.4)[F349EF33-2C2B-32F4-BE0F-284D3A56E2DF]@0xffffff801e230000->0xffffff801e246fff
            dependency: com.apple.iokit.IOPCIFamily(2.9)[98683EFC-EF7A-3169-8DD1-9227B9A27BAA]@0xffffff801e491000->0xffffff801e4c1fff

Process name corresponding to current thread (0xffffffa1db5bb598): kernel_task
Boot args: amfi_get_out_of_my_way=0x1 ipc_control_port_options=0 -nokcmismatchpanic 

Mac OS version:
22E252

Kernel version:
Darwin Kernel Version 22.4.0: Mon Mar  6 21:00:17 PST 2023; root:xnu-8796.101.5~3/RELEASE_X86_64
Kernel UUID: CF2A42DA-3F7C-30C6-9433-6F2076FF1F94
roots installed: 0
KernelCache slide: 0x000000001b600000
KernelCache base:  0xffffff801b800000
Kernel slide:      0x000000001b6dc000
Kernel text base:  0xffffff801b8dc000
__HIB  text base: 0xffffff801b700000
System model name: iMacPro1,1 (Mac-7BA5B2D9E42DDD94)
System shutdown begun: NO
Panic diags file available: YES (0x0)
Hibernation exit count: 0

System uptime in nanoseconds: 1569746396130
Last Sleep:           absolute           base_tsc          base_nano
  Uptime  : 0x0000016d7c2d26d0
  Sleep   : 0x0000016c34605169 0x0000000cafd889e4 0x0000000000000000
  Wake    : 0x0000016c47092906 0x000000014b93d904 0x0000016c46a547f5
Compressor Info: 0% of compressed pages limit (OK) and 0% of segments limit (OK) with 0 swapfiles and OK swap space
Zone info:
  Zone map: 0xffffff8841214000 - 0xffffffa841214000
  . PGZ   : 0xffffff8841214000 - 0xffffff8845215000
  . VM    : 0xffffff8845215000 - 0xffffff8d11548000
  . RO    : 0xffffff8d11548000 - 0xffffff8eaabae000
  . GEN0  : 0xffffff8eaabae000 - 0xffffff9376ee1000
  . GEN1  : 0xffffff9376ee1000 - 0xffffff9843214000
  . GEN2  : 0xffffff9843214000 - 0xffffff9d0f547000
  . GEN3  : 0xffffff9d0f547000 - 0xffffffa1db87a000
  . DATA  : 0xffffffa1db87a000 - 0xffffffa841214000
  Metadata: 0xffffffd05c6a9000 - 0xffffffd07c6a9000
  Bitmaps : 0xffffffd07c6a9000 - 0xffffffd0826a9000
  Extra   : 0 - 0

**Kext Download Source**
github

**Comment by zxystd** [comment]
Trace in #782
