### ISSUE TITLE
High temperature of AIRport after waking up.

### ISSUE THREAD

**Issue by SudoFormatAll** [OpenIntelWireless/itlwm#868]
**Have You Read Our Docs**
YES

**Are You Reporting A Bug**
YES

**Environment**
    Kext Version: Airportitwlm 2.2.0 (but also present on 2.1.0 Stable for BigSur).
    WiFi Card Model: Killer(R) Wi-Fi 6 AX1650i 160MHz Wireless Network Adapter (201NGW)
    PCI Product ID: AA5E56EC ( PCIROOT(0)#PCI(1403) ),  \Device\NTPNP_PCI0009 [device.txt](https://github.com/OpenIntelWireless/itlwm/files/11208913/device.txt)
    macOS Version: macOS 11.1 (OC 0.9.0)

**Description**
High temperature of AIRport after waking up from sleep.
![befor](https://user-images.githubusercontent.com/103313570/231389512-1f5b6b11-dee8-4b93-9793-f5e7cd5d0201.jpg)![afta](https://user-images.githubusercontent.com/103313570/231389521-d6a93a61-9b72-4ea8-a979-fc7f9125f978.jpg)
doesn't matter:
wifi ON or OFF before sleep
how long sleep. (10sec or 10min)

**Bug Report Archive**
[Log_2023-04-13_02-18-06.log](https://github.com/OpenIntelWireless/itlwm/files/11208909/Log_2023-04-13_02-18-06.log)

**Kext Download Source**
https://github.com/OpenIntelWireless/itlwm/releases/download/v2.2.0-alpha/AirportItlwm-Big_Sur-v2.2.0-DEBUG-alpha-ddd2768.zip

**Comment by SudoFormatAll** [comment]
@zxystd Can you at least explain what is my mistake?
what am I doing wrong?
high temperatures start after sleep is a fact, I have checked this many times.

**Comment by zxystd** [comment]
@SudoFormatAll You know it is `AIRport` process, it is written by Apple, not me, and not relate to the repository, you should find help in other ways.
