### ISSUE TITLE
NOt works on this 

### ISSUE THREAD

**Issue by TahmiedHossain** [OpenIntelWireless/itlwm#869]
I have a wifi card which model is "Qualcomm Atheros QCA9377 Wireless network  adapter". I installed hackintosh successfully. But I can't fix the wifi problem with itlwm or airportitlwm. I have tried all the possible fixes for this. none of them ar works

**Comment by andreszerocross** [comment]
What???? This kext is for Intel Wifi, yours is Atheros. Did you read the "Read Me" in this Github??

**Comment by TahmiedHossain** [comment]
Is there any way to use wifi for Hackintosh with "Qualcomm Atheros QCA9377 Wireless network adapter"?
