### ISSUE TITLE
macOS wake on demand support

### ISSUE THREAD

**Issue by Rastafabisch** [OpenIntelWireless/itlwm#872]
Hello! 

If been using AirportItlwm and previously „standard“ itlwm on my hackintosh for some days now. The last missing feature I can’t get to work in waking on demand (network access) wirelessly. This is useful for file sharing and Remote Desktop connections. 
I tried enabling „wake on wifi“ in the BIOS but that didn’t make a difference. I’m not quite sure if there’s anything else to try or whether this is the current software limitation. 

Thank you for this amazing piece of software anyway!
Best, Rastafabi

**Comment by zxystd** [comment]
Maybe the feature you are talking is `wowl`, considering about hackintosh properties, this feature depends on much unstable things, so we are not plan to implement it yet and in the future.
