### ISSUE TITLE
支持mac os 13的版本正式版什么时候发布呀

### ISSUE THREAD

**Issue by sonhineboy** [OpenIntelWireless/itlwm#873]
支持mac os 13的版本正式版什么时候发布呀

**Comment by asxlf** [comment]
同问，现在13的开发版wifi能连，但是非常慢，灰色等个1，2分钟后才会连接，网卡型号：AX210

**Comment by xtvj** [comment]
我是AX211能连接，但上不了网。

**Comment by dawalishi0821** [comment]
先用itlwm顶着

**Comment by Kingson-Zhang** [comment]
同等，ax210 能驱动但是搜索不到网络

**Comment by zxystd** [comment]
应该是六月前，快了。

**Comment by panmili** [comment]
> 同问，现在13的开发版wifi能连，但是非常慢，灰色等个1，2分钟后才会连接，网卡型号：AX210
最新版本的很快

**Comment by sonhineboy** [comment]
> 应该是六月前，快了。

今天5-31了，快点发正式版吧！^_^

**Comment by williambj1** [comment]
https://github.com/OpenIntelWireless/itlwm/releases/tag/v2.2.0

**Comment by sonhineboy** [comment]
太赞了，回去就更新
