### ISSUE TITLE
Wifi and Bluetooth not working on Intel AC 7265

### ISSUE THREAD

**Issue by Human79** [OpenIntelWireless/itlwm#876]
**Have You Read Our Docs**
Yes

**Are You Reporting A Bug**
Yes 

**Environment**

- Kext Version: Latest Alpha
- WiFi Card Model: Intel AC 7265
- PCI Product ID: 0x095a
- macOS Version: 13.4

**Description**
Wifi doesn't seem to connect. It connects for a few seconds then does not find the IP address and then disconnects and never connects again! Bluetooth doesn't work as well.

**Bug Report Archive**
[bugreport_39922.zip](https://github.com/OpenIntelWireless/itlwm/files/11574367/bugreport_39922.zip)
[bugreport_49563.zip](https://github.com/OpenIntelWireless/itlwm/files/11574368/bugreport_49563.zip)
chive**

**Kext Download Source**
This Github repo

**Comment by zxystd** [comment]
Please try to disable 40mhz channel width on the router and then try again, if the problem also happens, please check your wifi password.

**Comment by Human79** [comment]
Same issue, I've limited the channel width but no dice :(

**Comment by receperoglu** [comment]
yes bluetooth not working.but wifi working

**Comment by Human79** [comment]
@receperoglu Can you explain how wifi works, it doesn't work for me!

**Comment by receperoglu** [comment]
Can you take a look at [this link](https://osxinfo.net/eklentiler/config-plist.49340/). There is a config file that I created for my own laptop. only wifi works.

**Comment by Human79** [comment]
@receperoglu  which Wi-Fi card model?

**Comment by zxystd** [comment]
This card model is confirmed to work(both WiFi and BT), and the log indicated that the card and driver is working, I suggest to use another router or cellphone hotspot to test again.

**Comment by Human79** [comment]
@zxystd I tested with my phone hotspot as well as another wifi network but doesn’t work. Also, to confirm, yes the driver does load but doesn’t connect. Can we reopen this issue?

**Comment by zxystd** [comment]
Maybe you can check the network card connected antennas? the relative rssi value is too low.
![image](https://github.com/OpenIntelWireless/itlwm/assets/16227538/7abbe12e-1706-4768-881c-d12e734d0865)

**Comment by Human79** [comment]
@zxystd The wifi card works perfectly in windows! And yes, the antennas are properly connected!

**Comment by zxystd** [comment]
> @zxystd The wifi card works perfectly in windows! And yes, the antennas are properly connected!

What about the wifi signal on Windows when it is connected? can you also show me the router setting?

**Comment by Human79** [comment]
@zxystd Wifi signal is fine in windows!
Here's the router settings :
![pic1](https://github.com/OpenIntelWireless/itlwm/assets/84245065/4a0f047b-9eea-4076-9094-bb1d96a0b6f1)
![pic2](https://github.com/OpenIntelWireless/itlwm/assets/84245065/a7b9b15c-b98b-41e4-b033-e67ba920b57c)

**Comment by Human79** [comment]
@zxystd Wifi connects on Intel-ac8265, this means that this not a router problem. Could be a model specific problem.

**Comment by Human79** [comment]
@zxystd Is any patch/modification possible that can make this card work?
Thanks a ton!

**Comment by receperoglu** [comment]
> @zxystd Is any patch/modification possible that can make this card work? Thanks a ton!

did you download the last kext update (3 days ago) it should work fine now

**Comment by Human79** [comment]
I'm using the `2.2.0 stable version`. Doesnt seem to work for me. Can you provide a screenshot of it working? Also the .kext you are using and maybe a log to help @zxystd ?

**Comment by zxystd** [comment]
@Human79 I don't know why your router not accept the 4-way handshake packets, but at least you can try this version which use the Linux way of sending packets with RS scaled rate. Related to https://github.com/OpenIntelWireless/itlwm/issues/764#issue-1188039195

[Ventura.zip](https://github.com/OpenIntelWireless/itlwm/files/11642281/Ventura.zip)

**Comment by Human79** [comment]
@zxystd This seems to work for me! Thanks

**Comment by Human79** [comment]
> @Human79 I don't know why your router not accept the 4-way handshake packets, but at least you can try this version which use the Linux way of sending packets with RS scaled rate. Related to [#764 (comment)](https://github.com/OpenIntelWireless/itlwm/issues/764#issue-1188039195)
> 
> [Ventura.zip](https://github.com/OpenIntelWireless/itlwm/files/11642281/Ventura.zip)

@zxystd Can you share the macOS Sonoma version of this kext? Thanks!

**Comment by zxystd** [comment]
@Human79 Now it is on main branch.

**Comment by mnzaroo** [comment]
I need Sequoia verison of ac7265 kext
