### ISSUE TITLE
AX201 Bluetooth not working after upgrade to 2.2.0 Stable

### ISSUE THREAD

**Issue by raucodes** [OpenIntelWireless/itlwm#878]
In Alpha the Bluetooth was working fine, now it is not working anymore. MacOS 13.4 Ventura and Intel AX201

OpenCore 0.9.2

**Comment by wilsonlei** [comment]
same card, same issue. I saw the stable release and installed it right away. Wifi is solid, but Bluetooth cannot be turned on anymore.

**Comment by zxystd** [comment]
are you sure? have you tried replacing to alpha version?

**Comment by johnpapad24** [comment]
> same card, same issue. I saw the stable release and installed it right away. Wifi is solid, but Bluetooth cannot be turned on anymore.

I don't think that those problems have anything to do with the iltwm drivers.

It seems like a problem with IntelBluetoothFirmware kext 

But generally in mac os (and ios) bluetooth is a strange thing and doesn't provide full support for all functions and devices (especially non apple ones)

**Comment by raucodes** [comment]
It works before without problems, Headset, Keyboard and TrackPad has worked perfectly... And Yes Im sure that we replaced all files.

**Comment by zxystd** [comment]
I mean replace back to before alpha version and see if the bluetooth will work again. I don't think the itlwm driver is related.

**Comment by wilsonlei** [comment]
The  IntelBluetoothFirmware version I had is 2.2.0 before upgrading to itlwm to 2.2.0. So the Bluetooth kext was not changed. If there is a way to download the alpha version of itlwm, I would like to give it a try to double check if it is a problem with itlwm or not.

**Comment by zxystd** [comment]
I am outside today, will back home tomorrow afternoon. What's the before working normal system version? Itlwm or Airportitlwm? By the way, have you upgrade your system to 13.4 or 13.5? Bluetooth stack have something badly changes from that version that made the Bluetooth broken.

**Comment by wilsonlei** [comment]
I use Airportitlwm. My system is 13.4 when Bluetooth was working. It's still 13.4 Thanks.

**Comment by raucodes** [comment]
> I am outside today, will back home tomorrow afternoon. What's the before working normal system version? Itlwm or Airportitlwm? By the way, have you upgrade your system to 13.4 or 13.5? Bluetooth stack have something badly changes from that version that made the Bluetooth broken.

Airportitlwm is what I used before and now. 13.5 is beta right?

**Comment by sileshn** [comment]
I can confirm updating Airportitlwm to 2.2.0-stable breaks bluetooth on Ventura. I am on 13.5 beta 2.

Reverting it back to 2.2.0-alpha fixes the issue. I have an [AX3000 Dual Band PCI-E](https://www.asus.com/in/networking-iot-servers/adapters/all-series/pce-ax3000/). 

[This](https://github.com/sileshn/Ryzentosh/commit/d68dd4180fcc0933f764c15ae5ed0fc7ff24ee48) commit has the 2.2.0-alpha version which has bt working on Ventura 13.5 beta2

**Comment by zxystd** [comment]
can you revert this commit a9d0ea9 and recompile Airportitlwm to see if the bluetooth can back to work? If confirm, maybe something with continuity broke the bluetooth, fresh reinstall Ventura may help?

**Comment by sileshn** [comment]
> can you revert this commit [a9d0ea9](https://github.com/OpenIntelWireless/itlwm/commit/a9d0ea94ea4f1c4e806852df39ab3a13e86e3453) and recompile Airportitlwm to see if the bluetooth can back to work? If confirm, maybe something with continuity broke the bluetooth, fresh reinstall Ventura may help?

Yup, that fixed it. Thanks.

For others, you will need the new BlueToolFixup.kext too. Attached the kexts for those who need it.

[Kexts.zip](https://github.com/OpenIntelWireless/itlwm/files/11641772/Kexts.zip)

![Screenshot 2023-06-03 at 10 35 30 AM](https://github.com/OpenIntelWireless/itlwm/assets/977360/bd9d934f-da97-46df-8e73-e28ca189bc78)

**Comment by zxystd** [comment]
It is not a fix, without this commit, Ventura users will suffer long time waiting to connect to the AP again, this commit is to disable virtual interface creation to avoid timeout several times.

**Comment by ameenjuz** [comment]
@zxystd 
temporary workaround
1: uncheck these two value bluetoothExternalDongleFailed&bluetoothlnternalControllerinfo in config
2: boot Monterey usb installer until reach to Disk Utility then restart unplugged the usb 
3: then boot to macOS Ventura 13.5 beta 2 then work fine bluetooth
I think that this issue has related to BlueToolFixup.kext not IntelBluetoothFirmware.kext

**Comment by abbasabidi85** [comment]
Yes the bluetooth is broken after upgrading to AirportItlwm 2.2.0 Stable, I have Intel Wireless 3165 AC wifi card and facing the same issue, I'm also on Ventura 13.4 Stable build with latest Opencore 0.9.2

If anyone find any workout for this please mention it here.

**Comment by TomHeaven** [comment]
Try disabling IntelBTPacher.kext. I encounters kernel panic with the kext on Ventura laptop with AX201. Now my bluetooth works fine with IntelBluetoothFirmware.kext (2.2.0) and BluetoolFixup.kext.

**Comment by wilsonlei** [comment]
Alright, I came across this https://github.com/OpenIntelWireless/IntelBluetoothFirmware/issues/435 and the solution there fixed the Bluetooth under 13.4 for me. I'm using the stable 2.2.0 of Airportitlwm with no problem now.

Add these to OC config.plist NVRAM section where you have the `boot-args`
```
<key>bluetoothInternalControllerInfo</key>
<data>AAAAAAAAAAAAAAAAAAA=</data>
<key>bluetoothExternalDongleFailed</key>
<data>AA==</data>
```

@zxystd  Thank you for making Intel wireless possible on mac!

**Comment by wilsonlei** [comment]
I think the Bluetooth only breaks after you upgrade to 13.4 and reset NVRAM after.

**Comment by abbasabidi85** [comment]
> Alright, I came across this [OpenIntelWireless/IntelBluetoothFirmware#435](https://github.com/OpenIntelWireless/IntelBluetoothFirmware/issues/435) and the solution there fixed the Bluetooth under 13.4 for me. I'm using the stable 2.2.0 of Airportitlwm with no problem now.
> 
> Add these to OC config.plist NVRAM section where you have the `boot-args`
> 
> ```
> <key>bluetoothInternalControllerInfo</key>
> <data>AAAAAAAAAAAAAAAAAAA=</data>
> <key>bluetoothExternalDongleFailed</key>
> <data>AA==</data>
> ```
> 
> @zxystd Thank you for making Intel wireless possible on mac!

Thank you so much, it worked! 

and @zxystd thank you so much for developing the drivers needed. ❤️

now AirportItlwm + Bluetooth is near og MacBook proficiency, connectivity is smooth, wifi is solid.
![Screenshot 2023-06-04 at 6 35 02 PM](https://github.com/OpenIntelWireless/itlwm/assets/75479506/6ffa0c51-3643-4016-b71a-f6598ccb8e4d)

**Comment by zxystd** [comment]
[BlueToolFixupTest.kext.zip](https://github.com/OpenIntelWireless/itlwm/files/11645903/BlueToolFixupTest.kext.zip)
I have added another patch to bypass NVRAM checking(not tested), you can test that if the bluetooth will work without adding the above two NVRAM section.

**Comment by abbasabidi85** [comment]
> [BlueToolFixupTest.kext.zip](https://github.com/OpenIntelWireless/itlwm/files/11645903/BlueToolFixupTest.kext.zip)
> I have added another patch to bypass NVRAM checking(not tested), you can test that if the bluetooth will work without adding the above two NVRAM section.

yes, after adding two NVRAM entries my iMessage and FaceTime is broken

I will update after testing this kext.

**Comment by zxystd** [comment]
> > [BlueToolFixupTest.kext.zip](https://github.com/OpenIntelWireless/itlwm/files/11645903/BlueToolFixupTest.kext.zip)
> > I have added another patch to bypass NVRAM checking(not tested), you can test that if the bluetooth will work without adding the above two NVRAM section.
> 
> The Kext you provided is not working and bluetooth is broken again.

oh, can you upload the bluetooth log for me? I don't have Ventura on hand.
```
sudo log show --last boot | grep -E "bluetooth" > ~/Desktop/shit.log
```

**Comment by abbasabidi85** [comment]
[shit.log](https://github.com/OpenIntelWireless/itlwm/files/11645937/shit.log)
 here it is

**Comment by ameenjuz** [comment]
after tested your added bypass NVRAM BlueToolFixupTest is not working on 13.5 beta 2
here is log
not saved value into nvram
![Screenshot 2023-06-04 at 6 08 28 PM](https://github.com/OpenIntelWireless/itlwm/assets/21066935/20feae71-055c-4569-85c4-6e7d87c84c4b)

[shit.log](https://github.com/OpenIntelWireless/itlwm/files/11645958/shit.log)

**Comment by zxystd** [comment]
@abbasabidi85 @ameenjuz I see, the patch is working, but seems that further work is needed, give me a second to see.

**Comment by zxystd** [comment]
[BlueToolFixup.kext.zip](https://github.com/OpenIntelWireless/itlwm/files/11646058/BlueToolFixup.kext.zip)

**Comment by ameenjuz** [comment]
> [BlueToolFixup.kext.zip](https://github.com/OpenIntelWireless/itlwm/files/11646058/BlueToolFixup.kext.zip)

Great job  you fixed finally  i appreciate your struggle
I tested worked fine on 13.4 and 13.5 beta 2

**Comment by zxystd** [comment]
@ameenjuz Thank you. So everybody suffer this issue can test this kext, I think it is not the fault of itlwm.

**Comment by ameenjuz** [comment]
@zxystd  your are right
It is not fault of itlwm 
It issue had related to bluetoolfixup

**Comment by abbasabidi85** [comment]
> BlueToolFixup.kext.zip

After this kext, time taken to pair with bluetooth devices is delayed as compared to NVRAM edit, auto-connect is not working. bluetooth doesn't seem smooth. anyways thank you for the kext at least now its working.

**Comment by ameenjuz** [comment]
@abbasabidi85  
Yes It is time taken to pair with bluetooth devices is delayed
Further fixes is need

**Comment by ameenjuz** [comment]
once again bt & wifi break on macOS Sonoma 14

**Comment by sileshn** [comment]
Bluetooth works for me on Sonoma

**Comment by RyzenDew** [comment]
> [BlueToolFixup.kext.zip](https://github.com/OpenIntelWireless/itlwm/files/11646058/BlueToolFixup.kext.zip)

This fixed BT on macos 14 thank you but my wifi is still broken but wifi is slow i can wait

**Comment by ameenjuz** [comment]
after reset nvram bt is not working on macOS 14

**Comment by zxystd** [comment]
https://github.com/OpenIntelWireless/IntelBluetoothFirmware/issues/437#issuecomment-1579931908

**Comment by gajosadrian** [comment]
> [BlueToolFixup.kext.zip](https://github.com/OpenIntelWireless/itlwm/files/11646058/BlueToolFixup.kext.zip)

I can totally confirm that this kext fixed my problems with bluetooth.
I have Ventura 13.4 and latest kext for bluetooth. Thanks bro ♥️

**Comment by diepeterpan** [comment]
> Alright, I came across this [OpenIntelWireless/IntelBluetoothFirmware#435](https://github.com/OpenIntelWireless/IntelBluetoothFirmware/issues/435) and the solution there fixed the Bluetooth under 13.4 for me. I'm using the stable 2.2.0 of Airportitlwm with no problem now.
> 
> Add these to OC config.plist NVRAM section where you have the `boot-args`
> 
> ```
> <key>bluetoothInternalControllerInfo</key>
> <data>AAAAAAAAAAAAAAAAAAA=</data>
> <key>bluetoothExternalDongleFailed</key>
> <data>AA==</data>
> ```
> 
> @zxystd Thank you for making Intel wireless possible on mac!

This also works for non Intel bluetooth which don't want to work after a NVRAM reset, thank you so much for posting.  Took me quite a bit of time to get to this one.

**Comment by ahdyt** [comment]
Hi Guys i'm on ventura 13.5, wifi and bluetooth are disabled, my wifi is intel ax201, using airportitlwm 2.2.0 stable or alpha didn't fix the problem, is there any other settings should I do?

I've tried 

<key>bluetoothInternalControllerInfo</key>
<data>AAAAAAAAAAAAAAAAAAA=</data>
<key>bluetoothExternalDongleFailed</key>
<data>AA==</data>

but not working either
my kexts

aiprotiltwm
intelbluetoothfirmware
bluetoolfixup

**Comment by diepeterpan** [comment]
> Hi Guys i'm on ventura 13.5, wifi and bluetooth are disabled, my wifi is intel ax201, using airportitlwm 2.2.0 stable or alpha didn't fix the problem, is there any other settings should I do?
> 
> I've tried
> 
> bluetoothInternalControllerInfo AAAAAAAAAAAAAAAAAAA= bluetoothExternalDongleFailed AA==
> 
> but not working either my kexts
> 
> aiprotiltwm intelbluetoothfirmware bluetoolfixup
> 
> i've also already deleted network preferences folders in library

Did you install IntelBTPatcher.kext

https://openintelwireless.github.io/IntelBluetoothFirmware/FAQ.html#what-additional-steps-should-i-do-to-make-bluetooth-work-on-macos-monterey-and-newer 

Something else I had to do for my Acer Aspire to get Bluetooth working was to tape two pins on the board as the Bluetooth was not detected by Windows either - 
![4B488E57-697A-449D-A550-34294EB339A1_1_105_c](https://github.com/OpenIntelWireless/itlwm/assets/15066052/25436f3c-afc0-4f60-83da-d19e086e2da4)

**Comment by ahdyt** [comment]
> > Hi Guys i'm on ventura 13.5, wifi and bluetooth are disabled, my wifi is intel ax201, using airportitlwm 2.2.0 stable or alpha didn't fix the problem, is there any other settings should I do?
> > I've tried
> > bluetoothInternalControllerInfo AAAAAAAAAAAAAAAAAAA= bluetoothExternalDongleFailed AA==
> > but not working either my kexts
> > aiprotiltwm intelbluetoothfirmware bluetoolfixup
> > i've also already deleted network preferences folders in library
> 
> Did you install IntelBTPatcher.kext
> 
> https://openintelwireless.github.io/IntelBluetoothFirmware/FAQ.html#what-additional-steps-should-i-do-to-make-bluetooth-work-on-macos-monterey-and-newer
> 
> Something else I had to do for my Acer Aspire to get Bluetooth working was to tape two pins on the board as the Bluetooth was not detected by Windows either - ![4B488E57-697A-449D-A550-34294EB339A1_1_105_c](https://user-images.githubusercontent.com/15066052/258633987-25436f3c-afc0-4f60-83da-d19e086e2da4.jpeg)

Oh yeah that one too, What I don't add is the IntelBluetoothInjector.

Are you on macos ventura using ax201 and same wifi && bluetooth too? Mind share your kexts and other configurations like device properties or boot-args? 

I'm currently using itlwm + Heliport for wifi workaround.

**Comment by diepeterpan** [comment]
> > > Hi Guys i'm on ventura 13.5, wifi and bluetooth are disabled, my wifi is intel ax201, using airportitlwm 2.2.0 stable or alpha didn't fix the problem, is there any other settings should I do?
> > > I've tried
> > > bluetoothInternalControllerInfo AAAAAAAAAAAAAAAAAAA= bluetoothExternalDongleFailed AA==
> > > but not working either my kexts
> > > aiprotiltwm intelbluetoothfirmware bluetoolfixup
> > > i've also already deleted network preferences folders in library
> > 
> > 
> > Did you install IntelBTPatcher.kext
> > https://openintelwireless.github.io/IntelBluetoothFirmware/FAQ.html#what-additional-steps-should-i-do-to-make-bluetooth-work-on-macos-monterey-and-newer
> > Something else I had to do for my Acer Aspire to get Bluetooth working was to tape two pins on the board as the Bluetooth was not detected by Windows either - ![4B488E57-697A-449D-A550-34294EB339A1_1_105_c](https://user-images.githubusercontent.com/15066052/258633987-25436f3c-afc0-4f60-83da-d19e086e2da4.jpeg)
> 
> Oh yeah that one too, What I don't add is the IntelBluetoothInjector.
> 
> Are you on macos ventura using ax201 and same wifi && bluetooth too? Mind share your kexts and other configurations like device properties or boot-args?
> 
> I'm currently using itlwm + Heliport for wifi workaround.

I am using Ventura and an AX210.

![image](https://github.com/OpenIntelWireless/itlwm/assets/15066052/46565750-18d9-4584-ac18-f7dd92cb1a3f)

Using version 2.40

Maybe try taping the pins as indicated in the previous post.

**Comment by ahdyt** [comment]
![Screenshot 2023-08-06 at 23 15 36](https://github.com/OpenIntelWireless/itlwm/assets/34616952/210221e6-3555-40ef-b565-05328ba9bec9)

**Comment by ahdyt** [comment]
> > > > Hi Guys i'm on ventura 13.5, wifi and bluetooth are disabled, my wifi is intel ax201, using airportitlwm 2.2.0 stable or alpha didn't fix the problem, is there any other settings should I do?
> > > > I've tried
> > > > bluetoothInternalControllerInfo AAAAAAAAAAAAAAAAAAA= bluetoothExternalDongleFailed AA==
> > > > but not working either my kexts
> > > > aiprotiltwm intelbluetoothfirmware bluetoolfixup
> > > > i've also already deleted network preferences folders in library
> > > 
> > > 
> > > Did you install IntelBTPatcher.kext
> > > https://openintelwireless.github.io/IntelBluetoothFirmware/FAQ.html#what-additional-steps-should-i-do-to-make-bluetooth-work-on-macos-monterey-and-newer
> > > Something else I had to do for my Acer Aspire to get Bluetooth working was to tape two pins on the board as the Bluetooth was not detected by Windows either - ![4B488E57-697A-449D-A550-34294EB339A1_1_105_c](https://user-images.githubusercontent.com/15066052/258633987-25436f3c-afc0-4f60-83da-d19e086e2da4.jpeg)
> > 
> > 
> > Oh yeah that one too, What I don't add is the IntelBluetoothInjector.
> > Are you on macos ventura using ax201 and same wifi && bluetooth too? Mind share your kexts and other configurations like device properties or boot-args?
> > I'm currently using itlwm + Heliport for wifi workaround.
> 
> I am using Ventura and an AX210.
> 
> ![image](https://user-images.githubusercontent.com/15066052/258654187-46565750-18d9-4584-ac18-f7dd92cb1a3f.png)
> 
> Using version 2.40
> 
> Maybe try taping the pins as indicated in the previous post.

The kexts version are unclear, I use OCAuxiliaryTools. Well I guess so, or perhaps USB Mapping. As the bluetooth just can be on or off but only cosmetics. Nothing happens.

**Comment by ahdyt** [comment]
![Screenshot 2023-08-06 at 23 21 45](https://github.com/OpenIntelWireless/itlwm/assets/34616952/89618696-d058-4d44-94f1-16d3f6be9ed9)

**Comment by lollo78** [comment]
> [BlueToolFixup.kext.zip](https://github.com/OpenIntelWireless/itlwm/files/11646058/BlueToolFixup.kext.zip)

Hi @zxystd, I tried the advices posted in this thread, and all the latest stable versions of the kexts required, but Bluetooth doesn't work for me. Sadly, also your BlueToolFixup.kext failed. I tried in Ventura and after I upgraded to Sonoma, but BT still not working.

In attached my shit.log: I really hope for a fix. 
[shit.log](https://github.com/OpenIntelWireless/itlwm/files/13464907/shit.log)

My card is an Intel AX210NGW and it works fine in Windows. So, it's not a faulty card.
Thanks for all

**Comment by yflwz** [comment]
Ventura 13.6 has the same problem, WIFI works normally, but Bluetooth cannot be driven.

**Comment by abbasabidi85** [comment]
> Bluetooth works for me on Sonoma

how? which kexts are you using and their specific versions?

**Comment by abbasabidi85** [comment]
> Ventura 13.6 has the same problem, WIFI works normally, but Bluetooth cannot be driven.

yes same issue in 13.6 bluetooth is unable to function properly i.e search devices, connect to save devices, connect to searched device etc

**Comment by TheLazyGeekGuy** [comment]
Does it work properly now ?

**Comment by abbasabidii** [comment]
> Does it work properly now ?

No still there are issues with connecting to bluetooth devices especially wireless mouse and sometimes it doesn't connect with earbuds(pixel buds a series) either
