### ISSUE TITLE
alguem sabe me ajudar tenho um dell latitude 5410 com o macOS ventura porem o wifi e o bluetooth nao estão funcionando minha placa e a AX201NGW intel 

### ISSUE THREAD

**Issue by sobral666** [OpenIntelWireless/itlwm#880]
alguem sabe me ajudar tenho um dell latitude 5410 com o macOS ventura porem o wifi e o bluetooth nao estao funcionando minha placa e uma  AX201NGW intel desde ja obrigado meu whatz (21)99760-2736

**Comment by zxystd** [comment]
Please use English and follow the issue template format, thanks.
