### ISSUE TITLE
Both itlwm and AirportItlwm don't work. Can only see Wi-Fi device in gfxutil.

### ISSUE THREAD

**Issue by dsanke** [OpenIntelWireless/itlwm#881]
**Have You Read Our Docs**
Yes.

**Are You Reporting A Bug**
I am not sure. It may not related to itlwm but I don't know what to do now.

**Environment**

- Kext Version: 2.2.0
- WiFi Card Model: Intel AC-3160
- PCI Product ID: 8086:08b3
- macOS Version: 12.6.6 Monterey

**Description**

I am using AMD Ryzen 3 5300U in a tiny machine without discrete GPU.
Both itlwm and AirportItlwm don't work. Can only see Wi-Fi device in gfxutil.
![截屏2023-06-05 13 47 36](https://github.com/OpenIntelWireless/itlwm/assets/2108751/11b87cab-66a8-41cf-9b08-6b48a9e776ee)
![截屏2023-06-05 13 51 09](https://github.com/OpenIntelWireless/itlwm/assets/2108751/1f2cbc53-c938-464f-96e7-5c3ba95bd09b)
I tried SSDT-BRG0 to make Wi-Fi card shown as PXSX, but the same result. It don't work.

**Bug Report Archive**

I can't get HeliPort run.

**Kext Download Source**

https://github.com/OpenIntelWireless/itlwm/releases/tag/v2.2.0

**Comment by zxystd** [comment]
https://openintelwireless.github.io/itlwm/Troubleshooting.html#runtime-logs
![image](https://github.com/OpenIntelWireless/itlwm/assets/16227538/789fdc9f-7fd5-4564-81a0-96f1ea7aa989)

Follow guide to get runtime log.

**Comment by dsanke** [comment]
[Log_2023-06-05_14-50-28.log](https://github.com/OpenIntelWireless/itlwm/files/11649494/Log_2023-06-05_14-50-28.log)
