### ISSUE TITLE
AirPlay/Screen Mirroring Not Working

### ISSUE THREAD

**Issue by urayz** [OpenIntelWireless/itlwm#882]
**Have You Read Our Docs**
Yes

**Are You Reporting A Bug**
No

**Environment**

- Kext Version: 2.2.0
- WiFi Card Model: Intel 9560NGW
- PCI Product ID: 8086,9DF0
- macOS Version: 13.5

**Description**
Wireless Screen Mirroring not working anymore after update to 2.2.0. Before that,on Monterey with ver. 2.1.0, I could use airplay.

**Kext Download Source**
Official Github itlwm page

**Comment by zxystd** [comment]
expected result.

**Comment by AlphaNecron** [comment]
They works for me on 2.2.0, but with low FPS, idk why.
