### ISSUE TITLE
Slow wifi speed - solution deactivate IPV6

### ISSUE THREAD

**Issue by Siggmaster** [OpenIntelWireless/itlwm#884]
**Have You Read Our Docs**
YES

**Are You Reporting A Bug**
YES

**Environment**

- Kext Version: 2.20 stable
- WiFi Card Model: AC8265
- PCI Product ID: Thinkpad T480
- macOS Version: Ventura 13.4

**Description**
I was facing slow and unstable internet with the latest AirportITWLM. Tried everything, including deactivating Bluetooth. 
Did some investigation and found out, that slow wifi speed is typical for the Intel 8265 card with IPV6 activated.

Solution: Decativate IPV6 via Terminal
networksetup -setv6off Wi-Fi
networksetup -setv6off Ethernet

Internet works stable and fast now. 
Bluetooth as well with NVRAM fix (bluetoothExternalDongleFailed & bluetoothInternalControllerInfo)

Thanks for your great work so far!

**Comment by zxystd** [comment]
https://github.com/OpenIntelWireless/itlwm/issues/876#issuecomment-1574822796

can you try this version?

**Comment by Siggmaster** [comment]
> [#876 (comment)](https://github.com/OpenIntelWireless/itlwm/issues/876#issuecomment-1574822796)
> 
> can you try this version?

Installed it right now, works flawless!

**Comment by zxystd** [comment]
@Siggmaster This change is not even test yet, if something wrong happened, please let me know. I am considering to merge it in v2.3.0 version. Thanks.

**Comment by Siggmaster** [comment]
@zxystd: Here my config which runs absolutely stable.
What were your changes in the 2.30?

[https://imgur.com/6ngMpUV](url)

**Comment by zxystd** [comment]
@Siggmaster the changes was track on https://github.com/OpenIntelWireless/itlwm/issues/764, and maybe alive on v2.3.0.
The actual change is the Tx(for STA mode, you can understand it as Upload) rate selection algorithm, on main branch, we are using the rate algorithm from OpenBSD and extend 40/80/160MHz feature support by me(only affect the gen1/DVM devices, gen2/gen3 devices using the rate algorithm from firmware), now I ported the RS rate algorithm which is from linux iwlwifi, intended to move closer to a more stable rate like linux iwlwifi driver.

**Comment by Siggmaster** [comment]
@zxystd : I can just confirm that the wifi is super stable on different router models. Upload rate about 100 mbit/s is no prob.

**Comment by zxystd** [comment]
thank you for the confirmation.
Is the ipv6 problem got fixed with this version?
By the way, does the main branch version have another problems except the ipv6 one?

**Comment by Siggmaster** [comment]
@zxystd : Did test it now, IPV6 activated, works great with IPV6 activated.

Here some testing of wifi and bluetooth, No intelbluetoothpatcher:

IntelBluetoothFirmware V2.20
BlueToolFixup V2.6.6.
No Bluetooth after wake from sleep, but with pkill bluetoothd after awake from sleep restarts bluetooth and auto-connect mouse/headset works

IntelBluetoothFirmware V2.20
BlueToolFixup V2.6.7:
Bluetooth ok after sleep, but no auto-connect of devices. Needs device off/on for re-connect.

AirportItwlm2.20: Works fine with IPV6 deactivated, works slow ith IPV6 activated
AirportItwlm 2.30: Works fine with IPV6 deactivated, works fine with IPV6 activated

**Comment by zxystd** [comment]
resolved in v2.3.0
