### ISSUE TITLE
Airportitlwm is not working Ventura

### ISSUE THREAD

**Issue by Dicheto2302** [OpenIntelWireless/itlwm#887]
**Have You Read Our Docs**
Yes

**Are You Reporting A Bug**
Maybe Yes 

**Environment**

- Kext Version: latest
- WiFi Card Model: AC 3165
- PCI Product ID: Idk
- macOS Version: 13.4

**Description**
After I reseted my nvram the OC disappeared as a boot entry. I fixed it, but the Airportitlwm is not working. OC configurator says that it's imported in config.plist and all the steps in troubleshoot menu are tried. 

**Bug Report Archive**
 It says that it is not running
 

**Kext Download  Source**
My EFI came with it, but I replaced it with the official one. 
Link to my EFI - https://github.com/mtahanian/EFI-Lenovo

The bluetooth is also not working, but my audio and video are working.

**Comment by zxystd** [comment]
Running log is needed.
