### ISSUE TITLE
[BUG] No WiFi shown after sleep

### ISSUE THREAD

**Issue by mehapps** [OpenIntelWireless/itlwm#889]
**Have You Read Our Docs**
Yes

**Are You Reporting A Bug**
Yes

**Environment**

- Kext Version: 2.2.0 Stable
- WiFi Card Model: 7265 AC
- PCI Product ID: 0x8086
- macOS Version: 12.6

**Description**

After the Mac goes to sleep, it comes back up but without any internet access. WiFi section shows no listed networks. 

**Bug Report Archive**

[Log_now.log](https://github.com/OpenIntelWireless/itlwm/files/11728744/Log_now.log)

**Kext Download Source**

Downloaded from GitHub releases on this repo

**Comment by zxystd** [comment]
这里不解决黑果的睡眠问题，谢谢。
