### ISSUE TITLE
wireless 7260 itlwm: acquiring device failed

### ISSUE THREAD

**Issue by AbelHe** [OpenIntelWireless/itlwm#893]
**Have You Read Our Docs**
Yes

**Are You Reporting A Bug**
Yes

**Environment**
- Kext Version: 2.2.0
- WiFi Card Model: Intel(R) Dual Band Wireless AC 7260  
- PCI Product ID: 0x08B1
- macOS Version: 12.6.7 (21G651)

**Description**

bluetooth and wifi both works fine on win10(booting via either way: window loader and opencore)
bluetooth works fine on macos, but wifi not.
I follow the troubleshooting manual, delete network and configuration files, but issues remains.
Also checked fast boot setting in BIOS, disabled.

**Bug Report Archive**

[    4.682099]: AirportItlwm::init IO80211Legacy_kexts-37.1 "IO80211Legacy_kexts-37.1" Jun  8 2023 23:56:37
[    4.682135]: itlwm: iwm_match devId=0x08B1
[    4.683066]: IO80211Controller::createIOReporters 0x390b4e28f3af8939
[    4.684644]: IO80211Controller::findAndAttachToFaultReporter no pipe found, making it
[    4.684773]: IO80211Controller::start _controller is 0x390b4e28f3af8939, provider is 0x390b4e2dc00ddef9
[    4.694870]: itlwm: iwm_attach
[    4.694947]: itlwm: , 
[    4.694954]: itlwm: alloc contig
[    4.955117]: itlwm: taskq taskq_create_thread lock
[    4.955122]: itlwm: taskq taskq_create_thread unlock
[    4.955123]: itlwm: config ieee80211
[    4.955136]: itlwm: ieee80211_channel_init
[    4.955136]: itlwm: taskq taskq_create_thread lock
[    4.955138]: itlwm: taskq taskq_create_thread lock
[    4.955140]: itlwm: taskq taskq_create_thread unlock
[    4.955142]: itlwm: taskq taskq_create_thread unlock
[    4.955143]: itlwm: ieee80211_set_link_state nstate=2, old_state=-1
[    4.955144]: itlwm: ieee80211_set_link_state LINK_STATE_IS_DOWN
[    4.955147]: itlwm: ieee80211_media_init
[    4.955148]: itlwm: taskq taskq_thread schedule task
[    4.955161]: itlwm: taskq taskq_create_thread lock
[    4.955163]: itlwm: taskq taskq_create_thread unlock
[    4.955164]: itlwm: taskq taskq_thread schedule task
[    4.955230]: itlwm: iwm_preinit
[    4.955231]: itlwm: iwm_prepare_card_hw
[    4.955237]: itlwm: iwm_start_hw
[    4.955238]: itlwm: iwm_prepare_card_hw
[    4.960251]: itlwm: iwm_apm_init
[    4.960274]: itlwm: itlwm: L1 Disabled - LTR Disabled
[    5.162103]: itlwm: itlwm: acquiring device failed
[    5.326068]: hook_thread_userret calleduserret(438): invoking callback; 0/4 remainingitlwm: itlwm: acquiring device failed
[    5.566796]: itlwm: itlwm: acquiring device failed
[    5.768561]: itlwm: itlwm: acquiring device failed
[    5.944553]: sandboxd rejected approval request from dirhelper for kTCCServiceSystemPolicyAllFiles (/private/var/folders/zz/zyxvpxvq6csfxvn_n00000sm00006d/T/com.apple.trustd/TemporaryItems): deniedSystem Policy: dirhelper(26) deny(1) file-write-unlink /private/var/folders/zz/zyxvpxvq6csfxvn_n00000sm00006d/T/com.apple.trustd/TemporaryItemssandboxd rejected approval request from dirhelper for kTCCServiceSystemPolicyAllFiles (/private/var/folders/zz/zyxvpxvq6csfxvn_n00000sm00006d/T/com.apple.trustd): deniedSystem Policy: dirhelper(26) deny(1) file-write-unlink /private/var/folders/zz/zyxvpxvq6csfxvn_n00000sm00006d/T/com.apple.trustdsandboxd rejected approval request from dirhelper for kTCCServiceSystemPolicyAllFiles (/private/var/folders/zz/zyxvpxvq6csfxvn_n00000sm00006d/T/locationd/TemporaryItems): deniedSystem Policy: dirhelper(26) deny(1) file-write-unlink /private/var/folders/zz/zyxvpxvq6csfxvn_n00000sm00006d/T/locationd/TemporaryItemssandboxd rejected approval request from dirhelper for kTCCServiceSystemPolicyAllFiles (/private/var/folders/zz/zyxvpxvq6csfxvn_n00000sm00006d/T/locationd): deniedSystem Policy: dirhelper(26) deny(1) file-write-unlink /private/var/folders/zz/zyxvpxvq6csfxvn_n00000sm00006d/T/locationdsandboxd rejected approval request from dirhelper for kTCCServiceSystemPolicyAllFiles (/private/var/folders/zz/zyxvpxvq6csfxvn_n00000sm00006d/T/com.apple.geod/TemporaryItems): deniedSystem Policy: dirhelper(26) deny(1) file-write-unlink /private/var/folders/zz/zyxvpxvq6csfxvn_n00000sm00006d/T/com.apple.geod/TemporaryItemssandboxd rejected approval request from dirhelper for kTCCServiceSystemPolicyAllFiles (/private/var/folders/zz/zyxvpxvq6csfxvn_n00000sm00006d/T/com.apple.geod): deniedSystem Policy: dirhelper(26) deny(1) file-write-unlink /private/var/folders/zz/zyxvpxvq6csfxvn_n00000sm00006d/T/com.apple.geodsandboxd rejected approval request from dirhelper for kTCCServiceSystemPolicyAllFiles (/private/var/folders/zz/zyxvpxvq6csfxvn_n00000sm00006d/T/.AddressBookLocks): deniedSystem Policy: dirhelper(26) deny(1) file-write-unlink /private/var/folders/zz/zyxvpxvq6csfxvn_n00000sm00006d/T/.AddressBookLockssandboxd rejected approval request from dirhelper for kTCCServiceSystemPolicyAllFiles (/private/var/folders/zz/zyxvpxvq6csfxvn_n00000sm00006d/T/.CalendarLocks): deniedSystem Policy: dirhelper(26) deny(1) file-write-unlink /private/var/folders/zz/zyxvpxvq6csfxvn_n00000sm00006d/T/.CalendarLocksitlwm: itlwm: acquiring device failed
[    6.163685]: ALF, old data swfs_pid_entry <ptr>, updaterules_msg <ptr>, updaterules_state <ptr>ALF, old data swfs_pid_entry <ptr>, updaterules_msg <ptr>, updaterules_state <ptr>itlwm: itlwm: acquiring device failed
[    6.175179]: itlwm: iwm_init_msix_hw
[    6.175180]: itlwm: iwm_conf_msix_hw
[    6.175184]: itlwm: iwm_check_rfkill RF_KILL hw: 0
[    6.175185]: itlwm: iwm_run_init_mvm_ucode justnvm=1
[    6.175187]: itlwm: iwm_load_ucode_wait_alive ucode_type=1
[    6.178944]: itlwm: load firmware iwm-7260-17 done
[    6.178977]: itlwm: iwm_start_fw ucode_type=1
[    6.178978]: itlwm: iwm_apm_init
[    6.178999]: itlwm: itlwm: L1 Disabled - LTR Disabled
[    6.247755]: Sandbox apply: corebrightnessd[145] com.apple.corebrightnessdSandbox apply: notifyd[143] <bytes>Sandbox apply: logd[82] <bytes>Sandbox apply: wifiFirmwareLoad[85] <bytes>itlwm: itlwm: acquiring device failed
[    6.623568]: itlwm: itlwm: acquiring device failed
[    6.895723]: itlwm: itlwm: acquiring device failed
[    6.918898]: successfully truncated homedirs to 23 bytessuccessfully truncated homedir_ancestors to 16 bytesSandbox apply: trustdFileHelper[198] <bytes>successfully truncated syncroots to 0 bytessuccessfully truncated syncroot_ancestors to 0 bytesALF, old data swfs_pid_entry <ptr>, updaterules_msg <ptr>, updaterules_state <ptr>Sandbox apply: usbmuxd[124] <bytes>ALF, old data swfs_pid_entry <ptr>, updaterules_msg <ptr>, updaterules_state <ptr>successfully truncated network-exemptions to 0 bytesSandbox apply: runningboardd[201] <bytes>1 duplicate report for Sandbox: contextstored(182) deny(1) user-preference-read kCFPreferencesAnyApplicationSystem Policy: diskarbitrationd(111) deny(1) file-read-data /dev/rdisk2s5s1Sandbox apply: nehelper[219] <bytes>uipc_accept: peer disconnected unp_gencnt 27itlwm: itlwm: acquiring device failed
[    7.211664]: Sandbox apply: mDNSResponder[226] <bytes>Sandbox apply: mDNSResponderHel[243] <bytes>1 duplicate report for System Policy: diskarbitrationd(111) deny(1) file-read-data /dev/rdisk2s5s1Sandbox: mDNSResponderHel(243) deny(1) file-read-data /Library/Preferences/com.apple.security.plistSandbox: mDNSResponderHel(243) deny(1) user-preference-read com.apple.securitySandbox: mDNSResponderHel(243) deny(1) user-preference-read kCFPreferencesAnyApplicationSandbox apply: nsurlsessiond[241] <bytes>1 duplicate report for Sandbox: mDNSResponderHel(243) deny(1) user-preference-read kCFPreferencesAnyApplicationSandbox: contextstored(182) deny(1) mach-lookup com.apple.tccd.systemSandbox apply: dasd[132] <bytes>1 duplicate report for Sandbox: contextstored(182) deny(1) mach-lookup com.apple.tccd.systemSandbox: dasd(132) allow file-read-data /Library/Preferences/SystemConfiguration/preferences.plistSandbox apply: distnoted[236] <bytes>itlwm: itlwm: acquiring device failed
[    7.696005]: Sandbox apply: secinitd[257] <bytes>itlwm: itlwm: acquiring device failed
[    7.849151]: Sandbox apply: com.apple.geod[255] <bytes>itlwm: itlwm: acquiring device failed
[    8.134389]: itlwm: itlwm: acquiring device failed
[    8.341762]: itlwm: itlwm: acquiring device failed
[    8.554274]: itlwm: itlwm: acquiring device failed
[    8.554278]: itlwm: itlwm: unable to init nic
[    8.554279]: itlwm: itlwm: failed to load init firmware
[    8.554280]: itlwm: iwm_stop_device
[    8.720405]: Sandbox apply: usbd[244] <bytes>itlwm: itlwm: acquiring device failed
[    8.929649]: Sandbox apply: rpcsvchost[273] <bytes>uipc_accept: peer disconnected unp_gencnt 50itlwm: itlwm: acquiring device failed
[    9.027130]: 1 duplicate report for Sandbox: mediaremoted(88) allow file-read-data /Library/Preferences/com.apple.networkd.plistSandbox: mediaremoted(88) allow file-read-data /private/var/root/Library/MediaRemote/DeviceInfo.plistSandbox apply: systemstats[91] <bytes>itlwm: itlwm: acquiring device failed
[    9.272207]: itlwm: iwm_conf_msix_hw
[    9.281444]: itlwm: iwm_check_rfkill RF_KILL hw: 0
[    9.290575]: itlwm: iwm_prepare_card_hw
[    9.300894]: itlwm: attach failed.
[    9.309950]: itlwm: ieee80211_ifdetach
[    9.318968]: itlwm: ieee80211_proto_detach
[    9.327986]: itlwm: ieee80211_crypto_detach
[    9.336985]: itlwm: ieee80211_node_detach
[    9.345991]: itlwm: ifmedia_delete_instance
[    9.345999]: itlwm: taskq taskq_thread schedule task done
[    9.355174]: itlwm: taskq taskq_thread schedule task wakeup
[    9.359356]: Sandbox apply: com.apple.cmio.r[147] <bytes>itlwm: taskq taskq_thread schedule task done
[    9.373192]: itlwm: taskq taskq_thread schedule task wakeup
[    9.386775]: Sandbox apply: distnoted[278] <bytes>itlwm: releaseAll
[    9.396736]: Sandbox apply: mds_stores[279] <bytes>itlwm: releaseAll
[    9.407688]: itlwm: attach fail
[    9.416623]: itlwm: free
[    9.425220]: itlwm: virtual void ItlHalService::free()
[   22.506256]: successfully parsed 1/4 entries for file itlwm_logs.logsuccessfully parsed 1/4 entries for file itlwm_logs.logsuccessfully parsed 1/4 entries for file itlwm_logs.logsuccessfully parsed 1/4 entries for file HeliPort_logs.logsuccessfully parsed 1/4 entries for file HeliPort_logs.logsuccessfully parsed 1/4 entries for file HeliPort_logs.logSandbox: homed(414) deny(1) mach-lookup com.apple.coreduetd.knowledgeSandbox: homed(414) deny(1) mach-lookup com.apple.coreduetd.contextCorpse released, count at 1

**Kext Download Source**

download from github release

**Comment by zxystd** [comment]
EFI related issue.
