### ISSUE TITLE
Issues with Nothing Phone 1 Hotspot and WPA/WEP Security when Connected via Xiaomi Mi Pad 6

### ISSUE THREAD

**Issue by BudDeuce** [OpenIntelWireless/itlwm#904]
**Have You Read Our Docs**
Yes

**Are You Reporting A Bug**
Yes

**Environment**

- Kext Version:  itlwm: 2.2.0 fw: 17.3216344376.0
- WiFi Card Model: Wireless 3165
- PCI Product ID: 0x8110
- macOS Version: 13.5 (22G74)

**Description**
When my friend is attempting to use the Nothing Phone 1's hotspot, it is necessary for him to first connect to his Xiaomi Mi Pad 6's hotspot. This leads to problems with WPA/WEP security. The system displays an error message stating that the phone was previously joined as WPA2/WPA3 Personal, not WEP. After some time, a prompt appears, asking him to enter a WEP password, but attempting to join the network using this password fails. However, when he manually selects the network option from the WiFi menu, the connection is established successfully.

**Bug Report Archive**
https://we.tl/t-8CqrgQbsTD

**Kext Download Source**
https://github.com/OpenIntelWireless/itlwm/releases/download/v2.2.0/AirportItlwm_v2.2.0_stable_Ventura.kext.zip

**Comment by zxystd** [comment]
Sorry, the log file is expired, can you upload here directly?

**Comment by BudDeuce** [comment]
Sure, I will get the log files as soon as I can.

**Comment by BudDeuce** [comment]
Here you go: https://drive.google.com/file/d/1cfoVMOvDfwBc9klRzesWtDCFpXPpxKwb/view?usp=sharing

The file was too big to upload here (264 MB), so I used Drive instead. The link shouldn't expire now.

**Comment by zxystd** [comment]
Please follow this guide to get the full log.
https://openintelwireless.github.io/itlwm/Troubleshooting.html#runtime-logs

**Comment by BudDeuce** [comment]
What a ride of nostalgia, some commit fixed this issue btw.

**Comment by rkt21** [comment]
Hi buddeuce this problem not solve yet.  I not to able send to message on discord
![IMG-20240624-WA0005](https://github.com/OpenIntelWireless/itlwm/assets/99807936/41444fa9-4645-48c5-b855-bfcc403e2fac)

**Comment by BudDeuce** [comment]
Open your own issue

**Comment by rkt21** [comment]
Buddeuce If you know how to solve this issue plz dm in discord.

**Comment by Jkkushwaha49** [comment]
Budduece I jkkushwaha why you blocked me in discord please unblock me I can't send you any message

**Comment by rkt21** [comment]
Plz unblock me also bud.
