### ISSUE TITLE
Intel AX210 （M7633-006）Wireless network interface card cannot be driven

### ISSUE THREAD

**Issue by QianShanWoDu** [OpenIntelWireless/itlwm#905]
**Have You Read Our Docs**
Yes.

**Are You Reporting A Bug**
Yes.

**Environment**

- Kext Version: itlwm.kext(2.2.0 and 2.3.0 );airportitlwm.kext(2.2.0 and 2.3.0 )
- WiFi Card Model: Intel AX210 （M7633-006）
- PCI Product ID: PCI\VEN_8086&DEV_2725&SUBSYS_00248086&REV_1A
- macOS Version: Ventura13.5

**Description**
First of all, thank you bosses for your efforts for Black Apple. The situation is as follows:
My host model is beelink ser5pro (cpu: AMD5600H), Bluetooth can be used normally, but the wireless network interface card cannot be driven after trying various methods. Forced loading and resetting the network will not work. The cache will be reset when updating the driver. Enter "kextstat | grep -i" KEXT S_NAME "at end point to prompt" Executing: /usr/bin/kmutil showloaded No variant specified, falling back to release ".

**Bug Report Archive**
[bugreport_56808.zip](https://github.com/OpenIntelWireless/itlwm/files/12269077/bugreport_56808.zip)
[Log_2023-08-06_17-18-22.log](https://github.com/OpenIntelWireless/itlwm/files/12269076/Log_2023-08-06_17-18-22.log)

**Kext Download Source**
(https://github.com/OpenIntelWireless/itlwm/releases)

**Comment by diepeterpan** [comment]
I checked the code and the subsys you have '00248086' is in there so the card should be supported, then I also checked the kmutil command on my machine where my AX210 with a different subsys 40208086 model is working but the message "No variant specified, " seems irrelevant - kextstat | grep -i "itlwm"

![image](https://github.com/OpenIntelWireless/itlwm/assets/15066052/31e8123d-8a1b-4533-9bea-4fa9ed670bdc)

This seems more closer to the error looking at the log file, do you have Windows on the same machine, check if the Wifi is working in Windows.

[    2.268482]: itlwm: iwx_set_hw_ready
[    2.273572]: itlwm: : L1 Disabled - LTR Disabled
[    2.476355]: itlwm: : acquiring device failed_

**Comment by diepeterpan** [comment]
All see this - https://community.intel.com/t5/Wireless/Wifi-not-working-in-Linux-using-AX200-on-Beelink-mini-PC/m-p/1498596

My guess is the Wifi is switched off by BIOS, similar to Bluetooth issue I had, try taping the pins which will force the Wifi and Bluetooth to be on, could at least eliminate it as the source of the problem.

![4B488E57-697A-449D-A550-34294EB339A1_1_105_c](https://github.com/OpenIntelWireless/itlwm/assets/15066052/58dd5014-167b-4a4e-9e10-0869160147d1)

**Comment by zxystd** [comment]
Fix your EFI please...
maybe BIOS/PCIE setting/VT-d etc.

**Comment by QianShanWoDu** [comment]
谢谢，各位!

**Comment by Wanchengshan** [comment]
@QianShanWoDu 请问解决了吗，我也是识别不到怎么办不知道

**Comment by QianShanWoDu** [comment]
> @QianShanWoDu 请问解决了吗，我也是识别不到怎么办不知道

没有解决。我用USB WiFi了。
