### ISSUE TITLE
Intel(R) AX201 Wireless not working on Sonoma Dev 5

### ISSUE THREAD

**Issue by bruhmeme1234** [OpenIntelWireless/itlwm#907]
**Have You Read Our Docs**
YES

YES

**Environment**

- Kext Version: Airportitlwm Sonoma Preview 5 (2.3.0)
- WiFi Card Model: Intel(R) AX201 @ 160MHz
- PCI Product ID: 0x8086
- macOS Version: 14.0 Beta (23A5312d)

**Description**
Previously I'm using the Fenvi BCM94360NG for both my macOS and Windows. Just this Monday I used my AX201 again to test my new WiFi 6 Router. On Windows everything works fine. But on macOS, not so much. Bluetooth works but Wireless isn't. Last time I used my AX201 on Sonoma is with the Preview 4 and everything works fine. But now it's not working. It's getting detected in System Information but I can't open it. It's permanently off. I hope this can be fixed.

**Bug Report Archive**
Which one on the link should I follow to get this? I'm really sorry I'm a dummy at this.. 

**Kext Download Source**
(https://github.com/OpenIntelWireless/itlwm/issues/883)

**Comment by zxystd** [comment]
log is needed.
https://openintelwireless.github.io/itlwm/
