### ISSUE TITLE
Itlwm disconnects, reconnects, then has a hard time staying connected.

### ISSUE THREAD

**Issue by BudDeuce** [OpenIntelWireless/itlwm#908]
**Have You Read Our Docs**
Yes

**Are You Reporting A Bug**
Yes

**Environment**

- Kext Version: 2.2.0
- WiFi Card Model: AX201
- PCI Product ID: 34f0
- macOS Version: 13.5.1

**Description**
Hello there, thank you for your hard work on itlwm; I unfortunately have the issue where WiFi frequently disconnects itself from my laptop. AirportItwm does the same thing as well, -vht40 improves the issue, but does not solve it. I mean no additional stress towards the team.

**Bug Report Archive**
[bugreport_53603.zip](https://github.com/OpenIntelWireless/itlwm/files/12441649/bugreport_53603.zip)

**Kext Download Source**
[(https://github.com/OpenIntelWireless/itlwm/releases/download/v2.2.0/itlwm_v2.2.0_stable.kext.zip)](https://github.com/OpenIntelWireless/itlwm/releases/download/v2.2.0/itlwm_v2.2.0_stable.kext.zip)

**Comment by zxystd** [comment]
No disconnection was seen from the log.
