### ISSUE TITLE
Unable to load AirportItlwm on Macbook pro late 2013

### ISSUE THREAD

**Issue by yuri1313** [OpenIntelWireless/itlwm#912]
**Have You Read Our Docs**
Yes

**Are You Reporting A Bug**
No

**Environment**

- Kext Version: 2.2.0
- WiFi Card Model: AX210
- macOS Version: 13.5.1

**Description**
Currently trying to replace my BCM94360cs on my Macbook Pro retina Late 2013 (A1502) with an Intel AX210 (using an adapter board) - Running OpenCore Legacy Patcher 0.6.8.
Enabled SecureBoot in config.plist
itlwm.Kext loads ok by following the regular process (add to EFI Kext's directory and add entry in config.plist)
When using AirportItlwm.Kext it doesn't automatically load (as with itlwm), however, extension loads manually by triggering kextload in terminal.

Appreciate any help with this topic :)

**Kext Download Source**
Github release list (not custom build)

**Comment by zxystd** [comment]
Please follow the OpenCore's guide to collect OC logs.
