### ISSUE TITLE
Cannot connect to 802.11ax 5 GHz WiFi SSID with Intel AX210

### ISSUE THREAD

**Issue by KA2107** [OpenIntelWireless/itlwm#913]
**Have You Read Our Docs**
Yes

**Are You Reporting A Bug**
Yes

**Environment**
Router: 
GL-iNet GL-MT3000 Beryl AX running OpenWrt 23.05-SNAPSHOT (Mediatek filogic, mt76 driver)
(OR)
Dynalink DL-WRX36 running OpenWrt 23.05-SNAPSHOT (Qualcomm ath11k driver)

Client:
2017 MacBook Air, macOS Ventura 13.5.2, OpenCore Legacy Patcher (OCLP) 0.6.8, Intel AX210 M.2 WiFi 6E Card using Adapter

5 GHz SSID: KSH1_5GHz
802.11ax, 20 MHz, Channel 40 or 157 or 165, Country: US
Mixed WPA2-PSK (CCMP / AES) + WPA3-SAE, 
802.11w (Protected Management Frames) set to OPTIONAL

2.4 SSID: KSH1_2.4GHz
802.11ax, 20 MHz, Channel 6, Country: US
Mixed WPA2-PSK (CCMP / AES) + WPA3-SAE, 
802.11w (Protected Management Frames) set to OPTIONAL

- Kext Version: 
AirportItlwm 
(NOT itlwm) 
(git commit d93923051d205f9dc245c69c38e9f0f35bfb5e89)

- WiFi Card Model: 
Intel AX210 M.2 WiFi 6E Card

- PCI Product ID: 
Bluetooth USB Host Controller:
Product ID:	0x0032
Vendor ID:	0x8087  (Intel Corporation)

- macOS Version: 
macOS Ventura 13.5.2

**Description**
I cannot connect to 5 GHz SSID (KSH1_5GHz).
I can connect to 2.4 GHz SSID (KSH1_2.4GHz).

**Bug Report Archive**
[Heliport_Diagnostic_Report.zip](https://github.com/OpenIntelWireless/itlwm/files/12591870/Heliport_Diagnostic_Report.zip)
[Log_2023-09-12_19-19-53.log](https://github.com/OpenIntelWireless/itlwm/files/12591871/Log_2023-09-12_19-19-53.log)

**Kext Download Source**
[AirportItlwm.kext.zip](https://github.com/OpenIntelWireless/itlwm/files/12591885/AirportItlwm.kext.zip)
Custom built locally with 802.11ax enabled as per instructions at https://github.com/OpenIntelWireless/itlwm/issues/897#issuecomment-1625497763

**Comment by zxystd** [comment]
Hi, 11ax mode is not test pass yet, have you tried the released one? v2.3.0-alpha or v2.2.0-stable.

**Comment by zxystd** [comment]
> I tried AirportItlwm_v2.2.0_stable_Ventura.kext.zip and I am able to connect to the 5 GHz SSID in 802.11ac (VHT) mode.
> 
> I built git commit [e66257e](https://github.com/OpenIntelWireless/itlwm/commit/e66257e525b55930f4ea7f0958d6f09d945ab3cf) (latest in master) (with 802.11ax enabled) [AirportItlwm.kext.zip](https://github.com/OpenIntelWireless/itlwm/files/12600818/AirportItlwm.kext.zip) and I am NOT able to connect to 5 GHz SSID.

What about the log?

**Comment by zxystd** [comment]
```
[  544.232117]: itlwm: ieee80211_he_negotiate chan_width=80
```
@KA2107  are you sure you used the latest commit? it may not negotiate to 80MHz channel on the latest commit.

**Comment by zxystd** [comment]
@KA2107 I see, your openwrt configuration is set to HE 20MHz but also announcing phy_cap_info[0] that support 40MHZ_80MHZ_IN_5G capability....

**Comment by zxystd** [comment]
[AirportItlwm.kext.zip](https://github.com/OpenIntelWireless/itlwm/files/12615567/AirportItlwm.kext.zip)
@KA2107 can you try this one?

**Comment by zxystd** [comment]
well, I forgot to enable it.
[AirportItlwm.kext.zip](https://github.com/OpenIntelWireless/itlwm/files/12616176/AirportItlwm.kext.zip)

**Comment by Ophelie22** [comment]
> Software Versions: CoreWLAN: 16.0 (1657) CoreWLANKit: 16.0 (1657) Menu Extra: 17.0 (1728) System Information: 15.0 (1502) IO80211 Family: 12.0 (1200.13.0) Diagnostics: 11.0 (1163) AirPort Utility: 6.3.9 (639.21)
> 
> Interfaces: en0: Card Type: Wi-Fi (0x8086, 0x24) Firmware Version: itlwm: 2.3.0 fw: 68.01d30b0c.0 MAC Address: 68:7a:64:XX:XX:XX Locale: FCC Country Code: US Supported PHY Modes: 802.11 a/b/g/n/ac/ax Supported Channels: 1 (2GHz), 2 (2GHz), 3 (2GHz), 4 (2GHz), 5 (2GHz), 6 (2GHz), 7 (2GHz), 8 (2GHz), 9 (2GHz), 10 (2GHz), 11 (2GHz), 12 (2GHz), 13 (2GHz), 36 (5GHz), 40 (5GHz), 44 (5GHz), 48 (5GHz), 52 (5GHz), 56 (5GHz), 60 (5GHz), 64 (5GHz), 100 (5GHz), 104 (5GHz), 108 (5GHz), 112 (5GHz), 116 (5GHz), 120 (5GHz), 124 (5GHz), 128 (5GHz), 132 (5GHz), 136 (5GHz), 140 (5GHz), 144 (5GHz), 149 (5GHz), 153 (5GHz), 157 (5GHz), 161 (5GHz), 165 (5GHz) Wake On Wireless: Supported AirDrop: Supported Auto Unlock: Supported Status: Connected
> 
> Current Network Information: KSH1_2.4GHz: PHY Mode: 802.11ax Channel: 6 (2GHz, 40MHz) Country Code: US Network Type: Infrastructure Security: WPA2/WPA3 Personal Signal / Noise: -33 dBm / 58 dBm Transmit Rate: 36 MCS Index: 11
> 
> KSH1_5GHz: PHY Mode: 802.11 Channel: 157 (5GHz, 20MHz) Network Type: Infrastructure Security: WPA2/WPA3 Personal Signal / Noise: -47 dBm / 58 dBm

**Comment by Ophelie22** [comment]
I have the same configuration, ans since i pu th the ventura i can connect to internet , with wifi et bluetothh is onluuy work with ethernet . What i have to do? Do you have a tuto that show it on youtube or something like this?

**Comment by almajthob** [comment]
"Hi there,
I have a question that's a bit unrelated, but I'm hoping you can help. I recently installed macOS Ventura 13.4 on my Surface Pro 7, and I'm experiencing issues connecting it to my iPhone 12 5G hotspot.
I just wanted to know if it's possible to update macOS Ventura to version 13.5.1 after installing it on the Surface Pro 7.
Thanks in advance for your assistance!"

**Comment by zxystd** [comment]
@KA2107 
[AirportItlwm.kext.zip](https://github.com/OpenIntelWireless/itlwm/files/12646001/AirportItlwm.kext.zip)

**Comment by almajthob** [comment]
the new AirportItlwm.kext work for me :)

**Comment by almajthob** [comment]
i think its better than the old one
work for me 80%

**Comment by zxystd** [comment]
@KA2107 Thank you, what about other modes?

**Comment by almajthob** [comment]
I still have a problem connecting to the Wi-Fi hotspot on my iPhone 12. 
Is there anything I can do to show you where the error is?

**Comment by zxystd** [comment]
@KA2107 Thank you very much for helping with the testing!

**Comment by zxystd** [comment]
will be there after Chinese National holiday.

**Comment by zxystd** [comment]
no issue on the driver from the log, please check your password. and try to clean and reconnect by Heliport



---Original---
From: "Keshav ***@***.***&gt;
Date: Tue, Oct 3, 2023 10:09 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [OpenIntelWireless/itlwm] Cannot connect to 802.11ax 5 GHz WiFiSSID with Intel AX210 (Issue #913)




 
I upgraded to Sonoma and therefore shifted to itlwm.kext (with 802.11ax enabled, locally built from latest git). I tried connecting using Heliport. I see the macbook show up as connected in my router connected devices page, but there's no IP address assigned in macOS Sonoma. Not sure if this is an issue in itlwm, Heliport or macOS Sonoma itself.
 
Heliport Diagnostics Report
 bugreport_34780.zip
 

 

 
Any idea how to get itlwm

**Comment by zxystd** [comment]
> Just giving my updates below: I tried removing Heliport using AppCleaner (in order to delete the preferences files as well) and after a reboot, re-installing Heliport. Still did not work.
> 

Passwords are stored in KeyChain.

> I also tried directly adding the SSID and password in the Info.plist inside the itlwm.kext. The behavior is similar to trying to connect using Heliport.
> 

If you try this way, you can close Heliport, it should work after reboot.

> In both cases, the device is associated with router, but the en0 interface does not have IP address (neither IPv4 nor IPv6) assigned, and the en0 status shows as "inactive". Not sure what that means.
> 

inactive means the network interface is not 'UP', which also means the itlwm.kext not really connected to the router.

> I tried Airportitlwm kext attached at [#883 (comment)](https://github.com/OpenIntelWireless/itlwm/issues/883#issuecomment-1670749680) and my Macbook got stuck at boot. It did not boot to login screen. Not sure if default OCLP config (for Broadcom card) is messing with Airportitlwm kext.
> 

Airportitlwm uses the native OS dependencies like the native wifi driver, different to the OCLP patches(reactive old drivers/libraries from old systems).

**Comment by zxystd** [comment]
@KA2107 Are you sure you don't have patched the Sonoma with OCLP?

**Comment by zxystd** [comment]
@KA2107 AirportItlwm is working, but the OCLP replaced userspace frameworks and binaries(token from Ventura), you should not only disabled the kexts loading.

**Comment by lowprofileusername** [comment]
> With the release of OCLP 1.0.0, I upgraded to macOS Sonoma in my 2017 Macbook Air.
> 
> Since the AirportItlwm build for Sonoma is still in development, is not yet (somewhat) stable and lacks 802.11ax, I shifted to itlwm.kext (with 802.11ax enabled, locally built from latest git).
> 
> I tried connecting using Heliport. I see the macbook show up as connected in my router connected devices page, but there's no IP address assigned in macOS Sonoma.
> 
> Heliport Diagnostics Report [bugreport_34780.zip](https://github.com/OpenIntelWireless/itlwm/files/12787799/bugreport_34780.zip)
> 
> Heliport Screenshot ![Heliport](https://github.com/OpenIntelWireless/itlwm/assets/223929/666c655a-2dc0-4f00-99c9-d8a3e2aecada)
> 
> Notice in the above screenshot
> 
> IP Address is "Unknown" and Router is 127.0.0.1 (localhost).
> 
> macOS Network Settings Window ![macOS_Network_Settings](https://github.com/OpenIntelWireless/itlwm/assets/223929/87d95ce5-1bf5-4bf0-a950-9b3c4d4f4c02)
> 
> Looks like either Heliport is not attached to the "Ethernet" network device in macOS settings. (OR) DHCP is not working.
> 
> Not sure if this is an issue in itlwm, Heliport or macOS Sonoma itself.

so to bump this thread, I did tried to modify the kext to enable ax as you did .and my tx rates shows 140mbps as in your screenshot. did you solve this problem?

**Comment by KA2107** [comment]
@lowprofileusername I am no longer using any Apple Mac device.
