### ISSUE TITLE
WPA3 Enterprise does not work - AX210 - Sonoma

### ISSUE THREAD

**Issue by madman9999** [OpenIntelWireless/itlwm#914]
**Have You Read Our Docs**
Yes

**Are You Reporting A Bug**
Yes

**Environment**

- Kext Version: 2.3.0 Preview 5 Alpha
- WiFi Card Model: AX210
- PCI Product ID: 0x8086 - 0x2725
- macOS Version: 14.0

**Description**
I can't connect to my AP using WPA3 Enterprise. It works with WPA2 PSK.

**Bug Report Archive**
Using AirportItlwm.

**Kext Download Source**
Directly from github.

**Comment by madman9999** [comment]
Tried also WPA2 TLS-EAP, also no luck. It worked both with Broadcom before. So I am not sure, if this is already implemented in the Intel drivers.

**Comment by zxystd** [comment]
Please read the document.
