### ISSUE TITLE
Sonoma 14.0 VMware Bridging

### ISSUE THREAD

**Issue by hipco** [OpenIntelWireless/itlwm#916]
VMware Network Bridging doesn't work anymore on Sonoma 14.0 with AirportItlwm.kext (Preview 05). VMware Network Sharing works.

Off topic but a big improvement: Airplay does work again !!!!

**Comment by Parachute0801** [comment]
Same problem here!

**Comment by Pidbid** [comment]
Same problem here!

**Comment by zxystd** [comment]
Works with itlwm.kext or LAN driver?

**Comment by hipco** [comment]
With the integrated Ethernet NIC everything works as expected.

**Comment by Parachute0801** [comment]
Yes, with the LAN driver everything works fine, so the problem must be with the kext.

thx in advance!! 😄

**Comment by zinohome** [comment]
Same problem here! VMware Fusion 13.0.2. VMware Network Bridging doesn't work on Sonoma 14.0

**Comment by ito** [comment]
It’s a general problem, nog itlwm specific.

**Comment by zinohome** [comment]
But In Ventura， the same card ， vmware bridge is working fine.

**Comment by zxystd** [comment]
Anyone had tried USB WIFI dongle? is it the same result?

**Comment by Parachute0801** [comment]
> Anyone had tried USB WIFI dongle? is it the same result?

I am trying to test it with a tplink usb wifi but vmware does not detect it in the configuration so i cannot test it.

**Comment by zxystd** [comment]
@Parachute0801 I suspect it's a the compatible problem on Sonoma with the VMWare, not sure.

**Comment by Parachute0801** [comment]
> @Parachute0801 I suspect it's a the compatible problem on Sonoma with the VMWare, not sure.

Ok, in the next few days I will try to put a virtual machine in bridge mode in parallels or vbox. 
Thank you!

**Comment by Parachute0801** [comment]
I just tried it with parallels 18 and it happens the same as with VMware.

**Comment by zinohome** [comment]
I tested in virtualbox, the same problem, bridge via wifi can not work.

**Comment by inforj** [comment]
same problem in parallels 19.1.10, bridge network not work.

**Comment by yflwz** [comment]
The main reason is that the WIFI wireless network card cannot be found in the new bridge in the mac system.
![截屏2024-01-17 16 36 02](https://github.com/OpenIntelWireless/itlwm/assets/19662528/d5bc2783-59f5-4905-a840-4c812b1a2542)

**Comment by FlyingThaCat** [comment]
Same problem here

**Comment by Huang-JunDong** [comment]
pd19 have same problem here.

**Comment by FlyingThaCat** [comment]
Are this resolved or ?

**Comment by hipco** [comment]
Nope. Let's wait for macOS Sequoia.
