### ISSUE TITLE
系统是10.13.6High Sierra，我下载的是AirportItlwm_v2.2.0_stable_HighSierra.kext.zip，在opencore里导入后，wifi还是没效果，需要注意啥？Sonoma我用Issues里提供的那个，wifi是可以正常工作的

### ISSUE THREAD

**Issue by df257** [OpenIntelWireless/itlwm#922]
不用Sonoma是因为：浏览器打开个网页，稍微动一下鼠标，网页就成空白看不到内容了，不知道是不是显卡导致的。
所以，我想试试High Sierra装N卡的驱动后卡不卡，显卡是1060移动端的。
我下载了这个网址的驱动https://www.nvidia.com/download/driverResults.aspx/149652/
![image](https://github.com/OpenIntelWireless/itlwm/assets/7835444/06100538-3fd3-4c6d-88dd-5a246836e1b0)
但是装不上去，提示我系统需要10.13.6版本，但是我的系统安装的是10.13.6

**Comment by zxystd** [comment]
10.15以下的版本需要强行加载IO80211Family，具体操作自行百度。
