### ISSUE TITLE
Wi-Fi appears disabled

### ISSUE THREAD

**Issue by kaelthasmanu** [OpenIntelWireless/itlwm#928]
**Have You Read Our Docs**

Yes

**Are You Reporting A Bug**

I don't know if it's a bug

**Environment**

- Kext Version: v2.2.0Stable
- WiFi Card Model: RTL8821AE 
- PCI Product ID: I dont know
- macOS Version: Ventura

**Description**

Wi-Fi appears disabled, I cannot activate it

**Bug Report Archive**

**Kext Download Source**

https://github.com/OpenIntelWireless/itlwm/releases/tag/v2.2.0

this is my file log 
[Log_2023-10-26_Oct-22-12.log](https://github.com/OpenIntelWireless/itlwm/files/13182864/Log_2023-10-26_Oct-22-12.log)

**Comment by zxystd** [comment]
Are you sure it is your log?

**Comment by kaelthasmanu** [comment]
oh sorry, apparently I was wrong is this :

[Log_2023-10-26_22-52-49.log](https://github.com/OpenIntelWireless/itlwm/files/13184536/Log_2023-10-26_22-52-49.log)

**Comment by kaelthasmanu** [comment]
@KA2107 Yes it is true and from what I have read I think that Hackintosh does not have support so let me close this issue, thank you very much
