### ISSUE TITLE
AX211wifi和蓝牙可以切换开关但无法使用

### ISSUE THREAD

**Issue by Susuper2019** [OpenIntelWireless/itlwm#939]
wifi和蓝牙可以开启和关闭。
wifi连接后，提示无网络，停一小会会断开。
蓝牙可以切换开关，也可以被手机扫到，其他设备连接会提示没打开。
目前是使用的此EFI https://github.com/CloverLeafBG/Gigabyte-B660M-AORUS-ELITE-AX-OC-Hackintosh/releases，主板与其是一致的，网卡都是AX211，
当前状态：还没定制USB，系统升级到macos14

**Comment by Susuper2019** [comment]
wifi问题，发现选择2.4g的wifi就可以了，5g的不行

**Comment by Leonw2229** [comment]
> wifi问题，发现选择2.4g的wifi就可以了，5g的不行

如果是链接所有的5G Wi-Fi都有问题的话，试试动动外置天线，我的ax200是天线坏了，转动到特定的位置就只能链接2.4Ghz的Wi-Fi，转到某一部分位置就全部正常
