### ISSUE TITLE
Can't build Airportitlwm 2.3.0 Beta:

### ISSUE THREAD

**Issue by Matgen84** [OpenIntelWireless/itlwm#943]
**Have You Read Our Docs**

**Are You Reporting A Bug**

**Environment**

- Kext Version: Airportitlwm (all)
- WiFi Card Model: Intel 9560 ac CNVi
- PCI Product ID: 8086:a370:8086:0034
- macOS Version:  12.7.2
- XCode : 14.3

**Description**
I can't build Airportitlwm 2.3.0 Beta: PrivateSPI.pch don't found Include/libkern/libkern.h

**Bug Report Archive**

**Kext Download Source**
OpenIntelWireless GitHub repo

**Comment by zxystd** [comment]
MacKernelSDK is needed. 
https://github.com/OpenIntelWireless/itlwm/blob/master/.github/workflows/main.yml
workflow file for your reference.
