### ISSUE TITLE
Airportitlwm ruins bluetooth

### ISSUE THREAD

**Issue by thebiscuitaep** [OpenIntelWireless/itlwm#946]
**Have You Read Our Docs**
Yes

**Are You Reporting A Bug**
Yes

**Environment**

- Kext Version: I tried 2.2.0-stable and 2.3.0-alpha
- WiFi Card Model: Intel ax201
- PCI Product ID: I dont know
- macOS Version: Ventura

**Description**
I researched and what I found: the 2.2.0-alpha is working with INTEL BT FIX.kext but other versions doesn't working with bluetooth also if I add intelbtfix.kext to my config on boot verbose it shows a error at least 30 times: Itlwm: taskq task_add iwx_newstate_task add to queue it boots but bluetooth still doesn't working I tried using itlwm+heliport+intelbtfix.kext but it still shows same error and bluetooth isn't working.

I tried using this kexts: 

AirportBrcmFixup.kext

when I disable kexts below it doesnt show error and boots faster but bluetooth isn't working
IntelBluetoothFirmware.kext
IntelBluetoothInjector.kext
IntelBTPatcher.kext
BrcmPatchRAM3.kext

**Bug Report Archive**

**Kext Download Source**

Github

**Comment by zxystd** [comment]
https://openintelwireless.pages.dev/IntelBluetoothFirmware/FAQ#what-does-this-kext-do

> IntelBluetoothInjector
> Do NOT use this Kext on macOS Monterey and newer
> 
> Codeless Kext that enables the on-off switch on older versions of macOS.
