### ISSUE TITLE
macOS sonoma hidden network

### ISSUE THREAD

**Issue by Maged-ahmed41** [OpenIntelWireless/itlwm#948]
Please help me, I cannot connect to hidden networks, whether 2.4 or 5ghz
This is the version I use and the one before it is v2.3.0-alpha
sonoma 14.0

**Comment by nsby494** [comment]
itlwm.kext+heliport can connect to hidden networks

**Comment by zxystd** [comment]
Hidden network is not supported in AirportItlwm driver, you can use itlwm.kext with Heliport client.
