### ISSUE TITLE
sonoma，Sometimes turn on the computer or waking up from sleep,wifi is closed

### ISSUE THREAD

**Issue by vllcher** [OpenIntelWireless/itlwm#950]
My macos's version is sonoma 14.2.1,the kext version is [v2.3.0-alpha](https://github.com/OpenIntelWireless/itlwm/releases/tag/v2.3.0-alpha),Sometimes turn on the computer and enter the system,wifi is not open,You need to click on Turn on Wi-Fi and then click on the wifi icon again, wait for known networks to come up for your network and then click on it,Then you can connect,Of course, sometimes this is also the case after waking up from sleep and entering the system.Also, I had a situation where I entered the system and the wifi icon showed that it was connected, but when I opened a browser to access it, it said that it was not connected to the network, and then a few minutes later, the system crashed and rebooted.

**Comment by zxystd** [comment]
Runtime log/Panic log are needed.
