### ISSUE TITLE
Airportitlwm Broken on macOS 14.4 beta

### ISSUE THREAD

**Issue by Lorys89** [OpenIntelWireless/itlwm#953]
It broke like in the first betas

macos 14.4 beta
intel ax210ngw
kernel macos 23.4.0

**Comment by Lorys89** [comment]
API interfaces modified?

**Comment by zxystd** [comment]
Close until complete information is added according to the issue template.

**Comment by Lorys89** [comment]
> Close until complete information is added according to the issue template.
[Kernel-2024-01-30-094249.panic.zip](https://github.com/OpenIntelWireless/itlwm/files/14095036/Kernel-2024-01-30-094249.panic.zip)

**Comment by zxystd** [comment]
@Lorys89 Please add `keep_syms=1` to `boot-args` and trigger again, the panic info lack of symbols.

**Comment by Lorys89** [comment]
> @Lorys89 Please add `keep_syms=1` to `boot-args` and trigger again, the panic info lack of symbols.
[Kernel-2024-01-30-100854.panic.zip](https://github.com/OpenIntelWireless/itlwm/files/14095377/Kernel-2024-01-30-100854.panic.zip)

**Comment by zxystd** [comment]
sorry I misspell it, it is `keepsyms=1`.

**Comment by Lorys89** [comment]
> sorry I misspell it, it is `keepsyms=1`.

[Kernel-2024-01-30-102933.panic.zip](https://github.com/OpenIntelWireless/itlwm/files/14095639/Kernel-2024-01-30-102933.panic.zip)

**Comment by Lorys89** [comment]
[Kext From KDK 14.4 beta.zip](https://github.com/OpenIntelWireless/itlwm/files/14095984/Kext.From.KDK.14.4.beta.zip)

**Comment by zxystd** [comment]
@Lorys89 Got it, will resolve tomorrow. Sonoma is definitely shit.

**Comment by Lorys89** [comment]
> @Lorys89 Got it, will resolve tomorrow. Sonoma is definitely shit.

Ok, Thank you for your commitment, sonoma is really shit, I sent you kext taken from kdk if you need anything else let me know.

**Comment by Lorys89** [comment]
@zxystd you have news?

**Comment by zxystd** [comment]
@Lorys89 I had a fever yesterday. will see the kexts difference later.

**Comment by zxystd** [comment]
[Sonoma_14.4Beta.zip](https://github.com/OpenIntelWireless/itlwm/files/14119732/Sonoma_14.4Beta.zip)

**Comment by Lorys89** [comment]
> [Sonoma_14.4Beta.zip](https://github.com/OpenIntelWireless/itlwm/files/14119732/Sonoma_14.4Beta.zip)

Thanks, the kext works on 14.4 😉

**Comment by zxystd** [comment]
@Lorys89 
- ax210 is gen3 device which controls rate scaling inside the firmware, different with gen1 devices(the issue #934 author has), so I think you are facing not 'the same' issue.
- From Sonoma, Apple drops `IO80211FamilyLegacy`, I build AirportItlwmV2 on the top of `IO80211Family`, but using some hacks, you can simply interpret it as me implementing a set of IO80211FamilyLegacy myself. This implementation may have side effects such as the iService not working etc. Since `IO80211Family` uses skywalk API instead of original Ethernet API(Also we can foresee that the Ethernet API will also be dropped in macOS 15), without these hacks we should follow the Apple's API and rewrite the whole driver, that's what I would never do.

**Comment by alighafourian** [comment]
@zxystd hi and tnx for 14,4 fix 
i have one probelm Airplay work lagy and i repoert this problem before:
https://github.com/OpenIntelWireless/itlwm/issues/923#issuecomment-1770584322

 you say disable MIMO and its make this problem can you make boot-arg for force enable MIMO?

**Comment by 5T33Z0** [comment]
FYI: this updated 14.4 kext is not backward compatible. It causes a KP in 14.3!

**Comment by zxystd** [comment]
Apple drops the compatible, not me. that is why I call them shit.

**Comment by 5T33Z0** [comment]
Ah, ok. I feel the same way. 14.4 beta 1 killed my whole system. I had to reinstall 14.3 on a new volume from USB flash drive, move files over and then kill the old volume.

**Comment by alighafourian** [comment]
https://github.com/OpenIntelWireless/itlwm/actions/runs/7782670974 
last build dosnt work with my 7265 wifi or its release for 14.3 not for 14.4b1?

**Comment by CloverLeafBG** [comment]
> https://github.com/OpenIntelWireless/itlwm/actions/runs/7782670974 last build dosnt work with my 7265 wifi or its release for 14.3 not for 14.4b1?

Correct. Last build is released for 14.3. The beta version issued above will not work on anything but 14.4

**Comment by DmitriyyyyS** [comment]
@zxystd Hi, could you please update the repository with the latest Airportitlwm changes you made for macOS 14.4 (beta) or post the source code here, thanks!

**Comment by zxystd** [comment]
> @zxystd Hi, could you please update the repository with the latest Airportitlwm changes you made for macOS 14.4 (beta) or post the source code here, thanks!

14.4 is still in beta, we don't know if it will change something on later beta versions, when I upload the changes, 14.3 and below version will never support.

**Comment by ankit0183** [comment]
can you please give me kext for 14.2.1  wifi i tried but not working anything

**Comment by alighafourian** [comment]
@zxystd  14.4 out

**Comment by zxystd** [comment]
Already merge ef2e0762d1548b07bcab95570ae44e9bb6470933.

**Comment by Beefcat** [comment]
With iMac20,1 (Gigabyte Z490 Aorus Master) I have AXE300RGB pci card. My system have 2 networks. Onboard works fine (en1). 

I want to have pci work (wifi 6e) but it is not allowing me to toggle en2 on. Do I need to have Securebootmodel enabled ? My device-id is
![en2 wifi 6e](https://github.com/OpenIntelWireless/itlwm/assets/528671/78d809c2-6d56-40bc-9c54-5ec1a15561c0)

Tx.
