### ISSUE TITLE
location no work in 14.4 Beta (23E5211a) 

### ISSUE THREAD

**Issue by alighafourian** [OpenIntelWireless/itlwm#959]
in 14.4 Beta (23E5211a) loacation not work i try tern off and on it but nothing change wont work :

**Have You Read Our Docs**
Yes 

**Are You Reporting A Bug**
Yes

Loges
without DebugEnhancer.kext
[Log_2024-02-29_19-48-09.log](https://github.com/OpenIntelWireless/itlwm/files/14450729/Log_2024-02-29_19-48-09.log)

**Environment**

- Kext Version: https://github.com/OpenIntelWireless/itlwm/issues/953#issuecomment-1920413379
- WiFi Card Model: 7265n
- PCI Product ID: 0x8086, 0x5002
- macOS Version: 14.4 Beta (23E5211a)

**Description**
![Screenshot 2024-02-29 at 19 47 03](https://github.com/OpenIntelWireless/itlwm/assets/51196916/38b9bc75-4c7a-4c27-917e-16355a858010)

![Screenshot 2024-02-29 at 19 47 26](https://github.com/OpenIntelWireless/itlwm/assets/51196916/2d63761b-f466-428f-ba9b-ffad6647a15e)

**Comment by alighafourian** [comment]
with DebugEnhancer.kext

[Log_2024-02-29_19-52-09.log](https://github.com/OpenIntelWireless/itlwm/files/14450791/Log_2024-02-29_19-52-09.log)

**Comment by zxystd** [comment]
Location service is confirmed working.
