### ISSUE TITLE
Poor speed -  Sonoma | Intel 8260 WiFI

### ISSUE THREAD

**Issue by ds2k5** [OpenIntelWireless/itlwm#960]
**Have You Read Our Docs**
No

**Are You Reporting A Bug**
No

**Environment**

- Kext Version:  v2.3.0-DEBUG-alpha-618eb94.zip 
- WiFi Card Model: Intel 8260 
- PCI Product ID:  
- Card Type: 0x8086, 0x1010
- macOS Version: 14.3.1

Using 5GHz WiFI

**Description**
If do Speedtest the Download is arround 4 MB/s
Upload is 42 MB/s

**Bug Report Archive**
Heliport did not work

**Kext Download Source**

https://github.com/OpenIntelWireless/itlwm/releases/download/v2.3.0-alpha/AirportItlwm-Sonoma-v2.3.0-DEBUG-alpha-618eb94.zip

**Comment by zxystd** [comment]
speedtest is not an accurate measurement method, use iperf3 or other tools.
