### ISSUE TITLE
[Feature Request] add MIMO enabled Boot arg for increase performance for airplay in old intel wifi 

### ISSUE THREAD

**Issue by alighafourian** [OpenIntelWireless/itlwm#964]
in mac os sonoma 14 some apple Feature like airplay work good but in old wifi like 7265N its not work as well i think if u make boot arg for force enable MIMO can make aiplay work well as preview05 kext u make for sonoma 
**Have You Read Our Docs**
Yes

**Are You Reporting A Bug**
No

**Environment**

- Kext Version: 2.3
- WiFi Card Model: 7265N
- PCI Product ID: 0x8086, 0x5002
- macOS Version: 14.4

**Description**

**Comment by zxystd** [comment]
I think you are talking #923 about airplay laggy after iwm upgrade to rs version? please try this verison https://github.com/OpenIntelWireless/itlwm/issues/934#issuecomment-2001310377 to see if it would help.

**Comment by alighafourian** [comment]
yes work perfect 
can u send sorcecode?

**Comment by zxystd** [comment]
> yes work perfect can u send sorcecode?

Not yet, will commit after test pass.

**Comment by alighafourian** [comment]
> > yes work perfect can u send sorcecode?
> 
> Not yet, will commit after test pass.

Ok tnx for support

**Comment by alighafourian** [comment]
> > yes work perfect can u send sorcecode?
> 
> Not yet, will commit after test pass.

I close this
