### ISSUE TITLE
Intel Wireless 7260 " iMessage & FaceTime " Sonoma 14.4 ?

### ISSUE THREAD

**Issue by Odroid13** [OpenIntelWireless/itlwm#966]
First of all I wanted to thank you for the work you do ^^

Thanks to your kext, I have AirportItlwm.kext Wifi & Bluetooth working. perfectly, on Mac OS Monterey, I can use iMessage & FaceTime, everything is perfect.

I installed Sonoma 14.4, I took the Kext for Sonoma, everything works perfectly but I can't use iMessage & FaceTime.
iCloud works

When I use the Hackintool software, I noticed that the Intel Wirless 7260 Wifi card is checked with Mac OS Sonoma 14.4 and that on Mac OS Monterey, the Wirless 7260 Wifi card is unchecked.

![Sonoma](https://github.com/OpenIntelWireless/itlwm/assets/97029183/b12e66e1-c19f-4c38-9425-496d0f918af5)

I tell myself that maybe this is the problem that is preventing me from having the iMessage & FaceTime services?

When I use the RJ45 cable, the iMessage & FaceTime services work perfectly.

I want to do a test but I don't know how to uncheck the WiFi card like on the Monterey screeshot.

![Monterey](https://github.com/OpenIntelWireless/itlwm/assets/97029183/da77d70f-775d-447d-83c0-26108c93a1ce)

Thanks

**Comment by Odroid13** [comment]
I just tried itlwm.kext with Heliport and everything works ^^

In Hackintool, the Wifi card is unchecked, I think that to solve the problem with AirportItlwm.kext it must not be checked in Hackintool.

For the moment I use itlwm.kext with Heliport.
Thanks

**Comment by anonymous-writer** [comment]
built-in can be changed with this parameter. Right device property you will get from the Hackintool.

![image](https://github.com/OpenIntelWireless/itlwm/assets/35840715/39dae9d3-b8cb-44f4-9dd5-b9396ac99df3)

**Comment by zxystd** [comment]
It should be build-in, the hackintool reads the IOBuildIn property to desire whether it should be checked.

**Comment by kamikaze07** [comment]
there is any fix for this?, iServices doesn´t work on Sonoma 14.4.1 with AirportItlwm.kext 2.3.0 kext

**Comment by Rainringgoaway** [comment]
> I just tried itlwm.kext with Heliport and everything works ^^
> 
> In Hackintool, the Wifi card is unchecked, I think that to solve the problem with AirportItlwm.kext it must not be checked in Hackintool.
> 
> For the moment I use itlwm.kext with Heliport. Thanks

heliport can't read location.
