### ISSUE TITLE
AirportItlwm-2.3.0-Sonoma 14.4 not enabled

### ISSUE THREAD

**Issue by rhkjyn** [OpenIntelWireless/itlwm#967]
Have You Read Our Docs
Yes

Are You Reporting A Bug
Yes

Environment

Kext Version: AirportItlwm 2.3.0-alpha
WiFi Card Model: Intel Wifi 6 AX200
PCI Product ID: 8086
macOS Version: Sonoma 14.4

Description: 
The driver has no effect under sonoma14.4, the wifi switch cannot be turned on normally, and HeliPort prompts that itlwm is not enabled.

**Comment by zxystd** [comment]
This model/system version is confirmed working.
