### ISSUE TITLE
Question regarding updating to newer firmware

### ISSUE THREAD

**Issue by anonymous-writer** [OpenIntelWireless/itlwm#972]
**Have You Read Our Docs**
Yes

**Are You Reporting A Bug**
No

**Environment**

- Kext Version: v2.3.0-alpha
- WiFi Card Model: AX-210
- PCI Product ID: -
- macOS Version: Sonoma

**Description**
I'm trying to install the latest firmware for my card with itlwm. The new kext load the firmware as it shoud be.
But I can't get to start scanning the network. The scan is simply canceled.

Do I have to do additional things to get it work with new latest firmware ? 
I tested the firmware to see if it worked under Ubuntu and it works. Maybe someone knows what is to do and want to help.

I did the update like it was done here.
https://github.com/OpenIntelWireless/itlwm/commit/54542db89d85890715418413a321c96a336c4eab

[Firmware_AX210.zip](https://github.com/OpenIntelWireless/itlwm/files/14851032/Firmware_AX210.zip)

![Bildschirmfoto 2024-04-03 um 17 56 59](https://github.com/OpenIntelWireless/itlwm/assets/35840715/b07dd295-2aeb-468e-a3cc-57f0defef86b)

[itlwm-master_including_new_firmware.zip](https://github.com/OpenIntelWireless/itlwm/files/14855177/itlwm-master_including_new_firmware.zip)

[Sonoma_14_4-AirportItlwm.kext.zip](https://github.com/OpenIntelWireless/itlwm/files/14855004/Sonoma_14_4-AirportItlwm.kext.zip)

Greetings Michael

**Comment by zxystd** [comment]
Different with bluetooth firmwares, every wifi firmware has its features and APIs, we should do compat works on driver code, not simply loading the firmware into hardware. Why do you want to upgrade firmware? I had done some upgrade works for preparing support of wifi7 devices, but not really done and well testing so it is now only in my private repository.

**Comment by anonymous-writer** [comment]
Thank you @zxystd  for your work.
I thought I could try this to see if anything improved in terms of compatibility. But with your answer I understood why it's not so easy.

I was playing around with Wireguard VPN yesterday and suddenly imassenger worked. Unfortunately I couldn't understand why. Activating VPN again didn't help.

Thanks again for your work.

**Comment by zxystd** [comment]
@anonymous-writer If you have another network interface to connect to the internet, then the imessage will work.

**Comment by diepeterpan** [comment]
> @anonymous-writer If you have another network interface to connect to the internet, then the imessage will work.

Is there perhaps a loop-back / "ethernet proxy over wifi" that we can install to fake this?

**Comment by anonymous-writer** [comment]
Yesterday I found a solution that makes imessage and facetime work again.
However, you need a second computer with an SSH server. A Rassbery, for example.

I'll still test and then write more.
