### ISSUE TITLE
Sonoma 14.5 panic (possible overflow) when connected to certain wifi networks

### ISSUE THREAD

**Issue by johnpapad24** [OpenIntelWireless/itlwm#975]
**Have You Read Our Docs**
YES

**Are You Reporting A Bug**
YES
**Environment**

- Kext Version: Airportitlwm v2.3.0-alpha (sonoma 14.4+) (4ac4c79)
- WiFi Card Model: Intel® Dual Band Wireless-AC 8260
- PCI Product ID: 
- macOS Version: sonoma 14.5 beta 1 to beta 4 (23F5074a) and possibly beyond

**Description**
panics (related to possible overflows) experienced connected and downloading to certain wifi networks on airport itlwm and sonoma 14.5 beta using intel wireless ac 8260

The kernel panic is available below:

panic(cpu 3 caller 0xffffff8002d760a1): mbuf_watchdog: 1 waiters stuck for 25 secs
22867/22897 mbufs in use:
	22573 mbufs allocated to data
	215 mbufs allocated to packet headers
	79 mbufs allocated to socket names and addresses
	30 mbufs allocated to caches
659/682 mbuf 2KB clusters in use
13496/13503 mbuf 4KB clusters in use
0/0 mbuf 16KB clusters in use
61116 KB allocated to network (approx. 99% in use)
0 KB returned to the system
worker thread runs: 391, expansions: 209, cl 0/0, bigcl 390/69528, 16k 0/0
worker thread last run time: 298 (25 seconds ago)

top proc mbuf space 104192 bytes by wifip2pd:330

top ifcq_len 5 packets by en0

mbuf leak detection table:
	total captured: 1904 (one per 500)
	total allocs outstanding: 78
	new hash recorded: 1608 allocs, 585 traces
	hash collisions: 60 allocs, 286 traces
	overwrites: 1084 allocs, 0 traces
	lock conflicts: 0

top 5 outstanding traces:
[1] 25 outstanding alloc(s), 953 hit(s), 272 collision(s)
[2] 22 outstanding alloc(s), 22 hit(s), 0 collision(s)
[3] 9 outstanding alloc(s), 337 hit(s), 0 collision(s)
[4] 5 outstanding alloc(s), 21 hit(s), 0 collision(s)
[5] 4 outstanding alloc(s), 34 hit(s), 0 collision(s)

    trace [1]           trace [2]           trace [3]       	trace [4]           trace [5]      
    ------------------  ------------------  ------------------      ------------------  ------------------ 
 1: 0xffffff800097532a  0xffffff800097532a  0xffffff800097532a  0xffffff800097532a  0xffffff800097532a  
 2: 0xffffff800094dc81  0xffffff800094dd28  0xffffff800094dc81  0xffffff800094dd28  0xffffff800094dd28  
 3: 0xffffff800097b490  0xffffff800097415e  0xffffff8000978eec  0xffffff8000978eec  0xffffff800097b490  
 4: 0xffffff8000946461  0xffffff800094dbf5  0xffffff800097bec7  0xffffff800097bec7  0xffffff8000946461  
 5: 0xffffff80025108cb  0xffffff800097b490  0xffffff8000945763  0xffffff8000945763  0xffffff80025108cb  
 6: 0x0  0xffffff8000946461  0x0  0x0  0x0  
 7: 0x0  0xffffff80025108cb  0x0  0x0  0x0  
 8: 0x0  0x0  0x0  0x0  0x0  
 9: 0x0  0x0  0xffffff8000b108aa  0xffffff8000b108aa  0x0  
10: 0xffffff8000b108aa  0x0  0xffffff8000b0f0ce  0xffffff8000b0f0ce  0xffffff8000b108aa  
11: 0xffffff8000b0f0ce  0x0  0xffffff8000b0e6f6  0xffffff8000b0e6f6  0xffffff8000b0f0ce  
12: 0xffffff8000b0e6f6  0xffffff8000b108aa                                          0xffffff8000b0e6f6  
13:                     0xffffff8000b0f0ce                                                              
14:                     0xffffff8000b0e6f6                                                              
15:                                                                                                     
16:                                                                                                     

Panicked task 0xffffff99af8f73d8: 4 threads: pid 1: launchd
Backtrace (CPU 3), panicked thread: 0xffffff867e87eb30, Frame : Return Address
0xffffffc477e836d0 : 0xffffff8002826571 
0xffffffc477e83720 : 0xffffff800298bc00 
0xffffffc477e83760 : 0xffffff800297b1bc 
0xffffffc477e837e0 : 0xffffff80027bf971 
0xffffffc477e83800 : 0xffffff800282685d 
0xffffffc477e838f0 : 0xffffff8002825f03 
0xffffffc477e83950 : 0xffffff8002fdb38b 
0xffffffc477e83a40 : 0xffffff8002d760a1 
0xffffffc477e83a60 : 0xffffff8002d74818 
0xffffffc477e83ad0 : 0xffffff8002d4dbf5 
0xffffffc477e83b40 : 0xffffff8002d7415e 
0xffffffc477e83be0 : 0xffffff8002d4dbf5 
0xffffffc477e83c50 : 0xffffff8002d7a446 
0xffffffc477e83cc0 : 0xffffff8002d86fed 
0xffffffc477e83de0 : 0xffffff8002d983ee 
0xffffffc477e83ed0 : 0xffffff8002d980a1 
0xffffffc477e83f40 : 0xffffff8002e55060 
0xffffffc477e83fa0 : 0xffffff80027bfdb6 

Process name corresponding to current thread (0xffffff867e87eb30): launchd

Mac OS version:
23F5074a

Kernel version:
Darwin Kernel Version 23.5.0: Wed Apr 24 21:23:04 PDT 2024; root:xnu-10063.121.3~3/RELEASE_X86_64
Kernel UUID: AD00268F-F1D6-3116-9F95-EE3301906DE9
roots installed: 0
KernelCache slide: 0x0000000002400000
KernelCache base:  0xffffff8002600000
Kernel slide:      0x00000000024e4000
Kernel text base:  0xffffff80026e4000
__HIB  text base: 0xffffff8002500000
System model name: MacBookPro15,2 (Mac-827FB448E656EC26)
System shutdown begun: NO
Panic diags file available: YES (0x0)
Hibernation exit count: 0

System uptime in nanoseconds: 322659376939
Last Sleep:           absolute           base_tsc          base_nano
  Uptime  : 0x0000004b1fff6568
  Sleep   : 0x0000000000000000 0x0000000000000000 0x0000000000000000
  Wake    : 0x0000000000000000 0x00000011174dfe80 0x0000000000000000
Compressor Info: 0% of compressed pages limit (OK) and 0% of segments limit (OK) with 1 swapfiles and OK swap space
Zone info:
  Zone map: 0xffffff8015c5d000 - 0xffffffa015c5d000
  . PGZ   : 0xffffff8015c5d000 - 0xffffff8016c5e000
  . VM    : 0xffffff8016c5e000 - 0xffffff84e36c4000
  . RO    : 0xffffff84e36c4000 - 0xffffff867cf90000
  . GEN0  : 0xffffff867cf90000 - 0xffffff8b499f6000
  . GEN1  : 0xffffff8b499f6000 - 0xffffff901645c000
  . GEN2  : 0xffffff901645c000 - 0xffffff94e2ec2000
  . GEN3  : 0xffffff94e2ec2000 - 0xffffff99af929000
  . DATA  : 0xffffff99af929000 - 0xffffffa015c5d000
  Metadata: 0xffffffa0203f1000 - 0xffffffa0403f1000
  Bitmaps : 0xffffffa0403f1000 - 0xffffffa041bf1000
  Extra   : 0 - 0

last started kext at 16008181202: >AudioAUUC	1.70 (addr 0xffffff7f977a3000, size 12288)
loaded kexts:
com.intel.driver.EnergyDriver	3.7.0
me.kishorprins.VoodooInput	1.1.3
as.acidanthera.voodoo.driver.PS2Keyboard	2.3.5
com.zxystd.!I!BFirmware	2.3.0
com.zxystd.AirportItlwm	2.3.0
com.1Revenger1.RMISMBus	1.0
com.1Revenger1.VoodooRMI	1.3.3
com.sinet3k.Sinetek-rtsx	9.0.0
science.firewolf.rtsx	0.9.6
de.leo-labs.VoodooSMBus	3.0
ru.joedm.SMCSuperIO	1.3.2
as.acidanthera.mieze.!IMausi	1.0.7
as.acidanthera.voodoo.driver.PS2!C	2.3.5
as.lvs1974.RTCMemoryFixup	1.0.7
as.vit9696.SMCProcessor	1.3.2
as.lvs1974.HibernationFixup	1.4.9
ru.usrsse2.SMCBatteryManager	1.3.2
as.vit9696.VirtualSMC	1.3.2
as.acidanthera.BlueToolFixup	2.6.8
com.zxystd.!IBTPatcher	2.3.0
as.vit9696.!AALC	1.8.9
as.vit9696.WhateverGreen	1.6.6
org.acidanthera.driver.CPUFriend	1.2.7
as.lvs1974.DebugEnhancer	1.0.8
as.vit9696.Lilu	1.6.7
>AudioAUUC	1.70
>!APlatformEnabler	2.7.0d0
>X86PlatformShim	1.0.0
>AGPM	135
@filesystems.autofs	3.0
>!AHDAHardwareConfigDriver	540.3
>!AHDA	540.3
>!AGraphicsDevicePolicy	8.1.9
@AGDCPluginDisplayMetrics	8.1.9
>!AUpstreamUserClient	3.6.11
>pmtelemetry	1
@filesystems.nfs	1
|IOUserEthernet	1.0.1
>usb.!UUserHCI	1
>!AUIO	1
>!ASunrise	1
>!AHV	1
>!A!ISlowAdaptiveClocking	4.0.0
>ACPI_SMC_PlatformPlugin	1.0.0
@UVCService	1
>!A!IKBLGraphics	22.0.5
>!ASMCLMU	7400.2
>AGDCBacklightControl	8.1.9
>!AFIVRDriver	4.1.0
>!ABacklight	180.9
>!AMCCSControl	1.17
>!A!IPCHPMC	2.0.1
>!A!IKBLGraphicsFramebuffer	22.0.5
>!ATopCaseHIDEventDriver	7440.8
>!AFileSystemDriver	3.0.1
@filesystems.tmpfs	1
@filesystems.lifs	1
@filesystems.hfs.kext	650.120.1
@BootCache	40
@!AFSCompression.!AFSCompressionTypeZlib	1.0.0
@!AFSCompression.!AFSCompressionTypeDataless	1.0.0d1
>!ASmartBatteryManager	161.0.0
@filesystems.apfs	2236.120.10
@private.KextAudit	1.0
>!AAHCIPort	380
>!ARTC	2.0.1
>!AHPET	1.8
>!AACPIButtons	6.1
>!ASMBIOS	2.1
>!AACPIEC	6.1
>!AAPIC	1.7
@!ASystemPolicy	2.0.0
@nke.applicationfirewall	405
|IOKitRegistryCompatibility	1
|EndpointSecurity	1
@Dont_Steal_Mac_OS_X	7.0.0
>!ADiskImages2	276.120.5
@kec.!AEncryptedArchive	1
>!UAudio	640.12
>!AAudioClockLibs	340.8
>DspFuncLib	540.3
@kext.OSvKernDSPLib	530
>!AGraphicsControl	8.1.9
@kext.triggers	1.0
>IOHIDPowerSource	1
>!ACallbackPowerSource	1
|IOAVB!F	1220.1
>!ARSMChannel	1
|IORSM!F	1
>!AIPAppender	1.0
@plugin.IOgPTPPlugin	1250.2
@!AGPUWrangler	8.1.9
|IOSlowAdaptiveClocking!F	1.0.0
>IOPlatformPluginLegacy	1.0.0
>X86PlatformPlugin	1.0.0
>!AHDA!C	540.3
|IOHDA!F	540.3
|IOAudio!F	540.3
@vecLib.kext	1.2.0
>!ABacklightExpert	1.1.0
>!ASMBus!C	1.0.18d1
>IOPlatformPlugin!F	6.0.0d8
|IONDRVSupport	598
|IOAccelerator!F2	481.40.2
@!AGraphicsDeviceControl	8.1.9
|IOGraphics!F	598
>driverkit.serial	6.0.0
|IOSerial!F	11
>!AActuatorDriver	7440.9
>!AMultitouchDriver	7440.9
>!AInputDeviceSupport	7440.1
>!AHS!BDriver	7440.8
>IO!BHIDDriver	9.0.0
>usb.cdc	5.0.0
>usb.networking	5.0.0
>usb.!UHostCompositeDevice	1.2
>!ABSDKextStarter	3
|IOSurface	352.50.1
@filesystems.hfs.encodings.kext	1
>!ASyntheticGame!C	11.5.1
>usb.!UHostPacketFilter	1.0
|IOUSB!F	900.4.2
>!AXsanScheme	3
|IO80211!F	1200.13.0
>corecapture	1.0.4
|IOAHCIBlock!S	359
|IOAHCI!F	304
>!A!ILpssGspi	3.0.60
>usb.!UXHCIPCI	1.2
>usb.!UXHCI	1.2
>!AEFINVRAM	2.1
>!AEFIRuntime	2.1
|IOHID!F	2.0.0
|IOSMBus!F	1.1
|IOTimeSync!F	1250.2
|IOSkywalk!F	1.0
>mDNSOffloadUserClient	1.0.1b8
|IONetworking!F	3.4
>DiskImages	493.0.0
|IO!B!F	9.0.0
|IOReport!F	47
$quarantine	4
$sandbox	300.0
@kext.!AMatch	1.0.0d1
>!ASSE

**Kext Download Source**
Github

**Comment by johnpapad24** [comment]
panic(cpu 3 caller 0xffffff8002d760a1): mbuf_watchdog: 1 waiters stuck for 25 secs
22867/22897 mbufs in use:
	22573 mbufs allocated to data
	215 mbufs allocated to packet headers
	79 mbufs allocated to socket names and addresses
	30 mbufs allocated to caches
659/682 mbuf 2KB clusters in use
13496/13503 mbuf 4KB clusters in use
0/0 mbuf 16KB clusters in use
61116 KB allocated to network (approx. 99% in use)
0 KB returned to the system
worker thread runs: 391, expansions: 209, cl 0/0, bigcl 390/69528, 16k 0/0
worker thread last run time: 298 (25 seconds ago)

top proc mbuf space 104192 bytes by wifip2pd:330

top ifcq_len 5 packets by en0

mbuf leak detection table:
	total captured: 1904 (one per 500)
	total allocs outstanding: 78
	new hash recorded: 1608 allocs, 585 traces
	hash collisions: 60 allocs, 286 traces
	overwrites: 1084 allocs, 0 traces
	lock conflicts: 0

top 5 outstanding traces:
[1] 25 outstanding alloc(s), 953 hit(s), 272 collision(s)
[2] 22 outstanding alloc(s), 22 hit(s), 0 collision(s)
[3] 9 outstanding alloc(s), 337 hit(s), 0 collision(s)
[4] 5 outstanding alloc(s), 21 hit(s), 0 collision(s)
[5] 4 outstanding alloc(s), 34 hit(s), 0 collision(s)

    trace [1]           trace [2]           trace [3]       	trace [4]           trace [5]      
    ------------------  ------------------  ------------------      ------------------  ------------------ 
 1: 0xffffff800097532a  0xffffff800097532a  0xffffff800097532a  0xffffff800097532a  0xffffff800097532a  
 2: 0xffffff800094dc81  0xffffff800094dd28  0xffffff800094dc81  0xffffff800094dd28  0xffffff800094dd28  
 3: 0xffffff800097b490  0xffffff800097415e  0xffffff8000978eec  0xffffff8000978eec  0xffffff800097b490  
 4: 0xffffff8000946461  0xffffff800094dbf5  0xffffff800097bec7  0xffffff800097bec7  0xffffff8000946461  
 5: 0xffffff80025108cb  0xffffff800097b490  0xffffff8000945763  0xffffff8000945763  0xffffff80025108cb  
 6: 0x0  0xffffff8000946461  0x0  0x0  0x0  
 7: 0x0  0xffffff80025108cb  0x0  0x0  0x0  
 8: 0x0  0x0  0x0  0x0  0x0  
 9: 0x0  0x0  0xffffff8000b108aa  0xffffff8000b108aa  0x0  
10: 0xffffff8000b108aa  0x0  0xffffff8000b0f0ce  0xffffff8000b0f0ce  0xffffff8000b108aa  
11: 0xffffff8000b0f0ce  0x0  0xffffff8000b0e6f6  0xffffff8000b0e6f6  0xffffff8000b0f0ce  
12: 0xffffff8000b0e6f6  0xffffff8000b108aa                                          0xffffff8000b0e6f6  
13:                     0xffffff8000b0f0ce                                                              
14:                     0xffffff8000b0e6f6                                                              
15:                                                                                                     
16:                                                                                                     

Panicked task 0xffffff99af8f73d8: 4 threads: pid 1: launchd
Backtrace (CPU 3), panicked thread: 0xffffff867e87eb30, Frame : Return Address
0xffffffc477e836d0 : 0xffffff8002826571 
0xffffffc477e83720 : 0xffffff800298bc00 
0xffffffc477e83760 : 0xffffff800297b1bc 
0xffffffc477e837e0 : 0xffffff80027bf971 
0xffffffc477e83800 : 0xffffff800282685d 
0xffffffc477e838f0 : 0xffffff8002825f03 
0xffffffc477e83950 : 0xffffff8002fdb38b 
0xffffffc477e83a40 : 0xffffff8002d760a1 
0xffffffc477e83a60 : 0xffffff8002d74818 
0xffffffc477e83ad0 : 0xffffff8002d4dbf5 
0xffffffc477e83b40 : 0xffffff8002d7415e 
0xffffffc477e83be0 : 0xffffff8002d4dbf5 
0xffffffc477e83c50 : 0xffffff8002d7a446 
0xffffffc477e83cc0 : 0xffffff8002d86fed 
0xffffffc477e83de0 : 0xffffff8002d983ee 
0xffffffc477e83ed0 : 0xffffff8002d980a1 
0xffffffc477e83f40 : 0xffffff8002e55060 
0xffffffc477e83fa0 : 0xffffff80027bfdb6 

Process name corresponding to current thread (0xffffff867e87eb30): launchd

Mac OS version:
23F5074a

Kernel version:
Darwin Kernel Version 23.5.0: Wed Apr 24 21:23:04 PDT 2024; root:xnu-10063.121.3~3/RELEASE_X86_64
Kernel UUID: AD00268F-F1D6-3116-9F95-EE3301906DE9
roots installed: 0
KernelCache slide: 0x0000000002400000
KernelCache base:  0xffffff8002600000
Kernel slide:      0x00000000024e4000
Kernel text base:  0xffffff80026e4000
__HIB  text base: 0xffffff8002500000
System model name: MacBookPro15,2 (Mac-827FB448E656EC26)
System shutdown begun: NO
Panic diags file available: YES (0x0)
Hibernation exit count: 0

System uptime in nanoseconds: 322659376939
Last Sleep:           absolute           base_tsc          base_nano
  Uptime  : 0x0000004b1fff6568
  Sleep   : 0x0000000000000000 0x0000000000000000 0x0000000000000000
  Wake    : 0x0000000000000000 0x00000011174dfe80 0x0000000000000000
Compressor Info: 0% of compressed pages limit (OK) and 0% of segments limit (OK) with 1 swapfiles and OK swap space
Zone info:
  Zone map: 0xffffff8015c5d000 - 0xffffffa015c5d000
  . PGZ   : 0xffffff8015c5d000 - 0xffffff8016c5e000
  . VM    : 0xffffff8016c5e000 - 0xffffff84e36c4000
  . RO    : 0xffffff84e36c4000 - 0xffffff867cf90000
  . GEN0  : 0xffffff867cf90000 - 0xffffff8b499f6000
  . GEN1  : 0xffffff8b499f6000 - 0xffffff901645c000
  . GEN2  : 0xffffff901645c000 - 0xffffff94e2ec2000
  . GEN3  : 0xffffff94e2ec2000 - 0xffffff99af929000
  . DATA  : 0xffffff99af929000 - 0xffffffa015c5d000
  Metadata: 0xffffffa0203f1000 - 0xffffffa0403f1000
  Bitmaps : 0xffffffa0403f1000 - 0xffffffa041bf1000
  Extra   : 0 - 0

last started kext at 16008181202: >AudioAUUC	1.70 (addr 0xffffff7f977a3000, size 12288)
loaded kexts:
com.intel.driver.EnergyDriver	3.7.0
me.kishorprins.VoodooInput	1.1.3
as.acidanthera.voodoo.driver.PS2Keyboard	2.3.5
com.zxystd.!I!BFirmware	2.3.0
com.zxystd.AirportItlwm	2.3.0
com.1Revenger1.RMISMBus	1.0
com.1Revenger1.VoodooRMI	1.3.3
com.sinet3k.Sinetek-rtsx	9.0.0
science.firewolf.rtsx	0.9.6
de.leo-labs.VoodooSMBus	3.0
ru.joedm.SMCSuperIO	1.3.2
as.acidanthera.mieze.!IMausi	1.0.7
as.acidanthera.voodoo.driver.PS2!C	2.3.5
as.lvs1974.RTCMemoryFixup	1.0.7
as.vit9696.SMCProcessor	1.3.2
as.lvs1974.HibernationFixup	1.4.9
ru.usrsse2.SMCBatteryManager	1.3.2
as.vit9696.VirtualSMC	1.3.2
as.acidanthera.BlueToolFixup	2.6.8
com.zxystd.!IBTPatcher	2.3.0
as.vit9696.!AALC	1.8.9
as.vit9696.WhateverGreen	1.6.6
org.acidanthera.driver.CPUFriend	1.2.7
as.lvs1974.DebugEnhancer	1.0.8
as.vit9696.Lilu	1.6.7
>AudioAUUC	1.70
>!APlatformEnabler	2.7.0d0
>X86PlatformShim	1.0.0
>AGPM	135
@filesystems.autofs	3.0
>!AHDAHardwareConfigDriver	540.3
>!AHDA	540.3
>!AGraphicsDevicePolicy	8.1.9
@AGDCPluginDisplayMetrics	8.1.9
>!AUpstreamUserClient	3.6.11
>pmtelemetry	1
@filesystems.nfs	1
|IOUserEthernet	1.0.1
>usb.!UUserHCI	1
>!AUIO	1
>!ASunrise	1
>!AHV	1
>!A!ISlowAdaptiveClocking	4.0.0
>ACPI_SMC_PlatformPlugin	1.0.0
@UVCService	1
>!A!IKBLGraphics	22.0.5
>!ASMCLMU	7400.2
>AGDCBacklightControl	8.1.9
>!AFIVRDriver	4.1.0
>!ABacklight	180.9
>!AMCCSControl	1.17
>!A!IPCHPMC	2.0.1
>!A!IKBLGraphicsFramebuffer	22.0.5
>!ATopCaseHIDEventDriver	7440.8
>!AFileSystemDriver	3.0.1
@filesystems.tmpfs	1
@filesystems.lifs	1
@filesystems.hfs.kext	650.120.1
@BootCache	40
@!AFSCompression.!AFSCompressionTypeZlib	1.0.0
@!AFSCompression.!AFSCompressionTypeDataless	1.0.0d1
>!ASmartBatteryManager	161.0.0
@filesystems.apfs	2236.120.10
@private.KextAudit	1.0
>!AAHCIPort	380
>!ARTC	2.0.1
>!AHPET	1.8
>!AACPIButtons	6.1
>!ASMBIOS	2.1
>!AACPIEC	6.1
>!AAPIC	1.7
@!ASystemPolicy	2.0.0
@nke.applicationfirewall	405
|IOKitRegistryCompatibility	1
|EndpointSecurity	1
@Dont_Steal_Mac_OS_X	7.0.0
>!ADiskImages2	276.120.5
@kec.!AEncryptedArchive	1
>!UAudio	640.12
>!AAudioClockLibs	340.8
>DspFuncLib	540.3
@kext.OSvKernDSPLib	530
>!AGraphicsControl	8.1.9
@kext.triggers	1.0
>IOHIDPowerSource	1
>!ACallbackPowerSource	1
|IOAVB!F	1220.1
>!ARSMChannel	1
|IORSM!F	1
>!AIPAppender	1.0
@plugin.IOgPTPPlugin	1250.2
@!AGPUWrangler	8.1.9
|IOSlowAdaptiveClocking!F	1.0.0
>IOPlatformPluginLegacy	1.0.0
>X86PlatformPlugin	1.0.0
>!AHDA!C	540.3
|IOHDA!F	540.3
|IOAudio!F	540.3
@vecLib.kext	1.2.0
>!ABacklightExpert	1.1.0
>!ASMBus!C	1.0.18d1
>IOPlatformPlugin!F	6.0.0d8
|IONDRVSupport	598
|IOAccelerator!F2	481.40.2
@!AGraphicsDeviceControl	8.1.9
|IOGraphics!F	598
>driverkit.serial	6.0.0
|IOSerial!F	11
>!AActuatorDriver	7440.9
>!AMultitouchDriver	7440.9
>!AInputDeviceSupport	7440.1
>!AHS!BDriver	7440.8
>IO!BHIDDriver	9.0.0
>usb.cdc	5.0.0
>usb.networking	5.0.0
>usb.!UHostCompositeDevice	1.2
>!ABSDKextStarter	3
|IOSurface	352.50.1
@filesystems.hfs.encodings.kext	1
>!ASyntheticGame!C	11.5.1
>usb.!UHostPacketFilter	1.0
|IOUSB!F	900.4.2
>!AXsanScheme	3
|IO80211!F	1200.13.0
>corecapture	1.0.4
|IOAHCIBlock!S	359
|IOAHCI!F	304
>!A!ILpssGspi	3.0.60
>usb.!UXHCIPCI	1.2
>usb.!UXHCI	1.2
>!AEFINVRAM	2.1
>!AEFIRuntime	2.1
|IOHID!F	2.0.0
|IOSMBus!F	1.1
|IOTimeSync!F	1250.2
|IOSkywalk!F	1.0
>mDNSOffloadUserClient	1.0.1b8
|IONetworking!F	3.4
>DiskImages	493.0.0
|IO!B!F	9.0.0
|IOReport!F	47
$quarantine	4
$sandbox	300.0
@kext.!AMatch	1.0.0d1
>!ASSE

**Comment by sameerasw** [comment]
Can confirm this behaviour for me but back in 14.2.1 .... Certain WiFi (Home WiFi) makes the entire OS instantly kernel panic and reboot.

Mostly I noticed when I turn off mobile hotspot so the WiFi networks automatically switches to home. It's just that one specific 2.4GHz WiFi so far.

**Comment by zxystd** [comment]
Don't see anything relate to this kext, and no other people report the same issue.

**Comment by zxystd** [comment]
@sameerasw If kernel panic happened, please get the panic log and report back to me, thanks.

**Comment by johnpapad24** [comment]
the brand of the router with the problematic hotspot was huawei.
