### ISSUE TITLE
[BUG] Itlwm.kext wont automatically connect to hidden wifi network

### ISSUE THREAD

**Issue by matte-oss** [OpenIntelWireless/itlwm#976]
**Have You Read Our Docs**

Yes

**Are You Reporting A Bug**

Yes

**Environment**

- Kext Version: 2.2.0
- WiFi Card Model: Intel dual band wireless-AC 7265
- PCI Product ID: 
- macOS Version: 12.7.4

**Description**

I add my hidden wifi network to HeliPort, everything works fine. I reboot my hackintosh and HeliPort has forgot my network, i need to re-add it

**Bug Report Archive**

I'm trying to install the debug kext, but It does not work

**Kext Download Source**

Official GitHub page

**Comment by matte-oss** [comment]
Tried with my phone network (a wifi that isn't hidden) and It works normally

**Comment by zxystd** [comment]
It is expected.

**Comment by matte-oss** [comment]
Is there a way to make it connect automatically?

**Comment by zxystd** [comment]
@matte-oss 
![image](https://github.com/OpenIntelWireless/itlwm/assets/16227538/0d570015-249e-4caa-9cd2-e2ef4c0c9d67)
Hard code your ssid and password into the itlwm.kext/Contents/info.plist

**Comment by matte-oss** [comment]
Thank you so much!

**Comment by tiyo** [comment]
> [@matte-oss](https://github.com/matte-oss) ![image](https://github.com/OpenIntelWireless/itlwm/assets/16227538/0d570015-249e-4caa-9cd2-e2ef4c0c9d67) Hard code your ssid and password into the itlwm.kext/Contents/info.plist

Added, but it's still not working. Do I also need to set the password type?
