### ISSUE TITLE
Ax211 Ventura wifi working but in Sonoma not working

### ISSUE THREAD

**Issue by yzg011** [OpenIntelWireless/itlwm#984]
Environment

working well
Kext Version: AirportItlwm.kext.v2.3.0(Ventura )
WiFi Card Model:  ax211. (0x00948086)
macOS Version: Ventura 13.6

not working
Kext Version: AirportItlwm.kext.v2.3.0(Sonoma 14.4)
WiFi Card Model:  ax211. (0x00948086)
macOS Version: Sonoma 14.5

pls help me. thanks

**Comment by yzg011** [comment]
all kext use the  stable version

**Comment by yzg011** [comment]
wifi switch can't open bluetooth  is  working

**Comment by zxystd** [comment]
attached the runtime log please, and can you post the hacklintool->pci info here? I don't see any intel wireless device that with device id 0x0094.
https://openintelwireless.github.io/itlwm/Troubleshooting.html#runtime-logs

**Comment by yzg011** [comment]
![1715391861-122124tvz7rzyxkt35f00t](https://github.com/OpenIntelWireless/itlwm/assets/24872854/d5967bfe-c0ae-4367-b2fb-9d0ff7295099)
thanks for your quick answer
right now I am not in home

**Comment by yzg011** [comment]
https://imacos.top/2024/05/11/14/

so many persons have this issue，but I try this way also， not working

**Comment by zxystd** [comment]
4ac4c79bc7e34f8764038fc382630a29eb46213d
0x51F1 is already added in stable 2.3.0 version, are you sure you use the stable version downloaded in release page?

**Comment by yzg011** [comment]
yes of course。 Sonoma 14.4 debug and stable version  have checked。 not working

**Comment by andreszerocross** [comment]
There is default entry in config.plist for new opencore version. Make sure you're set it's "NO" or Disabled

![image](https://github.com/OpenIntelWireless/itlwm/assets/9614101/f5fdf784-78cb-475a-9531-32e0c0ecbea2)

**Comment by yzg011** [comment]
I didn't set. any mini kernel value

**Comment by yzg011** [comment]
> There is default entry in config.plist for new opencore version. Make sure you're set it's "NO" or Disabled
> 
> ![image](https://private-user-images.githubusercontent.com/9614101/339298860-f5fdf784-78cb-475a-9531-32e0c0ecbea2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyNzEyMTUsIm5iZiI6MTcxODI3MDkxNSwicGF0aCI6Ii85NjE0MTAxLzMzOTI5ODg2MC1mNWZkZjc4NC03OGNiLTQ3NWEtOTUzMS0zMmUwYzBlY2JlYTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTNUMDkyODM1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDM4NDFkMGFlYzdlNDc5ZWE2OGMzNjA2ZGIxMWNhMDdmNTk1Zjg1Y2JlNjUyODZjMGEwZTczZWRiMWZiZjZhNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.t1wy_HK4hKsaWTnQha_sD-FvQ3faHUiioLRdsKzQnXs)

will check and replay

**Comment by yzg011** [comment]
> There is default entry in config.plist for new opencore version. Make sure you're set it's "NO" or Disabled
> 
> ![image](https://private-user-images.githubusercontent.com/9614101/339298860-f5fdf784-78cb-475a-9531-32e0c0ecbea2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzMzQ3NzEsIm5iZiI6MTcxODMzNDQ3MSwicGF0aCI6Ii85NjE0MTAxLzMzOTI5ODg2MC1mNWZkZjc4NC03OGNiLTQ3NWEtOTUzMS0zMmUwYzBlY2JlYTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTRUMDMwNzUxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWU1Zjc2YjIxYjRlZDI5YjE3ZGMyZGFiYjMzODI0ZDg5YWI1YmI0NTFmNTIyMTNjMzY5MjBkMTI3ODdiODIwMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.uaI0ezY1iahiYCQUWtls85HVn--D3DrrHgf6dqhDBB8)

solved ！thanks
