### ISSUE TITLE
Help FV AC 1200

### ISSUE THREAD

**Issue by rootfast** [OpenIntelWireless/itlwm#985]
I have a Fenvi AC1200 card I updated to Sonoma 14.5 but the wifi stopped picking up even with the Kext 14.4 can anyone help me ?
Adapt AC 7260 (FV AC1200)

**Comment by DevRBezerra** [comment]
with itlwn +heliport it worked. however, only with the airport it does not work, the wifi icon appears but it appears disconnected
![Captura de Tela 2024-06-16 às 19 15 56](https://github.com/OpenIntelWireless/itlwm/assets/151099526/221f719f-f89f-46b5-9cfd-80396887ecea)
