### ISSUE TITLE
imessage only works when connected to VPN

### ISSUE THREAD

**Issue by Alectardy98** [OpenIntelWireless/itlwm#988]
**Have You Read Our Docs**
Yes 

**Are You Reporting A Bug**
Yes

**Environment**

- Kext Version: its the test kext for BE200
- WiFi Card Model: BE200
- PCI Product ID: ??? it is actually 3 question marks
- macOS Version: 14.1.1

**Description**
Wifi is working great and I am getting full speeds. The issue I am having is that when trying to use Imessage or other iservices messages wont send unless I connect to a vpn. When I am on a VPN everything is working properly. I have done all of the correct things setting my ethernet port as built in and en0 and my wifi card as en1, as well as setting proper system information. Icloud backup and app store seam to be working regardless, but messages hang on sending when I am not connected to a vpn. The vpn is the mac app for private internet access if that helps

**Bug Report Archive**
I am not usigin heliport

**Kext Download Source**
Yes this is custom built, here is the info https://github.com/OpenIntelWireless/itlwm/issues/955

**Comment by ghost** [comment]
Sounds like #942

**Comment by itsjuoum** [comment]
How did you solve this? I'm having the same issue on Sonoma 14.6 using AirportItlwm_v2.3.0_stable_Sonoma14.4.
