### ISSUE TITLE
Interface gets no IP from DHCP on Sonoma 14.5

### ISSUE THREAD

**Issue by djseban** [OpenIntelWireless/itlwm#992]
**Have You Read Our Docs**
Yes

**Are You Reporting A Bug**
Yes

**Environment**

- Kext Version: 2.3.0 stable
- WiFi Card Model: Intel AX200 (Comfast AX3000)
- PCI Product ID: 8086:2723 
- macOS Version: 14.5

**Description**
So lately I was trying to set up a hackintosh using QEMU with PCI passthrough. While GPU works okay I cannot seem to get my AX200 working - macOS Wi-Fi UI shows up, I can connect, but Wi-Fi interface does not get IP. Tried setting static IP, still no connection, neither to local nor to wide area network.

[Log_2024-06-27_00-23-29.log](https://github.com/user-attachments/files/15997119/Log_2024-06-27_00-23-29.log)
About WiFiDiagnostics I am not sure what to upload because archive is like 200MB, I can provide any file from this archive is asked

**Kext Download Source**
Official Github

**Comment by zxystd** [comment]
wrong password.
