### ISSUE TITLE
airportltlwm在macOS15上不工作，itlwm+heliport正常

### ISSUE THREAD

**Issue by Eternity070628** [OpenIntelWireless/itlwm#995]
**Have You Read Our Docs**

**Are You Reporting A Bug**

**Environment**

- Kext Version: 2.3.0
- WiFi Card Model: 
- PCI Product ID: 
- macOS Version: 15

**Description**

**Bug Report Archive**

**Kext Download Source**

**Comment by williambj1** [comment]
Duplicate of #983
