### ISSUE TITLE
Intel(R) Wireless-AC 9260无线网卡使用2.3.0版本的AirportItlwm.kext 能加载这个驱动，但无法搜索到Wi-Fi信号

### ISSUE THREAD

**Issue by DTTZLS** [OpenIntelWireless/itlwm#997]
**Have You Read Our Docs**
yes

**Are You Reporting A Bug**
yes

**Environment**

- Kext Version: 2.3.0
- WiFi Card Model: Intel(R) Wireless-AC 9260
- PCI Product ID:  0X00148086
- macOS Version: 14.4.1

**Description**
使用AirportItlwm.kext 能加载这个驱动，也已经按照指南强制加载，但是Wi-Fi依旧无法搜索到信号，但是使用itlwm.kext配合App可以正常使用。硬件ID在window下显示是00148086，但是我在AirportItlwm.kext中的Info.plist描述文件中并没有看到这个硬件ID，尝试添加进去，但结果依旧是无法搜索到Wi-Fi信号。

**Bug Report Archive**

**Kext Download Source**
下载来源是软件的发布页面。

**Comment by zxystd** [comment]
9260只有0x25268086这个id，你应该是看成子设备id了，itlwm的日志呢？没有日志只能算一卦了。
