### ISSUE TITLE
Request to add intel be200

### ISSUE THREAD

**Issue by krtko1** [OpenIntelWireless/itlwm#998]
**Have You Read Our Docs**
Yes

**Are You Reporting A Bug**
No

**Environment**

- Kext Version: 
- WiFi Card Model: intel be200
- PCI Product ID: 
- macOS Version: 

**Description**
What is needed to add driver for intel be200

**Comment by VToime** [comment]
#955

**Comment by krtko1** [comment]
Thanks, sorry I don't find it
